<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">-->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Pemerintah Kota Cimahi - Sumber Daya Manusia</title>

<LINK href="<?echo $this->baseUrl;?>/css/sdm/style.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/style_sdm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/coloring_sdm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/topmenu.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/popup.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/confirm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/sdm/menutab.css" type="text/css" rel="stylesheet">
<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">

<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/jquery.form.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ui.core.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ui.datepicker.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/common.js"></script>
<!--SCRIPT type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/navigation.js"></SCRIPT-->
<SCRIPT type="text/javascript" src="<? echo $this->baseUrl;?>/js/navigation.js"></SCRIPT>

<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ddsmoothmenu.js"></script>

<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/popup.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/util.js"></script>

 <!--
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/jquery.autocomplete.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/tabcontent.js"></script>
<SCRIPT type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/table.sorter.js"></SCRIPT>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/fsmenu.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/oa_fn.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/ext-base.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/ext-all.js"></script>
-->

<script type="text/javascript">
function Add(URL) {
    	window.location.href=URL;
    	}
function listdata(par){
	var url = '/sdmmodule/reminder/pensiun?par='+par;
	BukaWindows(url,'700','500');	
}
function BukaWindows(url,wid,heg){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = wid, popH = heg;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}
</script>

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Masukkan no halaman yang ingin Anda tuju:';
	var on_page = '1';
	var per_page = '25';
	var onload_functions = new Array();
	var onunload_functions = new Array();
	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript">

// Current Server Time script (SSI or PHP)- By JavaScriptKit.com (http://www.javascriptkit.com)
// For this and over 400+ free scripts, visit JavaScript Kit- http://www.javascriptkit.com/
// This notice must stay intact for use.

//Depending on whether your page supports SSI (.shtml) or PHP (.php), UNCOMMENT the line below your page supports and COMMENT the one it does not:
//Default is that SSI method is uncommented, and PHP is commented:

//var currenttime = '<!--#config timefmt="%B %d, %Y %H:%M:%S"--><!--#echo var="DATE_LOCAL" -->' //SSI method of getting server date
///var currenttime = 'May 10, 2011 10:46:11' //PHP method of getting server date
///////////Stop editting here/////////////////////////////////
<? $date=date('F d, Y hh:mm:ss');?>
//var currenttime = '<? echo $date?>';
//var dayarray=new Array("Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu");
//var montharray=new Array("Januari","Februari","Maret","April","Mei","Juni","July","Agustus","September","Oktober","November","Desember")
//var serverdate=new Date(currenttime)

var currenttime = '<? print date("F d, Y H:i:s", time())?>' //PHP method of getting server date
///////////Stop editting here/////////////////////////////////

var dayarray=new Array("Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu");
var montharray=new Array("Januari","Februari","Maret","April","Mei","Juni","July","Agustus","September","Oktober","November","Desember")
var serverdate=new Date(currenttime);

function padlength(what){
var output=(what.toString().length==1)? "0"+what : what
return output
}

function displaytime(){
serverdate.setSeconds(serverdate.getSeconds()+1)
var datestring=dayarray[serverdate.getDay()]+", "+padlength(serverdate.getDate())+" "+montharray[serverdate.getMonth()]+" "+serverdate.getFullYear()
var timestring=padlength(serverdate.getHours()-1)+":"+padlength(serverdate.getMinutes())+":"+padlength(serverdate.getSeconds())
document.getElementById("servertime").innerHTML=datestring+" | "+timestring
}

window.onload=function(){
setInterval("displaytime()", 1000)
}

function showChart(par){
if (par=='pendidikan'){
	var url = '<?php echo $this->basePath; ?>/sdmmodule/portalchart/chartpendidikanb'; 
}	
if (par=='golongan'){
	var url = '<?php echo $this->basePath; ?>/sdmmodule/portalchart/chartgolonganb'; 
}
if (par=='usia'){
	var url = '<?php echo $this->basePath; ?>/sdmmodule/portalchart/chartusiab'; 
}
	var param = {par:par};
	jQuery.get(url, param, function(data) {
		jQuery("#targetchart").html(data);
	});
}

function getReminder(par){

	var url = '<?php echo $this->basePath; ?>/sdmmodule/reminder/reminder'; 
	var param = {par:par};
	jQuery.get(url, param, function(data) {
		jQuery("#targetremind").html(data);
	});
}
function viewData(mod,par){
var url = '<?php echo $this->basePath;?>/sdmmodule/portalchart/view';
var param = {mod:mod,par:par};
	jQuery.get(url, param, function(data) {
		jQuery("#targetremind").html(data);
		//centerPopup();
		//loadPopup();			
	});
}

</script>

