<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
	<tr>
		<td width="30%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td>Lokasi</td>
					<td>
					<select id="operand" name="operand">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon I</td>
					<td>
					<select id="operand1" name="operand1">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon II</td>
					<td>
					<select id="operand2" name="operand2">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon III</td>
					<td>
					<select id="operand3" name="operand3">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon IV</td>
					<td>
					<select id="operand4" name="operand4">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon V</td>
					<td>
					<select id="operand5" name="operand5">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
			
			</table>	
		</td>
		<td width="70%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td>
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('c_lokasi_unitkerja','')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
					</td>
				</tr>
				<tr>
					<td>				
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('c_eselon_i','1')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('c_eselon_ii','2')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('c_eselon_ii','2')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('c_eselon_iii','3')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('c_eselon_iii','3')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('c_eselon_iv','4')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('c_eselon_iv','4')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v","onChange"=>"javascript:cariCombo('c_eselon_v','5')");}										
										else{$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v","onChange"=>"javascript:cariCombo('c_eselon_v','5')");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>					
					</td>
				</tr>	
			
			</table>		
		</td>		
	</tr>
</table>		