<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
	<tr>
		<td width="40%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td width="70%">Lokasi</td>
					<td>
					<select id="operand" name="operand">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon I</td>
					<td>
					<select id="operand1" name="operand1">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Pengadilan Tk Banding</td>
					<td>
					<select id="operand2" name="operand2">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Pengadilan Tingkat I</td>
					<td>
					<select id="operand3" name="operand3">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Unit Kerja</td>
					<td>
					<select id="operand4" name="operand4">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
			</table>	
		</td>
		<td width="60%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td>
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('c_lokasi_unitkerja','')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
					</td>
				</tr>
				<tr>
					<td>				
									<?
										$jmleseloniList=count($this->eseloniList);
										
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[trim((string)$this->eseloniList[$i][c_eselon_i])] = (string)$this->eseloniList[$i][n_unitkerja];			 
											}
										$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_i","onChange"=>"javascript:cariComboPngl('c_eselon_i','1')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii.";".(string)$this->eseloniiList[$i]->c_parent)] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariComboPngl('c_eselon_ii','2')");}
										else {$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariComboPngl('c_eselon_ii','2')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
										
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_ii.";".(string)$this->eseloniiiList[$i]->c_eselon_iii.";".(string)$this->eseloniiiList[$i]->c_satker)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
												
											}										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariComboPngl('c_eselon_iii','3')");}										
										else{$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariComboPngl('c_eselon_iii','3')");}										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv)]= (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 320px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariComboPngl('c_eselon_iv','4')"); 
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 
									?>					
					</td>
				</tr>	
			
			</table>		
		</td>		
	</tr>
</table>		