<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>
	<h3 class="title"><b><u>Riwayat Jabatan</u></b><h3>
	<br>
	<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
			<tr>
			<td width="15%">Eselon</td>
			<td width="2%">:</td> 
			<td>					
									<?
										$jmlEslList=count($this->eselonList);
										$eslList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlEslList; $i++) {
												$eslList[(string)$this->eselonList[$i]->c_eselon] = (string)$this->eselonList[$i]->n_eselon;			 
											}
										$eslAtrib = array("style"=>"width: 140px","onChange"=>"javascript:getNmJabatan()"); 		
										echo $ctrlFrm->formSelect('c_eselonjabdiv',$this->c_eselonjabdiv, $eslAtrib, $eslList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Nama Jabatan</td>
			<td>:</td> 
			<td>
			<span id="targetjabdiv">	
									<?
									
										$jmljabList=count($this->nmJabatanList);										
										$jabList[''] = '--Pilih--';
											for ($i = 0; $i < $jmljabList; $i++) {
												$jabList[(string)$this->nmJabatanList[$i]['c_jabatan']] = (string)$this->nmJabatanList[$i]['n_jabatan'];			 
											}
										echo $ctrlFrm->formSelect('c_jabatan_jabdiv',$this->c_jabatan_jabdiv,null,$jabList); 							
									?>
			</span>						
				<input type="text" name="d_akhir_jabat" id="d_akhir_jabat" value="<?=$this->d_akhir_jabat?>" size="30">
			&nbsp;Tahun TMT Jabatan : <input type="text" name="d_akhir_jabat" id="d_akhir_jabat" value="<?=$this->d_akhir_jabat?>" size="10">				
			</td>
		</tr>
</table>
<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">		
		<tr>
			<td width="15%">Lokasi</td>
			<td width="2%">:</td> 
			<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon II</td>
			<td>:</td> 
			<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
			</td>
			</tr>						
		<tr>
			<td>Eselon III</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon IV</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon V</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
										else{$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			</td>
		</tr>							
	</table>

<script>
function getNmJabatan(){
	var c_eselonjabdiv=document.getElementById('c_eselonjabdiv').value;	
	var url = '<?php echo $this->basePath; ?>/sdmmodule/monitoringserbaguna/combonamajabatan'; 
	var param = {c_eselonjabdiv:c_eselonjabdiv};
	jQuery.get(url, param, function(data) {
		jQuery("#targetjabdiv").html(data);
	});
}
</script>	