<? 
// $file_type = "vnd.ms-word";
// $file_ending = "doc";
// header("Content-Type: application/$file_type");
// header("Content-Disposition: attachment; filename=nomorpendaftaran.$file_ending");
// header("Pragma: no-cache");
// header("Expires: 0");
$vImg = $this->basePath."/upld/Uploaddata/getphoto?f=logo_ma.gif";
$html ='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
</style></head>
<body>

<table border="0" align="center" width="100%">
	<tr>
		<td colspan="3"  align="left" >
			<img src="'.$vImg.'" ALT="some text" width="60" height="80">
			<font size="3" face="arial"><b>Pemerintah Kota Cimahi</b></font>
		</td>

	</tr>
	<tr>
		<td width="20%"><h2><font size="2" face="arial"><b>Nomor Pendaftaran</b></font></h2></td>
		<td width="2%">:</td>
		<td>
			<h2><font size="2" face="arial"><b>'.$this->nomordaftar.'</b></font></h2>
		</td>
	</tr>
</table>	
<table border="0" align="center" width="100%">
	
	<tr>
		<td width="15%"><font size="2" face="arial">Nomor KTP</font></td>
		<td width="2%">:</td>
		<td><font size="2" face="arial">'.$this->i_ktp.'</font></td>
	</tr>	
	<tr>
		<td><font size="2" face="arial">Nama</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->n_pendaftar.'</font></td>
	</tr>	
	<tr>
		<td><font size="2" face="arial">Pendidikan</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->n_pendidikan.'</font></td>
	</tr>	
	<tr>
		<td><font size="2" face="arial">Alamat</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->a_rumah.'  RT. '.$this->a_rt.' / RW. '.$this->a_rw.'</font></td>
	</tr>	
	<tr>
		<td><font size="2" face="arial">Kelurahan</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->a_kelurahan.'</font></td>
	</tr>
	<tr>
		<td><font size="2" face="arial">Kecamatan</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->a_kecamatan.'</font></td>
	</tr>
	<tr>
		<td><font size="2" face="arial">Kota / Kab.</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->n_kota.'</font></td>
	</tr>
	<tr>
		<td><font size="2" face="arial">Propinsi</font></td>
		<td>:</td>
		<td><font size="2" face="arial">'.$this->n_propinsi.'</font></td>
	</tr>	
</table>';
echo $html;
	
?>