function insertDaftarOl(){
	jQuery("#formdaftaronline").ajaxForm(maintain_daftarol);
}
var maintain_daftarol = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formdaftaronline;
		astr= "document.formdaftaronline";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/
				if((!i_ktp.value)){cekVal = sdmValidasiData(astr,"i_ktp","Nomor KTP harus diisi....!");return false;break;}							
				if((!n_pendaftar.value)){cekVal = sdmValidasiData(astr,"n_pendaftar","Nama Pendaftar harus diisi....!");return false;break;}
				if((!c_pend.value)){cekVal = sdmValidasiData(astr,"c_pend","Pendidikan harus diisi....!");return false;break;}				
				break;
			}
			
		}
		
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/maintaindata',
	type: 'post',
	resetForm: false
};

function cariData(){
	var i_ktp=document.getElementById('i_ktp').value;
	var url = '<?php echo $this->basePath;?>/sdmmodule/pendaftaranonline/daftaronline';	
	var param = {i_ktp:i_ktp};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
		});
}