<div id="backgroundPopup">
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td>
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>	
		<center>
		<div class="hideshow">
			<table width="100%">
				<tr>
					<td align="center">
					<?echo $this->judul;?>
					</td>
				</tr>
			</table>				
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						<?echo $this->chart;?>
						<table border="0" width="50%" align="center" class="tbl2">
							<tr>
								<th>Gol I</th>
								<th>Gol II</th>
								<th>Gol III</th>
								<th>Gol IV</th>
							</tr>
							<tr class="event2">
								<td align="right"><?=$this->jmlgol1?></td>
								<td align="right"><?=$this->jmlgol2?></td>
								<td align="right"><?=$this->jmlgol3?></td>
								<td align="right"><?=$this->jmlgol4?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>		
		</div>	
		</center>
	</div>
</div>	