<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
/* 		jQuery("#d_tmt_eselon").datepicker();
		jQuery("#d_mulai_jabat").datepicker();
		jQuery("#d_akhir_jabat").datepicker();
		jQuery("#d_tmt_lantik").datepicker();
		jQuery("#d_sk_jabat").datepicker(); */
		$( "#d_tmt_eselon" ).datepicker({	changeMonth: true,changeYear: true});
		$( "#d_mulai_jabat" ).datepicker({	changeMonth: true,changeYear: true});
		$( "#d_akhir_jabat" ).datepicker({	changeMonth: true,changeYear: true});
		$( "#d_tmt_lantik" ).datepicker({	changeMonth: true,changeYear: true});
		$( "#d_sk_jabat" ).datepicker({	changeMonth: true,changeYear: true});
		
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','<?php echo $this->basePath; ?>/sdmmodule/datajabatan/jabatanjs');">Jabatan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jabatan Struktural
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Jabatan </h2>	
	<?php $opr='rjbt'; include "$this->leftMenu/linkriwayat.phtml";?>
<form id="formjabatan" method="post" name="formjabatan">		
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>

<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>

<div class="panel">

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">Eselon<span class="hightlight">*</span></td>
								<td width="2%">:</td> 
								<td>					
									<?
										$jmlEslList=count($this->eselonList);
										$eslList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlEslList; $i++) {
												$eslList[(string)$this->eselonList[$i]->c_eselon] = (string)$this->eselonList[$i]->n_eselon;			 
											}
										$eslAtrib = array("style"=>"width: 300px","onChange"=>"javascript:getEselon();if (this[this.selectedIndex].value == '16' ){document.formjabatan.j_jabatan.options[1].selected = true; } else {document.formjabatan.j_jabatan.options[0].selected = true}"); 		
										echo $ctrlFrm->formSelect('c_eselon',$this->c_eselon, $eslAtrib, $eslList); 							
									?>
									<input type="hidden" name="c_eselon2" id="c_eselon2" value="<?=$this->c_eselon?>">
								</td>							
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Dengan Kode Ref.)</td>
								<td>:</td> 
								<td>					
									<input type="hidden" name="c_jabatan" id="c_jabatan" value="<?=$this->c_jabatan?>">
									<input type="text" name="n_jabatan" id="n_jabatan" value="<?=$this->n_jabatan?>" size="30">
									<input type="button" value="Cari" onClick="CariJabatan()">
								</td>								
							</tr>	
							<tr>
								<td>TMT. Jabatan<span class="hightlight">*</span></td>
								<td>:</td> 
								<td>					
									<input type="hidden" name="d_mulai_jabat2" id="d_mulai_jabat2" value="<?=$this->d_mulai_jabat?>" size="10">
									<input type="text" name="d_mulai_jabat" id="d_mulai_jabat" value="<?=$this->d_mulai_jabat?>" size="10"> s/d
									<input type="text" name="d_akhir_jabat" id="d_akhir_jabat" value="<?=$this->d_akhir_jabat?>" size="10">
									<span class="hightlight">dd-mm-yyyy</span>
								</td>								
							</tr>
							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">TMT Eselon<span class="hightlight">*</span></td>
								<td width="2%">:</td> 
								<td>					
									<input type="text" name="d_tmt_eselon" id="d_tmt_eselon" value="<?=$this->d_tmt_eselon?>" size="10">
									<span class="hightlight">dd-mm-yyyy</span>
								</td>
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Tanpa Kode Ref.)</td>
								<td>:</td> 
								<td>					
									<textarea id="n_jabatan_nokode" name="n_jabatan_nokode" rows="1"><?=$this->n_jabatan_nokode?></textarea>
								</td>
							</tr>
							<tr>
								<td>Jumlah Angka Kredit</td>
								<td>:</td> 
								<td>					
									<input type="text" name="q_angka_kredit" id="q_angka_kredit" value="<?=$this->q_angka_kredit?>" size="10" onkeyup="isNumber('q_angka_kredit')">
								</td>
							</tr>	
								<tr>
								<td>Kategori Jabatan</td>
								<td>:</td> 
								<td>	
									<select name="j_jabatan" id="j_jabatan">
									<OPTION value="P" <?=$this->seljp?>>Berpengaruh terhadap Jabatan Saat ini</option>
									<OPTION value="T" <?=$this->seljt?>>Tidak Berpengaruh terhadap Jabatan Saat ini</option>
									</select>	
								</td>								
							</tr>	
						</table>	
					</td>
				</tr>
				<?
			if  (trim($this->c_jabatan) == '' && ($this->e_njabatan != '' || $this->e_jabatanket != '')){?>
				<tr>
					<td colspan="3" ><h3 class="title">Nama Jabatan yang akan diubah : <u><? if ($this->e_njabatan != '') echo $this->e_njabatan; else if($this->e_jabatanket != '') echo $this->e_jabatanket;?></u>
					<?php if ($this->e_unit) { echo "(".$this->e_unit. ($this->e_instansi ? ', '.$this->e_instansi:"").")";}?>
				
					<h3></td>
				</tr>
				<?}?>
							
			</table>
		</td>
	</tr>	
</table>
<?if ($this->c_lokasi_unitkerja=='1'){?>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>UNIT KERJA</u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Lokasi</td>
								<td width="2%">:</td> 
								<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo3('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
								</td>
							</tr>
							<tr>
								<td>Eselon I</td>
								<td>:</td> 
								<td>					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[trim((string)$this->eseloniList[$i]->c_eselon_i).";".trim((string)$this->eseloniList[$i]->n_unitkerja)] = (string)$this->eseloniList[$i]->n_unitkerja;
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo3('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
								</td>
							</tr>
							<tr>
								<td width="30%">Eselon II</td>
								<td width="2%">:</td> 
								<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii).";".trim((string)$this->eseloniiList[$i]->n_unitkerja)] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo3('targetesliii')");  	
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
								</td>
							</tr>						
							<tr>
								<td width="30%">Eselon III</td>
								<td width="2%">:</td> 
								<td>					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_iii).";".trim((string)$this->eseloniiiList[$i]->n_unitkerja)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo3('targetesliv')");  	
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
								</td>
							</tr>
							<tr>
								<td>Eselon IV</td>
								<td>:</td> 
								<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv).";".trim((string)$this->eselonivList[$i]->n_unitkerja)] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo3('targeteslv')");  	
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
								</td>
							</tr>
							<tr>
								<td>Eselon V</td>
								<td>:</td> 
								<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[trim((string)$this->eselonvList[$i]->c_eselon_v).";".trim((string)$this->eselonvList[$i]->n_unitkerja)] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");  	
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
								</td>
							</tr>
							<tr>
								<td width="17%">Alamat Kantor</td>
								<td width="2%">:</td> 
								<td>					
									<textarea id="a_alamat_kantor" name="a_alamat_kantor" rows="1"><?=$this->a_alamat_kantor?></textarea>
								</td>
							</tr>							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>HASIL AKHIR NAMA JABATAN</u></b><h3></td>
							</tr>
							<tr>
								<td colspan="3">					
									<textarea id="jabat_lengkap" name="jabat_lengkap" rows="7"><?=$this->e_jabatan?></textarea>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
<?}  else{include ("listcombo2.phtml");}?>	
</table>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>SURAT KEPUTUSAN<u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Nomor</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="i_sk_jabat" id="i_sk_jabat" value="<?=$this->i_sk_jabat?>" size="30">
								</td>
							</tr>
							<tr>
								<td>Tanggal</td>
								<td>:</td> 
								<td>					
									<input type="text" name="d_sk_jabat" id="d_sk_jabat" value="<?=$this->d_sk_jabat?>" size="10">
									<span class="hightlight">dd-mm-yyyy</span>
								</td>
							</tr>
							<tr>
								<td>Pejabat</td>
								<td>:</td> 
								<td>					
									<input type="text" name="n_sk_pejabat" id="n_sk_pejabat" value="<?=$this->n_sk_pejabat?>" size="50">
								</td>
							</tr>
							<tr>
								<td>File Surat Keputusan</td>
								<td>:</td> 
								<td>
									<div class="fileinputs">
										<input type="file" size=55 id="e_file_sk" name="e_file_sk"  value="<? echo $this->e_file_sk?>"onChange="setvalueuplfile(this.value,'efiledok','pdf')" />
										<div class="fakefile">
											<input type="text" size=54 name="a_file" id="a_file" value="<? echo $this->e_file_sk?>"/>
										</div>
									</div>
									<input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $e_file_sk?>"/>	

								</td>
							</tr>								
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>							
							<tr>
								<td width="30%">Tanggal Pelantikan</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="d_tmt_lantik" id="d_tmt_lantik" value="<?=$this->d_tmt_lantik?>" size="10">
									<span class="hightlight">dd-mm-yyyy</span>
								</td>
							</tr>	
							<tr>
								<td width="30%">Lokasi KPPN</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="n_lok_kppn" id="n_lok_kppn" value="<?=$this->n_lok_kppn?>" size="20">
								</td>
							</tr>
							<tr>
								<td>Lokasi Taspen</td>
								<td>:</td> 
								<td>					
									<input type="text" name="n_lok_taspen" id="n_lok_taspen" value="<?=$this->n_lok_taspen?>" size="20">
								</td>
							</tr>	
							<tr>
								<td>Keterangan</td>
								<td>:</td> 
								<td>					
									<textarea id="e_keterangan" name="e_keterangan" rows="1"><?=$this->e_keterangan?></textarea>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
</div>
<br>
	<div class="panel">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
			<tr>
				<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
				<td></td>
				<td align="right">
					<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','');"> 									
					<input type="submit" value="<?=$this->par;?>" onClick="insertJabatan()">
					<input type="hidden" id="proses" name="proses" value="<?=$this->par;?>">
					<?php if ($this->id) {?><input type="hidden" id="id" name="id" value="<?=$this->id;?>"><?}?>
				</td>
			</tr>
		</table>
	</div>
</form>
</div>
<div id="targetdetil"></div>
<script>
function CariJabatan(){
var c_eselon =document.getElementById('c_eselon').value;
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listnamajabatan';
var param = {c_eselon:c_eselon};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}

function cariCombo3(){
	var c_eselon =document.getElementById('c_eselon').value;
	var c_lokasi_unitkerja=document.getElementById('c_lokasi_unitkerja').value;	
	var eseloni=document.getElementById('c_eselon_i').value;
	var eselonii=document.getElementById('c_eselon_ii').value;
	var eseloniii=document.getElementById('c_eselon_iii').value;
	var eseloniv=document.getElementById('c_eselon_iv').value;
	var a_alamat_kantor=document.getElementById('a_alamat_kantor').value;
	var n_jabatan=document.getElementById('n_jabatan').value;
	
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listcombo'; 
	var param = {n_jabatan:n_jabatan,a_alamat_kantor:a_alamat_kantor,c_eselon:c_eselon,c_lokasi_unitkerja:c_lokasi_unitkerja,eseloni:eseloni,eselonii:eselonii,eseloniii:eseloniii,eseloniv:eseloniv};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);
		if(c_lokasi_unitkerja=='1'){
		getEselon();
		}
		
	});
}

function getEselon(){
var esl =document.getElementById('c_eselon').value;
if (esl=='01' || esl=='02')
	{
		document.forms[0].c_eselon_ii.disabled = "disabled" ;
		document.forms[0].c_eselon_iii.disabled = "disabled" ;
		document.forms[0].c_eselon_iv.disabled = "disabled" ;
		document.forms[0].c_eselon_v.disabled = "disabled" ;

	}
 else if (esl=='03' || esl=='04')
	{
		document.forms[0].c_eselon_ii.disabled = false ;
		document.forms[0].c_eselon_iii.disabled = "disabled" ;
		document.forms[0].c_eselon_iv.disabled = "disabled" ;
		document.forms[0].c_eselon_v.disabled = "disabled" ;
	}
	
else if (esl=='05' || esl=='06')
	{
		document.forms[0].c_eselon_ii.disabled = false ;
		document.forms[0].c_eselon_iii.disabled = false ;
		document.forms[0].c_eselon_iv.disabled = "disabled" ;
		document.forms[0].c_eselon_v.disabled = "disabled" ;
	}
else if (esl=='07' || esl=='08')
	{
		document.forms[0].c_eselon_ii.disabled = false ;
		document.forms[0].c_eselon_iii.disabled = false ;
		document.forms[0].c_eselon_iv.disabled = false ;
		document.forms[0].c_eselon_v.disabled = "disabled" ;
	}
else if (esl=='09')
	{
		document.forms[0].c_eselon_ii.disabled = false ;
		document.forms[0].c_eselon_iii.disabled = false ;
		document.forms[0].c_eselon_iv.disabled = false ;
		document.forms[0].c_eselon_v.disabled = false ;
	}
else	
	{
		document.forms[0].c_eselon_ii.disabled = false ;
		document.forms[0].c_eselon_iii.disabled = false ;
		document.forms[0].c_eselon_iv.disabled = false ;
		document.forms[0].c_eselon_v.disabled = false ;
	} 	
}
</script>	

