<? require_once 'Zend/View.php';
   require_once 'share/tanggal.php'; 
   
	$ctrlDate = new tanggal(); 
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   		
   for ($i = 0; $i < 60; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }
   $biayaList = array("-"=>"--Pilih--","B"=>"Beasiswa","NB"=>"Non Beasiswa");	

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}

?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_pend_ijazah").datepicker();
	});
</script>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/listpendidikan','<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/pendidikanjs');">Pendidikan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Pendidikan
			</div>	        
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Data Pendidikan</h2>	
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		<form id="formpendidikan" method="post" name="formpendidikan">		
	<div class="panel">
		<div class="spacer"></div> 						

			<div id="target">
			<? 
						if ($this->jenipend=='1' || $this->jenipend=='2'){include("pendidikanbview.phtml");}
						else{include("pendidikanaview.phtml");}
			?>
			</div>
			<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
				<tr>
					
					<td></td>
					<td align="right">
						<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/listpendidikan','');"> 
					</td>
				</tr>
			</table>	
		
	</div>
	</form>
</div>
