<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();

?>
<table width="100%"  id="listcombo">
	<tr>
		<td width="25%" align="left">&nbsp;</td>
		<td width="20%" align="right">Lokasi</td>
		<td width="2%">:</td> 
		<td align="left">					
			<?
				$jmlLokList=count($this->lokasiList);
				$lokList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlLokList; $i++) {
					$lokList[trim((string)$this->lokasiList[$i]->c_lokasi)] = (string)$this->lokasiList[$i]->n_lokasi;			 
					}
				$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo3('targetesli')"); 
				echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="right">Eselon I</td>
		<td align="right">:</td> 
		<td align="left">					
			<?
				$jmleseloniList=count($this->eseloniList);
				$eseloniList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniList; $i++) {
						$eseloniList[trim((string)$this->eseloniList[$i]->c_eselon_i).";".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
					}
				$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo3('targeteslii')");  	
				echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="right">Eselon II</td>
		<td align="right">:</td> 
		<td align="left">				
			<?
				$jmleseloniiList=count($this->eseloniiList);
				$eseloniiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiList; $i++) {
						$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii).";".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
					}
				if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo3('targetesliii')");}
				else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo3('targetesliii')");}
				echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="right">Eselon III</td>
		<td align="right">:</td> 
		<td align="left">					
			<?
				$jmleseloniiiList=count($this->eseloniiiList);
				$eseloniiiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiiList; $i++) {
						$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_iii).";".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
					}
				
				if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo3('targetesliv')");  	}				
				else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo3('targetesliv')");}
				
				echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="right">Eselon IV</td>
		<td align="right">:</td> 
		<td align="left">				
			<?
				$jmleselonivList=count($this->eselonivList);
				$eselonivList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonivList; $i++) {
						$eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv).";".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
					}
				if ($ceseloncpns>=7){
				$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo3('targeteslv')"); 
				}
				else{
				$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo3('targeteslv')"); 
				}
				
				
				echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="right">Eselon V</td>
		<td align="right">:</td> 
		<td align="left">				
			<?
				$jmleselonvList=count($this->eselonvList);
				$eselonvList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonvList; $i++) {
						$eselonvList[trim((string)$this->eselonvList[$i]->c_eselon_v).";".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
					}
				if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}				
				else{$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}
				echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 	
			?>
		</td>
	</tr>	
</table>
