<? require_once 'Zend/View.php';
   require_once 'share/pesan.php';
require_once 'share/halaman_list.php';

   $ctrlFrm = new Zend_View();
   $pesan = new pesan();
   $halaman = new halaman_list();

	  
$jumkelompokList = count($this->listKelompok);     
?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Referensi II
			</div>
	        <a name="top"></a>
<?
$proses		= $this->proses;
$keterangan	= $this->keterangan;
$status		= $this->status;
echo $pesan->show_message($proses, $keterangan, $status);
?>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Referensi Kelompok Diklat Teknis</h2>

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  
<div class="add" title="Tambah Data" onclick="openFormKelompok('insert','','');"></div>
<?	if ($jumkelompokList == 0) {
		echo "<font color=\"red\">Data Referensi Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center" width="50%">
			<tr>
		    <th width="10%">Kode Kelompok</th>
			<th width="80%">Nama Kelompok</th>
			<th colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumkelompokList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->listKelompok as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				
				<td><?php  echo $this->escape($val['c_kelompok']);?></td>
				<td><?php  echo $this->escape($val['n_kelompok']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="openFormKelompok('update','<?=trim($this->escape($val['c_kelompok']))?>');"></div>	
				</td>
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusKelompok('kelompok','<?=trim($this->escape($val['c_kelompok']))?>','<?=trim($this->escape($val['n_kelompok']))?>')"></div>
				</td>	
		  </tr>
	<?php endforeach; ?> 		  	  
<?	}	?>
	</table>									
	<?php
	$totalData = $this->totalData;
	$numToDisplay = $this->numToDisplay;
	$currentPage = $this->currentPage;
	$modul	= $this->basePath.'/sdmmodule/refkelompok/listkelompok';
	echo $halaman->halamanList($totalData, $numToDisplay, $currentPage, $modul);

	?>					
									
	</fieldset>		 
	</form>
