function openFormJurusan(par,c_jurusan,n_jurusan,q_strata){
	var url = "<?php echo $this->basePath; ?>/sdmmodule/refjurusan/jurusanolahdata";
	var opt = {par:par, c_jurusan:c_jurusan, n_jurusan:n_jurusan,q_strata:q_strata};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			//jQuery("#formjurusan").ajaxForm(maintain_jurusan);
		});		
} 

function insertJurusan(){
	jQuery("#formjurusan").ajaxForm(maintain_jurusan);
}

var maintain_jurusan = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formjurusan").ajaxForm(maintain_jurusan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/refjurusan/insertjurusan',
	type: 'post',
	resetForm: false
};

function updateJurusan(){
	jQuery("#formjurusan").ajaxForm(update_jurusan);
}

var update_jurusan = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formjurusan").ajaxForm(maintain_jurusan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/refjurusan/updatejurusan',
	type: 'post',
	resetForm: false
};

function HapusJurusan(param1, param2, param3){
	if(ConfirmDelete(param1, param3))
	{	//alert("test");
		handler = '<?php echo $this->basePath; ?>/sdmmodule/refjurusan/deletejurusan';
		var opt = {c_jurusan : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	} 
}
