<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmJabatanList = count($this->nmJabatanList);  
?>
<div id="backgroundPopup"></div>
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
		<tr>
		<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
		</tr>
		</table>
		<div style="overflow: hidden;">
			<div class="wrap">
				<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h2 class="title">Daftar Nama Jabatan</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
						   <table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl2" width="100%">
								<tr>
									<th class="nosort" width="4%">No.</th>
									<th>Nama Jabatan</th>
									<th>Kode Jabatan</th>
								</tr> 
<? 		if ($jmlnmJabatanList == 0) {?>
								<tr class="event">
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
<?		}else{
				foreach ($this->nmJabatanList as $key => $val):  
										if ($key%2==0) { ?>
										<tr class="event">
										<? } else if ($key%2==1) { ?>
										<tr class="event2">
										<? } 
										$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
										?>
											<td class="clcenter"><?php echo $noUrut;?></td>											
											<td><a href="#" onclick="pilihData('<?php echo $this->escape($val['c_jabatan']);?>','<?php echo $this->escape($val['n_jabatan']);?>','<?php echo $this->escape($val['c_eselon']);?>')"><?php echo $this->escape($val['n_jabatan']);?></a></td>
											<td align="left"><?php echo $this->escape($val['c_jabatan']);?></td>	
											
										</tr>
<?php 
				endforeach;}
?>
							
							</table>
						<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>
		</div>
	</div>
	
<script>
function pilihData(cJabat,nJabat,cEselon){
	document.getElementById('n_jabatan').value=nJabat;
	document.getElementById('c_jabatan').value=cJabat;
	closeDetil();
}
</script>