<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldataPraTpm = count($this->dataPraTpm);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong> TPM &nbsp;
			<strong>&#8250;</strong>&nbsp;Daftar TPM
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $this->pesan;?></h2>				
	</div>
	<h2 class="title">Daftar TPM</h2>
<div class="panel">	

	<form action="" method="post"> 
		<fieldset class="fields"> 
Periode : <input type="text" name="periode" id="periode" value="<?echo $this->periode?>" size="5">
	  <input type="button" value="Cari" onclick="javascript:cariPeriode();">
	<br>
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th width="10%">Nomor Surat</th>
			<th width="15%">Usulan Jabatan</th>
			<th width="5%">Tanggal</th>
			<th>Unit Kerja</th>
			<th width="4%">&nbsp;</th>
		</tr>

<? 		if (count($this->dataPraTpm) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->dataPraTpm as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				if ($usulan_id!=$usulan_id2){
				$usulan_nomor=$this->escape($val['usulan_nomor']);
				$usulan_keterangan=$this->escape($val['usulan_keterangan']);
				$tvinstansi_kd=$this->escape($val['tvinstansi_kd']);
				$tpm_tgl=$this->escape($val['mod_date']);
				}
				else{
				$usulan_nomor="";
				$usulan_keterangan="";
				$tvinstansi_kd="";
				$tpm_tgl="";
				}
				$usulan_id2=$this->escape($val['usulan_id']);
				?>
					<td align="left"><?php echo $this->escape($val['usulan_nomor']);?></td>
					<td align="left"><?php echo $this->escape($val['n_jabatan']);?></td>					
					<td class="clcenter"><?php echo $this->escape($val['mod_date']);?></td>
					<td align="left">
					<?php 
					echo $this->escape($val['neselon4']).", ".$this->escape($val['neselon3']).", ".$this->escape($val['neselon2']).", ".$this->escape($val['neselon1']);
					?>
					</td>								
					<td class="clcenter"><img src="/images/page.gif" title="Cetak SK" class=link onclick="cetaksk('<?=$usulan_id?>')" ></td>				
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>		 
	</form>
	
<script>

function cetaksk(usulan_id){
	var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/sktpm'; 
	var param = {usulan_id:usulan_id};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);
	});
}
function cariPeriode(){
	var periode=document.getElementById('periode').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/daftartpm'; 
	var param = {periode:periode};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);
	});
}

</script>
