<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/halaman_list.php'; 
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmPegList = count($this->PegawaiList);  
$halaman = new halaman_list(); 
?>
<div id="backgroundPopup"></div>

	<div id="popupContact">

		<div style="overflow: hidden;">
			<div class="wrap">
				<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h2 class="title">Usulan TPM</h2>					
					<div class="inner" id="targettbl">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div>
<div class="delete" title="Close" onclick="closeDetil()"></div>
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th>Nomor Surat</th>
			<th>Usulan Jabatan</th>
			<th>Tanggal</th>
			<th>Unit Kerja</th>
			<th>Periode</th>
			<th>Keterangan</th>
		</tr> 
<? 		if (count($this->dataTpmUsul) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
								
				foreach ($this->dataTpmUsul as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				$usulan_keterangan=$this->escape($val['usulan_keterangan']);
				$n_jabatan=$this->escape($val['n_jabatan']);
				$mod_date=$this->escape($val['mod_date']);
				$tvinstansi_kd=$this->escape($val['tvinstansi_kd']);
				$unitkerja=trim($this->escape($val['unitkerja']));
				$periode_text=$this->escape($val['periode_text']);
				$periode_keterangan=$this->escape($val['periode_keterangan']);
				$usulan_nomor=$this->escape($val['usulan_nomor']);

				$c_eselon_i=$this->escape($val['c_eselon_i']);
				$c_eselon_ii=$this->escape($val['c_eselon_ii']);
				$c_eselon_iii=$this->escape($val['c_eselon_iii']);
				$c_eselon_iv=$this->escape($val['c_eselon_iv']);
				$c_parent=$this->escape($val['c_parent']);
				$c_satker=$this->escape($val['c_satker']);
				
				$n_unitkerja=$this->escape($val['n_unitkerja']);				
				

				$neselon1=$this->escape($val['neselon1']);
				$neselon2=$this->escape($val['neselon2']);
				$neselon3=$this->escape($val['neselon3']);
				$neselon4=$this->escape($val['neselon4']);
								
				?>
					<td><a href="#" onclick="pilihData('<?php echo $usulan_id;?>','<?php echo $usulan_nomor;?>','<?php echo $n_jabatan;?>','<?php echo $mod_date;?>','<?php echo $unitkerja;?>','<?php echo $periode_text;?>','<?php echo $periode_keterangan;?>','<?php echo $c_eselon_i;?>','<?php echo $c_eselon_ii;?>','<?php echo $c_eselon_iii;?>','<?php echo $c_eselon_iv;?>','<?php echo $c_satker;?>','<?php echo $c_parent;?>','<?php echo $neselon1;?>','<?php echo $neselon2;?>','<?php echo $neselon3;?>','<?php echo $neselon4;?>')"><?php echo $this->escape($val['usulan_nomor']);?></a></td>
					<td align="left"><?php echo $this->escape($val['n_jabatan']);?></td>					
					<td align="center"><?php echo $this->escape($val['mod_date']);?></td>
					<td align="left"><?php echo $this->escape($val['unitkerja']);?></td>
					<td align="left"><?php echo $this->escape($val['periode_text']);?></td>
					<td align="left"><?php echo $this->escape($val['periode_keterangan']);?></td>
				</tr>
				<?php endforeach;}?>	
	</table>
				<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>
		</div>
	</div>

<script>
function pilihData(usulan_id,usulan_nomor,usulan_keterangan,mod_date,tvinstansi_kd,periode_text,periode_keterangan,c_eselon_i,c_eselon_ii,c_eselon_iii,c_eselon_iv,c_satker,c_parent,neselon1,neselon2,neselon3,neselon4){
	document.getElementById('usulan_id').value=usulan_id;
	document.getElementById('usulan_nomor').value=usulan_nomor;	
	document.getElementById('n_jabatan').value=usulan_keterangan;	
	document.getElementById('mod_date').value=mod_date;
	document.getElementById('unitkerja').value=tvinstansi_kd;
	document.getElementById('periode_text').value=periode_text;
	document.getElementById('periode_keterangan').value=periode_keterangan;
	
	document.getElementById('c_eselon_i').value=c_eselon_i;
	document.getElementById('c_eselon_ii').value=c_eselon_ii;
	document.getElementById('c_eselon_iii').value=c_eselon_iii;
	document.getElementById('c_eselon_iv').value=c_eselon_iv;
	document.getElementById('c_satker').value=c_satker;
	document.getElementById('c_parent').value=c_parent;


	
if (c_eselon_i=='03' || c_eselon_i=='04' || c_eselon_i=='05')
	{
		$("#unitkerjay").css("display","block");
		$("#unitkerjax").css("display","none");
	document.getElementById('n_eselon_iy').value=neselon1;
	document.getElementById('n_eselon_iiy').value=neselon2;
	document.getElementById('n_eselon_iiiy').value=neselon3;
	document.getElementById('n_eselon_ivy').value=neselon4;			
	}
else{
		$("#unitkerjax").css("display","block");
		$("#unitkerjay").css("display","none");
	document.getElementById('n_eselon_ix').value=neselon1;
	document.getElementById('n_eselon_iix').value=neselon2;
	document.getElementById('n_eselon_iiix').value=neselon3;
	document.getElementById('n_eselon_ivx').value=neselon4;			
}

	
	closeDetil();
}
</script>