<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldptigaList = count($this->dptigaList);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong>&#8250;</strong>TPM
			<strong>&#8250;</strong>Usulan TPM
	</div>

<!--<div class="search-panel">-->
	<form method="post" id="frmCariUsulanTPM" name="frmCariUsulanTPM">
<!--	
	<table width="100%" border="0" cellpadding="0" cellspacing="1" align="center">
	<tr>
	<td align=left valign=center>
	<?
	// $status = array(""=>"--Pilih--",
						// "usul"=>"Usulan",
						// "proses"=>"Proses");
	// echo $ctrlFrm->formSelect('status', $this->status, null, $status);						
?>
<!--&nbsp;&nbsp;-->
<?
/* 	$kategoriCari = array(""=>"--Pilih--",
						"usulan_nomor"=>"No. Surat",
						"n_jabatan"=>"Usulan Jabatan");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari); */						
?>
<!--	<input type="text" id="carii" name="carii" align="center" value ="<? //echo $this->katakunciCari;?>">
	<input type="button" name="cari" value ="Search" onclick="javascript:usulantpmlist();">
-->
<!--
Periode : <input type="text" name="periode" id="periode" value="<?echo $this->periode?>" size="5">
	  <input type="button" value="Cari" onclick="javascript:cariPeriode();">	
	</td>
	</tr>
				
</table>
-->

</form>
<!--</div>-->

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Usulan TPM</h2>
<div class="panel">	
Periode : <input type="text" name="periode" id="periode" value="<?echo $this->periode?>" size="5">
	  <input type="button" value="Cari" onclick="javascript:cariPeriode();">
	<form action="" method="post"> 
		<fieldset class="fields"> 
<div class="add" title="Tambah Data" onclick="usulTpmM('insert');"></div>
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th>Nomor Surat</th>
			<th>Usulan Jabatan</th>
			<th>Tanggal</th>
			<th>Unit Kerja</th>
			<th>Periode</th>
			<th>Keterangan</th>
			<th width="5%" colspan="2">&nbsp;</th>
		</tr> 
<? 		if (count($this->dataTpmUsul) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
								
				foreach ($this->dataTpmUsul as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				?>
					<td align="left"><?php echo $this->escape($val['usulan_nomor']);?></td>
					<td align="left"><?php echo $this->escape($val['n_jabatan']);?></td>					
					<td align="center"><?php echo $this->escape($val['mod_date']);?></td>
					<td align="left">
					<?php 

					echo $this->escape($val['neselon4']).", ".$this->escape($val['neselon3']).", ".$this->escape($val['neselon2']).", ".$this->escape($val['neselon1']);
					?>
					</td>
					<td align="left"><?php echo $this->escape($val['periode_text']);?></td>
					<td align="left"><?php echo $this->escape($val['periode_keterangan']);?></td>
					<? if ($this->escape($val['tpm_status']) != '2') { ?> 
					<td class="clcenter">
						<div class="edit" title="Ubah Data" onclick="usulTpmM('update','<?=$usulan_id?>');"></div>	
					</td>
					
						<td class="clcenter">
							<div class="delete" title="Hapus Data"  onClick="javascript:HapusUsulTpm('<?=$usulan_id?>')"></div>
						</td>	
					<? 
					} else{
					?>
					
					<td class="clcenter">
						<div class="view" title="Ubah Data" onclick="usulTpmM('view','<?=$usulan_id?>');"></div>	
					</td>
					<td class="clcenter">&nbsp;</td>	
					<?}?>	
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>		 
	</form>
	
<script>
function usulantpmlist()
{
	//status = document.getElementById('status').value;
	kategoriCari = document.getElementById('kategoriCari').value;
	carii = document.getElementById('carii').value;
	//var param = {kategoriCari:kategoriCari,carii:carii,status:status};
	var param = {kategoriCari:kategoriCari,carii:carii};
	var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/listusultpm';
	jQuery.get(url,param,function(data) {
	jQuery("#tableview").html(data);
	});
}

function cariPeriode(){
	var periode=document.getElementById('periode').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/listusultpm'; 
	var param = {periode:periode};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);
	});
}
</script>