<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" bgcolor="#DDDDDD">
	<!--head>
		<LINK href="<?echo $this->baseUrl;?>/css/adm/style.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/style_adm.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/coloring_adm.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/load.css" type="text/css" rel="stylesheet">

		<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">

		<!--<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.js"></script>-->
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-1.6.2.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-ui-1.8.14.custom.min.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.form.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/navigation.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/popup.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/datepicker.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/global.js"></script>

		<script>
			function checkPasswordSemula(){
	var userid = document.getElementById('userid').value;
	var passwordLama = document.getElementById('userPasswdLama').value;
	
	url = "<?php echo $this->basePath; ?>/admmodule/admuser/checklogin"
	
	var opt = {userid : userid , passwordLama:passwordLama};
	jQuery.get(url,opt,function(data) {
	
		if(data != '1'){
			alert('Password Semula Tidak Sesuai.');
			document.getElementById('userPasswdLama').value = '';
			document.getElementById('userPasswdLama').focus();
		}
	});
}

function checkPasswd(){
	var pwd1 = document.getElementById('userPasswd').value;
	var pwd2 = document.getElementById('userPasswd2').value;
	
	if(pwd1 != pwd2){
		alert('Password dan Ulangi Password Harus Sama.');
		document.getElementById('userPasswd2').value = '';
		//document.getElementById('userPasswd2').focus();
	}
}

function ubahPassword(){
	jQuery("#frmuserubahpassword").ajaxForm(ubahPassword_opt);
}

var ubahPassword_opt = {
	target : '#targetPopup',
	url: '<?php echo $this->basePath; ?>/admmodule/admuser/prosesubahpassword',
	beforeSubmit : function(){
	},
	success : function() {
		window.close();
		//alert('Ubah Paswsword Berhasil.');
	},
	type: 'post', 
	resetForm: false
};

/* akhir cdr ubah password masing-masing user */
/*--------------------------------------------*/

		</script>
	</head-->
	
<body bgcolor="#CCFFCC">

<? 
   require_once 'Zend/View.php';
   require_once "service/adm/Adm_Admmenu_Service.php";
   
   
   $ctrlFrm = new Zend_View();
   $admmenu_serv = Adm_Admmenu_Service::getInstance();
   

$ctrlFrm = new Zend_View();
?>

		<h2 class="title">Ubah Password</h2>					
		<form method="post" name="frmuserubahpassword" id="frmuserubahpassword">
			<table width="100%" class="std">
				<tr>
					<td>Password Semula</td>
					<td>:</td>
					<td>
						<?php 
						$passwdAtrib = array("size"=>"35",
									"maxlength"=>"35",
									"onBlur" => "checkPasswordSemula();"
									);
						echo $ctrlFrm->formPassword('userPasswdLama', $userPasswdLama, $passwdAtrib);
						echo $ctrlFrm->formHidden('userid', $this->userid, $useridAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>
					<?php 
					if ($perintah == 'ubahPassword'){
						echo "Password Baru";
					} else {
						echo "Password";
					}
					?>
					</td>
					<td>:</td>
					<td>
						<?php 
						$passwdAtrib = array("id" => "userPasswd",
									"size"=>"35",
									"maxlength"=>"35"
									);
						echo $ctrlFrm->formPassword('userPasswd', $userPasswd, $passwdAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>Ulangi Password</td>
					<td>:</td>
					<td>
						<?php 
						$passwd2Atrib = array("id" => "userPasswd2",
									"size"=>"35",
									"maxlength"=>"35",
									"onBlur" => "javascript:checkPasswd();"
									);
						echo $ctrlFrm->formPassword('userPasswd2', $userPasswd2, $passwd2Atrib);
						?>
					</td>
				</tr>
				<tr>
					<td align="right" colspan="3">
						<?php
						$attrBatal = array("onClick" => "selectWindow.close();");
						echo $ctrlFrm->formSubmit('perintah', 'Batal', null); 
						$attrSimpan = array("onClick" => "ubahPassword();");
						echo $ctrlFrm->formSubmit('perintah', 'Simpan', $attrSimpan); 
						?>
					</td>
				</tr>
			</table>
		</form>
		<span class="corners-bottom"><span></span></span>
<div id="targetPopup"></div>

	</body>
</html>