<? 
   require_once 'Zend/View.php';
   require_once "service/adm/Adm_Admmenu_Service.php";

   
   $ctrlFrm = new Zend_View();
   $admmenu_serv = Adm_Admmenu_Service::getInstance();
   

$ctrlFrm = new Zend_View();
?>
<div id="backgroundPopup2" >
	<div id="popupContact2">
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr class="event">
				<td>
					<h2>Ganti Kata Kunci</h2>
				</td>
				<td>
					<div class="delete" title="Close" onclick="closeDetil2()"></div>
				</td>
			</tr>
		</table>
		<br>
		<form method="post" name="frmgantipassword" id="frmgantipassword">
			<table width="100%" class="std">
				<tr>
					<td>Password Semula</td>
					<td>:</td>
					<td>
						<?php 
						echo $ctrlFrm->formHidden('userid', $this->userid, null);
						$passwdAtrib = array("size"=>"35",
											"maxlength"=>"35",
											"onBlur" => "checkPasswordSemula();"
											);
						echo $ctrlFrm->formPassword('userPasswdLama', $userPasswdLama, $passwdAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>Password Baru</td>
					<td>:</td>
					<td>
						<?php 
						$passwdAtrib = array("id" => "userPasswd",
											"size"=>"35",
											"maxlength"=>"35"
											);	
						echo $ctrlFrm->formPassword('userPasswd', $userPasswd, $passwdAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>Ulangi Password</td>
					<td>:</td>
					<td>
						<?php 
						$passwd2Atrib = array("id" => "userPasswd2",
											"size"=>"35",
											"maxlength"=>"35",
											"onBlur" => "javascript:checkPasswd();"
											);
						echo $ctrlFrm->formPassword('userPasswd2', $userPasswd2, $passwd2Atrib);
						?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<div class="right">
							<input type="button"    value="Kembali" onClick="javascript:closeDetil2();"> 
							<input type="reset"   value="Ulangi"> 
							<?php 
								$simpanAttrib = array("onClick" => "javascript:prosesGantiPassword();");
								echo $ctrlFrm->formSubmit('perintah', 'Simpan', $simpanAttrib);
							?>
						</div>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>	