<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<LINK href="<?echo $this->baseUrl;?>/css/adm/style.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/style_adm.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/coloring_adm.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/popup.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/confirm.css" type="text/css" rel="stylesheet">
		<LINK href="<?echo $this->baseUrl;?>/css/adm/ui.datepicker.css" type="text/css" rel="stylesheet">
		<link type="text/css" href="<?echo $this->baseUrl;?>/css/ui-lightness/jquery-ui-1.8.14.custom.css" rel="stylesheet" />
		<LINK href="<?echo $this->baseUrl;?>/css/load.css" type="text/css" rel="stylesheet">

		<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">

		<!--<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.js"></script>-->
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-1.6.2.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-ui-1.8.14.custom.min.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.form.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/navigation.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/popup.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/datepicker.js"></script>
		<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/global.js"></script>

	</head>
	<body>

<? 
   require_once 'Zend/View.php';
   require_once "service/adm/Adm_Admmenu_Service.php";

   
   $ctrlFrm = new Zend_View();
   $admmenu_serv = Adm_Admmenu_Service::getInstance();
   

$ctrlFrm = new Zend_View();
?>
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tbl">
			<tr class="event">
				<td>
					<h2>Ganti Kata Kunci</h2>
				</td>
				<td>
					<div class="delete" title="Close" onclick="closeDetil2()"></div>
				</td>
			</tr>
		</table>
		<br>
		<form method="post" name="frmgantipassword" id="frmgantipassword">
			<table width="100%" class="std">
				<tr>
					<td>Password Semula</td>
					<td>:</td>
					<td>
						<?php 
						echo $ctrlFrm->formHidden('userid', $this->userid, null);
						$passwdAtrib = array("size"=>"35",
											"maxlength"=>"35",
											"onBlur" => "checkPasswordSemula();"
											);
						echo $ctrlFrm->formPassword('userPasswdLama', $userPasswdLama, $passwdAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>Password Baru</td>
					<td>:</td>
					<td>
						<?php 
						$passwdAtrib = array("id" => "userPasswd",
											"size"=>"35",
											"maxlength"=>"35"
											);	
						echo $ctrlFrm->formPassword('userPasswd', $userPasswd, $passwdAtrib);
						?>
					</td>
				</tr>
				<tr>
					<td>Ulangi Password</td>
					<td>:</td>
					<td>
						<?php 
						$passwd2Atrib = array("id" => "userPasswd2",
											"size"=>"35",
											"maxlength"=>"35",
											"onBlur" => "javascript:checkPasswd();"
											);
						echo $ctrlFrm->formPassword('userPasswd2', $userPasswd2, $passwd2Atrib);
						?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<div class="right">
							<input type="button"    value="Kembali" onClick="javascript:closeDetil2();"> 
							<input type="reset"   value="Ulangi"> 
							<?php 
								$simpanAttrib = array("onClick" => "javascript:prosesGantiPassword();");
								echo $ctrlFrm->formSubmit('perintah', 'Simpan', $simpanAttrib);
							?>
						</div>
					</td>
				</tr>
			</table>
		</form>
	</body
</html>	