<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmlPegawaiList = count($this->pegawaiList);

?>
<?if ($this->wewenang=='O'){?>		
	<div class="add" title="Tambah Data" onclick="CpnsM('insert','');"></div>
<?}?>	
	   
   <table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
		<tr>
			<th class="nosort" width="5%">No.</th>
			<th width="62%">Biodata</th>
			<th width="20%">Nama Jabatan</th>
			<th width="5%">&nbsp;</th>
		</tr> 
<? 		if ($jmlPegawaiList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->pegawaiList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					$e_jabatan='';
					$pangkat = $this->escape($val['n_pangkat']);
					$golongan = $this->escape($val['n_golongan']);
					$golPangkat = $golongan." - ".$pangkat;
					$n_lokasi_unitkerja=$this->escape($val['n_lokasi_unitkerja']);
					$n_eselon=$this->escape($val['n_eselon']);
					$n_jabatan=$this->escape($val['n_jabatan']);
					$tmtkgb = $this->escape($val['d_tmt_kgb']);
					$e_jabatan	= $this->escape($val['e_jabatan']);
					$n_status_kepegawaian="";
					if($this->escape($val['c_peg_status'])=='MIL'){$n_status_kepegawaian="/".$this->escape($val['n_status_kepegawaian']);}
				?>
					<td class="clcenter"><?php echo $noUrut;?></td>
					<td width="30%">
					<table border="0" cellspacing="1" cellpadding="2" class="std">
						<tr>
						<td width="10%">Nama</td>
						<td width="1%">:</td>
						<td width="52%"><?php echo ''.($this->escape($val['n_peg_gelardepan']) != '' ? $this->escape($val['n_peg_gelardepan']) .'. ' :'');?><?php echo $this->escape($val['n_peg']);?><?php echo ''.($this->escape($val['n_peg_gelarblkg']) != '' ? ', '.$this->escape($val['n_peg_gelarblkg']) : '' );?></td>
						<td width="10%">Jns. Kel</td>
						<td width="1%">:</td>
						<td width="25%">
						<?php 
							if($this->escape($val['c_peg_jeniskelamin'])=="L"){echo "Laki-laki";}
							if($this->escape($val['c_peg_jeniskelamin'])=="P"){echo "Perempuan";}
						?>
						</td>
						</tr>
						<tr>
						<td>Nip</td>
						<td>:</td>
						<td><?php echo $this->escape($val['i_peg_nip_new']);?></td>
						<td>Eselon</td>
						<td>:</td>
						<td><?php echo $n_eselon;?></td>
						</tr>
						<tr>
						<td>Gol/Pangkat</td>
						<td>:</td>
						<td><?php echo $golPangkat;?></td>
						<td>Stat.Peg.</td>
						<td>:</td>
						<td><?php echo $this->escape($val['n_peg_status']).$n_status_kepegawaian;?></td>						
						</tr>
					
					</table>
					</td>	
				    <td width="50%"><?=$e_jabatan;?></td>
				    
<?if($this->wewenang=='E'){?>
					<td class="clcenter">
					<?if ($this->escape($val['c_peg_status'])!='2CP'){?>
						<div class="view" title="lihat data" onclick="PnsM('pns','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}else{?>
						<div class="view" title="lihat data" onclick="CpnsM('update','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}?>		
					</td>
<?}else{?>
					<td class="clcenter">
					<?if ($this->escape($val['c_peg_status'])!='2CP'){?>
						<div class="edit" title="Ubah Data" onclick="PnsM('pns','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}else{?>
						<div class="edit" title="Ubah Data" onclick="CpnsM('update','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}?>		
					</td>
<?}?>	
				</tr>
				<?php endforeach;}?>
	
	</table>
<?

$orderBy=$this->orderBy;
$modul = $this->basePath."/sdmmodule/datapegawai/listpegawai?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol&c_eselon_i=$this->c_eselon_i&c_eselon_ii=$this->c_eselon_ii&c_eselon_iii=$this->c_eselon_iii&c_eselon_iv=$this->c_eselon_iv&c_lokasi_unitkerja=$this->c_lokasi_unitkerja"; 
echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>	
	 
	