<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmlPegawaiList = count($this->pegawaiList);

		
	
?>	   
	<div class="add" title="Tambah Data" onclick="insCutiM('insert','');"></div>	
   <table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
		<tr>
			<th class="nosort" width="5%">No.</th>
			<th width="10%">Nama</th>
			<th width="20%">NIP</th>
			<th width="20%">Unit Kerja</th>
			<th width="10%">Mulai Cuti</th>
			<th width="10%">Akhir Cuti</th>
			<th width="25%">No. Surat</th>
			<th width="25%">&nbsp;</th>
		</tr> 
<? if ($jmlPegawaiList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}
else{
				foreach ($this->pegawaiList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					$e_jabatan='';
					$pangkat = $this->escape($val['n_pangkat']);
					$n_lokasi_unitkerja=$this->escape($val['n_lokasi_unitkerja']);
					$n_status_kepegawaian="";
					if($this->escape($val['c_peg_status'])=='MIL'){$n_status_kepegawaian="/".$this->escape($val['n_status_kepegawaian']);}
				?>
					<td><?php echo $noUrut;?></td>
					<td><?php echo $this->escape($val['n_peg']);?></td>
					<td><?php echo $this->escape($val['i_peg_nip']);?></td>
					<td><?php echo $this->escape($val['n_unitkerja']);?></td>
					<td><?php echo $this->escape($val['d_cuti_mulai']);?></td>
					<td><?php echo $this->escape($val['d_cuti_akhir']);?></td>
					<td><?php echo $this->escape($val['i_surat_cuti']);?></td>
					<td class="clcenter">&nbsp
					<div class="edit" title="Ubah Data" onclick="updCutiM('update','<?=$this->escape($val['i_peg_nip'])?>');"></div>	
					</td>
	
				</tr>
				<?php endforeach;}?>
	
	</table>
<?

$orderBy=$this->orderBy;
$modul = $this->basePath."/sdmmodule/cuti/listpegawai?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol&c_eselon_i=$this->c_eselon_i&c_eselon_ii=$this->c_eselon_ii&c_eselon_iii=$this->c_eselon_iii&c_eselon_iv=$this->c_eselon_iv&c_lokasi_unitkerja=$this->c_lokasi_unitkerja"; 
echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>