<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   for ($i = 0; $i < 60; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }
?>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" id="targetpend">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>Pendidikan</b><h3>
								</td>
							</tr>
							<tr>
								<td width="16%">Pendidikan<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
									<?php
										$jmljenjang = count($this->nmJenjangList);														   
										$jenjangReff[''] = '--Pilih--';							
										for ($i = 0; $i < $jmljenjang; $i++) {
											$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
											$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;
										}
										$pendAtrib = array("onChange"=>"javascript:cariPend()"); 
										echo $ctrlFrm->formSelect('c_pend',$this->c_pend,$pendAtrib,$jenjangReff);
									?>								
								</td>
							</tr>
						<tr>
							<td>Nama Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								$pendidikanAtrib = array("size"=>"70","class"=>""); 
								echo $ctrlFrm->formText('n_pend_lembaga', $this->n_pend_lembaga, $pendidikanAtrib); 
							?>
							</td>
						</tr>							
						<tr>
							<td>Tahun Mulai</td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_mulai', $this->d_pend_mulai, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Akhir</td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_akhir', $this->d_pend_akhir, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Nomor Ijazah</td>
							<td>:</td> 
							<td>
							<?php 
								$noIjazahAtrib = array("size"=>"25",
												 "maxlength"=>"30",
												 "class"=>""); 
								echo $ctrlFrm->formText('i_pend_ijazah', $this->i_pend_ijazah, $noIjazahAtrib);
							 ?>
							</td>
						</tr>
						<tr>
							<td>Tanggal Ijazah</td>
							<td>:</td> 
							<td>
								<input type="text" id="d_pend_ijazah" name="d_pend_ijazah" value="<?=$this->d_pend_ijazah?>" size = "15">
								<span class="hightlight">tgl-bln-thn</span>
							</td>
						</tr>							
			</table>