function LhkpnM(par,nip,i_nomor_lhkpn,d_tahun_lapor){
	url = "<?php echo $this->basePath; ?>/sdmmodule/lhkpn/lhkpn"	
	var opt = {par:par,nip:nip,i_nomor_lhkpn:i_nomor_lhkpn,d_tahun_lapor:d_tahun_lapor};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 

var maintain_lhkpn = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.frmcatatlhkpn;
		astr= "document.frmcatatlhkpn";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/

				if((!i_peg_nip.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","Nip harus diisi....!");return false;break;}
				if((!d_tahun_lapor.value)){cekVal = sdmValidasiData(astr,"d_tahun_lapor","Tahun Pelaporan harus diisi....!");return false;break;}
				if((!i_nomor_lhkpn.value)){cekVal = sdmValidasiData(astr,"i_nomor_lhkpn","Nomor surat harus diisi....!");return false;break;}
				if((!d_lhkpn.value)){cekVal = sdmValidasiData(astr,"d_lhkpn","Tanggal LHKPN harus diisi....!");return false;break;}
		
		
				 break;
			}
		}
		
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#frmcatatlhkpn").ajaxForm(maintain_lhkpn);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/lhkpn/maintaindata',
	type: 'post',
	resetForm: false
};
function insertLhkpn(){
	jQuery("#frmcatatlhkpn").ajaxForm(maintain_lhkpn);
}