<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
   
$ctrlDate = new tanggal(); 
$ctrlFrm = new Zend_View();

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}

?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_lhkpn").datepicker();
	});
</script>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/listpendidikan','<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/pendidikanjs');">Pendidikan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data LHKPN
			</div>	        
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Data LHKPN</h2>	
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>

<form id="frmcatatlhkpn"  method="post" name="frmcatatlhkpn" >	
	<div class="panel">
		<div class="spacer"></div> 
		<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null);?>
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
		<tr>
		   <td>Tahun Laporan</td>
		   <td>:</td> 
		   <td>
				<input type="text" id="d_tahun_lapor" name="d_tahun_lapor" value="<?=$this->d_tahun_lapor?>" size="10">
				<input type="hidden" id="d_tahun_lapor2" name="d_tahun_lapor2" value="<?=$this->d_tahun_lapor?>" size="10">
		   </td> 
		</tr>
		<tr>
		   <td>Nomor Harta Kekayaan</td>
		   <td>:</td> 
		   <td>
				<input type="text" id="i_nomor_lhkpn" name="i_nomor_lhkpn" value="<?=$this->i_nomor_lhkpn?>" size="80">				
				<input type="hidden" id="i_nomor_lhkpn2" name="i_nomor_lhkpn2" value="<?=$this->i_nomor_lhkpn?>" size="80">
		   </td> 
		</tr>
		<tr>
		   <td>Formulir yang diserahkan</td>
		   <td>:</td> 
		   <td>
				<input name="c_formulira" id="c_formulira" value="A" type="checkbox" <?if ($this->c_formulira){echo "checked";}?>>&nbsp;Fomulir A <br>
				<input name="c_formulirb" id="c_formulirb" value="B" type="checkbox" <?if ($this->c_formulirb){echo "checked";}?>>&nbsp;Fomulir B
		   </td> 
		</tr>
		<tr>
		   <td>Tanggal Menyampaikan Laporan</td>
		   <td>:</td> 
		   <td>
				<input type="text" id="d_lhkpn" name="d_lhkpn" value="<?=$this->d_lhkpn?>" size="10">
		   </td> 
		</tr>
</table>
</div>			
<br>
	<div class="panel">
		<div class="spacer"></div>			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td align="right">
								<div class="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/lhkpn/lhkpnlist','');"> 
								</div>
							</td>
						</tr>
			</table>	
</div>
</form>	

</div>	

