<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=substr($this->pesancek,0,5);
	if ($pesancek=='Gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapasangan/listpasangan','<?php echo $this->basePath; ?>/sdmmodule/datapasangan/pasanganjs');">Suami/Istri</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Suami/Istri
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Data Suami/Istri</h2>
<div class="boxholder">	
		<div class="search-panel">
			<?php include "$this->leftMenu/toplink.phtml";?>
		</div>	
<br>		
<form id="formpasangan" method="post" name="formpasangan">		
	<div class="panel">
		<div class="spacer"></div> 
						<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="25%">Pasangan</td>
					<td width="2%">:</td> 
					<td>					
						<?
								
								if ($this->c_pasangan=='I'){echo "Istri";}
								elseif($this->c_pasangan=='S'){echo "Suami";}
								else {echo "-";}	
						?>
					</td>
				</tr>
				<tr>
					<td>Suami/Istri Ke
					</td>
					<td>:</td> 
					<td>					
						<?echo $this->q_pasangan;?>
					</td>
				</tr>
				<tr>
					<td>Pekerjaan</td>
					<td>:</td> 
					<td>					
						<?=$this->c_pekerjaan?>
					</td>
				</tr>
				<tr>
					<td>NIP Suami/Istri</td>
					<td>:</td> 
					<td>					
						<?=$this->i_nip_pasangan?>
					</td>
				</tr>
				<tr>
					<td>Nama Suami/Istri</td>
					<td>:</td> 
					<td>					
						<?=$this->n_nama?>
					</td>
				</tr>				
				<tr>
					<td>Tempat Lahir / Tanggal Lahir</td>
					<td>:</td> 
					<td>					
						<?=$this->a_tempat_lahir?> /
						<?=$this->d_tanggal_lahir?>
					</td>
				</tr>
				<tr>
					<td>Tanggal Menikah</td>
					<td>:</td> 
					<td>					
						<?=$this->d_tanggal_nikah?>
					</td>
				</tr>
				<tr>
					<td>Nomor KARIS/KARSU</td>
					<td>:</td> 
					<td>					
						<?=$this->i_karis?>
					</td>
				</tr>				
				<tr>
					<td>Keterangan</td>
					<td>:</td> 
					<td>
					<?php 
						echo $this->e_keterangan;
					?>
					</td>
				</tr>
			</table>				
</div>
<br>				
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td align="left">&nbsp;</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapasangan/listpasangan','');"> 
						</div>
					</td>
				</tr>			
			</table>
	</div>
</div>	
	</form>
