<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<?if ($this->par=='2'){?>
	<tr>
		<td width="25%">Pekerjaan</td>
		<td width="2%">:</td> 
		<td>					
		<input type="text" size="70" name="c_pekerjaan" id="c_pekerjaan" value="<?=$this->c_pekerjaan?>">
		</td>
	</tr>
	<tr>
		<td>NIP Suami/Istri</td>
		<td>:</td> 
		<td>					
		<input type="text" name="i_nip_pasangan" id="i_nip_pasangan" value="<?=$this->i_nip_pasangan?>" size="50">
		</td>
	</tr>
<?} else{?>
	<tr>
		<td width="25%">Pekerjaan</td>
		<td width="2%">:</td> 
		<td>					
		<input type="text" size="70" name="c_pekerjaan" id="c_pekerjaan" value="<?=$this->c_pekerjaan?>">
		</td>
	</tr>
<?}?>	
</table>