<? require_once 'Zend/View.php';
   require_once 'share/oa_date.php'; 
   
	$ctrlDate = new oa_date();     
	$ctrlFrm = new Zend_View();
	
	$thnskrg = date("Y");


	$jumAktList = count($this->aktList);
   //echo $jumIjinList;
   for ($j = 0; $j < $jumAktList; $j++) {
     $akt[$j] = array("no" =>$j+1,
						"tanggal"  			=>(string)$this->aktList[$j]['tanggal'],
						"mulai"  			=>(string)$this->aktList[$j]['mulai'],
						"selesai"  			=>(string)$this->aktList[$j]['selesai'],
						"aktifitas"			=>(string)$this->aktList[$j]['aktifitas'],
						"nmFile"			=>(string)$this->aktList[$j]['nmFile']);	
   } 
   
	$pesan = $this->pesan;

	$spath = $this->getScriptPaths();
   $this->addScriptPath($spath[0] . 'absensi');
   echo $this->render('aktifitasjs.phtml'); 

   
   $catatan = $this->catatan;
?>
<div class="contentdata-modul" id="modul">
	 <div class="navlink">
		<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
		<strong> &#8250; </strong> SDM 
		<strong> &#8250; </strong> Absensi
		<strong> &#8250; </strong> Pencatatan Akifitas
	
	</div>
	<h3 class="title">DAFTAR AKTIFITAS HARIAN PEGAWAI</h3>
	&nbsp;&nbsp;&nbsp;&nbsp;Menu ini digunakan untuk mencatat, mengubah dan menghapus aktifitas harian pegawai.
	Pilih tanggal pada 'Periode' aktifitas dan tekan tombol 'CARI' untuk melihat data aktifitas pada suatu 
	tanggal tertentu. Untuk memasukkan data aktifitas baru, tekan ikon 'Tambah Data' pada kanan atas tabel. Untuk menghapus
	atau mengubah data tekan ikon 'Hapus Data' atau 'Edit Data' pada kolom paling kanan tabel. 
	<div class="spacer"></div>
	<a name="top"></a>	
	
	
	<form id="frmCatatAkt" action="<?php echo $this->basePath; ?>/sdm/absensi/catataktifitas" method="post" name="frmCatatAkt">
		<div class="search-panel">
		<fieldset class="panel-form4">
				<dl>
					<dd class="col-left">NIP</dd>
					<dd class="dot2">:</dd>
					<dd class="col-right4">
					<?php 
						$nip = $this->escape($this->nip);
						echo $ctrlFrm->formHidden('nipH', $nip, null)."&nbsp;";
						echo $nip;
					?>
					<dd class="col-left">&nbsp;</dd>
					<dd class="dot2">&nbsp;</dd>
				</dl>
				<dl>
					<dd class="col-left">Nama</dd>
					<dd class="dot2">:</dd>
					<dd class="col-right4">
					<?php 
						$nama = $this->escape($this->nama);
						echo $nama;
					?>
					<dd class="col-left">&nbsp;</dd>
					<dd class="dot2">&nbsp;</dd>
				</dl>
				<dl>
					<dd class="col-left">Tanggal Aktifitas</dd>
					<dd class="dot2">:</dd>
					<dd class="col-right4">
					<?php 
					// $hr1 = $_POST['hr1'];
					// $bln1 = $_POST['bln1'];
					// $thn1 = $_POST['thn1'];
					// echo $ctrlDate->formTanggal_oa('hr1',$hr1,'bln1',$bln1,'thn1',$thn1); 
					
					$hr1 = $_POST['hr1'];
					$bln1 = $_POST['bln1'];
					$thn1 = $_POST['thn1'];
					$hr2 = $_POST['hr2'];
					$bln2 = $_POST['bln2'];
					$thn2 = $_POST['thn2'];
					$tgl1 = $thn1."-".$bln1."-".$hr1;
					$tgl2 = $thn2."-".$bln2."-".$hr2;
					 
					$skr=date("Y-m-d");
					$blnSkr = date("m");
					$thnSkr = date("Y");
					$hrSkr = date("d");
					//echo "hr1= ".$hr1."<br>";
					
					if (($hr1 == '--') || ($hr1 == null)){
						$hr1 = '01';
					}
					if (($bln1 == '--') || ($bln1 == null)){
						$bln1 = $blnSkr;
					}
					if ($thn1 == null) {
						$thn1 = $thnSkr;
					}
					
					if (($hr2 == '--') || ($hr2 == null)){
						$hr2 = $hrSkr;
					}
					if (($bln2 == '--') || ($bln2 == null)){
						$bln2 = $blnSkr;
					}
					if ($thn2 == null) {
						$thn2 = $thnSkr;
					}
					?>
					<?php echo $ctrlDate->formTanggal_oa('hr1',$hr1,'bln1',$bln1,'thn1',$thn1); ?> &nbsp;<b>s/d</b>&nbsp;
				    <?php echo $ctrlDate->formTanggal_oa('hr2',$hr2,'bln2',$bln2,'thn2',$thn2);  ?>&nbsp;
					
					<dd class="col-left">&nbsp;</dd>
					<dd class="dot2">&nbsp;</dd>
				</dl>
				<dl>
					<dd class="col-left">&nbsp;</dd>
					<dd class="dot2">&nbsp;</dd>
					<dd class="col-right2">
					<input id="perintah" type="submit" value="Cari" name="perintah" onClick="javascript:cariAkt();">
					<?
						//$aForm = "document.frmCatatAkt";
						// $atribSubmit = array("onclick"=>"javascript:catatAkt();");
						// echo $ctrlFrm->formSubmit('perintah', 'CATAT', $atribSubmit)."&nbsp;";
						//$atribSubmit = array("onclick"=>"javascript:cariAkt();");
						//echo $ctrlFrm->formSubmit('perintah', 'Cari', $atribSubmit)."&nbsp;";
					?>
				</dl>
		</fieldset>
		</div>
		
		<? if (!$pesan == null) {
		?>
			<div class="spacer"> </div>
			<fieldset id="message" class="confirm"><? echo $pesan; ?></fieldset>
			<div class="spacer"> </div>	
		<?}?>
		
		<div class="space-line"></div>
		<fieldset  class="panel-form">	
		<div class="title2">Aktifitas Harian Pegawai</div>
		
		<a href="#"  title="Tambah Data" class="link" onClick="javascript:tambahAkt('TAMBAH')" >
			<div class="add">
			</div>
		</a>
		
<?
	if ($jumAktList == 0) {
?>
<div class="spacer"> </div>
<center>
<?
		//echo "Data Absensi Tidak Ditemukan";
		echo "<font color='red'>Data Aktifitas Harian Tidak Ditemukan</font>";
?>
</center>

	
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
				<tr>
			    <th width="4%">No.</th>
			    <th width="10%">Tanggal</th>
			    <th width="10%">Mulai</th>
			    <th width="10%">Selesai</th>
			    <th width="46%">Aktifitas</th>
				<th width="12%">Nama File</th>
				<th width="3%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
				</tr>
		</table>
<? } else { ?>
	<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
				<tr>
			    <th width="4%">No.</th>
			    <th width="10%">Tanggal</th>
			    <th width="10%">Mulai</th>
			    <th width="10%">Selesai</th>
			    <th width="46%">Aktifitas</th>
				<th width="12%">Nama File</th>
				<th width="3%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
				</tr>
		<?php foreach ($akt as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
			
				<?php
					$tglAkt = $ctrlDate->convertTglMachineToHuman($this->escape($val['tanggal']));
					$jamAkt = $this->escape($val['mulai']);
					// $nama = $this->escape($val['nama']);
					// $nip = $this->escape($val['nip']);
					$konfDel = "Tanggal: ".$tglAkt." Jam: ".$jamAkt;
				?>
				<td class="clcenter"><?php echo $this->escape($val['no']);?> </a></td>
				<td>&nbsp;<?php echo $ctrlDate->convertTglMachineToHuman($this->escape($val['tanggal']));?> </a></td>
				<td>&nbsp;<?php echo $this->escape($val['mulai']);?></td>
				<td>&nbsp;<?php echo $this->escape($val['selesai']);?></td>
				<td>&nbsp;<?php echo $this->escape($val['aktifitas']);?></td>
				<td>&nbsp;<?php echo $this->escape($val['nmFile']);?> </a></td>
				<td class="clcenter">
				<? if ($this->escape($val['nmFile']) != '' ) { ?>
					<img src="<?php echo $this->basePath; ?>/images/file.gif" title="Lihat File Pendukung" class="link" onClick="javascript:ningali('<? echo $this->escape($val['nmFile']); ?>');"></a>
				<? }?>
				</td>
				<td class="clcenter">					
					<a href="#"  class="link" onClick="javascript:ubahAkt('UPDATE','<? echo $nip; ?>','<? echo $this->escape($val['tanggal']);?>','<? echo $this->escape($val['mulai']); ?>')">
						<div class="edit" title="Ubah Data" ></div>	
					</a>
						<div class="delete" title="Hapus Data"  onClick="javascript:hapusAktifitas('Aktifitas Harian', '<?php echo $this->escape($this->nip);?>', '<?php echo $this->escape($val['tanggal']);?>', '<? echo $this->escape($val['mulai']); ?>', '<? echo $konfDel; ?>')"></div>
				</td>
		  </tr>
	<?php endforeach;?> 		  	  
		</table>
	<? } ?>

		</fieldset>
	</form>
		  	<div class="space-line"></div>
		  	<div><a href="#top" class="top" title="Kembali ke atas">Kembali ke atas</a></div>	  	

</div>
	
