<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
require_once 'share/halaman_list.php';
$ctrlFrm = new Zend_View();
$ctrlDate = new tanggal(); 
$halaman = new halaman_list();
 $srvc = $this->srviceE;
   $bulanDesc = array("01"=>"Januari",
                      "02"=>"Februari",
                      "03"=>"Maret",
                      "04"=>"April",
                      "05"=>"Mei",
                      "06"=>"Juni",
                      "07"=>"Juli",
                      "08"=>"Agustus",
                      "09"=>"September",
                      "10"=>"Oktober",
                      "11"=>"November",
                      "12"=>"Desember");

$thnSekarang = $this->thnSekarang;
$blnSekarang = $this->blnSekarang;
$srvc = $this->srviceE;

?>
<div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong>Absensi
				<strong> &#8250; </strong>Maintain Hari Kerja
</div>
<a name="top"></a>
	<div style="overflow: hidden;">
		<div class="wrap">
			<div class="panel">
				<div class="inner">
					<span class="corners-top"><span></span></span>
					<h2 class="title">Maintain Hari Kerja</h2>
								<table border="0" cellpadding="0" cellspacing="1" class="std">								
									<tr>
										<td width="5%">&nbsp;</td> 
										<td width="30%">Periode</td>
										<td width="2%">:</td> 
										<td>
										<?										
											$thn_atr = array("style"=>"width:40px",
											"maxlength"=>"4");
											echo $ctrlFrm->formSelect('blnHariKerja', $blnSekarang, null,$bulanDesc)."&nbsp;";
											echo $ctrlFrm->formText('thnHariKerja', $thnSekarang, $thn_atr)."&nbsp;";
										?>											
										</td> 
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td>&nbsp;</td>
										<td>&nbsp;</td> 
										<td>
											<input type='button' id='iiCariPegAbsensi' value='Buat' onClick='ioCariPegAbsensi()'>&nbsp;
											<input type='button' id='iiCariPegAbsensi' value='Simpan' onClick='ioCariPegAbsensi()'>
										</td> 
									</tr>
								</table>									
<!--								
								<table border="0" cellpadding="0" cellspacing="1" class="tbl">
									<tr>
										<th rowspan='2'>No</th>			
										<th rowspan='2'>Tanggal</th>
										<th rowspan='2'>Hari</th>
										<th colspan='2'>Jam Kerja</th>
										<th colspan='2'>Jam Istirahat</th>		
										<th rowspan='2'>Status</th>
									</tr>
									<tr>
										<th>Mulai</th>			
										<th>Selesai</th>
										<th>mulai</th>
										<th>Selesai</th>
									</tr>
												<tr class="event">
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>
													<td>&nbsp;</td>								
													<td>&nbsp;</td>
												</tr>				
								</table>		
-->								
<?
echo "	
			<table align='center' border='1' cellspacing='0' cellpadding='2' class='tbl'>
				<tr>
					<th rowspan='2'>No</th>			
					<th rowspan='2'>Tanggal</th>
					<th rowspan='2'>Hari</th>
					<th colspan='2'>Jam Kerja</th>
					<th colspan='2'>Jam Istirahat</th>		
					<th rowspan='2'>Status</th>
				</tr>
				<tr>
					<th>Mulai</th>			
					<th>Selesai</th>
					<th>mulai</th>
					<th>Selesai</th>
				</tr>";
	   $hari = array("Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu");
	   $bulan = array("","Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September",
	   "Oktober","November","Desember");
	   $bln=$blnSekarang;
	   $noUrut=0;							
       for ($i=1; $i<32; $i++)
       {
          $tahunE = date("Y", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $bulanE = date("m", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $tglE = date("d", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $hariE = date("w", mktime(0, 0, 0, $bln, $i, $thnSekarang));
		  $mulaiKerja = $srvc->cekJamKerja($hariE);
		  //echo "xxxxx ".$mulaiKerja;
		  if ($bulanE==$bln)
          { 
		     $noUrut++;
		     if ($i%2==0)
			 { 
			    if (($hariE=="0") || ($hariE=="6"))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event' id='triHariKe$i'>"; 
				}
			 }
			 else
			 { 
			    if (($hariE=="0") || ($hariE=="6"))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event2' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event2' id='triHariKe$i'>"; 
				}
			 }
echo "				
					<td class='clcenter'>".$noUrut."</td>			
					<td class='clcenter'>".$tglE." ".$bulanDesc[$bulanE]." ".$tahunE."</td>			
					<td class='clcenter'>".$hari[$hariE]."</td>			
					<td class='clcenter'>";
					$mskMulai = $mulaiKerja['d_jamkerja_mulai'];
					
echo "				<input type='text' id='itMskMulai$i' name='itMskMulai$i' value='".
                    $mskMulai."' style='width:70px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$mskSelesai = $mulaiKerja['d_jamkerja_selesai'];
echo "				<input type='text' id='itMskSelesai$i' name='itMskSelesai$i' value='".
                    $mskSelesai."' style='width:70px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakMulai = $mulaiKerja['d_jamistrht_mulai'];
echo "				<input type='text' id='itBreakMulai$i' name='itBreakMulai$i' value='".
                    $breakMulai."' style='width:70px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakSelesai = $mulaiKerja['d_jamistrht_selesai'];
echo "				<input type='text' id='itBreakSelesai$i' name='itBreakSelesai$i' value='".
                    $breakSelesai."' style='width:70px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td align='left'><input type='hidden' id='ihiStatus$i' name='ihiStatus$i' value='".
					$valStatus."'>
					<input type='checkbox' id='iiStatus$i' onClick='swtStatus(this.value)' name='iiStatus$i' value='".
					$i."' class='icSetStatus' $chCkd>&nbsp;<span id='siStatusHari$i'>".$valStatus."</span>
					</td>			
				</tr>";
		  }
       }								
								

//$modul = $this->basePath."/sdm/datapegawai/pegawaisearch";
//echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>							
					<span class="corners-bottom"><span></span></span>
				</div>
			</div>
		</div>
	</div>	
