
function KesehatanM(par,id){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datakesehatan/kesehatan"	
	var opt = {par:par,id:id};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formkesehatan").ajaxForm(maintain_kesehatan);
		});		
} 
var maintain_kesehatan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formkesehatan;
		astr= "document.formkesehatan";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!n_penyakit.value)){cekVal = sdmValidasiData(astr,"n_penyakit","Nama Penyakit harus diisi....!");return false;break;}
				if((!d_rawatmulai.value)){cekVal = sdmValidasiData(astr,"d_rawatmulai","Tanggal Mulai harus diisi....!");return false;break;}
				break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formkesehatan").ajaxForm(maintain_kesehatan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datakesehatan/maintaindata',
	type: 'post',
	resetForm: false
};
function insertKesehatan(){
	jQuery("#formkesehatan").ajaxForm(maintain_kesehatan);
}

function HapusDataKesehatan(nip,id)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datakesehatan/hapusdata"
		var opt = {nip:nip,id:id};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
