<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();

	  
$jumkesehatanList = count($this->kesehatanList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Kesehatan
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Kesehatan</h2>

<?php $opr='rkes';include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">		
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	  
<div class="add" title="Tambah Data" onclick="KesehatanM('insert','');"></div>
<?}	if ($jumkesehatanList == 0) {
		echo "<font color=\"red\">Data Kesehatan Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="20%">Nama Penyakit</th>
			<th width="12%">Tanggal Sakit</th>
			<th width="12%">Tanggal Sembuh</th>
			<th width="16%">Nama Rumah Sakit</th>
			<th width="20%">Alamat Rumah Sakit</th>
			<th width="6%" colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumkesehatanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->kesehatanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					$id=trim($this->escape($val['id']));
					?>
				<td>
					<?php echo $this->escape($val['n_penyakit']);?>
				</td>
				<td><?php  echo $this->escape($val['d_rawatmulai']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_rawatakhir']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['n_rmhsakit']);?></td>
				<td><?php echo $this->escape($val['a_rmhsakit']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="KesehatanM('update','<?=trim($this->escape($val['id']))?>');"></div>	
				</td>
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataKesehatan('<?=$nip?>','<?=trim($this->escape($val['id']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
