<?  require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list();  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Utama</a> 
				<strong> &#8250; </strong>Rekapitulasi Data Pendaftar
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Rekapitulasi Data Pendaftar Tahun <?=date('Y')?></h2>
<!--	
	<div class="search-panel">
				<form id="frmSearch" method="post" name="frmSearch">
					Berdasarkan :
					<?
							// $cCol = array(""=>"--Pilih--",
									// "1"=>"Pilihan Jabatan",
									// "2"=>"Wilayah");	
							// $var =array("onchange"=>"cariData()");				
							// echo $ctrlFrm->formSelect('cCol', $this->cCol, $var, $cCol); 							
					?>						
					<input type="submit" value="Cari" onclick="javascript:cariData();">		   
				</form>						
	</div>	
<br>	
-->
<div class="right">
<input type="button"  onclick="Cetak();" value="Cetak">
</div>
<table width="50%" border="0" cellpadding="0" cellspacing="1" class="std">

<?	if ($this->dataList == 0) {
		echo "<font color=\"red\">Data Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
			<th width="15%">Pilihan Jabatan</th>
			<th width="30%">Wilayah</th>
			<th width="10%">Jumlah</th>
		</tr>
<?
	if ($this->dataList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->dataList as $key => $val): 
		$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? }?>
				<td><?php 
				if ($c_jab!=$this->escape($val['c_posisi_jabatan'])){
				echo $this->escape($val['n_posisi_jabatan']);
				}
				$c_jab=$this->escape($val['c_posisi_jabatan']);
				?></td>
				<td><?php  echo $this->escape($val['n_wilayah'])." - ".$this->escape($val['n_pengadilan']);?></td>
				<td><?php  echo $this->escape($val['jumlah']);?></td>				

		  </tr>
	<?php 
		$jmltot=$this->escape($val['jumlah'])*1+$jmltot;
		endforeach;
	?>
<?	}	?>
		<tr class="event">
			<td colspan="2">Total</td>
			<td><?=$jmltot?></td>
		</tr>
	</table>
<div id="popupview"></div>	
	</fieldset>		 
	</form>
	
<script>
function Cetak()
{
	url = "<?php echo $this->basePath; ?>/sdmmodule/hasilpendaftaranonline/cetakrekap";	
	windowOpens();
} 

function windowOpens(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 700, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

</script>		
