<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
   
$ctrlDate = new tanggal();   
   
   $ctrlFrm = new Zend_View();
 

$jumdikmilList = count($this->dikmilList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Pendidikan Kejuruan Militer
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>	

	<h2 class="title">Pendidikan Kejuruan Militer</h2>
<?php $opr = 'djml'; include "$this->leftMenu/linkdatadiklat.phtml";?>
<div class="boxholder">	
	<div class="panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	
<div class="add" title="Tambah Data" onclick="diklatMilM('insert','');"></div>
<?}	if ($jumdikmilList == 0) {
		echo "<font color=\"red\">Data Pendidikan Kejuruan Militer Tidak Ditemukan</font>";
}
?>
		<table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
				<tr>
				<th width="20%">Kelompok/Jenis</th>
				<th width="8%">Nama</th>
				<th width="8%">Tahun Masuk</th>
				<th width="8%">Tahun Lulus</th>
				<th width="15%">Status</th>
				<th width="15%">Tempat</th>
				<th width="4%" colspan="2">&nbsp;</th>
				</tr>

<?
	if ($jumdikmilList == 0) {
?>				<tr class="event">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				</tr>
<? } else { ?>				
		<?php foreach ($this->dikmilList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
				<? 
					$nip=trim($this->escape($val['i_peg_nip']));

				?>					
				<td class="clleft"><?php echo $this->escape($val['n_jenis_kel']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_kejuruanmil']);?></td>
				<td class="clleft"><?php echo ''.($this->escape($val['d_tahun_masuk']) > 0 ? $this->escape($val['d_tahun_masuk']) : '');?></td>
				<td class="clleft"><?php echo ''.($this->escape($val['d_tahun_lulus']) > 0 ? $this->escape($val['d_tahun_lulus']) : '');?></td>
				<td class="clleft"><?php echo $this->escape($val['n_status']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_tempat']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="diklatMilM('update','<?=$nip?>','<?=$this->escape($val['id'])?>');"></div>	
				</td>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDiklatMilM('<?=$nip?>','<?=$this->escape($val['id'])?>')"></div>
				</td>
<?}?>				
		  </tr>
	<?php endforeach;?> 	
	<? } ?>
	</table>									
<div id="targetdetil"></div>						
		</div>		 
		</form>
<script>
function detilPend(nip,cPend){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/detilpelatihan';
var param = {nip:nip,cPend:cPend};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}
</script>	