<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_dokumen_sk").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datask/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datask/dataskjs');">Data Pegawai</a>
				<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datask/listdatask','<?php echo $this->basePath; ?>/sdmmodule/datask/dataskjs');">Data SK Pegawai</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data SK
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Data SK</h2>	
<div class="boxholder">	
<form name="formdatask" id="formdatask" enctype="multipart/form-data" method="post" action="">
	<div class="panel">
		<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="20%">NIP<span class="hightlight">*</span></td>
					<td width="2%">:</td> 
					<td>					
						<input type="text" name="i_peg_nip" id="i_peg_nip" value="<?=$this->i_peg_nip?>" size="20" readonly="true">
					</td>
				</tr>
				<tr>
					<td>Nama<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_peg" id="n_peg" value="<?=$this->n_peg?>" size="60" readonly="true">
					</td>
				</tr>					
				<tr>
					<td>Jenis Dokumen<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>					
							<?php 
								$jmljnsDokList = count($this->jnsDokList);
								$jnsDokList[''] = '--Pilih--';
								for ($i = 0; $i < $jmljnsDokList; $i++) {									   
									$jnsDokList[(string)$this->jnsDokList[$i]->c_dokumen] = (string)$this->jnsDokList[$i]->n_dokumen;			 
								}
									$statkepegAtrib = array("onChange"=>"javascript:getStatPeg()");
									echo $ctrlFrm->formSelect('c_jns_dokumen_sk', $this->c_jns_dokumen_sk,null, $jnsDokList)
							?>							
						<input type="hidden" name="c_jns_dokumen_sk2" id="c_jns_dokumen_sk2" value="<?=$this->c_jns_dokumen_sk?>">
					</td>
				</tr>
				<tr>
					<td>Nomor Dukumen</td>
					<td>:</td> 
					<td>					
						<input type="text" name="i_dokumen_sk" id="i_dokumen_sk" value="<?=$this->i_dokumen_sk?>" size="70">
						<input type="hidden" name="i_dokumen_sk2" id="i_dokumen_sk2" value="<?=$this->i_dokumen_sk?>" size="70">
					</td>
				</tr>
				<tr>
					<td>Nama Dukumen<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_dokumen_sk" id="n_dokumen_sk" value="<?=$this->n_dokumen_sk?>" size="70">
					</td>
				</tr>				
				<tr>
					<td>Tanggal Dokumen</td>
					<td>:</td> 
					<td>
						<input type="text" name="d_dokumen_sk" id="d_dokumen_sk" value="<?=$this->d_dokumen_sk?>" size="10">
						<span class="hightlight">tgl-bln-thn</span>
					</td>
				</tr>				
				<tr>
					<td>File</td>
					<td>:</td> 
					<td>					
						<div class="fileinputs">
							<input type="file" size=55 id="e_file_sk" name="e_file_sk"  value="<? echo $this->e_file_sk?>"onChange="setvalueuplfile(this.value,'efiledok','jpg')" />
							<div class="fakefile">
								<input type="text" size=54 name="a_file" id="a_file" value="<? echo $this->e_file_sk?>"/>
							</div>
						</div>
						<input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $e_file_sk?>"/>		
					</td>
				</tr>				
	</table>
</div>
<br>
	<div class="panel">
		<div class="spacer"></div> 	
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">		
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datask/listdatask?i_peg_nip=<?=$this->i_peg_nip?>&n_peg=<?=$this->n_peg?>','');"> 
							<input type="submit" value="<?=$this->par;?>" onClick="insertDataSk()">
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
</div>	
	</form>