
function insertDataSk(){
	jQuery("#formdatask").ajaxForm(maintain_sk);
}
var maintain_sk = {

 	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formdatask;
		astr= "document.formdatask";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{				
				if((!i_peg_nip.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","NIP tidak boleh kosong....!");return false;break;}		
				if((!c_jns_dokumen_sk.value)){cekVal = sdmValidasiData(astr,"c_jns_dokumen_sk","Jenis Dokumen tidak boleh kosong....!");return false;break;}
				if((!i_dokumen_sk.value)){cekVal = sdmValidasiData(astr,"i_dokumen_sk","Nomor Dokumen tidak boleh kosong....!");return false;break;}		
				 break;
			}
		}		
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formdatask").ajaxForm(maintain_sk);
		return false;
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datask/maintaindata',
	type: 'post',
	resetForm: false
};


function setvalueuplfile(v,n,f) { 
	  if (f!="") {
	    var pass=false;
	    var af=f.split("/");
        var nval=eval("document.forms[0]."+n);
		var ext=v.substring(v.lastIndexOf(".")+1,v.length);
		if ((ext==f)||(ext=='png')||(ext=='gif')||(ext=='pdf')||(ext=='docx')||(ext=='doc')){ 
		document.forms[0].a_file.value=v; 
		}
		else{
		  alert ("Hanya untuk file berekstensi '"+f+"',jpg,gif,png,pdf,docx,doc ");
		  nval.value="";
		  document.forms[0].a_file.value=""; 
		  return;	  
		}
	  }
}


function HapusDataSk(i_peg_nip,n_peg,c_jns_dokumen_sk,i_dokumen_sk)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datask/hapusdata"
		var opt = {i_peg_nip:i_peg_nip,n_peg:n_peg,c_jns_dokumen_sk:c_jns_dokumen_sk,i_dokumen_sk:i_dokumen_sk};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function GetFile(f)
{

	url = "<?php echo $this->basePath; ?>/sdmmodule/datask/viewdokumen?f="+f;	
	windowOpens();
} 

function windowOpens(){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = 700, popH = 600;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}

function cariListPegawai(){
	jQuery("#frmSearch").ajaxForm(search);
}

var search = {
	target:'#tableview',
	beforeSubmit: function() {
		var col=document.getElementById('cCol').value;
		if(!col){
			alert("Combo Pilihan harus diisi....!") 
			return false;
			document.getElementById('cCol').focus;
		}
	
	}, 
	success:function(){
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datask/listpegawai',
	type: 'post',
	resetForm: false
};
