<? 
	require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmlPegawaiList = count($this->pegawaiList);
	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
	<a href="<? echo $this->basePath; ?>/sdm">Halaman Utama</a>&nbsp;
	<strong>&#8250;</strong>&nbsp;Daftar SK Pegawai&nbsp;
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Daftar SK Pegawai</h2>
	<div class="search-panel">
				<form id="frmSearch" method="post" name="frmSearch">
					Pencarian berdasarkan :
					<?
							$cCol = array(""=>"--Pilih--",
									"i_peg_nip"=>"NIP",
									"n_peg"=>"Nama");								
							echo $ctrlFrm->formSelect('cCol', $this->cCol, null, $cCol); 							
					?>						
					<span id="targetcari"><input type="text" name="nCol" id="nCol" value="<?echo $this->nCol?>" size="40%"></span>
					<input type="submit" value="Cari" onclick="javascript:cariListPegawai();">		   
				</form>						
	</div>	
	<div class="space-line"></div>
	<form action="" method="post"> 
		<fieldset class="fields"> 
		<table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
		<tr>
			<th width="5%">No.</th>
			<th width="15%">NIP</th>
			<th width="30%">Nama</th>
			<th>Jabatan</th>
		</tr> 
<? 		if ($jmlPegawaiList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->pegawaiList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					$pangkat = $this->escape($val['n_pangkat']);
					$golongan = $this->escape($val['n_golongan']);
					$golPangkat = $golongan." - ".$pangkat;
					$n_lokasi_unitkerja=$this->escape($val['n_lokasi_unitkerja']);
					$n_eselon=$this->escape($val['n_eselon']);
					$n_jabatan=$this->escape($val['n_jabatan']);
					$tmtkgb = $this->escape($val['d_tmt_kgb']);
					$n_status_kepegawaian="";
					if($this->escape($val['c_peg_status'])=='MIL'){$n_status_kepegawaian="/".$this->escape($val['n_status_kepegawaian']);}
				?>
					<td align="right" width="5%"><?php echo $noUrut;?></td>
					<td align="left" width="10%"><a href="#" onclick="getDataSk('<?php echo $this->escape($val['i_peg_nip']);?>','<?php echo $this->escape($val['n_peg']);?>')"><?php echo ''.($this->escape($val['i_peg_nip_new']) ? $this->escape($val['i_peg_nip_new']) : $this->escape($val['i_peg_nip']));?></a></td>
					<td align="left" width="25%"><?php echo $this->escape($val['n_peg']);?></td>
					<td align="left"><?php echo $n_jabatan." ".$this->escape($val['unitkerjalengkap']);?></td>
			
				</tr>
				<?php endforeach;}?>
	
	</table>
<div id="targetdetil"></div>
<?
$orderBy=$this->orderBy;
$modul = $this->basePath."/sdmmodule/datask/listpegawai?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol";
echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>	
</fieldset>		 
</form>

<script>
function getDataSk(i_peg_nip,n_peg){
var url = '<?php echo $this->basePath; ?>/sdmmodule/datask/listdatask';
var param = {i_peg_nip:i_peg_nip,n_peg:n_peg};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);getEselon();
	});
}
</script>		