<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmldataskList = count($this->dataskList);
  $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
	<a href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a>&nbsp;<strong>&#8250;</strong>&nbsp;SDM&nbsp;
	<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datask/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datask/dataskjs');">Data Pegawai</a>
	&#8250;</strong>&nbsp;Data SK Pegawai&nbsp;
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Data SK Pegawai</h2>
	<div class="panel">
		<div class="spacer"></div> 
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
			<tr>
				<td width="10%">NIP</td>
				<td width="2%">:</td>
				<td><input type="text" name="i_peg_nip" id="i_peg_nip" value="<?=$this->i_peg_nip?>" size="20"></td>
			</tr>
			<tr>
				<td>Nama</td>
				<td>:</td>
				<td><input type="text" name="n_peg" id="n_peg" value="<?=$this->n_peg?>" size="70"></td>
			</tr>			
		</table>
	</div>
					
	<form action="" method="post"> 
		<fieldset class="fields"> 
			   <div class="add" title="Tambah Data" onclick="DataSkM('insert','<?=$this->i_peg_nip?>','<?=$this->n_peg?>');"></div>
		<table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
		<tr>
			<th>No.</th>
			<th>Jenis Dokumen</th>
			<th>Nomor Dokumen</th>
			<th>Nama Dokumen</th>
			<th>Nama File</th>
			<th width="5%" colspan="2">&nbsp;</th>
		</tr> 
<? 		if ($jmldataskList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->dataskList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
				$c_jns_dokumen_sk=$this->escape($val['c_jns_dokumen_sk']);
				$i_dokumen_sk=$this->escape($val['i_dokumen_sk']);
				?>
					<td class="clcenter" width="5%"><?php echo $noUrut;?></td>
					<td width="25%"><?php echo $this->escape($val['n_dokumen']);?></td>
					<td width="25%"><?php echo $this->escape($val['i_dokumen_sk']);?></td>	
					<td width="25%"><?php echo $this->escape($val['n_dokumen_sk']);?></td>
					<td align="center" width="10%">
						<?$e_file_sk=$this->escape($val['e_file_sk']);?>			

					<? 
						if ($e_file_sk)
						{
					?>
				
						<a href="#"><img onClick="javascript:GetFile('<?php echo "/sdm/dosier/".$e_file_sk ?>');" src='../images/pdf.gif' title='Attachment' class='link' ><a>
					<?
						}
					?>						
					</td>					
					<td class="clcenter">
						<div class="edit" title="Ubah Data" onclick="DataSkM('pns','<?=$this->i_peg_nip?>','<?=$this->n_peg?>','<?php echo $this->escape($val['c_jns_dokumen_sk']);?>','<?php echo $this->escape($val['i_dokumen_sk']);?>');"></div>
					</td>
					<td class="clcenter">
						<div class="delete" title="Hapus Data"  onClick="javascript:HapusDataSk('<?=$this->i_peg_nip?>','<?=$this->n_peg?>','<?php echo $this->escape($val['c_jns_dokumen_sk']);?>','<?php echo $this->escape($val['i_dokumen_sk']);?>')"></div>
					</td>					
				</tr>
				<?php endforeach;}?>
	
	</table>
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">		
				<tr>
					<td>
						<div class="right">
							<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datask/listpegawai','');"> 
						</div>
					</td>
				</tr>			
			</table>	
	</fieldset>		 
	</form>

<script>
function DataSkM(par,i_peg_nip,n_peg,c_jns_dokumen_sk,i_dokumen_sk){
var url = '<?php echo $this->basePath; ?>/sdmmodule/datask/datask';
var param = {par:par,i_peg_nip:i_peg_nip,n_peg:n_peg,c_jns_dokumen_sk:c_jns_dokumen_sk,i_dokumen_sk:i_dokumen_sk};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);getEselon();
	});
}
</script>		