<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once "share/halaman.php";  

$tanggal = new tanggal();
$halaman = new halaman();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;
	   $harilst = array("Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu");
	   $bulanLst = array("01"=>"Januari","02"=>"Februari","03"=>"Maret","04"=>"April","05"=>"Mei","06"=>"Juni","07"=>"Juli",
	   "08"=>"Agustus","09"=>"September","10"=>"Oktober","11"=>"November","12"=>"Desember");
	   $absensilst = array("V"=>"Hadir & Pulang Tepat Waktu",
	                       "DL"=>"Dinas Luar",
						   "CB"=>"Cuti Bersama",
						   "C"=>"Cuti",
						   "S"=>"Sakit",
						   "I"=>"Ijin",
						   "TK"=>"Tanpa Keterangan",
						   "L"=>"Terlambat Datang",
						   "E"=>"Pulang Cepat");
					  
$thnSekarang = $this->tahunabsen;
$blnSekarang = $this->bulanabsen;
$thnSekarang2 = $this->tahunabsen2;
$blnSekarang2 = $this->bulanabsen2;
$periode = $thnSekarang.'-'.$blnSekarang; 
$periode2 = $thnSekarang2.'-'.$blnSekarang2; 
     $kodeijinlst = $this->absensimsn_serv->getKodeIjinLst();
     $jmlkodeijinlst = count($kodeijinlst);
?>
<div class="navlink">
	<a  href="<? echo $this->baseUrl; ?>/main">Halaman Utama</a> 
	<strong> &#8250; </strong> Absensi 
	<strong> &#8250; </strong> Rekap Absensi Pegawai
</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>

<div class="search-panel">
<?
            if ($this->c_lokasi_unitkerja=='1') 
            { ?>		
	           <table border="0" cellpadding="0" cellspacing="1" class="tbl2" id="listcombo"  width="100%">
                  <tr>
			         <td width="25%">Lokasi</td>
			         <td width="2%">:</td> 
			         <td width="73%">					
					<?
					$jmlLokList=count($this->lokasiList);
					//$lokList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlLokList; $i++) 
                                  {
						$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
					}
					if ($this->c_eselon_i=='01')
                                  {
						//$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo()"); 
						$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
					}
                                  else
                                  {
						$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja"); }
					echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
					?>
			        </td>
		          </tr>
		          <tr>
			         <td>Eselon I</td>
			         <td>:</td> 
			         <td>					
					<?
					$jmleseloniList=count($this->eseloniList);
					$eseloniList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniList; $i++) 
                                  {
						$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
						//$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i] = (string)$this->eseloniList[$i]->n_unitkerja;			 
					}
					$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
					//$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo()");  	
					echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i." ".$this->eseloniDesc,$eslAtrib,$eseloniList); 							
					?>
			         </td>
		          </tr>
		          <tr>   
			         <td>Eselon II</td>
			         <td>:</td> 
			         <td>				
									<?
					$jmleseloniiList=count($this->eseloniiList);
					$eseloniiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiList; $i++) 
                                  {
						$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
					}
					if ($ceseloncpns>=3) { $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')"); }
					else { $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')"); }
					echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
					?>
			         </td>
			      </tr>						
		          <tr>
			         <td>Eselon III</td>
			         <td>:</td> 
			         <td>					
									<?
					$jmleseloniiiList=count($this->eseloniiiList);
					$eseloniiiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiiList; $i++) 
                                  {
						$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
					}
					if ($ceseloncpns>=5) { $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
					else {	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')"); }
					echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
					?>
			         </td>
		          </tr>
		          <tr>
			         <td>Eselon IV</td>
			         <td>:</td> 
			         <td>				
									<?
					$jmleselonivList=count($this->eselonivList);
					$eselonivList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonivList; $i++) 
                                  {
						$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
					}
					if ($ceseloncpns>=7)
                                  {
					    $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
					}
					else
                                  {
					    $eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
					}
					echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
					?>
			         </td>
		          </tr>
		          <tr>
			         <td>Eselon V</td>
			         <td>:</td> 
			         <td>				
									<?
					$jmleselonvList=count($this->eselonvList);
					$eselonvList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonvList; $i++) 
                                  {
						$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
					}
					if ($ceseloncpns>=9)
                                  { $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v"); }										
					else { $eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v"); }
					echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			         </td>
		          </tr>							
	           </table>
           <? }         
            else {?>
			   <table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">
			      <tr>
					  <td width="25%" align="left">Lokasi</td>
					  <td width="2%" align="left">:</td> 
					  <td width="73%" align="left">					
									<?
					$jmlLokList=count($this->lokasiList);
					//$lokList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlLokList; $i++) {
						$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
					}
					$lokAtrib = array("style"=>"width: 320px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
					//$lokAtrib = array("style"=>"width: 320px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo()"); 
					echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
					  </td>
				   </tr>
				   <tr>
					  <td align="left">Eselon I</td>
					  <td align="left">:</td> 
					  <td align="left">					
									<?
					$jmleseloniList=count($this->eseloniList);
					$eseloniList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniList; $i++) {
						$eseloniList[trim((string)$this->eseloniList[$i][c_eselon_i].";".(string)$this->eseloniList[$i][n_unitkerja])] = (string)$this->eseloniList[$i][n_unitkerja];			 
					}
					$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
					echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
					  </td>
				   </tr>
				   <tr>
		              <td align="left">Pengadilan Tk Banding</td>
		              <td align="left">:</td> 
		              <td align="left">							
									<?
					$jmleseloniiList=count($this->eseloniiList);
					$eseloniiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiList; $i++) {
						$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii.";".(string)$this->eseloniiList[$i]->c_parent.";".(string)$this->eseloniiList[$i]->n_unitkerja)] = (string)$this->eseloniiList[$i]->n_unitkerja;
					}
					if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
					else {$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
					echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
					   </td>
				   </tr>						
				   <tr>
		              <td align="left">Pengadilan Tingkat I</td>
		              <td align="left">:</td> 
		              <td align="left">								
									<?
					$jmleseloniiiList=count($this->eseloniiiList);
					$eseloniiiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiiList; $i++) {
						$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_ii.";".(string)$this->eseloniiiList[$i]->c_eselon_iii.";".(string)$this->eseloniiiList[$i]->c_satker.";".(string)$this->eseloniiiList[$i]->n_unitkerja)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
					}										
					if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
					else{$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}										
					echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
					   </td>
				   </tr>
				   <tr>
		               <td align="left">Unit Kerja</td>
		               <td align="left">:</td> 
		               <td align="left">			
									<?
					$jmleselonivList=count($this->eselonivList);
					$eselonivList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonivList; $i++) {
						$eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv.";".(string)$this->eselonivList[$i]->n_unitkerja)] = (string)$this->eselonivList[$i]->n_unitkerja;			 
					}
					$eslAtrib = array("style"=>"width: 320px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
					echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 
									?>
					   </td>
				   </tr>						
			   </table>
<?          }?>	
	           <table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">
			<tr>
				<td width="25%" align="left"><b>Periode Absensi </b></td>
					  <td width="2%" align="left">:</td> 
				<td width="73%" align="left"><b>
				<?
				$blnatr = array("style"=>"width:100px");
				$thnatr = array("style"=>"width:40px");
				echo $ctrlFrm->formSelect('bulanabsen', $blnSekarang, $blnatr, $bulanLst)." ";
				echo $ctrlFrm->formText('tahunabsen', $thnSekarang, $thnatr)."&nbsp; sampai dengan &nbsp;";
				echo $ctrlFrm->formSelect('bulanabsen2', $blnSekarang2, $blnatr, $bulanLst)." ";
				echo $ctrlFrm->formText('tahunabsen2', $thnSekarang2, $thnatr)."&nbsp;";
				echo $ctrlFrm->formButton('cari_rekap', 'Proses', $blnatr );

				?>
				</b></td>
			</tr>
	</table>
</div>

<div class="panel" id='pentry'>
   <input type='hidden' id='mode' name='mode' value='0'>
	<table width="100%" class="tbl">
		<tbody>
			<tr>
				<th rowspan='2'>No</th>
				<th rowspan='2'>Nip</th>
				<th rowspan='2'>Nama</th>
				<th colspan='<?=$jmlkodeijinlst?>'>Absensi</th>
			</tr>
			<tr>
<?
     for ($i=0; $i<$jmlkodeijinlst; $i++)
     {
        echo "<th>".$kodeijinlst[$i]['n_ijin']."</th>";
     }
?>
<!---
				<th>Hdr & Plg Tepat Waktu</th>
				<th>Dinas Luar</th>
				<th>Cuti Bersama</th>
				<th>Cuti</th>
				<th>Sakit</th>
				<th>Ijin</th>
				<th>Tanpa Keterangan</th>
				<th>Terlambat Datang</th>
				<th>Pulang Cepat</th>
!--->
			</tr>
			<?php
			if(count($this->pegawaidatalst)){
				$jmlmasukkerja = $this->absensimsn_serv->getJmlHariKerja($periode);
				$ipage = (($this->currentPage-1)*($this->numToDisplay))+1;
				foreach ($this->pegawaidatalst as $key => $val): 
				      $jmlhadir = $this->absensimsn_serv->getJmlMasukKerja($this->escape($val['i_peg_nip']), $periode);
				      $jmlsrtIjin = $this->absensimsn_serv->getJmlSuratIjin($this->escape($val['i_peg_nip']), $periode);
					if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
					<td class="clright"><?=$ipage?></td>
					<td class="clleft" >
					<a href='#' onClick='rekapabsenpeg()'><?=$this->escape($val['i_peg_nip'])?></a></td>
					<td class="clleft"><?=$this->escape($val['n_peg'])?></td>
<?
     for ($i=0; $i<$jmlkodeijinlst; $i++)
     {
        echo "<td class='clright'>".$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, $kodeijinlst[$i]['c_ijin'])."</td>";
     }
?>
<!---
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "V")?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "DL")?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "CB")?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "C")?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "S")?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlDataIjin($this->escape($val['i_peg_nip']), $periode, $periode2, "I")?></td>

					<td class="clright"><?=$this->absensimsn_serv->getJmlIjinV($this->escape($val['i_peg_nip']), $periode)?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlIjin($this->escape($val['i_peg_nip']), $periode, 'DL')?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlIjin($this->escape($val['i_peg_nip']), $periode, 'CB')?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlIjin($this->escape($val['i_peg_nip']), $periode, 'C')?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlIjin($this->escape($val['i_peg_nip']), $periode, 'S')?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlIjin($this->escape($val['i_peg_nip']), $periode, 'I')?></td>
					<td class="clright"><?=$jmlmasukkerja-($jmlhadir-$jmlsrtIjin)?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlTerlambat($this->escape($val['i_peg_nip']), $periode)?></td>
					<td class="clright"><?=$this->absensimsn_serv->getJmlCepatPlg($this->escape($val['i_peg_nip']), $periode)?></td>
!--->
					</tr>
					<?php
					$ipage++;
				endforeach;
			}
			?>
		</tbody>
	</table>
   <div class="panel">
   <div class="right">
<?
       $totalData 		= $this->pegawaidatalstJml;
	$numToDisplay	= $this->numToDisplay;
	$currentPage = $this->currentPage;
	$fungsi = $this->basePath.'/sdmmodule/dataabsensi/listdataabsensiku';
	$fungsijs = $this->basePath.'/sdmmodule/dataabsensi/lstdataabsensijs';
	$param1 = $this->c_lokasi_unitkerja;
	$param2 = $this->bulanabsen;
	$param3 = $this->tahunabsen;
	$param4 = $this->c_eselon;
	$modul = "pentry";
	$halaman->showPagebr($totalData, $numToDisplay, $currentPage, $modul, $fungsi, $fungsijs, $param1, $param2, $param3, $param4);
?>
   </div>
   <br>
   <br>
   </div>
</div>

