<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once "share/halaman.php";  

$tanggal = new tanggal();
$halaman = new halaman();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;
/*
$jmllokasilist = count($this->lokasilist);
for ($i=0; $i<$jmllokasilist; $i++)
{
	$datalokasilist[(string)$this->lokasilist[$i]['c_lokasi']] = (string)$this->lokasilist[$i]['n_lokasi'];
}
$jmleselon1lst = count($this->eselon1lst);
for ($i=0; $i<$jmleselon1lst; $i++)
{
	$dataeselon1lst[(string)$this->eselon1lst[$i]['c_eselon_i']] = (string)$this->eselon1lst[$i]['n_unitkerja'];
}
$jmleselon2lst = count($this->eselon2lst);
for ($i=0; $i<$jmleselon2lst; $i++)
{
	$dataeselon2lst[(string)$this->eselon2lst[$i]['c_eselon_ii']] = (string)$this->eselon2lst[$i]['n_unitkerja'];
}

$jmlLokasiList = count($this->LokasiList);
for ($i=0; $i<$jmlLokasiList; $i++)
{
	$kdLokasiList[(string)$this->LokasiList[$i]['kd_lokasi']] = (string)$this->LokasiList[$i]['kd_lokasi'].". ".(string)$this->LokasiList[$i]['ur_upb'];
}
*/
	   $harilst = array("Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu");
	   $bulanLst = array("01"=>"Januari","02"=>"Februari","03"=>"Maret","04"=>"April","05"=>"Mei","06"=>"Juni","07"=>"Juli",
	   "08"=>"Agustus","09"=>"September","10"=>"Oktober","11"=>"November","12"=>"Desember");
	   $absensilst = array("V"=>"Hadir & Pulang Tepat Waktu",
	                       "DL"=>"Dinas Luar",
						   "CB"=>"Cuti Bersama",
						   "C"=>"Cuti",
						   "S"=>"Sakit",
						   "I"=>"Ijin",
						   "TK"=>"Tanpa Keterangan",
						   "L"=>"Terlambat Datang",
						   "E"=>"Pulang Cepat");
					  
$thnSekarang = $this->tahunabsen;
$blnSekarang = $this->bulanabsen;
$periode = $thnSekarang.'-'.$blnSekarang; 
$thnSekarang2 = $this->tahunabsen2;
$blnSekarang2 = $this->bulanabsen2;
$periode2 = $thnSekarang2.'-'.$blnSekarang2; 
     $kodeijinlst = $this->absensimsn_serv->getKodeIjinLst();
     $jmlkodeijinlst = count($kodeijinlst);

?>

<div class="search-panel">
<?
            if ($this->c_lokasi_unitkerja=='1') 
            { ?>		
	           <table border="0" cellpadding="0" cellspacing="1" class="tbl2" id="listcombo"  width="100%">
                  <tr>
			<td width="35%">Lokasi</td>
			<td width="2%">:</td> 
			<td width="63%"><?
			              $lokasiList = $this->reff_serv->getLokasi(" and c_lokasi='$this->c_lokasi_unitkerja'");

					$jmlLokList=count($lokasiList);
					for ($i = 0; $i < $jmlLokList; $i++) {
						$lokList[(string)$lokasiList[$i]->c_lokasi] = (string)$lokasiList[$i]->n_lokasi;			 
					}
					echo $lokList[$this->c_lokasi_unitkerja];						

?></td>
		    </tr>
		          <tr>
			         <td>Eselon I</td>
			         <td>:</td> 
			         <td>					
					<?
                                  $c_eselon_i = explode(' ',$this->c_eselon_i);
                                  $jmlkata = count($c_eselon_i);
                                  $vc_eselon_i = "";
                                  for ($j=0; $j<$jmlkata; $j++) { $vc_eselon_i .= $c_eselon_i[$j+1].' '; }
                                  echo $vc_eselon_i;
					?>
			         </td>
		          </tr>
		          <tr>   
			         <td>Eselon II</td>
			         <td>:</td> 
			         <td>				
									<?
                                  $c_eselon_ii = explode(' ',$this->c_eselon_ii);
                                  $jmlkata = count($c_eselon_ii);
                                  $vc_eselon_ii = "";
                                  for ($j=0; $j<$jmlkata; $j++) { $vc_eselon_ii .= $c_eselon_ii[$j+1].' '; }
                                  echo $vc_eselon_ii;
					?>
			         </td>
			      </tr>						
		          <tr>
			         <td>Eselon III</td>
			         <td>:</td> 
			         <td>					
									<?
                                  $c_eselon_iii = explode(' ',$this->c_eselon_iii);
                                  $jmlkata = count($c_eselon_iii);
                                  $vc_eselon_iii = "";
                                  for ($j=0; $j<$jmlkata; $j++) { $vc_eselon_iii .= $c_eselon_iii[$j+1].' '; }
                                  echo $vc_eselon_iii;
					?>
			         </td>
		          </tr>
		          <tr>
			         <td>Eselon IV</td>
			         <td>:</td> 
			         <td>				
									<?
                                  $c_eselon_iv = explode(' ',$this->c_eselon_iv);
                                  $jmlkata = count($c_eselon_iv);
                                  $vc_eselon_iv = "";
                                  for ($j=0; $j<$jmlkata; $j++) { $vc_eselon_iv .= $c_eselon_iv[$j+1].' '; }
                                  echo $vc_eselon_iv;
					?>
			         </td>
		          </tr>
		          <tr>
			         <td>Eselon V</td>
			         <td>:</td> 
			         <td>				
									<?
                                  $c_eselon_v = explode(' ',$this->c_eselon_v);
                                  $jmlkata = count($c_eselon_v);
                                  $vc_eselon_v = "";
                                  for ($j=0; $j<$jmlkata; $j++) { $vc_eselon_v .= $c_eselon_v[$j+1].' '; }
                                  echo $vc_eselon_v;
									?>
			         </td>
		          </tr>							
			<tr>
		          <td align="left">Pegawai</td>
		          <td align="left">:</td> 
		          <td align="left">	<?=$this->i_peg_nip?>. <?=$this->n_peg?></td>
			</tr>
	           </table>
           <? }         
            else {?>
	          <table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">
		      <tr>
			   <td width="25%" align="left">Lokasi</td>
			   <td width="2%" align="left">:</td> 
			   <td width="73%" align="left">					
				<?
			       $lokasiList = $this->reff_serv->getLokasi("");
				$jmlLokList=count($lokasiList);
				for ($i = 0; $i < $jmlLokList; $i++) {
						$lokList[(string)$lokasiList[$i]->c_lokasi] = (string)$lokasiList[$i]->n_lokasi;			 
				}
				echo $lokList[$this->c_lokasi_unitkerja];						
				?>
			   </td>
			</tr>
			<tr>
			   <td align="left">Eselon I</td>
			   <td align="left">:</td> 
			   <td align="left">					
				<?
				$jmleseloniList=count($this->eseloniList);
				$eseloniList[''] = '--Pilih--';
				for ($i = 0; $i < $jmleseloniList; $i++) {
				    $eseloniList[trim((string)$this->eseloniList[$i][c_eselon_i].";".(string)$this->eseloniList[$i][n_unitkerja])] = (string)$this->eseloniList[$i][n_unitkerja];			 
				}
				$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
				echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
				?>
			   </td>
			</tr>
			<tr>
		          <td align="left">Pengadilan Tk Banding</td>
		          <td align="left">:</td> 
		          <td align="left">							
			   <?
			      $jmleseloniiList=count($this->eseloniiList);
			      $eseloniiList[''] = '--Pilih--';
			      for ($i = 0; $i < $jmleseloniiList; $i++) {
				   $eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii.";".(string)$this->eseloniiList[$i]->c_parent.";".(string)$this->eseloniiList[$i]->n_unitkerja)] = (string)$this->eseloniiList[$i]->n_unitkerja;
			      }
			      if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
			      else {$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
			      echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
			      ?>
			   </td>
			</tr>						
			<tr>
		          <td align="left">Pengadilan Tingkat I</td>
		          <td align="left">:</td> 
		          <td align="left">								
			   <?
			   $jmleseloniiiList=count($this->eseloniiiList);
			   $eseloniiiList[''] = '--Pilih--';
			   for ($i = 0; $i < $jmleseloniiiList; $i++) {
						$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_ii.";".(string)$this->eseloniiiList[$i]->c_eselon_iii.";".(string)$this->eseloniiiList[$i]->c_satker.";".(string)$this->eseloniiiList[$i]->n_unitkerja)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
			   }										
			   if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
			   else{$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}										
			   echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
			   ?>
			   </td>
			</tr>
			<tr>
		          <td align="left">Unit Kerja</td>
		          <td align="left">:</td> 
		          <td align="left">			
			   <?
				$jmleselonivList=count($this->eselonivList);
				$eselonivList[''] = '--Pilih--';
				for ($i = 0; $i < $jmleselonivList; $i++) {
				   $eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv.";".(string)$this->eselonivList[$i]->n_unitkerja)] = (string)$this->eselonivList[$i]->n_unitkerja;			 
				}
				$eslAtrib = array("style"=>"width: 320px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
				echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 
			    ?>
			    </td>
			</tr>						
			<tr>
		          <td align="left">Pegawai</td>
		          <td align="left">:</td> 
		          <td align="left">	<?=$this->i_peg_nip?>. <?=$this->n_peg?></td>
			</tr>
		</table>
<?        }?>	<br><br>
	           <table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">
			<tr>
				<td width="35%" align="left"><b>Periode Absensi </b></td>
					  <td width="2%" align="left">:</td> 
				<td width="63%" align="left"><b>
				<?
				$blnatr = array("style"=>"width:100px");
				$thnatr = array("style"=>"width:40px");
				echo $bulanLst[$blnSekarang]." ".$thnSekarang."&nbsp; sampai dengan &nbsp;";
				echo $bulanLst[$blnSekarang2]." ".$thnSekarang2;
				?>
				</b></td>
			</tr>
                    <tr><td colspan='3'>&nbsp;</td></tr>
                    <tr><td colspan='3'><b><u>Data-Data Ijin</u></b></td></tr>
                    <tr><td colspan='3'>&nbsp;</td></tr>
<?
     for ($i=0; $i<$jmlkodeijinlst; $i++)
     {
        echo "<tr><td>".$kodeijinlst[$i]['n_ijin']."</td><td>:</td><td>".
        $this->absensimsn_serv->getJmlDataIjin($this->i_peg_nip, $periode, $periode2, $kodeijinlst[$i]['c_ijin'])."</td></tr>";
     }

?>
	</table>
</div>

   <div class="panel">
   <div class="right">
   </div>
   <br>
   <br>
   </div>
