<?php 
require_once 'share/halaman_list.php'; 
$halaman = new halaman_list(); 
?>
<div id="backgroundPopup">
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
			</tr>
		</table>
		<?echo $this->view;?>
		<?
		
		$modul = $this->basePath."/sdmmodule/monitoringserbaguna/cetakview?limit=".$this->limit;
		echo $halaman->halamanListPopup($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
		?>		
	</div>
</div>	