<div id="backgroundPopup" >
	<center>
	<div id="popupContact" style="height:350px; width:550px;" >	

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Help : Nomor Kartu Identitas</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>
			<form onsubmit="xjxmW.closeWindow(' .  . ')xajax_add('HELP','querylahir',document.getElementById('keyd').value);return false;" id="fd1" name="fd1" enctype="multipart/form-data" method="post">
			
			
			<table border="0" width="100%" class="table">
		
		<tbody><tr class="row">
             <td>No. KARPEG</td>
			 <td>
			<input type="text" onkeypress="return justnumber(event)" value="" id="no_karpeg" name="no_karpeg" size="30"></td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('no_karpeg').value != '' ) {document.getElementById('query_nip').value = strg + ' i_peg_karpeg like ' + '\'%'+ document.getElementById('no_karpeg').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input0" id="bt_input0">
				</td>
		</tr>
		<tr class="row1">
             <td>No. TASPEN</td>
			 <td>
			<input type="text" onkeypress="return justnumber(event)" value="" id="no_karpeg" name="no_karpeg" size="30">
					</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('no_karpeg').value != '' ) {document.getElementById('query_nip').value = strg + ' i_peg_taspen like ' + '\'%'+ document.getElementById('no_karpeg').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input1" id="bt_input1">
				</td>
		</tr>
		<tr class="row">
             <td>No. KTP</td>
			 <td>
			<input type="text" onkeypress="return justnumber(event)" value="" id="no_ktp" name="no_ktp" size="30">
					</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('no_ktp').value != '' ) {document.getElementById('query_nip').value = strg + ' i_peg_ktp like ' + '\'%'+ document.getElementById('no_ktp').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input1" id="bt_input1">
				</td>
		</tr>
		<tr class="row1">
             <td>No. ASKES</td>
			 <td>
			<input type="text" onkeypress="return justnumber(event)" value="" id="no_askes" name="no_askes" size="30">
					</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('no_askes').value != '' ) {document.getElementById('query_nip').value = strg + ' i_peg_askes like ' + '\'%'+ document.getElementById('no_askes').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input1" id="bt_input1">
				</td>
		</tr>
		<tr class="row">
             <td>No. KORPRI</td>
			 <td>
			<input type="text" onkeypress="return justnumber(event)" value="" id="no_korpri" name="no_korpri" size="30">
					</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('no_korpri').value != '' ) {document.getElementById('query_nip').value = strg + ' i_peg_korpri like ' + '\'%'+ document.getElementById('no_korpri').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input1" id="bt_input1">
				</td>
		</tr>
			
			 
         
		<tr>
             <td align="center" colspan="3" class="row">&nbsp;
     			</td>
         </tr>
		 <tr>
             <td align="center" colspan="3" class="row1">
			 <textarea cols="70" rows="5" id="query_nip" name="query_nip"></textarea>
						</td>
         </tr>
		 <tr class="row1">
             <td align="left" colspan="2">
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'OR ';}  else {document.getElementById('query_nip').value = document.getElementById('query_nip').value + ' OR ';} document.getElementById('bt_input0').disabled= false;document.getElementById('bt_input1').disabled= false;document.getElementById('bt_input2').disabled= false;document.getElementById('bt_input3').disabled= false;document.getElementById('bt_input4').disabled= false;" value=" OR " tabindex="56" name="bt0">
			 	&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'AND ';}  else {document.getElementById('query_nip').value = document.getElementById('query_nip').value + ' AND ';} document.getElementById('bt_input0').disabled= false;document.getElementById('bt_input1').disabled= false;document.getElementById('bt_input2').disabled= false;document.getElementById('bt_input3').disabled= false;document.getElementById('bt_input4').disabled= false;" value=" AND " tabindex="57" name="bt2">
				&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="56" name="bt1">
			 	&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt2">
			</td>
			 <td align="right">
			 <input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg;closeDetil()}" value="OK !" tabindex="58" name="bt3">
			 </td>
         </tr></tbody></table>      
			</form>
			
			</fieldset>
	
	</div>
	</center>
</div>	