<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList['#'] = '--';
   for ($i = 0; $i < 40; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   } $blnArrayList['#'] = '--';	

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_barangkat").datepicker();
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/listluarnegeri','<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/luarnegerijs');">Luar Negeri</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Luar Negeri
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Data Luar Negeri</h2>	
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
<form id="formluarnegeri" method="post" name="formluarnegeri">		
	<div class="panel">
		<div class="spacer"></div> 
						<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Negara</td>
					<td>:</td> 
					<td>
						<?php 
							$jmlNegaraList = count($this->negaraList);
							for ($i = 0; $i < $jmlNegaraList; $i++) {
							if ($this->c_negara==$this->negaraList[$i]->c_negara){echo $this->negaraList[$i]->n_negara;}
							}
						?>	
					</td>
				</tr>
				<tr>
					<td>Tujuan</td>
					<td>:</td> 
					<td>
						<?=$this->a_tujuan?>
					</td>
				</tr>
				<tr>
					<td>Pembiayaan / Sponsor</td>
					<td>:</td> 
					<td>
						<?
							if ($this->c_biaya=="01"){ echo "Dinas";}
							elseif ($this->c_biaya=="02"){ echo "Mandiri";}
							elseif ($this->c_biaya=="03"){ echo "Penyelenggara";}
							elseif ($this->c_biaya=="04"){ echo "Sponsor";}
							else{echo "-";}
						?>
					</td>
				</tr>				
				
				<tr>
					<td>Tanggal Berangkat</td>
					<td>:</td> 
					<td>
						<?=$this->d_barangkat?>
					</td>
				</tr>
				<tr>
					<td>Lama Kunjungan</td>
					<td>:</td> 
					<td>
						<?=$this->q_hari?> Hari /
						<?=$this->q_bulan?> Bulan /
						<?=$this->q_tahun?> Tahun
					</td>
				</tr>
				<tr>
					<td>Keterangan</td>
					<td>:</td> 
					<td>
					<?php 
						echo $this->e_keterangan;
					?>
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">		
				</tr>
						<tr>
							<td>
								<div class="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/listluarnegeri','');"> 
								</div>
							</td>
						</tr>			
			</table>
	</div>
	</form>
</div>	
