<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmPegList = count($this->PegawaiList);  
?>
<div id="backgroundPopup">
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
		<tr>
		<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
		</tr>
		</table>
		<div style="overflow: hidden;">
			<div class="wrap">
				<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h2 class="title">Daftar Pegawai</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
						   <table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
								<tr>
									<th width="4%">No.</th>
									<th width="10%">NIP</th>
									<th width="30%">Nama</th>
									<th width="15%">Jenis Kelamin</th>
									<th width="15%">Gol/Pangkat</th>
									<th width="20%">Jabatan</th>
								</tr> 
<? 		if ($jmlnmPegList == 0) {?>
								<tr class="event">
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
<?		}else{
				foreach ($this->PegawaiList as $key => $val):  
										if ($key%2==0) { ?>
										<tr class="event">
										<? } else if ($key%2==1) { ?>
										<tr class="event2">
										<? } 
										$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
										?>
											<td class="clcenter"><?php echo $noUrut;?></td>
											<td><a href="#" onclick="pilihData('<?=$this->par?>','<?php echo $this->escape($val['i_peg_nip']);?>','<?php echo $this->escape($val['n_peg']);?>','<?php echo $this->escape($val['n_jabatan']);?>')"><?php echo $this->escape($val['i_peg_nip']);?></a></td>
											<td><?php echo $this->escape($val['n_peg']);?></td>
											<td><?php echo $this->escape($val['n_nama']);?></td>
											<td><?php echo $this->escape($val['c_golongan'])."/".$this->escape($val['n_pangkat']);?></td>
											<td><?php echo $this->escape($val['n_jabatan']);?></td>		
										</tr>
<?php 
				endforeach;}
?>
							
							</table>
						<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>
		</div>
	</div>
</div>	
<script>
function pilihData(par,nip,nama,jabatan){
if (par=='b'){
	document.getElementById('i_peg_nipatasanpnilai').value=nip;
	document.getElementById('n_peg_atasanpnilai').value=nama;	
	document.getElementById('n_jabatan_atasanpnilai').value=jabatan;	
	}
else if (par=='c'){
	document.getElementById('i_peg_nipatasanpnilai').value=nip;
	document.getElementById('n_peg_atasanpnilai').value=nama;	
	document.getElementById('n_jabatan_atasanpnilai').value=jabatan;	
	}	
else{
	document.getElementById('i_peg_nippnilai').value=nip;
	document.getElementById('n_peg_nippnilai').value=nama;	
	document.getElementById('n_jabatan_pnilai').value=jabatan;
	document.getElementById('i_peg_nippnilai').focus();
}
	document.getElementById('i_peg_nippnilai').focus();	
	closeDetil();
}
</script>