<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
   
$ctrlDate = new tanggal();   
   
   $ctrlFrm = new Zend_View();
 

$jumPelatihanList = count($this->pelatihanList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>Diklat Fungsional
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>	

	<h2 class="title">Diklat Fungsional</h2>
	<?php include "$this->leftMenu/linkdatadiklat.phtml";?>
<div class="boxholder">	
	<div class="panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	
<div class="add" title="Tambah Data" onclick="diklatFungsionalM('insert','');"></div>
<?}	if ($jumPelatihanList == 0) {
		echo "<font color=\"red\">Data Diklat Fungsional Tidak Ditemukan</font>";
}
?>
<table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
				<tr>
			    <th width="15%">Jenis Pelatihan</th>
				<th width="15%">Kelompok</th>
				<th width="15%">Nama</th>
				<th width="8%">Lama</th>
				<th width="15%">Penyelenggara</th>
				<th width="15%">Sertifikat</th>
				<th width="4%" colspan="2">&nbsp;</th>
				</tr>

<?
	if ($jumPelatihanList == 0) {
	
?>				<tr class="event">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				</tr>
<? } else { ?>				
		<?php foreach ($this->pelatihanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
				<? 
					$nip=trim($this->escape($val['i_peg_nip']));

				?>
					
				<td>
					<?php echo $this->escape($val['n_jns_fungsional']);?>
				</td>
				<td><?php echo $this->escape($val['n_kel_pelatihan']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_nama_kelompok']);?></td>
				<td class="clleft"><?php echo $this->escape($val['q_pelatihan']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_penyelenggara']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['i_sertifikat']);?><br><?php echo $this->escape($val['d_sertifikat']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="diklatFungsionalM('update','<?=$nip?>','<?=trim($this->escape($val['c_jns_fungsional']))?>','<?=trim($this->escape($val['c_kel_pelatihan']))?>','<?=trim($this->escape($val['c_jns_kelompok']))?>','<?=trim($this->escape($val['c_nama_kelompok']))?>');"></div>	
				</td>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="diklatFungsionalM('delete','<?=$nip?>','<?=trim($this->escape($val['c_jns_fungsional']))?>','<?=trim($this->escape($val['c_kel_pelatihan']))?>','<?=trim($this->escape($val['c_jns_kelompok']))?>','<?=trim($this->escape($val['c_nama_kelompok']))?>')"></div>
				</td>
<?}?>				
		  </tr>
	<?php endforeach;?> 	
	<? } ?>
	</table>									
<div id="targetdetil"></div>						
		</div>		 
		</form>
<script>
function detilPend(nip,cPend){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/detilpelatihan';
var param = {nip:nip,cPend:cPend};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}
</script>	