function diklatTeknisL(par,nip){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datadikteknis/listdiklat"	
	var opt = {par:par,nip:nip};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 
function diklatTeknisM(par,nip,c_kelompok){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datadikteknis/teknis"	
	var opt = {par:par,nip:nip,c_kelompok:c_kelompok};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 


var maintain_teknis = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formteknis;
		astr= "document.formteknis";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/								
					if((!c_kelompok.value)){cekVal = sdmValidasiData(astr,"c_kelompok","Kelompok harus diisi....!");return false;break;}
					if((!c_negara.value)){cekVal = sdmValidasiData(astr,"c_negara","Negara harus diisi....!");return false;break;}
					if((!n_diklat.value)){cekVal = sdmValidasiData(astr,"n_diklat","Nama Diklat harus diisi....!");return false;break;}
					if((!i_sertifikat.value)){cekVal = sdmValidasiData(astr,"i_sertifikat","Nomor Sertifikat harus diisi....!");return false;break;}					
					if((!d_sertifikat.value)){cekVal = sdmValidasiData(astr,"d_sertifikat","Tanggal Sertifikat harus diisi....!");return false;break;}					
				
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formteknis").ajaxForm(maintain_teknis);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datadikteknis/maintaindatateknis',
	type: 'post',
	resetForm: false
};
function insertTeknis(){
	jQuery("#formteknis").ajaxForm(maintain_teknis);
}

function HapusDataPelatihan(nip,c_pelatihan,dmulaipelatihan)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datapelatihan/hapusdata"
		var opt = {nip:nip,c_pelatihan:c_pelatihan,dmulaipelatihan:dmulaipelatihan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}


