<?
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();		
$currentPage = $this->currentPage;
$numToDisplay = $this->numToDisplay;

?>
<div class="navlink">
<a href="#" onclick="open_url_to_home('<?php echo $this->basePath; ?>/home/index/depan','<?php echo $this->basePath; ?>/home/index/main');">Halaman Utama</a>
</div>
<div class="panel">
	<div class="inner">
		<span class="corners-top"><span></span></span>
		<h2 class="title">Absen Mahasiswa</h2>
		<div class="search-panel">
<form method="post" id="frmCariAbsenmahasiswa" name="frmCariAbsenmahasiswa">
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
	<td align="left" width="180"> Program Studi :</td>
	<td>
	<?
				$jmlprodiList = count($this->prodiList);
				$prodiList['-'] = '--Pilih--';
				if(trim($this->n_level) =="jur0"){$prodiList['-'] = '--Pilih--';}
				for ($i = 0; $i < $jmlprodiList; $i++) {
					$prodiList[$this->prodiList[$i]->id] = (string)$this->prodiList[$i]->n_prodi;			 
				}
				$c_prodiAtrib = array("id"=>"prodi", "tabindex"=>"17", "onchange"=>"javascript:absenmahasiswalistBy();");
				echo $ctrlFrm->formSelect('prodi', trim($this->prodi), $c_prodiAtrib, $prodiList);
				?>
	</td>
	</tr>
	<tr>
	<td align="left" width="180"> Semester :</td>
	<td>
	<?
	$n_semesterList['-'] = '--Pilih--';
	$n_semesterList['1'] = 'Ganjil';
	$n_semesterList['2'] = 'Genap';
	$c_n_semesterAtrib = array("id"=>"semester", "tabindex"=>"17", "onchange"=>"javascript:absenmahasiswalistBy();");
	echo $ctrlFrm->formSelect('semester', trim($this->semester), $c_n_semesterAtrib, $n_semesterList);
	?>
	</td>
	</tr>
	<?
	if(trim($this->semester) == '1'){
	?>
	<tr>
	<td align="left" width="180"> Tahun Ajaran :</td>
	<td>
	<?
	$jmlthnAjaranList = count($this->thnAjaranList);
	$thnAjaranList['-'] = '--Pilih--';
		for ($i = 0; $i < $jmlthnAjaranList; $i++) {
		$thnAjaranList[$this->thnAjaranList[$i]->c_thnajaran] = (string)$this->thnAjaranList[$i]->n_thnajaran;			 
		}
	$c_thnAjaranAtrib = array("id"=>"tahun", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('tahun', trim($this->tahun), $c_thnAjaranAtrib, $thnAjaranList);
	?>
	</td>
	</tr>
	<? } if(trim($this->semester) == '2'){ ?>
	<tr>
	<td align="left" width="180"> Tahun Ajaran :</td>
	<td>
	<?
	$jmlthnAjaranList = count($this->thnAjaranList);
	$thnAjaranList['-'] = '--Pilih--';
		for ($i = 0; $i < $jmlthnAjaranList; $i++) {
		$thnAjaranList[$this->thnAjaranList[$i]->c_thnajaran1] = (string)$this->thnAjaranList[$i]->n_thnajaran;			 
		}
	$c_thnAjaranAtrib = array("id"=>"tahun", "tabindex"=>"17");
	echo $ctrlFrm->formSelect('tahun', trim($this->tahun), $c_thnAjaranAtrib, $thnAjaranList);
	?>
	</td>
	</tr>
	<? }  ?>

	<td align="left" width="180"> Kelas Ambil :</td>
	<td>
	<?
	$jmlkelasListBy = count($this->kelasListBy);
	$kelasListBy['-'] = '--Pilih--';
		for ($i = 0; $i < $jmlkelasListBy; $i++) {
		$kelasListBy[$this->kelasListBy[$i]->c_kelas] = (string)$this->kelasListBy[$i]->n_kelas;			 
		}
	$kelasAtrib = array("id"=>"kelas", "tabindex"=>"17", "onchange"=>"javascript:absenmahasiswalistBy();");
	echo $ctrlFrm->formSelect('kelas', trim($this->kelas), $kelasAtrib, $kelasListBy);
	?>
	</td>
	</tr>
	<tr>
	<td align="left" width="180"> Mata Kuliah :</td>
	<td>
	<?
	$jmlmatKulList = count($this->matKulList);
	$matKulList['-'] = '--Pilih--';
		for ($i = 0; $i < $jmlmatKulList; $i++) {
		$matKulList[$this->matKulList[$i]->id] = (string)$this->matKulList[$i]->n_matakuliah." / ".(string)$this->matKulList[$i]->Ajar_MatkulThn."  ".(string)$this->matKulList[$i]->c_konsentrasi;			 
		}
	$matakuliahAtrib = array("id"=>"matakuliah", "tabindex"=>"17", "onchange"=>"javascript:absenmahasiswalistBy();");
	echo $ctrlFrm->formSelect('matakuliah', trim($this->matakuliah), $matakuliahAtrib, $matKulList);
	?>
	</td>
	</tr>

	<tr>
	<td align="left" width="180"> Pertemuaan Ke :</td>
	<td>
	<?
	$jmlpertemuanListAll = count($this->pertemuanListAll);
	$pertemuanListAll['-'] = '--Pilih--';
		for ($i = 0; $i < $jmlpertemuanListAll; $i++) {
		$pertemuanListAll[$this->pertemuanListAll[$i]->id] = (string)$this->pertemuanListAll[$i]->n_pertemuan;			 
		}
	$n_pertemuaanAtrib = array("id"=>"pertemuaan", "tabindex"=>"17", "onchange"=>"javascript:absenmahasiswalistBy();");
	echo $ctrlFrm->formSelect('pertemuaan', trim($this->pertemuaan), $n_pertemuaanAtrib, $pertemuanListAll);
	
	
	$atribSubmit = array("onclick"=>"javascript:cariAbsenmahasiswa();");
	echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
	?>
	<input name="n_nama" id="n_nama" type="hidden" value="<?echo $this->getDetailPerkuliahan['n_nama']; ?>" />
	<input name="n_kelas" id="n_kelas" type="hidden" value="<?echo $this->getDetailPerkuliahan['n_kelas']; ?>" />
	<input name="n_matakuliah2" id="n_matakuliah2" type="hidden" value="<?echo $this->matakuliah; ?>" />
	<input name="n_matakuliah" id="n_matakuliah" type="hidden" value="<?echo $this->getDetailPerkuliahan['id']; ?>" />
	</td>
	</tr>

</table>

</table>
<table width="50%" border="0" cellpadding="0" cellspacing="1" align="center">
<?
	$kategoriCari = array("id_npm" => "NPM",  "n_mhs" => "Nama");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
?>
	<input type="text" name="carii" align="center" value ="<? echo $this->katakunciCari;?>">
				<?
			         $atribSubmit = array("onclick"=>"javascript:cariAbsenmahasiswa();");
			         echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
</table>
</form>
		</div>
		<div class="space-line"></div>
		<fieldset class="fields"> 
			<? 
			
			$status = $this->hasil;
			$proses = $this->proses;
			$keterangan = $this->keterangan;
			
			$pesan->show_message($proses, $keterangan, "$status" ); ?>
			
			<div class="add" title="Tambah Data" onClick="absenmahasiswaForm('insert','','<? echo $this->matakuliah; ?>');"></div> 
			<div class="prt" title="Cetak Form Absen" onClick="cetakabsen('insert','<? echo $this->matakuliah; ?>');"></div> 
			<div class="prt" title="Cetak Form Absen Mengulang" onClick="cetakabsen1('insert','<? echo $this->matakuliah; ?>');"></div> 
			<div class="blank"></div>
			
			
			<table id="sorter" class="sortable" cellspacing="1" cellpadding="2" border="0" align="center">
				<th class="nosort">No</th> 
				<th class="sorted order2 sortable">NPM</th> 
				<th class="sorted order2 sortable">Nama</th> 
				<th class="sorted order2 sortable">Mata Kuliah</th> 
				<th class="sorted order2 sortable">Tanggal</th> 
				<th class="sorted order2 sortable">Pertemuaan Ke</th> 
				<th class="sorted order2 sortable">Alasan</th> 
				<th colspan="2"  class="nosort">Tindakan</th>
				
				<?
				if (count($this->absenmahasiswaList) == 0){ 
				?>
					<tr class="event2"><td colspan="9"><font color="red">Data Tidak Ditemukan</font></td></tr>
				<?} else {
						
						
						foreach ($this->absenmahasiswaList as $key => $val): 
						if ($key%2==0) { ?>
							<tr class="event">
						<? } else if ($key%2==1) { ?>
							<tr class="event2">
						<? } 
						$id = $this->escape($val['id']); 
						$c_perkuliahan = $this->escape($val['c_perkuliahan']); 
						$n_nama = $this->escape($val['n_nama']); 
						$n_kelas = $this->escape($val['n_kelas']); 
						$jns_matakuliah = $this->escape($val['jns_matakuliah']);

						$n_matakuliah = $this->escape($val['n_matakuliah']);
						$d_tanggal = $this->escape($val['d_tanggal']);
						$id_npm = $this->escape($val['id_npm']);
						$n_mhs = $this->escape($val['n_mhs']);
						$n_alasan = $this->escape($val['n_alasan']);
						$n_mingguke = $this->escape($val['n_mingguke']);
						$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
						
						// form Hidden 
						echo $ctrlFrm->formHidden('id', $id, null);
						echo $ctrlFrm->formHidden('c_perkuliahan', $c_perkuliahan, null);
						echo $ctrlFrm->formHidden('n_nama', $n_nama, null);
						echo $ctrlFrm->formHidden('n_matakuliah', $n_matakuliah, null);
						echo $ctrlFrm->formHidden('n_kelas', $n_kelas, null);
						
						?>
						
						<td align="center"><? echo $noUrut;?>&nbsp;&nbsp;</td>
						<td class="clleft">&nbsp;<? echo $n_mhs;?></td>
						<td class="clleft">&nbsp;<? echo $id_npm;?></td>
						<td class="clleft">&nbsp;<? echo $n_matakuliah;?> <? echo $jns_matakuliah;?></td>
						<td align="center">&nbsp;<? echo $d_tanggal;?></td>
						<td align="center">&nbsp;<? echo $n_mingguke;?></td>
						<td align="center">&nbsp;<? echo $n_alasan;?></td>
						
						<td><div onClick="absenmahasiswaForm('update','<? echo $id;?>','<? echo $c_perkuliahan;?>');" class="edit" title="Input Data Absen"></div></td>
						<td><div class="delete" title="Hapus Data" onClick="absenmahasiswaHapus('Absenmahasiswa', '<? echo $id; ?>')" ></td>
						
					
						</tr>
					<?
					endforeach;
				}
				?>
			</table>
			<?	
			$totalData = $this->totAbsenmahasiswaList;
			$modul = $this->basePath."/bak/absenmahasiswa/absenmahasiswalist";
			$param1 = $this->prodi;$param2 = $this->tahun;$param3 = $this->semester;
			$param4 = $this->kelas;$param5 = $this->matakuliah;$param6 = $this->pertemuaan;
			echo $halaman->showPage($totalData, $numToDisplay, $currentPage, 'tableview', $modul, $param1, $param2, $param3, $param4, $param5);		
			?>
		</fieldset>		 
		
		<span class="corners-bottom"><span></span></span>
	</div>
</div>
<script type="text/javascript">
var sorter=new table.sorter("sorter");
sorter.init("sorter",0);
</script>