<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Diklat Teknis
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Diklat Teknis</h2>	
		
<form id="formteknis" method="post" name="formteknis">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Diklat Teknis<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_diklat_teknis" id="c_diklat_teknis" value="<?=$this->detailTeknis['c_diklat_teknis']?>" size="70" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Diklat Teknis<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_diklat_teknis" id="n_diklat_teknis" value="<?=$this->detailTeknis['n_diklat_teknis']?>" size="70">
					</td>
				</tr><tr>
					<td>Kode Kelompok<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_kelompok" id="c_kelompok" value="<?=$this->detailTeknis['c_kelompok']?>" size="70" maxlength="1">
					</td>
				</tr><tr>
					<td>Nama Kelompok<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_kelompok" id="n_kelompok" value="<?=$this->detailTeknis['n_kelompok']?>" size="70">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refteknis/listteknis','<?php echo $this->basePath; ?>/sdmmodule/refteknis/teknisjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertTeknis()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateTeknis()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
