<div id="backgroundPopup"></div>
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1">
			<tr>
				<td align="center">
					<?echo $this->judul;?>
				</td>
			</tr>
			<tr>
				<td align="right">
					<input type="button" value="Keluar"  onclick="closeDetil()">
				</td>
			</tr>
		</table>	
		<center>
		<div class="hideshow">
			
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						<?echo $this->chart;?>
						<table border="0" width="50%" align="center" class="tbl2">
							<tr>
								<th>Laki-laki</th>
								<th>Perempuan</th>
							</tr>
							<tr class="event2">
								<td align="right"><?=$this->jmllaki?></td>
								<td align="right"><?=$this->jmlwanita?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>		
		</div>	
		</center>
	</div>
