function insertRefNilai(){
	jQuery("#formnilai").ajaxForm(maintain_refnilai);
}

var maintain_refnilai = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formnilai;
		astr= "document.formnilai";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/ 
				if((!n_faktor_kinerja.value)){cekVal = sdmValidasiData(astr,"n_faktor_kinerja","Faktor Kinerja harus diisi....!");return false;break;}
				if((!n_standar_kinerja.value)){cekVal = sdmValidasiData(astr,"n_standar_kinerja","Standar Kinerja harus diisi....!");return false;break;}
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/maintaindataref',
	type: 'post',
	resetForm: false
};

function insertPenilaianMil(){
	jQuery("#formpenilaian").ajaxForm(maintain_nilai);
}


var maintain_nilai = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formpenilaian;
		astr= "document.formpenilaian";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/ 
				if((!i_peg_nip.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","Nip Kosong harus diisi....!");return false;break;}
				if((!d_nilai_kinerja.value)){cekVal = sdmValidasiData(astr,"d_nilai_kinerja","Tahun Penilaian Kinerja harus diisi....!");return false;break;}				
				 
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/maintaindata',
	type: 'post',
	resetForm: false
};

function refpenilaianM(par,c_nilai_kinerja){
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/refpenilaianmil"	
	var opt = {par:par,c_nilai_kinerja:c_nilai_kinerja};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 

function penilaianM(par,i_peg_nip){
	var tahun = document.getElementById('d_nilai_kinerja').value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/penilaianmil"	
	var opt = {par:par,i_peg_nip:i_peg_nip,tahun:tahun};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 
function penilaianMM(par,i_peg_nip,keydt,thn){
	var tahun = document.getElementById('d_nilai_kinerja').value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/penilaianmilubah"	
	var opt = {par:par,i_peg_nip:i_peg_nip,keydata:keydt,tahun:thn};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
}
function penilaianV(i_peg_nip){
	var d_nilai_kinerja = document.getElementById('d_nilai_kinerja').value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/listpenilaianmil"	
	var opt = {i_peg_nip:i_peg_nip,d_nilai_kinerja:d_nilai_kinerja};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 
function HapusData(i_peg_nip)
{
	var d_nilai_kinerja = document.getElementById('d_nilai_kinerja').value;
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/hapusdata"
		var opt = {i_peg_nip:i_peg_nip,d_nilai_kinerja:d_nilai_kinerja};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function getPenilai(keydata){
	//alert(keydata);
	url = "<?php echo $this->basePath; ?>/sdmmodule/detil/listpegawaipenilai"	
	var opt = {keydata:keydata};
	jQuery.get(url,opt,function(data) {
		jQuery("#popupview").html(data);
		centerPopup();
		loadPopup();		
		});		
} 

	
