<? 
$file_type = "vnd.ms-excel";
$file_ending = "xls";
header("Content-Type: application/$file_type");
header("Content-Disposition: attachment; filename=rekap.$file_ending");
header("Pragma: no-cache");
header("Expires: 0");

$html ='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<style type="text/css">
</style></head>
<body>';

$html .='
		<table border="1">
		<tr>
			<td>Pilihan Jabatan</td>
			<td>Wilayah</td>
			<td>Jumlah</td>
		</tr>';

	if ($this->dataList == 0) {
		
$html .='		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>';
	}	else { 
		foreach ($this->dataList as $key => $val):
$html .=' 
	<tr>
	<td>';
		if ($c_jab!=$this->escape($val['c_posisi_jabatan'])){
$html .=''.$this->escape($val['n_posisi_jabatan']).'';
		}
		$c_jab=$this->escape($val['c_posisi_jabatan']);
$html .='</td>
	<td>'.$this->escape($val['n_wilayah'])." - ".$this->escape($val['n_pengadilan']).'</td>
	<td>'.$this->escape($val['jumlah']).'</td>
	</tr>';
$jmltot=$this->escape($val['jumlah'])*1+$jmltot;	
 endforeach; 		  	  
	}	
$html .='
		<tr>
			<td colspan="2">Total</td>
			<td>'.$jmltot.'</td>
		</tr>
</table>';
echo $html;
?>