<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
	
	//var_dump($this->detailAgama);
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jenis Naik Golongan
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Jenis Naik Golongan</h2>	
		
<form id="formjenis" method="post" name="formjenis">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>	
						<input type="text" name="i_kode" id="i_kode" value="<?=$this->detailJenis['i_kode'];?>" size="70" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_nama" id="n_nama" value="<?=$this->detailJenis['n_nama'];?>" size="70">
					</td>
				</tr><tr>
					<td>Vsort<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="v_sort" id="v_sort" value="<?=$this->detailJenis['v_sort'];?>" size="70">
					</td>
				</tr><tr>
					<td>Kode Status<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_status" id="c_status" value="<?=$this->detailJenis['c_status'];?>" size="70" maxlength="1">
					</td>
				</tr><tr>
					<td>Tanggal Update<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="d_update" id="d_update" value="<?=date('d-m-Y',strtotime($this->detailJenis['d_update']));?>" size="10"> tgl-bln-thn
					</td>
				</tr>
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refjenis/listjenis','<?php echo $this->basePath; ?>/sdmmodule/refjenis/jenisjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertJenis()">
								<script type="text/javascript">
								$("#d_update").val("");
								</script>
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateJenis()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
	<script type="text/javascript">
	$(function() {
		$("#d_update").datepicker();
	});
	</script>