
function cariListPegawai(){
	var statuspegcari=document.getElementById('statuspegcari').value;
	var golcari=document.getElementById('golcari').value;
	var namacari=document.getElementById('namacari').value;
	var nipcari=document.getElementById('nipcari').value;	
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai';	
	var param = {statuspegcari:statuspegcari,golcari:golcari,namacari:namacari,nipcari:nipcari};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
		});
} 

function PegawaiM(par,nip){

	var url = '<?php echo $this->basePath;?>/sdmmodule/datapegawai/pegawai';	
	var param = {par:par,nip:nip};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
			jQuery("#formpegawai").ajaxForm(maintain_pegawai);
		});
}
function insertPegawai(){
	jQuery("#formpegawai").ajaxForm(maintain_pegawai);
}
var maintain_pegawai = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formpegawai;
		astr= "document.formpegawai";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/
				if((!i_peg_nip.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","NIP Pegawai harus diisi....!");return false;break;}
				if((!n_peg.value)){cekVal = sdmValidasiData(astr,"n_peg","Nama Pegawai harus diisi....!");return false;break;}				
				// if((!i_orgb.value)){cekVal = sdmValidasiData(astr,"i_orgb","Unit Kerja harus diisi....!");return false;break;}
				// if((!c_unit_kerja.value)){cekVal = sdmValidasiData(astr,"c_unit_kerja","Satuan Kerja harus diisi....!");return false;break;}
				// if((!c_peg_status.value)){cekVal = sdmValidasiData(astr,"c_peg_status","Status Pegawai harus diisi....!");return false;break;}				
				// if((!c_peg_jeniskelamin.value)){cekVal = sdmValidasiData(astr,"c_peg_jeniskelamin","Jenis Kelamin harus diisi....!");return false;break;}
				// if((!a_peg_lahir.value)){cekVal = sdmValidasiData(astr,"a_peg_lahir","Tempat lahir harus diisi....!");return false;break;}
				// if((!d_peg_lahir.value)){cekVal = sdmValidasiData(astr,"d_peg_lahir","Tanggal lahir harus diisi....!");return false;break;}
				//if((!c_peg_statusnikah.value)){cekVal = sdmValidasiData(astr,"d_peg_lahir","Status pernikahan harus diisi....!");return false;break;}
				// if((!n_peg_wn.value)){cekVal = sdmValidasiData(astr,"n_peg_wn","Kewarganegaraan harus diisi....!");return false;break;}
				// if((!c_peg_identitas.value)){cekVal = sdmValidasiData(astr,"c_peg_identitas","Identitas Diri harus diisi....!");return false;break;}
				// if((!i_peg_identitas.value)){cekVal = sdmValidasiData(astr,"i_peg_identitas","Nomor Identitas Diri harus diisi....!");return false;break;}
				// if((!c_golongan_darah.value)){cekVal = sdmValidasiData(astr,"c_golongan_darah","Golongan Darah harus diisi....!");return false;break;}
				break;
			}
			
		}
		
		//if (cekVal == false) {return false;}
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formpegawai").ajaxForm(maintain_pegawai);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/maintaindata',
	type: 'post',
	resetForm: false
};



function HapusDataPeg(nip)
{
	var where_to= confirm("Yakin anda akan hapus data NIP :"+nip);
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datapegawai/hapusdata"
		var opt = {nip:nip};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function setvalueuplpdf(v,n,f) { 

	  if (f!="") {
	    var pass=false;
	    var af=f.split("/");
        var nval=eval("document.forms[0]."+n);
		var ext=v.substring(v.lastIndexOf(".")+1,v.length);
		if ((ext==f)||(ext=='png')||(ext=='gif')){ 
		document.forms[0].a_file.value=v; 
		}
		else{
		  alert ("Hanya untuk file berekstensi '"+f+"',jpg,gif,png ");
		  nval.value="";
		  document.forms[0].a_file.value=""; 
		  return;	  
		}
	  }
}