<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
	
	//var_dump($this->detailStatuspegawai);
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Status Pegawai
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Status Pegawai</h2>	
		
<form id="formstatuspegawai" method="post" name="formstatuspegawai">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Status Pegawai<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>	
						<input type="text" name="c_peg_status" id="c_peg_status" value="<?=$this->detailStatuspegawai['c_peg_status'];?>" size="70" maxlength="3" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Status Pegawai<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_peg_status" id="n_peg_status" value="<?=$this->detailStatuspegawai['n_peg_status'];?>" size="70">
					</td>
				</tr>
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refstatuspegawai/liststatuspegawai','<?php echo $this->basePath; ?>/sdmmodule/refstatuspegawai/statuspegawaijs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertStatuspegawai()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateStatuspegawai()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
