       <ul id="maintab" class="tabs">
	 <li class=""><a href="#"><span>SIAP</span></a></li>
	 <li class=""><a href="rencana"><span>Perencanaan & Organisasi</span></a></li>
  	 <li class=""><a href="sdm"><span>Kepegawaian</span></a></li>
	 <li class=""><a href="keuangan"><span>Keuangan</span></a></li>
	 <li class=""><a href="aset"><span>Aset</span></a></li>
	 <li class=""><a href="logistik"><span>Logistik</span></a></li>
  	 <li class="selected"><span>Adm. User</span></li>
       </ul>