
				<h2 class="accessibility">Navigation</h2>
					<ul class="nav">
					      <li><a href="/main">Beranda</a></li>
						  
						<li><a href="./">Administrasi<!--[if IE 7]><!--></a><!--<![endif]-->
							<ul>
								<!--li class="sub"><a href="#admuser" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admuser/daftaruser','<?php echo $this->basePath; ?>/admmodule/adminuser/adminuserjs');">Administrasi User</a></li>
								<li class="sub"><a href="#admgroup" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admgroup/daftargroup','<?php echo $this->basePath; ?>/admmodule/adminsgroup/admingroupjs');">Administrasi Group</a></li-->
								<li class="sub"><a href="#admaplikasi" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admaplikasi/daftaraplikasi','<?php echo $this->basePath; ?>/admmodule/admaplikasi/admaplikasijs');">Administrasi Aplikasi</a></li>
								<li class="sub"><a href="#admaplikasi" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admmenu/daftarmenu','<?php echo $this->basePath; ?>/admmodule/admmenu/admmenujs');">Administrasi Menu</a></li>
								<li class="sub"><a href="#admaplikasi" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admgroup/daftargroup','<?php echo $this->basePath; ?>/admmodule/admgroup/admgroupjs');">Administrasi Group</a></li>
								<li class="sub"><a href="#admaplikasi" onclick="open_url_to_div('<?php echo $this->basePath; ?>/admmodule/admuser/daftaruser','<?php echo $this->basePath; ?>/admmodule/admuser/admuserjs');">Administrasi User</a></li>
							</ul>
						</li>
					</ul>

