<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">
<title>Pemerintah Kota Cimahi - Manajemen Administrasi</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<LINK href="<?echo $this->baseUrl;?>/css/adm/style.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/adm/style_adm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/adm/coloring_adm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/adm/popup.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/adm/confirm.css" type="text/css" rel="stylesheet">
<LINK href="<?echo $this->baseUrl;?>/css/adm/ui.datepicker.css" type="text/css" rel="stylesheet">
<link type="text/css" href="<?echo $this->baseUrl;?>/css/ui-lightness/jquery-ui-1.8.14.custom.css" rel="stylesheet" />
<LINK href="<?echo $this->baseUrl;?>/css/load.css" type="text/css" rel="stylesheet">

<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">

<!--<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.js"></script>-->
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/rencana/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/rencana/jquery.form.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.form.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/navigation.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/popup.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/global.js"></script>

<script type="text/javascript">
function Add(URL) {
    	window.location.href=URL;
    	}
</script>

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Masukkan no halaman yang ingin Anda tuju:';
	var on_page = '1';
	var per_page = '25';
	var onload_functions = new Array();
	var onunload_functions = new Array();
	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript">

// Current Server Time script (SSI or PHP)- By JavaScriptKit.com (http://www.javascriptkit.com)
// For this and over 400+ free scripts, visit JavaScript Kit- http://www.javascriptkit.com/
// This notice must stay intact for use.

//Depending on whether your page supports SSI (.shtml) or PHP (.php), UNCOMMENT the line below your page supports and COMMENT the one it does not:
//Default is that SSI method is uncommented, and PHP is commented:

//var currenttime = '<!--#config timefmt="%B %d, %Y %H:%M:%S"--><!--#echo var="DATE_LOCAL" -->' //SSI method of getting server date
var currenttime = '<? print date("F d, Y H:i:s", time())?>' //PHP method of getting server date
///////////Stop editting here/////////////////////////////////

var dayarray=new Array("Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu");
var montharray=new Array("Januari","Februari","Maret","April","Mei","Juni","July","Agustus","September","Oktober","November","Desember")
var serverdate=new Date(currenttime)

function padlength(what){
var output=(what.toString().length==1)? "0"+what : what
return output
}

function displaytime(){
serverdate.setSeconds(serverdate.getSeconds()+1)
var datestring=dayarray[serverdate.getDay()]+", "+padlength(serverdate.getDate())+" "+montharray[serverdate.getMonth()]+" "+serverdate.getFullYear()
var timestring=padlength(serverdate.getHours()-1)+":"+padlength(serverdate.getMinutes())+":"+padlength(serverdate.getSeconds())
document.getElementById("servertime").innerHTML=datestring+" | "+timestring
}

window.onload=function(){
setInterval("displaytime()", 1000)
}

</script>

