<div class="navlink">
	<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
	<strong> &#8250; </strong>Import Data
</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
</div>


<h2>Import Data</h2>
<div class="panel">

	<form id="formimport" method="post" name="formimport" enctype="multipart/form-data" action="">
<table>
<tr>
	<td width="30%">File Excel</td>
	<td width="2%">:</td>
	<td><input name="userfile" type="file" size="70">&nbsp;<input name="upload" type="submit" value="Proses" onclick="uploadData()"></td>	
</tr>
<tr>
	<td width="30%">&nbsp;</td>
	<td width="2%">&nbsp;</td>
	<td>&nbsp;</td>	
</tr>
<tr>
	<td width="30%">Download Template File Excel disini</td>
	<td width="2%">:</td>
	<td></td>	
</tr>
</table>

	
	
	</form>
</div>	