<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Universitas
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Universitas</h2>	
		
<form id="formuniversitas" method="post" name="formuniversitas">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Universitas<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_universitas" id="c_universitas" value="<?=$this->detailUniversitas['c_universitas']?>" size="70" maxlength="4" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Universitas 2<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_universitas2" id="n_universitas2" value="<?=$this->detailUniversitas['n_universitas2']?>" size="70">
					</td>
				</tr><tr>
					<td>N Rayon Pro<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_rayon_pro" id="n_rayon_pro" value="<?=$this->detailUniversitas['n_rayon_pro']?>" size="70" maxlength="3">
					</td>
				</tr><tr>
					<td>Q Strata<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="q_strata" id="q_strata" value="<?=$this->detailUniversitas['q_strata']?>" size="70" maxlength="1">
					</td>
				</tr><tr>
					<td>Nama Universitas<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_universitas" id="n_universitas" value="<?=$this->detailUniversitas['n_universitas']?>" size="70">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refuniversitas/listuniversitas','<?php echo $this->basePath; ?>/sdmmodule/refuniversitas/universitasjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertUniversitas()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateUniversitas()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
