<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
	
	//var_dump($this->detailKabupaten);
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Kabupaten
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Kabupaten</h2>	
		
<form id="formkabupaten" method="post" name="formkabupaten">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Kabupaten<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>	
						<input type="text" name="c_kabupaten" id="c_kabupaten" value="<?=$this->detailKabupaten['c_kabupaten'];?>" size="70" maxlength="4">
					</td>
				</tr><tr>
					<td>Nama Kabupaten<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_kabupaten" id="n_kabupaten" value="<?=$this->detailKabupaten['n_kabupaten'];?>" size="70">
					</td>
				</tr><tr>
					<td>Kode Propinsi<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_propinsi" id="c_propinsi" value="<?=$this->detailKabupaten['c_propinsi'];?>" size="70" maxlength="4">
					</td>
				</tr>
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refkabupaten/listkabupaten','<?php echo $this->basePath; ?>/sdmmodule/refkabupaten/kabupatenjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertKabupaten()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateKabupaten()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
