<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/Portalconf.php'; 

$idberita = $_REQUEST['idberita'];
/*$vFoto = $this->basePath."../data/sdm/photo/".trim($this->i_peg_nip).".jpg";

	if (!file_exists($vFoto)) {
		$vFoto = $this->basePath."../images/nophoto.jpg";
	} 
*/
?>



<div id="backgroundPopup">
  <div id="popupContact">  
    <div id="popupContactClose" title="Close" onclick="closeDetil()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
		<div style="overflow: hidden;">
			<div class="wrapper">
				<div class="panel" style="height: 600px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h3><?=$this->jdlagenda;?></h3>
				Tempat : <?=$this->n_tempat?><br>
				Waktu : <span class="date"><?=$this->tglagenda?></span>
				Acara : <?=$this->detilagenda?><br>
	  </div>
	</div>	
  </div>
</div>	