<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> Laporan
				<strong> &#8250; </strong> Monitoring Pensiun
			</div>
<div id="top"></div>

<h2 class="title">Monitoring Pensiun</h2>
<?php include "$this->leftMenu/fungsionallink.phtml";?>
<form id="formresult" method="post" action="" name="formresult">
	<div class="boxholder">				
	<div class="panel">
		<div class="spacer"></div> 
			<h3 class="title"><b><u>UNIT KERJA</u></b><h3>

		
	<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">

		<tr>
			<td width="25%">Lokasi</td>
			<td width="2%">:</td> 
			<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon II</td>
			<td>:</td> 
			<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliii')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
			</td>
			</tr>						
		<tr>
			<td>Eselon III</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliv')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon IV</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","disabled"=>"true","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon V</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
										else{$eslAtrib = array("style"=>"width: 300px","disabled"=>"true","id"=>"c_eselon_v");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			</td>
		</tr>							
	</table>
	<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
		<tr>
			<td width="25%">Status Kepegawaian</td>
			<td width="2%">:</td>
			<td>
							<?php 
									   $jmlStatusKePegRef = count($this->statusKePegRef);
									   $statkepegList[''] = '--Pilih--';
									   for ($i = 0; $i < $jmlStatusKePegRef; $i++) {									   
										$statkepegList[(string)$this->statusKePegRef[$i]->c_status_kepegawaian] = (string)$this->statusKePegRef[$i]->n_status_kepegawaian;			 
									   }
									   $statkepegAtrib = array("onChange"=>"javascript:getStatPeg()");
									  echo $ctrlFrm->formSelect('c_status_kepegawaian', $this->c_status_kepegawaian,$statkepegAtrib, $statkepegList)
								?>							
			</td>
		</tr>	
		<tr>
			<td width="25%">Golongan/Pangkat</td>
			<td width="2%">:</td> 
			<td id="targetgol">				
					<?
						$jmlgolref = count($this->statusGolRef);												   
						$golonganReff[''] = '--Pilih--';
						for ($i = 0; $i < $jmlgolref; $i++) {
								$n_peg_pangkat=trim($this->statusGolRef[$i]['n_peg_pangkat']);
								$c_peg_golongan=trim($this->statusGolRef[$i]['c_peg_golongan']);										   
								$golonganReff[trim((string)$this->statusGolRef[$i]['c_peg_golongan'])] = $c_peg_golongan."-".$n_peg_pangkat;											   
						}												 
						 echo $ctrlFrm->formSelect('c_golongan', $this->c_golongan, null, $golonganReff);
					?>
			</td>
		</tr>	
		<tr>
			<td>Bulan</td>
			<td>:</td> 
			<td>				
					<?
						$blnPar = array(""=>"--Pilih--","01"=>"Januari","02"=>"Pebruari","03"=>"Maret","04"=>"April","05"=>"Mei","06"=>"Juni","07"=>"Juli","08"=>"Agustus","09"=>"September","10"=>"Oktober","11"=>"Nopember","12"=>"Desember");
						echo $ctrlFrm->formSelect('blnawal',$this->blnawal, null, $blnPar)." ";						
						//echo $ctrlFrm->formSelect('blnakhir',$this->blnawal, null, $blnPar); 
						$thnx="";
						$thnList="";
						$thnx=date('Y');
						$thnList[''] = '--Pilih--';
						for ($i = 0; $i < 8; $i++) {									
						$thnList[$thnx*1+$i] = $thnx*1+$i;			 
						}											
						echo $ctrlFrm->formSelect('thnawal',$this->thnawal, null, $thnList);
						echo " s/d ";

						echo $ctrlFrm->formSelect('thnakhir',$this->thnakhir, null, $thnList);
					?>
			</td>
		</tr>
		<!--
		<tr>
			<td>Dasar Pengurutan</td>
			<td>:</td> 
			<td>				
					<?
						// $jmleselonvList=count($this->eselonvList);
						// $eselonvList[''] = '--Pilih--';
						// for ($i = 0; $i < $jmleselonvList; $i++) {
							// $eselonvList[(string)$this->eselonvList[$i]->c_eselon_v] = (string)$this->eselonvList[$i]->n_unitkerja;			 
						// }
						// echo $ctrlFrm->formSelect('c_eselon_v_cpns',$this->c_eselon_v_cpns, null, $eselonvList); 							
					?>
			</td>
		</tr>
		-->
	</table>	
</div>
<br>
	<div class="panel">			
		<div class="spacer"></div>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
				<td colspan="4" align="center">
					Awal Data : <input size="8" name="start" value="1" id="start" onkeypress="return justnumber(event)" type="text">
					&nbsp;&nbsp;&nbsp;&nbsp;
					Data per halaman : <input size="8" name="limit" value="25" onkeypress="return justnumber(event)" type="text">
				</td>
				</tr>
				<tr>
					<td align="center">
						&nbsp;
					</td>
				</tr>					
				<tr>
					<td align="center">
						<input type="submit" value="View" onclick="viewPens();"> 
						<input type="submit" value="Cetak Excel" onclick="viewExl()"> &nbsp;
					</td>
				</tr>
			</table>				
	</div>
</div>	

</form>	
<div id="popupview"></div>
<script>
function getStatPeg(){
	var c_status_kepegawaian=document.getElementById('c_status_kepegawaian').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/monitoringkgb/listgolongan'; 
	var param = {c_status_kepegawaian:c_status_kepegawaian};
	jQuery.get(url, param, function(data) {
		jQuery("#targetgol").html(data);	
	});

}
</script>
