function openFormSekolahmil(par,c_sekolahmil,n_sekolahmil){
	var url = "<?php echo $this->basePath; ?>/sdmmodule/refsekolahmil/sekolahmilolahdata";
	var opt = {par:par, c_sekolahmil:c_sekolahmil, n_sekolahmil:n_sekolahmil};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			//jQuery("#formsekolahmil").ajaxForm(maintain_sekolahmil);
		});		
} 

function insertSekolahmil(){
	jQuery("#formsekolahmil").ajaxForm(maintain_sekolahmil);
}

var maintain_sekolahmil = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formsekolahmil").ajaxForm(maintain_sekolahmil);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/refsekolahmil/insertsekolahmil',
	type: 'post',
	resetForm: false
};

function updateSekolahmil(){
	jQuery("#formsekolahmil").ajaxForm(update_sekolahmil);
}

var update_sekolahmil = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formsekolahmil").ajaxForm(maintain_sekolahmil);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/refsekolahmil/updatesekolahmil',
	type: 'post',
	resetForm: false
};

function HapusSekolahmil(param1, param2, param3){
	if(ConfirmDelete(param1, param3))
	{	//alert("test");
		handler = '<?php echo $this->basePath; ?>/sdmmodule/refsekolahmil/deletesekolahmil';
		var opt = {c_sekolahmil : param2};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				doCount(5);
			 });
	} 
}
