<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Nama Penjenjangan
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Nama Penjenjangan</h2>	
		
<form id="formnama" method="post" name="formnama">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode jenjang<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_jenjang" id="c_jenjang" value="<?=$this->detailNama['c_jenjang']?>" size="70" maxlength="2" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Nama<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_jenjang" id="n_jenjang" value="<?=$this->detailNama['n_jenjang']?>" size="70" >
					</td>
				</tr><tr>
					<td>Kode Jenis<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_jenis" id="c_jenis" value="<?=$this->detailNama['c_jenis']?>" size="70" maxlength="2">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refnama/listnama','<?php echo $this->basePath; ?>/sdmmodule/refnama/namajs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertNama()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateNama()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
