<!--footer-->
<footer id="footer">
    <div class="container">
    <div class="row">
        <div class="span4">
            <h3>Galeri</h3>
            <ul class="flickr clearfix"></ul>
        </div>
        <div class="span4">
            <h3>Agenda</h3>
            <ul class="ul-col1 clearfix">
				<?php
					foreach ($this->agendaPubList as $key => $val): 
						$date=$this->escape($val['d_agenda']);
						$date=konversi_tanggal("D, j M Y",$date)
				?>
					<li><span class="date"> <?php echo $date ?></span>
					<h4><a href="#detilagenda" onclick="detilagenda('<?php echo $this->escape($val['c_agenda']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h4>
				
					</li>
				<?php endforeach;?>
			</ul>
        </div>
        <div class="span4">
		 <h3>Kontak Kami</h3>
           <?php
				$jmlkontakkamiList = count($this->kontakkamiList);
					//echo $jmlkontakkamiList;
				   for ($j = 0; $j < $jmlkontakkamiList; $j++) {
					 $kontakkami[$j] = array("c_kontakkami"  		=>(string)$this->kontakkamiList[$j]['c_kontakkami'],
										"n_judul"      		=>(string)$this->kontakkamiList[$j]['n_judul'],
										 "n_detil"  		=>(string)$this->kontakkamiList[$j]['n_detil'],
										  "c_status"  		=>(string)$this->kontakkamiList[$j]['c_status']);
				   } 
				   
				   
					foreach ($kontakkami as $key => $val): 
						$n_judul	= $this->escape($val['n_judul']);		
						$n_detil	= ($val['n_detil']);
					?>
					<p><?php echo ($n_detil)  ?>
					</p>
					<?php endforeach;?>
        </div>
    </div>
    </div>
</footer>

<!--footer menu-->
<section id="footer-menu">
    <div class="container">
        <div class="row">
            <p class="span12"><span>&copy; Copyright <?php echo date('Y');?>, <span class="color2">Portal Kecamatan Pemerintah Kota Cimahi</span> | All Rights Reserved</span></p>
        </div>
    </div>
</section>
</body>
</html>
