<!--footer-->
<footer id="footer">
    <div class="container">
    <div class="row">
        <div class="span4">
            <h3>Galeri</h3>
            <ul class="flickr clearfix"></ul>
        </div>
        <div class="span4">
            <h3>Agenda</h3>
            <ul class="ul-col1 clearfix">
				<?php
					foreach ($this->agendaPubList as $key => $val): 
						$date=$this->escape($val['d_agenda']);
						$date=konversi_tanggal("D, j M Y",$date)
				?>
					<li><span class="date"> <?php echo $date ?></span>
					<h4><a href="#detilagenda" onclick="detilagenda('<?php echo $this->escape($val['c_agenda']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h4>
				
					</li>
				<?php endforeach;?>
			</ul>
        </div>
        <div class="span4">
            <h3>Contact Form</h3>
            <form id="contact" class="form-horizontal" method="post">
                <div class="controls">
                    <input type="text" id="inputName" placeholder="Name" name="inputName">
                    <label class="ferror" for="inputName" id="fname_error">Name is required.</label>
                </div>
                <div class="controls">
                    <input type="text" id="inputEmail" placeholder="Email" name="inputEmail">
                    <label class="ferror" for="inputEmail" id="femail_error">Email is required.</label>
                </div>
                <div class="controls">
                    <textarea rows="3" id="inputMessage" placeholder="Message" name="inputMessage"></textarea>
                    <label class="ferror" for="inputMessage" id="fmessage_error">Message is required.</label>
                </div>
                <div class="controls">
                    <input type="submit" class="btn btn-success btn-large footer-button" value="Submit">
                </div>
            </form>
        </div>
    </div>
    </div>
</footer>

<!--footer menu-->
<section id="footer-menu">
    <div class="container">
        <div class="row">
            <p class="span12"><span>&copy; Copyright <?php echo date('Y');?>, <span class="color2">Sistem Informasi Pemerintah Kota Cimahi Terintegrasi</span> | All Rights Reserved</span></p>
        </div>
    </div>
</section>
</body>
</html>
