 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=100%; initial-scale=1; maximum-scale=1; minimum-scale=1; user-scalable=no;" />
    <link rel="icon" href="images/favicon.png" type="image/png">
    <link rel="shortcut icon" href="images/favicon.png" type="image/png" />
    <title>Home Page</title>
    <link href="kecamatan/css/bootstrap.css" type="text/css" rel="stylesheet"/>
    <link href="kecamatan/css/style.css" type="text/css" rel="stylesheet"/>
    <link href="kecamatan/css/prettyPhoto.css" type="text/css" rel="stylesheet"/>
    <script type="text/javascript" src="kecamatan/js/jquery.min.js"></script>
    <script type="text/javascript" src="kecamatan/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.quicksand.js"></script>
    <script type="text/javascript" src="kecamatan/js/superfish.js"></script>
    <script type="text/javascript" src="kecamatan/js/hoverIntent.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.hoverdir.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.flexslider.js"></script>
    <script type="text/javascript" src="kecamatan/js/jflickrfeed.min.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.elastislide.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.tweet.js"></script>
    <script type="text/javascript" src="kecamatan/js/smoothscroll.js"></script>
    <script type="text/javascript" src="kecamatan/js/jquery.ui.totop.js"></script>
    <script type="text/javascript" src="kecamatan/js/main.js"></script>
    <script type="text/javascript" src="kecamatan/js/ajax-mail.js"></script>
    <script type="text/javascript" src="kecamatan/js/accordion.settings.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <link href="kecamatan/css/ie.css" type="text/css" rel="stylesheet"/>
    <![endif]-->