<title>Sistem Informasi Pemerintah Kota Cimahi Terintegrasi</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link rel='stylesheet' href='<?echo $this->baseUrl;?>/css/login.css' type='text/css' />

<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-1.6.2.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.form.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/navigation.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/popup.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/ui.datepicker.js"></script>
