
				<h2 class="accessibility">Navigation</h2>
					<ul class="nav">
					      <li><a href="main">Beranda</a></li>
						  
						<li>
							<a href="#Administrasiperkara">Informasi Perkara<!--[if IE 7]><!--></a><!--<![endif]-->
							<ul>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/administrasiperkara/daftaradministrasiperkara','<?php echo $this->baseUrl; ?>/siapmodule/administrasiperkara/administrasiperkarajs');">Data Perkara</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/administrasiperkara/laporanperkara','<?php echo $this->baseUrl; ?>/siapmodule/administrasiperkara/administrasiperkarajs');">Pelaporan Data Perkara</a></li>
							</ul>	
						</li>
						<li>
							<a href="#">Monitoring percepatan penyelesaian Perkara<!--[if IE 7]><!--></a><!--<![endif]-->
							<ul>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perkarakasasi/listperkarakasasi','<?php echo $this->baseUrl; ?>/siapmodule/perkarakasasi/perkarakasasijs');">Monitoring Perkara Kasasi</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perkarapk/listperkarapk','<?php echo $this->baseUrl; ?>/siapmodule/perkarapk/perkarapkjs');">Monitoring Perkara PK</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perkaragrasi/listperkaragrasi','<?php echo $this->baseUrl; ?>/siapmodule/perkaragrasi/perkaragrasijs');">Monitoring Perkara Grasi</a></li>
								<li class="sub"><a href="#">Monitoring Waktu Perkara</a>
							    <ul>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perdata/listperdata','<?php echo $this->baseUrl; ?>/siapmodule/perdata/perdatajs');">Perdata Umum</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perdatakhusus/listperdatakhusus','<?php echo $this->baseUrl; ?>/siapmodule/perdatakhusus/perdatakhususjs');">Perdata Khusus</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/pidana/listpidana','<?php echo $this->baseUrl; ?>/siapmodule/pidana/pidanajs');">Pidana Umum</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/pidanakhusus/listpidanakhusus','<?php echo $this->baseUrl; ?>/siapmodule/pidanakhusus/pidanakhususjs');">Pidana Khusus</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/tun/listtun','<?php echo $this->baseUrl; ?>/siapmodule/tun/tunjs');">TUN</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/pidanamiliter/listpidanamiliter','<?php echo $this->baseUrl; ?>/siapmodule/pidanamiliter/pidanamiliterjs');">Militer</a></li>
								   <li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/perdataagama/listperdataagama','<?php echo $this->baseUrl; ?>/siapmodule/perdataagama/perdataagamajs');">Agama</a></li>
							    </ul>
								</li>
							</ul>
						</li>
						<li>
							<a href="#">Monitoring Statistik Perkara<!--[if IE 7]><!--></a><!--<![endif]-->
							<ul>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/lisstskprkrkasasi','<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/statistikperkarajs');">Kasasi</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/lisstskprkrpk','<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/statistikperkarajs');">Peninjauan Kembali</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/lisstskprkrgrasi','<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/statistikperkarajs');">Grasi</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/lisstskprkrpajak','<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/statistikperkarajs');">Pajak</a></li>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/lisstskprkrhum','<?php echo $this->baseUrl; ?>/siapmodule/statistikperkara/statistikperkarajs');">Hum</a></li>
							</ul>
						</li>
						<li>
							<a href="#">Monitoring SDM<!--[if IE 7]><!--></a><!--<![endif]-->
							<ul>
								<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->baseUrl; ?>/siapmodule/hakimpensiun/listhakimpensiun','<?php echo $this->baseUrl; ?>/siapmodule/hakimpensiun/hakimpensiunjs');">Komposisi Hakim Masa Pensiun</a></li>
									<li class="sub"><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/siapmodule/monitoringpensiun/monitoringpensiun','<?php echo $this->basePath; ?>/siapmodule/monitoringpensiun/monitoringpensiunjs');">Komposisi Pensiun</a></li>
							</ul>
						</li>
					</ul>

