<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmlPegawaiList = count($this->pegawaiList);

?>


	<form action="" method="post"> 
		<fieldset class="fields"> 
   <table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
		<tr>
			<th>No.</th>
			<th>Photo</th>
			<th class="<?=$this->orderbya?>" width="62%" onclick="orderBy('n_peg','<?=$this->orderbyb?>','<?php echo $this->basePath; ?>/sdmmodule/monitoringcv/monitoringcv')">Biodata</th>
			<th width="20%">Jabatan</th>
			<th width="5%">&nbsp;</th>
		</tr> 
<? 		if ($jmlPegawaiList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->pegawaiList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					$pangkat = $this->escape($val['n_pangkat']);
					$golongan = $this->escape($val['c_golongan']);
					$golPangkat = $golongan." - ".$pangkat;
					$n_lokasi_unitkerja=$this->escape($val['n_lokasi_unitkerja']);
					$n_eselon=$this->escape($val['n_eselon']);
					$n_jabatan=$this->escape($val['n_jabatan']);
					$alamat=$this->escape($val['a_peg_rumah']).' RT: '.$this->escape($val['a_peg_rt']).' RW: '.$this->escape($val['a_peg_rw']).' Kel: '.$this->escape($val['a_peg_kelurahan']).' Kec: '.$this->escape($val['a_peg_kecamatan']).' Kota/Kab: '.$this->escape($val['n_peg_kota']).' Prop: '.$this->escape($val['n_peg_propinsi']);
		
				?>
					<td class="clcenter"><?php echo $noUrut;?></td>
					<td>
					<?
					$vFoto="";
					$vFoto = $this->basePath."/upld/Uploaddata/getphoto?f=".trim($this->escape($val['e_file_photo']));
					?>
					<img src="<?=$vFoto?>" width="55" height="60" >
					</td>
					<td>
					<table border="0" cellspacing="1" cellpadding="2" class="std">
						<tr>
						<td width="10%">Nama</td>
						<td width="1%">:</td>
						<td width="52%"><?php echo $this->escape($val['n_peg']);?></td>
						<td width="10%">Jns. Kel</td>
						<td width="1%">:</td>
						<td width="25%">
						<?php 
							if($this->escape($val['c_peg_jeniskelamin'])=="L"){echo "Laki-laki";}
							if($this->escape($val['c_peg_jeniskelamin'])=="P"){echo "Perempuan";}
						?>
						</td>
						</tr>
						<tr>
						<td>Nip</td>
						<td>:</td>
						<td><?php echo $this->escape($val['i_peg_nip']);?></td>
						<td>Eselon</td>
						<td>:</td>
						<td><?php echo $n_eselon;?></td>
						</tr>
						<tr>
						<td>Gol/Pangkat</td>
						<td>:</td>
						<td><?php echo $golPangkat;?></td>
						<td>Stat.Peg.</td>
						<td>:</td>
						<td><?php echo $this->escape($val['n_peg_status']);?></td>						
						</tr>	
				
					</table>
					</td>	
				    <td><?php echo $n_jabatan;?></td>
					<td class="clcenter"><input type="button" value="Cetak" onclick="cetakCv('<?=$this->escape($val['i_peg_nip'])?>')"> </td>
				</tr>
				<?php endforeach;}?>
	
	</table>

	</fieldset>		 
	</form>