<? 
	require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
?>
<div id="backgroundPopup" >
	<center>
	<div id="popupContact" style="height:310px; width:550px;" >
	

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Help : Diklat Pimpinan Terakhir</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>

			<form enctype="multipart/form-data" method="post" id="f" name="f">
			<table border="0" width="100%" class="table">
			<tbody>
<!--
				<tr valign="top" class="row">
					<td align="left" nowrap="">Tingkat</td>
					<td align="left" colspan="2">
						<select id="operand0" name="operand0">
							<option value="IN">Pernah / =</option>
							<option value="NOT IN">Belum Pernah</option>
						</select>
							<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="1" id="jns_pimt[]" name="jns_pimt[]">&nbsp;PIM I&nbsp;
							<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="2" id="jns_pimt[]" name="jns_pimt[]">&nbsp;PIM II&nbsp;
							<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="3" id="jns_pimt[]" name="jns_pimt[]">&nbsp;PIM III&nbsp;
							<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="4" id="jns_pimt[]" name="jns_pimt[]">&nbsp;PIM IV&nbsp;
							<input type="hidden" value="0" id="jumlahcek" name="jumlahcek">
							<input type="button" onclick="if (parseInt(document.getElementById('jumlahcek').value) &gt; 0) {var oprand = document.getElementById('operand0').value; var strg = document.getElementById('query_nip').value; var rstdrh = check_all(document.getElementsByName('jns_pimt[]'),document.getElementById('jumlahcek').value,true); if (strg != '') {document.getElementById('query_nip').value = strg + ' a.LEVELPIM ' + oprand + ' (' + rstdrh + ') ';} else {document.getElementById('query_nip').value = ' a.LEVELPIM ' + oprand + '(' + rstdrh + ') ';}}" value="Masukan!" tabindex="55" name="bt_input" id="bt_input">
					</td>
				</tr>	
-->				
				<tr class="row">
					<td align="left" nowrap="">Nama</td>
					<td align="left" colspan="2">
						<select id="operand" name="operand">
							<option value="=">Sama dengan</option>
							<option value="!=">Tidak Sama dengan</option>
						</select>&nbsp;
						<?php
						   $jmllistrpenjenjangan = count($this->listrpenjenjangan);
						   $listrpenjenjangan[''] = '--Pilih--';
							for ($i = 0; $i < $jmllistrpenjenjangan; $i++) {	 
								$listrpenjenjangan[$this->listrpenjenjangan[$i]->c_jenjang ]= (string)$this->listrpenjenjangan[$i]->n_jenjang;			 
						   }    
							$dikAtrib = array("onChange"=>"if (this[this.selectedIndex].value != '') {var strg = document.getElementById('query_nip').value;var oprand = document.getElementById('operand').value; if (strg == '') {document.getElementById('query_nip').value = ' c_penjenjangan ' + oprand + '\'' + this[this.selectedIndex].value + '\'';} else  {document.getElementById('query_nip').value = strg + ' c_penjenjangan ' + oprand + '\'' + this[this.selectedIndex].value + '\'';}}");
							echo $ctrlFrm->formSelect('jns_diklat', $this->jns_diklat, $dikAtrib, $listrpenjenjangan);
						?>						
					</td>
				</tr>
				<tr class="row1">
					<td align="left" nowrap="">Angkatan</td>
					<td align="left" colspan="2">
						<select id="operand1" name="operand1">
							<option value="=">Sama dengan</option>
							<option value="!=">Tidak Sama dengan</option>
						</select>&nbsp;
							<input type="text" onkeypress="return justromawi(event)" tabindex="2" maxlength="7" value="" size="20" name="angk_diklat" id="angk_diklat"> 
							<input type="button" onclick="if (document.getElementById('angk_diklat').value != '') {var thlls = document.getElementById('angk_diklat').value;var strg = document.getElementById('query_nip').value;var oprand = document.getElementById('operand1').value; if (strg == '') {document.getElementById('query_nip').value = ' q_angkatan ' + oprand + ' \'' + thlls + '\'';} else  {document.getElementById('query_nip').value = strg + ' q_angkatan ' + oprand + ' \'' + thlls + '\'';}}" value="Masukan!" tabindex="55" name="bt_input3" id="bt_input3">
					</td>
				</tr>
				<tr class="row1">
					<td align="left" nowrap="">Tahun</td>
					<td align="left" colspan="2">
						<select id="operand2" name="operand2">
							<option value="=">Sama dengan</option>
							<option value="!=">Tidak Sama dengan</option>
						</select>&nbsp;
							<input type="text" onkeypress="return justnumber(event)" tabindex="3" value="" maxlength="4" size="6" name="thn_diklat" id="thn_diklat">
							<input type="button" onclick="if (document.getElementById('thn_diklat').value != '') {var thlls = document.getElementById('thn_diklat').value;var strg = document.getElementById('query_nip').value;var oprand = document.getElementById('operand2').value; if (strg == '') {document.getElementById('query_nip').value = ' q_tahun ' + oprand + ' \'' + thlls + '\'';} else  {document.getElementById('query_nip').value = strg + ' q_tahun ' + oprand + ' \'' + thlls + '\'';}}" value="Masukan!" tabindex="55" name="bt_input3" id="bt_input3">
					</td>
				</tr>
				<tr>
					<td align="center" colspan="3" class="row">&nbsp;</td>
				</tr>			
							
				<tr>
					<td align="center" colspan="3" class="row1">
						<textarea cols="70" rows="5" id="query_nip" name="query_nip"></textarea>
					</td>
				</tr>
				<tr class="row1">
					<td align="left" nowrap="" colspan="3">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="55" name="bt1">
						&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {  document.getElementById('query_nip').value = ' OR ';} else  {document.getElementById('query_nip').value = strg + ' OR ';}" value=" OR " tabindex="56" name="bt0">
						&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {  document.getElementById('query_nip').value = ' AND ';} else  {document.getElementById('query_nip').value = strg + ' AND ';}" value=" AND " tabindex="57" name="bt2">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt2">
						&nbsp;<input type="button" onclick="document.getElementById('query_nip').value= ''" value=" Clear " tabindex="57" name="bt3">
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg; closeDetil()}" value="OK !" tabindex="58" name="bt3">
					</td>
				</tr>

			</tbody>
			</table> 	
			</form>
			
			

	
	</div>
	</center>
</div>	