<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
$ceseloncpns=$this->ceseloncpns*1;
?>

 	<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tpm").datepicker();
		
	});
	
	</script>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong> TPM &nbsp;
				<strong> &#8250; </strong><?=$this->jdl;?> PRA TPM
			</div>
<div id="top"></div>
<div id="confirm" class="<?echo $confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form id="formtpm" method="post" action="" name="formtpm"enctype="multipart/form-data" >
<h2 class="title"><?=$this->jdl;?> PRA TPM</h2>	
<div class="panel">
<table>
	<tr>
		<td width="22%">Nomor Surat <span class="hightlight">*</span></td>
		<td width="2%">:</td>
		<td>
			<input type="text" name="usulan_nomor" id="usulan_nomor" value="<?=$this->usulan_nomor?>" size="50" readonly="true">
			<input type="hidden" name="usulan_id" id="usulan_id" value="<?=$this->usulan_id?>" size="50">
			&nbsp;<input type="button" value="Cari Nomor Surat" onClick="cariTpmUsul()">
		</td>
	</tr>
	<tr>
		<td width="22%">Usulan Jabatan</td>
		<td width="2%">:</td>
		<td>
			<input type="hidden" name="usulan_keterangan" id="usulan_keterangan" size="80" value="<?=$this->usulan_keterangan?>">
			<input type="text" name="n_jabatan" id="n_jabatan" size="80" value="<?=$this->n_jabatan?>">
			<input type="hidden" name="tvinstansi_kd" id="tvinstansi_kd" value="<?=$this->tvinstansi_kd?>" size="80" readonly="true">
			<input type="hidden" name="c_eselon_i" id="c_eselon_i" value="<?=$this->c_eselon_i?>" size="80" readonly="true">
			<input type="hidden" name="c_eselon_ii" id="c_eselon_ii" value="<?=$this->c_eselon_ii?>" size="80" readonly="true">
			<input type="hidden" name="c_eselon_iii" id="c_eselon_iii" value="<?=$this->c_eselon_iii?>" size="80" readonly="true">
			<input type="hidden" name="c_eselon_iv" id="c_eselon_iv" value="<?=$this->c_eselon_iv?>" size="80" readonly="true">
			<input type="hidden" name="c_satker" id="c_satker" value="<?=$this->c_satker?>" size="80" readonly="true">
			<input type="hidden" name="c_parent" id="c_parent" value="<?=$this->c_parent?>" size="80" readonly="true">
			<input type="hidden" name="unitkerja" id="unitkerja" value="<?=$this->unitkerja?>" size="80" readonly="true">
			<input type="hidden" name="n_unitkerja" id="n_unitkerja" value="<?=$this->n_unitkerja?>" size="80" readonly="true">
			
		</td>
	</tr>	
</table>

<div id="unitkerjax" style="display: inline"><?include("unitkerjax.phtml");?></div>
<div id="unitkerjay" style="display: none"><?include("unitkerjay.phtml");?></div>

<table>	
	<tr>
		<td width="22%">Tanggal</td>
		<td width="2%">:</td>
		<td>
			<input type="text" name="mod_date" id="mod_date" value="<?=$this->mod_date?>" size="10"  readonly="true">&nbsp;<span class="hightlight">tgl-bln-thn</span>
		</td>
	</tr>

	<tr>
		<td width="22%">Periode</td>
		<td width="2%">:</td>
		<td>
			<input type="text" name="periode_text" id="periode_text" value="<?=$this->periode_text?>" size="80" readonly="true">
		</td>
	</tr>		
	<tr>
		<td width="22%">Keterangan Periode</td>
		<td width="2%">:</td>
		<td>
			<input type="text" name="periode_keterangan" id="periode_keterangan" value="<?=$this->periode_keterangan?>" size="80" readonly="true">
		</td>
	</tr>
<tr>
<td width="22%">Tanggal Pra TPM <span class="hightlight">*</span></td>
<td width="2%">:</td>
<td>
	<input type="text" name="d_tpm" id="d_tpm" value="<?=$this->tgl_pratpm?>" size="10">&nbsp;<span class="hightlight">tgl-bln-thn</span>
</td>
</tr>
<tr>
<td width="22%">Kegiatan Pra TPM <span class="hightlight">*</span></td>
<td width="2%">:</td>
<td>
	<input type="text" name="n_tpm" id="n_tpm" value="<?=$this->ket_pratpm?>" size="80">
</td>
</tr>
</table>	
<br>
<? 		if (count($this->dataPraTpm) == 0) {?>

			<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
				<th width="22%">NIP</th>
				<th width="38%">Nama</th>
				<th width="25%">No. Surat Rekomendasi</th>
				<th width="8%">&nbsp;</th>

				<tr class="event" id="tr_1">
					<td>						
						<textarea id="i_peg_nip_1" name="i_peg_nip_1" rows="1" readonly="true"><?=$this->i_peg_nip_1?></textarea>
					</td>
					<td>						
						<textarea id="n_peg_1" name="n_peg_1" rows="1" readonly="true"><?=$this->n_peg_1?></textarea>
						<input type="hidden" id="c_golongan_1" name="c_golongan_1" value="" size = "60">
						<input type="hidden" id="n_pangkat_1" name="n_pangkat_1" value="" size = "60">
						<input type="hidden" id="c_jnskelamin_1" name="c_jnskelamin_1" value="" size = "60">
					</td>					
					<td>						
						<textarea id="usulan_rekomendasi_pratpm_1" name="usulan_rekomendasi_pratpm_1" rows="1"><?=$this->usulan_rekomendasi_pratpm_1?></textarea>
					</td>
					<td>	
						<img src="<?echo $this->basePath;?>/images/plus.gif" title="Tambah Baris" class=link onclick=javascript:tambahBaris('1','1'); > 
						<img src="<?echo $this->basePath;?>/images/minus.gif" title="Hapus Baris" class=link onclick=javascript:hapusBarisx('1'); >
						<img src="<?echo $this->basePath;?>/images/page.png" title="Daftar Riwayat Hidup" class=link onclick=javascript:cetakdrh(document.getElementById('i_peg_nip_1').value); > 
					</td>
				</tr>
			</table>
<div id="tblind_1"></div>
<input type="hidden" id="counttable" name="counttable" value="1" size = "10">				
<?}else{?>			
			<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
				<th width="22%">NIP</th>
				<th width="38%">Nama</th>
				<th width="25%">No. Surat Rekomendasi</th>
				<th width="8%">&nbsp;</th>
<?
$con=1;				
				foreach ($this->dataPraTpm as $key => $val):
?>				
			<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl" id="tblIndikator_<?echo $con?>">	
<?			
				if ($key%2==0) { ?>
				<tr class="event" id="tr_<?echo $con?>">
				<? } else if ($key%2==1) { ?>
				<tr class="event2" id="tr_<?echo $con?>">
				<? } 
?>
					<td width="22%">
						<textarea id="i_peg_nip_<?echo $con?>" name="i_peg_nip_<?echo $con?>" rows="1" readonly="true"><?php echo $this->escape($val['peg_nip']);?></textarea>
					</td>
					<td width="38%">
						<textarea id="n_peg_<?echo $con?>" name="n_peg_<?echo $con?>" rows="1" readonly="true"><?php echo trim($this->escape($val['tpm_namalengkap']));?></textarea>
						<input type="hidden" id="c_golongan_<?echo $con?>" name="c_golongan_<?echo $con?>" value="<?php echo $this->escape($val['usulan_nomor']);?>" size = "60">
						<input type="hidden" id="n_pangkat_<?echo $con?>" name="n_pangkat_<?echo $con?>" value="<?php echo $this->escape($val['usulan_nomor']);?>" size = "60">
						<input type="hidden" id="c_jnskelamin_<?echo $con?>" name="c_jnskelamin_<?echo $con?>" value="<?php echo $this->escape($val['usulan_nomor']);?>" size = "60">
					</td>					
					<td width="25%">
						<textarea id="usulan_rekomendasi_pratpm_<?echo $con?>" name="usulan_rekomendasi_pratpm_<?echo $con?>" rows="1"><?php echo trim($this->escape($val['usulan_rekomendasi_pratpm']));?></textarea>
					</td>
					<td width="8%">
						<img src="<?echo $this->basePath;?>/images/plus.gif" title="Tambah Baris" class=link onclick=javascript:tambahBaris('<?=$con?>','<?=$con?>'); > 
						<img src="<?echo $this->basePath;?>/images/minus.gif" title="Hapus Baris" class=link onclick=javascript:hapusBaris('<?=$con?>',this); >
						<img src="<?echo $this->basePath;?>/images/page.png" title="Daftar Riwayat Hidup" class=link onclick="javascript:cetakdrh(document.getElementById('i_peg_nip_<?echo $con?>').value)" > 
					</td>
				</tr>
			</table>
		
				<?php $con++; endforeach;?>
				
			<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl" id="tblIndikator_<?echo $con?>">	
				<tr class="event" id="tr_<?echo $con?>">
					<td width="22%">
						<textarea id="i_peg_nip_<?echo $con?>" name="i_peg_nip_<?echo $con?>" rows="1" readonly="true"></textarea>
					</td>
					<td width="38%">
						<textarea id="n_peg_<?echo $con?>" name="n_peg_<?echo $con?>" rows="1" readonly="true"></textarea>
						<input type="hidden" id="c_golongan_<?echo $con?>" name="c_golongan_<?echo $con?>" value="" size = "60">
						<input type="hidden" id="n_pangkat_<?echo $con?>" name="n_pangkat_<?echo $con?>" value="" size = "60">
						<input type="hidden" id="c_jnskelamin_<?echo $con?>" name="c_jnskelamin_<?echo $con?>" value="" size = "60">
					</td>					
					<td width="25%">
						<textarea id="usulan_rekomendasi_pratpm_<?echo $con?>" name="usulan_rekomendasi_pratpm_<?echo $con?>" rows="1"></textarea>
					</td>
					<td width="8%">
						<img src="<?echo $this->basePath;?>/images/plus.gif" title="Tambah Baris" class=link onclick=javascript:tambahBaris('<?=$con?>','<?=$con?>'); > 
						<img src="<?echo $this->basePath;?>/images/minus.gif" title="Hapus Baris" class=link onclick=javascript:hapusBaris('<?=$con?>',this); >
						<img src="<?echo $this->basePath;?>/images/page.png" title="Daftar Riwayat Hidup" class=link onclick="javascript:cetakdrh(document.getElementById('i_peg_nip_<?echo $con?>').value)" > 
					</td>
				</tr>
			</table>
<div id="tblind_<?echo $con?>"></div>				
<input type="hidden" id="counttable" name="counttable" value="<?=count($this->dataPraTpm)?>" size = "10">					
<?}?>
</div>

	<div class="panel">

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
			<tr>
				<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
				<td></td>
				<td align="right">
					<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/tpm/listpratpm','<?php echo $this->basePath; ?>/sdmmodule/tpm/tpmjs');"> 									
					<input type="submit" value="<?=$this->par;?>" onClick="insertTpm()">
					<input type="hidden" id="proses" name="proses" value="<?=$this->par;?>">
					<input type="hidden" id="modul" name="modul" value="pratpm">
				</td>
			</tr>
		</table>

	</div>
<div id="popupview"></div>


</form>

<script>

function hapusBarisx(r) {
 	document.getElementById("usulan_rekomendasi_pratpm_1").value="";
	document.getElementById("c_jnskelamin_1").value="";
	document.getElementById("n_pangkat_1").value=""; 
	document.getElementById("c_golongan_1").value=""; 
	document.getElementById("n_peg_1").value=""; 
	document.getElementById("i_peg_nip_1").value=""; 	
}
function hapusBaris(induk,r) {
	var i=r.parentNode.parentNode.rowIndex;
	document.getElementById("tblIndikator_"+induk+"").deleteRow(i);
	var counttbl=document.getElementById('counttable').value;
	document.getElementById('counttable').value=counttbl*1-1;
}
function tambahBaris(par1){
	var html="";
	var countpar=par1*1+1;
	var counttbl=document.getElementById('counttable').value;
	var counttblx=counttbl*1+1;	
if  (par1*1>=counttbl*1)
{
	html = html + '<table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl" id="tblIndikator_'+countpar+'">';
	html = html + '<tr class="event" id="tr_'+countpar+'">';
	html = html + '<td width="22%">';
	html = html + '<textarea id="i_peg_nip_'+countpar+'" name="i_peg_nip_'+countpar+'" rows="1" readonly="true"></textarea>';
	html = html + '</td>';
	html = html + '<td width="38%">';
	html = html + '<textarea id="n_peg_'+countpar+'" name="n_peg_'+countpar+'" rows="1" readonly="true"></textarea>';
	html = html + '<input type="hidden" id="c_golongan_'+countpar+'" name="c_golongan_'+countpar+'" value="" size = "60">';
	html = html + '<input type="hidden" id="n_pangkat_'+countpar+'" name="n_pangkat_'+countpar+'" value="" size = "60">';
	html = html + '<input type="hidden" id="c_jnskelamin_'+countpar+'" name="c_jnskelamin_'+countpar+'" value="" size = "60">';
	html = html + '</td>';					
	html = html + '<td width="25%">';
	html = html + '<textarea id="usulan_rekomendasi_pratpm_'+countpar+'" name="usulan_rekomendasi_pratpm_'+countpar+'" rows="1" readonly="true"></textarea>';
	html = html + '</td>';
	html = html + '<td width="8%">';	
	html = html + '<img src="/images/plus.gif" title="Tambah Baris" class=link onclick=javascript:tambahBaris("'+countpar+'"); > ';
	html = html + '<img src="/images/minus.gif" title="Hapus Baris" class=link onclick=javascript:hapusBaris("'+countpar+'",this); >&nbsp;';
	html = html + '<img src="/images/page.png" title="Daftar Riwayat Hidup" class=link onclick=javascript:cetakdrh(document.getElementById("i_peg_nip_'+countpar+'").value); > ';
	html = html + '</td>';
	html = html + '</tr>';
	html = html + '</table>';	
	html = html + '<div id="tblind_'+countpar+'"></div>';
	document.getElementById("tblind_"+par1+"").innerHTML = html;
	document.getElementById('counttable').value=counttbl*1+1;	
}
	cariPegawai(par1);
}

function cariPegawai(nom){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listnamapejabatan';
var param = {nom:nom};
jQuery.get(url,param,function(data) {
jQuery("#popupview").html(data);
centerPopup();
loadPopup();});
}

/*function cetakdrh(nip){
var url = '<?php echo $this->basePath; ?>/sdmmodule/datacv/datacvtpm';
var param = {nip:nip};
jQuery.get(url,param,function(data) {
jQuery("#popupview").html(data);
centerPopup();
loadPopup();});
}*/
function cetakdrh(nip)
{
	url = "<?php echo $this->basePath; ?>/sdmmodule/datacv/datacvtpm?nip="+nip;	
	BukaWindows('1000','600');
}
function BukaWindows(wid,heg){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = wid, popH = heg;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}
function cariTpmUsul(nom){
var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/listtpmusulpopup';
var param = {nom:nom};
jQuery.get(url,param,function(data) {
jQuery("#popupview").html(data);
centerPopup();
loadPopup();});
}
</script>	