<? require_once 'Zend/View.php';
   require_once 'share/pesan.php';
   require_once 'share/formatangka.php';
   require_once 'share/halaman_list.php';

   $ctrlFrm = new Zend_View();
   $pesan = new pesan();
   $formatangka = new formatangka();
   $halaman = new halaman_list();

	  
$jumformulir7List = count($this->listFormulir7); 
$jumtotformulir7List = count($this->listJumFormulir7);
$jumgolList = count($this->listGol); 
			
?>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Formasi Kepegawaian <!--a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Maintain Data Pegawai</a-->
				<strong> &#8250; </strong>Formulir 7
			</div>
	        <a name="top"></a>
<?
$proses		= $this->proses;
$keterangan	= $this->keterangan;
$status		= $this->status;
echo $pesan->show_message($proses, $keterangan, $status);
?>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Formulir 7</h2>
	<form method="post" name="tampil" id="tampil" >
	<table width="50%" border="0" cellpadding="0" cellspacing="0">
	<tr><td size="20%">
	
	Tahun Anggaran </td><td size="1%">  :</td><td size="79%"> <select name="tahun" id="tahun">
				<? if($this->tahun != "" && $this->tahun != "Tahun"){
					echo "<option value=".$this->tahun.">".$this->tahun."</option>";
				 ?>
				 <option>Tahun</option>
				 <? for($i=date('Y')+5;$i>=date('Y')-2;$i--){
					echo "<option value=$i>$i</option>";
				    }
				  }else{ ?>
					 <option>Tahun</option>
				 <? for($i=date('Y')+5;$i>=date('Y')-2;$i--){
					echo "<option value=$i>$i</option>";
				    }
				    }
				 ?>
				 </select></td></tr>
	<tr><td>&nbsp;</td><td>&nbsp;</td><td><input type="button" value="Tampil" name="tampil" onclick="tampilTaun()"></td></tr>
	</table>
	</form><br><br>
	<div align="left">UNIT ORGANISASI : PERWAKILAN RI DILUAR NEGRI</div>
		<div align="center">DAFTAR KEBUTUHAN PEGAWAI LOCAL STAFF<br>TAHUN ANGGARAN <span class="thn_skr"><? echo $this->tahun; ?></span></div>
			<div class="add" title="Tambah Data" onclick="OpenFormulir7Olahdata('Insert','','');"></div>	
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  
	
		<tr><td width="10%"></td></tr>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center" width="50%">
			
			<tr>
		    <th width="5%">No</th>
			<th width="30%">PERWAKILAN</th>
			<th width="10%">JUMLAH PEGAWAI PADA 31-12-<span id="thn_sblm"><? echo $this->thn_sblm; ?></span> </th>
			<th width="10%">FORMASI TAHUN <span class="thn_skr"><? echo $this->tahun; ?></span></th>
			<th width="45%">KETERANGAN</th>
			<th colspan="2">&nbsp;</th>
			</tr>
			<tr>
			<th>1</th>
			<th>2</th>
			<th>3</th>
			<th>4</th>
			<th>5</th>
			<th colspan="2">&nbsp;</th>
			</tr>
			<? if($jumtotformulir7List != ""){
				foreach($this->listJumFormulir7 as $key => $val): ?>
			<tr class="event"><td colspan="2"><div align="center">JUMLAH SELURUHNYA</div></td>
			<td><? echo $this->escape($val['jum_pegawai']); ?></td>
			<td><? echo $this->escape($val['formasi']); ?></td><td>&nbsp;</td><td colspan="2">&nbsp;</td></tr>
<?			endforeach;
			} ?>
<?
	if ($jumformulir7List == 0) {
?>		
		      <tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">&nbsp;</td>
			</tr>
		
<? 	}	else { ?>

		<?php 	
			$i=1;
					
			foreach ($this->listFormulir7 as $key => $val):
				if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					//$nip=trim($this->escape($val['i_peg_nip']));*/
					
					?>
				
				<td><?php echo $i++; ?></td>
				<td><?php echo $this->escape($val['perwakilan']);?></td>
				<td><?php echo $this->escape($val['jum_pegawai']);?></td>
				<td><?php echo $this->escape($val['formasi']);?></td>
				<td><?php echo $this->escape($val['ket']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data" onclick="OpenFormulir7Olahdata('Update','<?=trim($this->escape($val['id']));?>','<?=trim($this->escape($val['perwakilan']))?>');"></div>	
				</td>
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusFormulir7('Formulir 7', '<?=trim($this->escape($val['id']))?>','<?=trim($this->escape($val['nm_jabatan']))?>')"></div>
				</td>
								
			</tr>
			
	<?php endforeach; ?>  	  
<?	}	
	?>
	</table>
	</fieldset>		 
	</form>
