<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<LINK href="<?echo $this->baseUrl;?>/css/sdm/style.css" type="text/css" rel="stylesheet">
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/jquery.form.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ui.core.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ui.datepicker.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/common.js"></script>
<SCRIPT type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/navigation.js"></SCRIPT>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/ddsmoothmenu.js"></script>
<script type="text/javascript" src="<? echo $this->baseUrl;?>/js/sdm/popup.js"></script>

</head>
<body>
<center>
<div id="targetremind">

<? 
		include('reminder.phtml');?>
</div>
</center>
</body>
</html>					
