<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_sertifikat").datepicker();
		jQuery("#d_diklat").datepicker();
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikanmiliter/listpendidikanmiliter','');">Pendidikan Militer</a>				
			<strong> &#8250; </strong><?=$this->jdl;?> Pendidikan Militer
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Pendidikan Militer</h2>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formdikmil" method="post" name="formdikmil" >		
<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
					<td  width="23%">Jenjang</td>
					<td  width="2%">:</td> 
					<td>
						<?php
						   $jmlcmbjenjang = count($this->cmbjenjang);
							for ($i = 0; $i < $jmlcmbjenjang; $i++) {	 
								if ($this->c_jenjang==$this->cmbjenjang[$i]->c_jenjang){echo $this->cmbjenjang[$i]->n_jenjang;}
							}  
						?>
					</td>
				</tr>
				<tr>
					<td>Sekolah</td>
					<td>:</td> 
					<td>
						<?php
						   $jmlcmbsekolah = count($this->cmbsekolah);
							for ($i = 0; $i < $jmlcmbsekolah; $i++) {	 
								if($this->c_sekolahmil==$this->cmbsekolah[$i]->c_sekolahmil){echo $this->cmbsekolah[$i]->n_sekolahmil;}
						   }    
						?>
					</td>
				</tr>					
				<tr>
					<td>Tahun Masuk</td>
					<td>:</td> 
					<td>					
						<?=$this->d_tahun_masuk?>
					</td>
				</tr>				
				<tr>
					<td>Tahun Lulus</td>
					<td>:</td> 
					<td>
						<?=$this->d_tahun_lulus?>
					</td>
				</tr>
				<tr>
					<td>Status</td>
					<td>:</td> 
					<td>
					<?
						if ($this->c_status=="1"){echo "Lulus";}
						elseif ($this->c_status=="2"){echo "Tidak Lulus";}
						else{echo "-";}
					?>	
					</td>
				</tr>
	
				<tr>
					<td>Tempat</td>
					<td>:</td> 
					<td>
						<?=$this->n_tempat?>
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikanmiliter/listpendidikanmiliter','');"> 									
							</td>
						</tr>
					</table>
</form>
	</div>
	</div>
	