<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();

	  
$jumjabatanList = count($this->jabatanList);     
	if ($jumjabatanList == 0) {
		echo "<font color=\"red\">Data Jabatan Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="10%">Eselon / TMT Eselon</th>
			<th width="20%">Nama Jabatan / TMT Jabatan</th>
			<th width="20%">No SK / Tgl. SK</th>
			<th width="16%">Tgl Pelantikan</th>
			</tr>		
<?
	if ($jumjabatanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { 

		  foreach ($this->jabatanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				<td class="clcenter">
					<a href="#" onclick="detiljabatan('<?=$nip?>','<?=trim($this->escape($val['c_jabatan']))?>','<?=trim($this->escape($val['n_nama']))?>')"><?php echo $this->escape($val['n_eselon']);?> <br> <?php echo $this->escape($val['d_tmt_eselon']);?></a>
				</td>
				<td><?php  echo $this->escape($val['n_jabatan']);?><br><?php  echo $this->escape($val['d_mulai_jabat']);?></td>
				<td class="clcenter"><u><?php  echo $this->escape($val['i_sk_jabat']);?></u><br><?php  echo $this->escape($val['d_sk_jabat']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['d_tmt_lantik']);?></td>

		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
