<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tmt_eselon").datepicker();
		jQuery("#d_mulai_jabat").datepicker();
		jQuery("#d_akhir_jabat").datepicker();
		jQuery("#d_tmt_lantik").datepicker();
		jQuery("#d_sk_jabat").datepicker();
		
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','<?php echo $this->basePath; ?>/sdmmodule/datajabatan/jabatanjs');">Jabatan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jabatan Struktural
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Jabatan Struktural</h2>	
<form id="formjabatan" method="post" name="formjabatan">		
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>

<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>

<div class="panel">

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">Eselon</td>
								<td width="2%">:</td> 
								<td>					
									<?
											$jmlEslList=count($this->eselonList);
											for ($i = 0; $i < $jmlEslList; $i++) {
												if ($this->c_eselon==$this->eselonList[$i]->c_eselon){$n_eselon=$this->eselonList[$i]->n_eselon;}
											}							
									?>								
									<input type="text" value="<?=$n_eselon?>" size="55" readonly="true">
								</td>							
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Dengan Kode Ref.)</td>
								<td>:</td> 
								<td>					
									<input type="hidden" name="c_jabatan" id="c_jabatan" value="<?=$this->c_jabatan?>">
									<input type="text" name="n_jabatan" id="n_jabatan" value="<?=$this->n_jabatan?>" size="30">
								</td>								
							</tr>	
							<tr>
								<td>TMT. Jabatan</td>
								<td>:</td> 
								<td>					
									<input type="text" name="d_mulai_jabat" id="d_mulai_jabat" value="<?=$this->d_mulai_jabat?>" size="10"> s/d
									<input type="text" name="d_akhir_jabat" id="d_akhir_jabat" value="<?=$this->d_akhir_jabat?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>								
							</tr>							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">TMT Eselon</td>
								<td width="2%">:</td> 
								<td>					
									<input type="text" name="d_tmt_eselon" id="d_tmt_eselon" value="<?=$this->d_tmt_eselon?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Tanpa Kode Ref.)</td>
								<td>:</td> 
								<td>					
									<textarea id="n_jabatan_nokode" name="n_jabatan_nokode" rows="1"><?=$this->n_jabatan_nokode?></textarea>
								</td>
							</tr>
							<tr>
								<td>Jumlah Angka Kredit</td>
								<td>:</td> 
								<td>					
									<input type="text" name="q_angka_kredit" id="q_angka_kredit" value="<?=$this->q_angka_kredit?>" size="10" onkeyup="isNumber('q_angka_kredit')">
								</td>
							</tr>								
						</table>	
					</td>
				</tr>
			</table>
		</td>
	</tr>	
</table>
<?if ($this->c_lokasi_unitkerja=='1'){?>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>UNIT KERJA</u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Lokasi</td>
								<td width="2%">:</td> 
								<td>					
									<?
											$jmlLokList=count($this->lokasiList);
											for ($i = 0; $i < $jmlLokList; $i++) {
												if ($this->c_lokasi_unitkerja==$this->lokasiList[$i]->c_lokasi){$n_lokasi=$this->lokasiList[$i]->n_lokasi;}
											}							
									?>								
									<input type="text" value="<?=$n_lokasi?>" size="55" readonly="true">
								</td>
							</tr>
							<tr>
								<td>Eselon I</td>
								<td>:</td> 
								<td>					
									<input type="text" value="<?=$this->n_eselon_i?>" size="55" readonly="true">
								</td>
							</tr>
							<tr>
								<td width="30%">Eselon II</td>
								<td width="2%">:</td> 
								<td>				
									<input type="text" value="<?=$this->n_eselon_i?>" size="55" readonly="true">
								</td>
							</tr>						
							<tr>
								<td width="30%">Eselon III</td>
								<td width="2%">:</td> 
								<td>					
									<input type="text" value="<?=$this->n_eselon_i?>" size="55" readonly="true">	
								</td>
							</tr>
							<tr>
								<td>Eselon IV</td>
								<td>:</td> 
								<td>				
									<input type="text" value="<?=$this->n_eselon_i?>" size="55" readonly="true">
								</td>
							</tr>
							<tr>
								<td>Eselon V</td>
								<td>:</td> 
								<td>				
									<input type="text" value="<?=$this->n_eselon_i?>" size="55" readonly="true">
								</td>
							</tr>
							<tr>
								<td width="17%">Alamat Kantor</td>
								<td width="2%">:</td> 
								<td>					
									<textarea id="a_alamat_kantor" name="a_alamat_kantor" rows="1"><?=$this->a_alamat_kantor?></textarea>
								</td>
							</tr>							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>HASIL AKHIR NAMA JABATAN</u></b><h3></td>
							</tr>
							<tr>
								<td colspan="3">					
									<textarea id="jabat_lengkap" name="jabat_lengkap" rows="7"><?=$this->jabat_lengkap?></textarea>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
<?}  else{include ("listcombo2.phtml");}?>	
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>SURAT KEPUTUSAN<u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Nomor</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="i_sk_jabat" id="i_sk_jabat" value="<?=$this->i_sk_jabat?>" size="30">
								</td>
							</tr>
							<tr>
								<td>Tanggal</td>
								<td>:</td> 
								<td>					
									<input type="text" name="d_sk_jabat" id="d_sk_jabat" value="<?=$this->d_sk_jabat?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>
							<tr>
								<td>Pejabat</td>
								<td>:</td> 
								<td>					
									<input type="text" name="n_sk_pejabat" id="n_sk_pejabat" value="<?=$this->n_sk_pejabat?>" size="50">
								</td>
							</tr>						
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>							
							<tr>
								<td width="30%">Tanggal Pelantikan</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="d_tmt_lantik" id="d_tmt_lantik" value="<?=$this->d_tmt_lantik?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>	
							<tr>
								<td width="30%">Lokasi KPPN</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="n_lok_kppn" id="n_lok_kppn" value="<?=$this->n_lok_kppn?>" size="20">
								</td>
							</tr>
							<tr>
								<td>Lokasi Taspen</td>
								<td>:</td> 
								<td>					
									<input type="text" name="n_lok_taspen" id="n_lok_taspen" value="<?=$this->n_lok_taspen?>" size="20">
								</td>
							</tr>	
							<tr>
								<td>Keterangan</td>
								<td>:</td> 
								<td>					
									<textarea id="e_keterangan" name="e_keterangan" rows="1"><?=$this->e_keterangan?></textarea>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
						<tr>
							<td></td>
							<td align="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','');"> 									

							</td>
						</tr>
					</table>



</div>
</form>
</div>
<div id="targetdetil"></div>

