<?php 
require_once 'Zend/View.php';
require_once "share/ma_date.php";  
require_once "share/ma_message.php";
require_once "service/adm/Adm_Admmenu_Service.php";


$ctrlFrm = new Zend_View();
$pesan1 = new ma_message();
$tanggal = new ma_date();
$admmenu_serv = Adm_Admmenu_Service::getInstance();
?>
		   
<div class="navlink">
	<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
	<strong> &#8250; </strong> Administrasi 
	<strong> &#8250; </strong><?=$this->jdl;?> Administrasi Group
</div>
<div id="top"></div>
	
<h2 class="title"><?=$this->jdl;?>Daftar Group</h2>

<?
/*<div class="search-panel">
	<form method="post" name="frmCariAplikasi" id="frmCariAplikasi">
		<center>
			<table>
				<tr>
					<td>Pencarian Berdasarkan :&nbsp;
						<?
						$isiKategoriCari = array("semua" => "Semua",
												"c_aplikasi" => "Kode Aplikasi",
												"n_aplikasi" => "Nama Aplikasi",
												"e_aplikasi" => "Keterangan Aplikasi");
												
						$kategoriCariAttrib = array("onClick" => "setKatakunci();");						
						echo $ctrlFrm->formSelect('kategoriCari', $kategoriCari, $kategoriCariAttrib, $isiKategoriCari);
						?>
					</td>
					<td>
						<?php 
							
							if 	($this->kategoriCari == 'semua'){
							?>
								<div id="cari" style="display:none">
							<?php
							} else {
							?>
								<div id="cari" style="display:block">
							<?php
							}
							$kataKunciAtrib = array("size"=>"31",
							"maxlength"=>"30",
							"class"=>""
							);
							echo $ctrlFrm->formText('kataKunci', $kataKunci, $kataKunciAtrib);
						?>
						</div>
					</td> 
					<td>
						<? 
						$buttonAtrib = array("onClick"=>"javascript:prosesCariUser();");
						echo $ctrlFrm->formSubmit('cari', 'Cari', $buttonAtrib); 
						?>
					</td>
				</tr>
			</table>
		</center>
	</form>
</div>
*/?>
<? 
$status = $this->hasil;
$proses = $this->proses;
$keterangan = $this->keterangan;

$pesan1->show_message($proses, $keterangan, "$status" ); 
?>
<div class="add" onclick="displayGroupOlahdata('insert', '');" title="Tambah Data"></div>	
	
<table width="100%" class="std">
	<tbody>
		<tr>
			<th>No.</th>
			<th colspan="2">Nama Group</th>
			<th colspan="2">Pemberi Akses</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</tr>
		<tr>
			<td colspan="3">
				<?
				if(count($this->aplikasiList)){
					foreach ($this->aplikasiList as $key => $val): 
						$i_aplikasi = $this->escape($val['i_aplikasi']);
						$n_aplikasi = $this->escape($val['n_aplikasi']);
						
						if($c_unit == $cUnitInput){
							$nUnitSelected = $n_unit;
						?>
							<li class="selected"><span><?php echo "Unit : $c_unit"; ?></span></li>
						<?php
						} else { ?>
							<li class="">
								<a href="#" title="<?php echo $n_aplikasi;?>">
									<span><?php echo "$n_aplikasi";?></span>
								</a>
							</li>
						<?
						}
					endforeach;
				}
				?>
			</td>
		</tr>
		<?php
		if(count($this->GroupList)){
		?>
			
			<?php
			$a =0;
			$noAwal = $numToDisplay*($currentPage -1)+1;
			foreach ($this->GroupList as $key => $val): 
				$noUrut 	= $noAwal+$a;
				$iGroup 	= $this->escape($val['i_group']);
				$nGroup		= $this->escape($val['n_group']);
				$nGroupOwner= $this->escape($val['n_group_owner']);
				
				if ($key%2==0) { ?>
				  <tr class="event">
				<? } else if ($key%2==1) { ?>
				  <tr class="event2">
				<? } ?>
					<td class="clleft" width="5%">&nbsp;<?php echo $noUrut; ?></td>
					<td class="clleft" width="4%">&nbsp;
						<img src="images/down.gif">
					</td>
					<td class="clleft" width="53%">&nbsp;<?php echo $nGroup; ?></td>
					<td class="clleft" width="30%">&nbsp;<?php echo $nGroupOwner; ?></td>
					
					<td width="4%">&nbsp;
						<div class="edit" onclick="displayGroupOlahdata('ubah','<?php echo $iGroup;?>');" title="Ubah Data"></div>
					</td>
					<td width="4%">
						<div class="delete" onclick="hapusGroup('Group Menu', '<?php echo $iGroup;?>', '<?php echo $nGroup;?>')" title="Hapus Data"></div>
					</td>
				</tr>
				<?php
				$a++;
			endforeach;
		} else {
		?>
			<tr class="event">
				<td class="clleft" width="5%" colspan="5">&nbsp;<font color="orange">Data Tidak Ada </font></td>
			</tr>
		<?php
		}?>
	</tbody>
</table>
