<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<table border="0" cellpadding="2" cellspacing="1" class="std" width="100%" id="listcombo">
	<tr>
		<td align="right" width="20%">Lokasi :</td>
		<td>					
			<?
			//var_dump($this->lokasiList);
				$jmlLokList=count($this->lokasiList);
				$lokList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlLokList; $i++) {
						$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
					}
				$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
				echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
			?>
		</td>
	</tr>
	<tr>
		<td align="right" width="20%">Eselon I</td>
		<td>					
			<?
				$jmleseloniList=count($this->eseloniList);
				$eseloniList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniList; $i++) {
					
						$eseloniList[trim((string)$this->eseloniList[$i]->c_eselon_i).";".trim((string)$this->eseloniList[$i]->n_unitkerja)] = (string)$this->eseloniList[$i]->n_unitkerja;			 
					}
				$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
				echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
			?>
		</td>
	</tr>
	<tr>
		<td align="right" width="20%">Eselon II</td>
		<td>				
			<?
				$jmleseloniiList=count($this->eseloniiList);
				$eseloniiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiList; $i++) {
						$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii).";".trim((string)$this->eseloniiList[$i]->n_unitkerja)] = (string)$this->eseloniiList[$i]->n_unitkerja;
					}
				if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
				else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
				echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
			?>
		</td>
	</tr>						
	<tr>
		<td align="right" width="20%">Eselon III</td>
		<td>					
			<?
				$jmleseloniiiList=count($this->eseloniiiList);
				$eseloniiiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiiList; $i++) {
						$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_iii).";".trim((string)$this->eseloniiiList[$i]->n_unitkerja)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
					}
				
				if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
				else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}
				
				echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
			?>
		</td>
	</tr>
	<tr>
		<td align="right" width="20%">Eselon IV</td>
		<td>				
			<?
				$jmleselonivList=count($this->eselonivList);
				$eselonivList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonivList; $i++) {
						$eselonivList[trim((string)$this->eselonivList[$i]->c_eselon_iv).";".trim((string)$this->eselonivList[$i]->n_unitkerja)] = (string)$this->eselonivList[$i]->n_unitkerja;			 
					}
				if ($ceseloncpns>=7){
				$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
				}
				else{
				$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
				}
				
				
				echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
			?>
		</td>
	</tr>
	<tr>
		<td align="right" width="20%">Eselon V</td>
		<td id="targeteslv">				
			<?
				$jmleselonvList=count($this->eselonvList);
				$eselonvList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonvList; $i++) {
						$eselonvList[trim((string)$this->eselonvList[$i]->c_eselon_v).";".trim((string)$this->eselonvList[$i]->n_unitkerja)] = (string)$this->eselonvList[$i]->n_unitkerja;			 
					}
				if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
				else{$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}
				echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
			?>
		</td>
	</tr>	
	<tr>
		<td align="right"><span class="highlight">*</span> Nama Group :</td>
		<td>
			<?php
			//var_dump($this->detailGroupMenu);
			$iGroup = $this->iGroup;
			$nGroup = $this->nGroup;
			
			?>
			<textarea id="n_group" name="n_group" rows="7"><?=$this->n_group?></textarea>
		</td>
	</tr>
	<tr>
		<td align="right">Wewenang :</td>
		<td>
			<?
			if($this->detailGroup['c_wewenang'] == 'O'){
				$checkO = 'checked';
				$checkE = '';
			} else {
				$checkO = '';
				$checkE = 'checked';
			}
			?>
			<input type="radio" id="c_wewenang" name="c_wewenang" value="E" <?echo "$checkE"; ?>>&nbsp;Eksekutif<br>
			<input type="radio" id="c_wewenang" name="c_wewenang" value="O" <?echo "$checkO"; ?>>&nbsp;Operator<br>
			<input type="radio" id="c_wewenang" name="c_wewenang" value="A" <?echo "$checkA"; ?>>&nbsp;Administrator Absensi
		</td>
	</tr>
	<tr>
		<td align="right">Sektoral :</td>
		<td>
			<?
			if($this->c_sektoral == 'L'){
				$checkD = '';
				$checkL = 'checked';
				$checkS = '';
				$checkW = '';
			} else if($this->c_sektoral == 'S'){
				$checkD = '';
				$checkL = '';
				$checkS = 'checked';
				$checkW = '';
			} else if($this->c_sektoral == 'W'){
				$checkD = '';
				$checkL = '';
				$checkS = '';
				$checkW = 'checked';
			} else{
				$checkD = 'checked';
				$checkL = '';
				$checkS = '';
				$checkW = '';
			}
			?>
			<input type="radio" id="c_sektoral" name="c_sektoral" value="D" <?echo "$checkD"; ?>>&nbsp;Dalam Sektoral<br>
			<input type="radio" id="c_sektoral" name="c_sektoral" value="L" <?echo "$checkL"; ?>>&nbsp;Lintas Sektoral<br>
			<input type="radio" id="c_sektoral" name="c_sektoral" value="S" <?echo "$checkS"; ?>>&nbsp;Semua Sektoral<br>
			<input type="radio" id="c_sektoral" name="c_sektoral" value="W" <?echo "$checkW"; ?>>&nbsp;Bawas
		</td>
	</tr>
</table>