<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jenis Hukuman
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Jenis Hukuman</h2>	
		
<form id="formhukuman" method="post" name="formhukuman">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Jenis Hukuman<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_hukuman" id="c_hukuman" value="<?=$this->detailHukuman['c_hukuman']?>" size="70" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Jenis Hukuman<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_hukuman" id="n_hukuman" value="<?=$this->detailHukuman['n_hukuman']?>" size="70" >
					</td>
				</tr><tr>
					<td>Q Tingkat Hukuman<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="q_tingkat_hukuman" id="q_tingkat_hukuman" value="<?=$this->detailHukuman['q_tingkat_hukuman']?>" size="70">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refhukuman/listhukuman','<?php echo $this->basePath; ?>/sdmmodule/refhukuman/hukumanjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertHukuman()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateHukuman()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
