<?
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
	$jmlKabList = count($this->kabupatenList);
	$kabupatenList['-'] = '--Pilih--';
	for ($i = 0; $i < $jmlKabList; $i++) {
		$kabupatenList[(string)$this->kabupatenList[$i]->c_kabupaten] = (string)$this->kabupatenList[$i]->n_kabupaten;			 
	}
	if($this->par=='targetkabupaten'){echo $ctrlFrm->formSelect('a_kota', $this->a_kota,null, $kabupatenList);}
	else{echo $ctrlFrm->formSelect('a_kota_lahir', $this->a_kota_lahir,null, $kabupatenList);}
?>
