<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList['#'] = '--';
   for ($i = 0; $i < 40; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   } $blnArrayList['#'] = '--';	

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_mulai_seminar").datepicker();
		jQuery("#d_akhir_seminar").datepicker();
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/dataseminar/listseminar','<?php echo $this->basePath; ?>/sdmmodule/dataseminar/seminarjs');">Seminar</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Seminar
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Seminar</h2>	
	
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
<form id="formseminar" method="post" name="formseminar">		
	<div class="panel">
		<div class="spacer"></div> 
						<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="30%">Nama Seminar / Simposium</td>
					<td width="2%">:</td> 
					<td>					
						<?=$this->n_seminar?>						
					</td>
				</tr>
				<tr>
					<td>Peran</td>
					<td>:</td> 
					<td>						

						<?
							echo ucwords($n_seminar_peran); 							
						?>							
					
					</td>
				</tr>
				<tr>
					<td>Mulai</td>
					<td>:</td> 
					<td>
						<?=$this->d_mulai_seminar?>
					</td>
				</tr>
				<tr>
					<td>Akhir</td>
					<td>:</td> 
					<td>
						<?=$this->d_akhir_seminar?> 
					</td>
				</tr>
				<tr>
					<td>Penyelenggara</td>
					<td>:</td> 
					<td>
						<?=$this->n_seminar_lembaga?>
					</td>
				</tr>
				<tr>
					<td>Tempat</td>
					<td>:</td> 
					<td>
						<?=$this->a_seminar?>
					</td>
				</tr>
				<tr>
					<td>Keterangan</td>
					<td>:</td> 
					<td>
					<?php 
						echo $this->e_keterangan;
					?>
					</td>
				</tr>
</table>
</div>
<br>
	<div class="panel">				
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				</tr>
						<tr>

							<td></td>
							<td>
								<div class="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/dataseminar/listseminar','');"> 
									
								</div>
							</td>
						</tr>			
			</table>			
	</div>
</div>	
	</form>
