<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tmt_eselon").datepicker();
		jQuery("#d_mulai_jabat").datepicker();
		jQuery("#d_akhir_jabat").datepicker();
		jQuery("#d_tmt_lantik").datepicker();
		jQuery("#d_sk_jabat").datepicker();
		
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datariwayatpegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datariwayatpegawai/pegawaijs');">Data Riwayat</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','<?php echo $this->basePath; ?>/sdmmodule/datajabatan/jabatanjs');">Jabatan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jabatan Fungsional
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Jabatan Fungsional</h2>	
<form id="formjabatan" method="post" name="formjabatan">		
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>

<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>

<div class="panel">

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="20%">Nama Jabatan</td>
					<td width="2%">:</td> 
					<td>					
						<?=$this->n_jabatan?>
					</td>								
				</tr>
				
				<tr>
					<td>Status</td>
					<td>:</td> 
					<td>					
					<?
						if ($this->c_statusjabatan=="1"){echo "Pembebasan Sementara";}
						elseif ($this->c_statusjabatan=="2"){echo "Pengangkatan Kembali";}
						elseif ($this->c_statusjabatan=="3"){echo "Pengukuhan";}
						elseif ($this->c_statusjabatan=="4"){echo "Pemberhentian";}
						else {echo "-";}			
						
					?>
					</td>
				</tr>
				<tr>
					<td>Alasan</td>
					<td>:</td> 
					<td id="tgtalasan">					
					<?
						$jmlstatusJabatList=count($this->statusJabatList);
						for ($i = 0; $i < $jmlstatusJabatList; $i++) {
							if ($this->c_alasan==$this->statusJabatList[$i]->c_statusfung){echo $this->statusJabatList[$i]->n_statusfung;}
						}						
					?>
					<input type="hidden" name="c_alasan2" id="c_alasan2" value="<?=$this->c_alasan?>">	
					</td>
				</tr>
				<tr>
					<td>TMT. Jabatan</td>
					<td>:</td> 
					<td>					
						<?=$this->d_mulai_jabat?> s/d
						<?=$this->d_akhir_jabat?>
					</td>								
				</tr>	
				<tr>
					<td>Jumlah Angka Kredit</td>
					<td>:</td> 
					<td>					
						<?=$this->q_angka_kredit?>
					</td>
				</tr>
				<tr>
					<td colspan="3"><h3 class="title"><b><u>SURAT KEPUTUSAN<u></b><h3></td>
				</tr>
				<tr>
					<td>Nomor</td>
					<td>:</td> 
					<td>					
						<?=$this->i_sk_jabat?>
					</td>
				</tr>
				<tr>
					<td>Tanggal</td>
					<td>:</td> 
					<td>					
						<?=$this->d_sk_jabat?>
					</td>
				</tr>
				<tr>
					<td>Pejabat</td>
					<td>:</td> 
					<td>					
						<?=$this->n_sk_pejabat?>
					</td>
				</tr>				
				<tr>
					<td>Lembaga</td>
					<td>:</td> 
					<td>					
						<?=$this->n_lembaga?>
					</td>
				</tr>
</table>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
						<tr>
							
							<td></td>
							<td align="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatanfungsional/listjabatan','');"> 									
							</td>
						</tr>
					</table>



</div>
</form>
</div>
<div id="targetdetil"></div>
<script>
function CariJabatan(){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listnamajabatan';
var param = {};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}

function cariAlasan(){
var c_kelompok= document.getElementById('c_statusjabatan').value;
var url = '<?php echo $this->basePath; ?>/sdmmodule/datajabatanfungsional/listcombo';
var param = {c_kelompok:c_kelompok};
jQuery.get(url,param,function(data) {
jQuery("#tgtalasan").html(data);

});
}

</script>	

