<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmJabatanList = count($this->nmJabatanList);  
?>
<div id="backgroundPopup" >
	<div id="popupContact" style="width: 500px; height: 500px;">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
		<tr>
		<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
		</tr>
		</table>
		<div style="overflow: hidden;">
			<div class="wrap">
				<div class="panel" style="border: solid 1px #000;padding: 5px;" >
					<h2 class="title">Daftar Nama Jabatan</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
						   <table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
								<tr>
									<th width="4%">No.</th>
									<!--<th>Kode Jabatan</th>-->
									<th>Nama Jabatan</th>
									<th width="15%">Tanggal Pelantikan</th>
								</tr> 
<? 		if ($jmlnmJabatanList == 0) {?>
								<tr class="event">									
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
<?		}else{
				foreach ($this->nmJabatanList as $key => $val):  
										if ($key%2==0) { ?>
										<tr class="event">
										<? } else if ($key%2==1) { ?>
										<tr class="event2">
										<? } 
										$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
										?>
											<td class="clcenter"><?php echo $noUrut;?></td>
											<td><a href="#" onclick="pilihData('<?php echo $this->escape($val['c_jabatan']);?>','<?php echo $this->escape($val['n_jabatan']);?>','<?php echo $this->escape($val['d_tmt_lantik']);?>')"><?php echo $this->escape($val['n_jabatan']);?></a></td>
											<!--<td><?php //echo $this->escape($val['n_jabatan']);?></td>-->
											<td><?php echo $this->escape($val['d_tmt_lantik']);?></td>	
										</tr>
<?php 
				endforeach;}
?>
							
							</table>
						<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>
		</div>
	</div>
</div>	
<script>
function pilihData(cJabat,nJabat,tmtLantik){
	document.getElementById('n_jabatan').value=nJabat;
	document.getElementById('c_jabatan').value=cJabat;
	document.getElementById('d_tmt_lantik').value=tmtLantik;	
	closeDetil();
}
</script>