
	<!-- what we do -->
	<div class="row">
		<div class="span8">
			<div class="title-divider">
				<h3>Pelayanan</h3>
				<div class="divider-arrow"></div>
			</div>
		</div>
		<div class="span8">
			<div class="block-grey">
				<div class="block-light wrap15">
				<?php
					 $jmlkategoripelayananList = count($this->kategoripelayananList);
						//echo $jmlkategoriprodhukumList;
					   for ($j = 0; $j < $jmlkategoripelayananList; $j++) {
						 $kategoripelayanan[$j] = array("c_kategori"=>(string)$this->kategoripelayananList[$j]['c_kategori'],
						 "n_kategori"=>(string)$this->kategoripelayananList[$j]['n_kategori'],
											"n_judul"=>(string)$this->kategoripelayananList[$j]['n_judul'],
											 "n_detil"=>(string)$this->kategoripelayananList[$j]['n_detil'],
											 "c_pelayanan"=>(string)$this->kategoripelayananList[$j]['c_pelayanan'],
											 "n_file"=>(string)$this->kategoripelayananList[$j]['n_file'],
											"i_nomor_pelayanan"=>(string)$this->kategoripelayananList[$j]['i_nomor_pelayanan'],
											"d_tahun_pelayanan"=>(string)$this->kategoripelayananList[$j]['d_tahun_pelayanan'],
											  "c_status"=>(string)$this->kategoripelayananList[$j]['c_status']);
					   } 
		?>
					<table class="widefat sortable" cellspacing="1">
		<tr>
			<th class="nosort" width="5%">No.</th>
			<th width="30%">Pelayanan</th>
			<th width="10%">Nomor</th>
			<th width="10%">Tahun</th>
			<th width="10%">Kategori</th>
		</tr> 
<? 		if ($jmlkategoripelayananList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($kategoripelayanan as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="alternate">
				<? } else if ($key%2==1) { ?>
				<tr class="alternate2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
				$cstatus = $this->escape($val['c_status']);
				$date=formatDate2($this->escape($val['d_kategoripelayanan']));
				if ($cstatus == 1) 	$status = 'Diterbitkan';
				else $status = 'Tidak Diterbitkan';
				
				?>
					<td class="clcenter"><?php echo $noUrut;?></td>
					<td><?php echo $this->escape($val['n_judul']);?></td>
					<td align="left"><?php echo $this->escape($val['i_nomor_pelayanan']);?></td>
					<td align="center"><?php echo $this->escape($val['d_tahun_pelayanan']);?></td>
					<td><?php echo $val['n_kategori'];?></td>
				</tr>
				<?php endforeach;}?>
	
			</table>
					
					
				</div>
			</div>
		</div>
	</div>
	<hr>	