<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/Portalconf.php'; 
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();

if ($this->tglpelayanan!='') {
  $dates=formatDate4($this->tglpelayanan);
  $xtime=substr($this->tglpelayanan,11,8);
  list($jam,$mnt,$det)=split(":",$xtime);
} else {
  $dates=date('d/m/Y');
  $jam=date("H");
  $mnt=date("i");
}

?>
<div id="backgroundPopup">
  <div id="popupContact">  
    <div id="popupContactClose" title="Close" onclick="closeDetil()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
		<div style="overflow: hidden;">
			<div class="wrapper">
				<div class="panel" style="height: 600px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h3><?=$this->jdlpelayanan;?></h3>
					<span class="date"><?=$dates." ".$jam.":".$mnt?> Jenis Pelayanan : <?=$this->sumber?></span>
					<p>
					<?=$this->detilpelayanan?>
	  </div>
	</div>	
  </div>
</div>	