function insertRefNilai(){
	jQuery("#formnilai").ajaxForm(maintain_refnilai);
}

var maintain_refnilai = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formnilai;
		astr= "document.formnilai";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/ 
				if((!n_faktor_kinerja.value)){cekVal = sdmValidasiData(astr,"n_faktor_kinerja","Faktor Kinerja harus diisi....!");return false;break;}
				if((!n_standar_kinerja.value)){cekVal = sdmValidasiData(astr,"n_standar_kinerja","Standar Kinerja harus diisi....!");return false;break;}
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/maintaindataref',
	type: 'post',
	resetForm: false
};

function insertPenilaianMil(){
	jQuery("#formpenilaian").ajaxForm(maintain_nilai);
}


var maintain_nilai = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formpenilaian;
		astr= "document.formpenilaian";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/ 
				if((!i_peg_nip.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","Nip Kosong harus diisi....!");return false;break;}
				if((!d_nilai_kinerja.value)){cekVal = sdmValidasiData(astr,"d_nilai_kinerja","Tahun Penilaian Kinerja harus diisi....!");return false;break;}				
				 
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/maintaindata',
	type: 'post',
	resetForm: false
};

function refpenilaianM(par,c_nilai_kinerja){
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/refpenilaianmil"	
	var opt = {par:par,c_nilai_kinerja:c_nilai_kinerja};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 

function penilaianM(par,i_peg_nip,id){
	var d_nilai_kinerja = document.getElementById('d_nilai_kinerja').value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/penilaianmil"	
	var opt = {par:par,i_peg_nip:i_peg_nip,id:id,d_nilai_kinerja:d_nilai_kinerja};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 
function penilaianV(i_peg_nip,penilai){
	var d_nilai_kinerja = document.getElementById('d_nilai_kinerja').value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/penilaianmil/listpenilaianmil"	
	var opt = {i_peg_nip:i_peg_nip,penilai:penilai,d_nilai_kinerja:d_nilai_kinerja};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 


function getPenilai(){
	url = "<?php echo $this->basePath; ?>/sdmmodule/detil/listpegawaipenilai"	
	var opt = {};
	jQuery.get(url,opt,function(data) {
		jQuery("#popupview").html(data);
		centerPopup();
		loadPopup();		
		});		
} 

	
