
function AnakM(par,id){
	url = "<?php echo $this->basePath; ?>/sdmmodule/dataanak/anak"	
	var opt = {par:par,id:id};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formanak").ajaxForm(maintain_anak);
		});		
} 
var maintain_anak = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formanak;
		astr= "document.formanak";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!c_anak.value)){cekVal = sdmValidasiData(astr,"c_anak","Status anak harus diisi....!");return false;break;}
				//if((!q_anak_ke.value)){cekVal = sdmValidasiData(astr,"q_anak_ke","Anak ke harus diisi....!");return false;break;}
				if((!n_nama.value)){cekVal = sdmValidasiData(astr,"n_nama","Nama anak ke harus diisi....!");return false;break;}
				if((!c_jns_kel.value)){cekVal = sdmValidasiData(astr,"c_jns_kel","Jenis Kelamin ke harus diisi....!");return false;break;}				
				break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formanak").ajaxForm(maintain_anak);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/dataanak/maintaindata',
	type: 'post',
	resetForm: false
};
function insertAnak(){
	jQuery("#formanak").ajaxForm(maintain_anak);
}

function HapusDataAnak(nip,id)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/dataanak/hapusdata"
		var opt = {nip:nip,id:id};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
