function diklatJenjangL(par,nip){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datadikpenjenjangan/listdiklat"	
	var opt = {par:par,nip:nip};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 

function diklatJenjangM(par,nip,c_penjenjangan){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datadikpenjenjangan/penjenjangan"	
	var opt = {par:par,nip:nip,c_penjenjangan:c_penjenjangan};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
		});		
} 


var maintain_penjenjangan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formjenjang;
		astr= "document.formjenjang";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/								
					if((!c_penjenjangan.value)){cekVal = sdmValidasiData(astr,"c_penjenjangan","Penjenjangan harus diisi....!");return false;break;}
					if((!q_angkatan.value)){cekVal = sdmValidasiData(astr,"q_angkatan","Angkatan harus diisi....!");return false;break;}
					if((!q_tahun.value)){cekVal = sdmValidasiData(astr,"q_tahun","Tahun harus diisi....!");return false;break;}
					if((!i_sertifikat.value)){cekVal = sdmValidasiData(astr,"i_sertifikat","Nomor Sertifikat harus diisi....!");return false;break;}					
					if((!d_sertifikat.value)){cekVal = sdmValidasiData(astr,"d_sertifikat","Tanggal Sertifikat harus diisi....!");return false;break;}					
				
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formjenjang").ajaxForm(maintain_penjenjangan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datadikpenjenjangan/maintaindatajenjang',
	type: 'post',
	resetForm: false
};
function insertPenjenjangan(){
	jQuery("#formjenjang").ajaxForm(maintain_penjenjangan);
}

function HapusDataPelatihan(nip,c_pelatihan,dmulaipelatihan)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datapelatihan/hapusdata"
		var opt = {nip:nip,c_pelatihan:c_pelatihan,dmulaipelatihan:dmulaipelatihan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}


