 <div class="row">
	<div class="span8">
		<div class="title-divider">
			<h3>Penghargaan</h3>
			<div class="divider-arrow"></div>
		</div>
	</div>
	
	<article class="blog-post span8">
		<div class="block-grey">
			<div class="block-light">
				<div class="wrapper-img">
					<a href="./portfolio2.html"><img src="cimteng/slider3.jpg" alt="photo"/></a>
				</div>
				<div class="wrapper">
					<h2 class="post-title"><?=$this->jdlpenghargaan;?></h2>
					<p>
						<?=$this->detilpenghargaan?>
						<a href="#" class="read-more">[...]</a>
					</p>
					<p class="tags">
						<?php echo $date ?>
					</p>
				</div>
			</div>
		</div>
	</article>
	
	
</div>