function cariListPenghargaan(){
	var status=document.getElementById('status').value;
	var key=document.getElementById('key').value;
	var url = '<?php echo $this->basePath; ?>/cmsmodule/penghargaan/listpenghargaan';	
	var param = {status:status,key:key};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
		});
} 

function PenghargaanM(par,idpenghargaan){

	var url = '<?php echo $this->basePath;?>/cmsmodule/penghargaan/penghargaan';	
	var param = {par:par,idpenghargaan:idpenghargaan};
		jQuery.get(url, param, function(data) {
			jQuery("#tableview").html(data);
			jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
		});
}
function insertPenghargaan(){
	jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
}
var maintain_penghargaan = {
	target:'#tableview',
	beforeSubmit: function() {		
		aobj= document.formpenghargaan;
		astr= "document.formpenghargaan";
		var cekVal="";
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/
				if((!title.value)){cekVal = sdmValidasiData(astr,"i_peg_nip","Judul Penghargaan harus diisi....!");return false;break;}
				break;
			}
			
		}
		
		//if (cekVal == false) {return false;}
	
	}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
	},
	url: '<?php echo $this->basePath; ?>/cmsmodule/penghargaan/maintaindata',
	type: 'post',
	resetForm: false
};



function HapusDataPenghargaan(idpenghargaan,jdl)
{
	var where_to= confirm("Yakin anda akan hapus data Penghargaan :"+jdl);
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/cmsmodule/penghargaan/hapusdata"
		 
		var opt = {idpenghargaan:idpenghargaan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function setvalueuplpdf(v,n,f) { 

	  if (f!="") {
	    var pass=false;
	    var af=f.split("/");
        var nval=eval("document.forms[0]."+n);
		var ext=v.substring(v.lastIndexOf(".")+1,v.length);
		if ((ext==f)||(ext=='png')||(ext=='gif')){ 
		document.forms[0].a_file.value=v; 
		}
		else{
		  alert ("Hanya untuk file berekstensi '"+f+"',jpg,gif,png ");
		  nval.value="";
		  document.forms[0].a_file.value=""; 
		  return;	  
		}
	  }
}