<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Lokasi
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Lokasi</h2>	
		
<form id="formlokasi" method="post" name="formlokasi">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode lokasi<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_lokasi" id="c_lokasi" value="<?=$this->detailLokasi['c_lokasi']?>" size="70" maxlength="1" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Lokasi<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_lokasi" id="n_lokasi" value="<?=$this->detailLokasi['n_lokasi']?>" size="70" >
					</td>
				</tr><tr>
					<td>Kode Status<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_status" id="c_status" value="<?=$this->detailLokasi['c_status']?>" size="70" maxlength="1">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/reflokasi/listlokasi','<?php echo $this->basePath; ?>/sdmmodule/reflokasi/lokasijs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertLokasi()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateLokasi()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
