<div class="navlink">
    <a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
    <strong> &#8250; </strong>Import Data
</div>
<div id="top"></div>
<div id="confirm" class="<?= $confirm ?>" style="display: none">
    <h2 class="title"><? echo $pesan = $this->pesan; ?></h2>	
</div>


<h2>Import Data</h2>
<div class="panel">
    <form id="formimport" method="post" name="formimport" enctype="multipart/form-data" action="">
        <table>
            <tr>
                <td width="30%">File Excel</td>
                <td width="2%">:</td>
                <td>
                    <div class="fileinputs">
                        <input type="file" size="70" id="userfile" name="userfile"  value="<? echo $a_file ?>" onChange="setvalueuplfile(this.value,'userfile','xls')" />
                        <div class="fakefile">
                            <input type="text" size="69" name="a_file" id="a_file" value="<? echo $a_file ?>"/>
                        </div>
                        <input name="upload" type="submit" value="Proses" onclick="uploadData()">		
                    </div>
                    <input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $a_file ?>"/>
                </td>

            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>	
            </tr>
            <tr>
                <td colspan="3" style="background-color: red;color: white;text-align: center;font-weight: bold;">
                    Template di bawah ini digunakan untuk memudahkan entry data. Jika sudah selesai melakukan entry data pada "sheet 1",<br />
                    pindahkan hasil entrian dari kolom yang berwarna biru (Kolom A s/d S), ke file excel baru dengan nama file bebas yang ber-format .xls
                </td>
            </tr>
            <tr>
                <td>Download Template File Excel Lokasi Kerja Kantor Pusat MA disini</td>
                <td>:</td>
                <td><a href="#"><span class="excel-icon" title="Download File" onclick="ambilFileKantorPusatMA()">&nbsp;&nbsp;&nbsp;&nbsp;</span></a></td>	
            </tr>
            <tr>
                <td>Download Template File Excel Lokasi Kerja Kantor Pusat MA disini</td>
                <td>:</td>
                <td><a href="#"><span class="excel-icon" title="Download File" onclick="ambilFileKantorPusatMA()">&nbsp;&nbsp;&nbsp;&nbsp;</span></a></td>	
            </tr>
            <tr>
                <td>Download Template File Excel Lokasi Kerja Pengadilan Dibawah Ditjen Umum disini</td>
                <td>:</td>
                <td><a href="#"><span class="excel-icon" title="Download File" onclick="ambilFilePengadilanDitjenUmum()">&nbsp;&nbsp;&nbsp;&nbsp;</span></a></td>	
            </tr>
            <tr>
                <td>Download Template File Excel Lokasi Kerja Pengadilan Dibawah Ditjen Agama disini</td>
                <td>:</td>
                <td><a href="#"><span class="excel-icon" title="Download File" onclick="ambilFilePengadilanDitjenAgama()">&nbsp;&nbsp;&nbsp;&nbsp;</span></a></td>	
            </tr>
            <tr>
                <td>Download Template File Excel Lokasi Kerja Pengadilan Dibawah Ditjen Tata Usaha disini</td>
                <td>:</td>
                <td><a href="#"><span class="excel-icon" title="Download File" onclick="ambilFilePengadilanDitjenTU()">&nbsp;&nbsp;&nbsp;&nbsp;</span></a></td>	
            </tr>
        </table>


    </form>
</div>	
<div id="trgt" style="display: none">
    <table>
        <tr>
            <td><h2>Harap bersabar proses pindah data sedang dilakukan....</h2></td>
        </tr>
    </table>
</div>
<div id="statusJajal"></div>