<? 	require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 


   $jmlPegawaiList = count($this->pegawaiList);
   //echo "jmlPegawaiList= ".$jmlPegawaiList;
   for ($j = 0; $j < $jmlPegawaiList; $j++) {
     $cv[$j] = array("i_peg_nip"  		=>(string)$this->pegawaiList[$j]['i_peg_nip'],
	                      "n_peg"      		=>(string)$this->pegawaiList[$j]['n_peg'],
						  "gol"  			=>(string)$this->pegawaiList[$j]['golMax'],
						  "pangkat"  		=>(string)$this->pegawaiList[$j]['pangkatMax'],
						  "statusPeg"  		=>(string)$this->pegawaiList[$j]['statusPeg'],
						  "eselon"  		=>(string)$this->pegawaiList[$j]['eselon'],
						  "kdUnitKerja"  	=>(string)$this->pegawaiList[$j]['kdUnitKerja'],
						  "unitKerja"  		=>(string)$this->pegawaiList[$j]['unitKerja']);
	}

	$numToDisplay = $this->numToDisplay;
	$currentPage = $this->currentPage;  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> Riwayat Hidup
			</div>
	        <a name="top"></a>
			<div style="overflow: hidden;">
					<div class="wrap">
						<div class="panel">
							<div class="inner">
								<span class="corners-top"><span></span></span>
								<h2 class="title">Daftar Riwayat Hidup</h2>
								<div class="search-panel">
								<form id="frmSearch" action="<?php echo $this->basePath; ?>/sdm/pegawai/pegawaisearch" method="post" name="frmSearch">
									<table border="0" cellpadding="0" cellspacing="1" class="std" width="70%">
										<tr>
											<td width="5%">&nbsp;</td>
											<td width="20%">NIP</td>
											<td width="2%">:</td> 
											<td>
											<?
												$nip = $_POST['nip'];
											   if ($nip == null) {
													$nip = $_REQUEST['param1'];
											   }
												$nipAtrib = array("size"=>"20",
														 "maxlength"=>"20",
														 "class"=>""); 
												echo $ctrlFrm->formText('nip', $nip, $nipAtrib); 
											?>
											</td>
										</tr>
										<tr>
											<td>&nbsp;</td>
											<td>Nama</td>
											<td>:</td> 
											<td>
											<?
												$nama = $_POST['nama'];
											   if ($nama == null) {
													$nama = $_REQUEST['param2'];
											   }
												$namaAtrib = array("size"=>"55",
																 "class"=>""); 
												echo $ctrlFrm->formText('nama', $nama, $namaAtrib);
											?>
											</td>
											&nbsp;				
											</td>
										</tr>
										<tr>
											<td>&nbsp;</td>
											<td>&nbsp;</td>
											<td>&nbsp;</td> 
											<td>
											<?
									        $atribSubmit = array("onclick"=>"javascript:commandSubmit();");
									        echo $ctrlFrm->formSubmit('perintah', 'CARI', $atribSubmit)."&nbsp;";
											?>
											</td>
										</tr>					
									</table>
								</form>
								
		<table align='center' width='80%' border='0' cellspacing='1' cellpadding='2' class='tbl'>
		   <tr>
				<th width='4%'>No.</th>
				<th width='20%'>Nama Pegawai</th>
				<th width='7%'>NIP</th>
				<th width='17%'>Gol./Pangkat</th>
				<th width='7%'>Eselon</th>
				<th width='11%'>Status Pegawai</th>
				<th width='34%'>Satuan Kerja</th>
	  	</tr> <? 		if ($jmlPegawaiList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{?>
				
<?
				
	foreach ($cv as $key => $val): 
	if ($key%2==0) 
	{ echo "<tr class='event'>"; } 
	else if ($key%2==1) 
	{ echo "<tr class='event2'>";  } 
	$noUrut = (($currentPage -1)* $numToDisplay) + $key +1;
	$pangkat = $this->escape($val['pangkat']);
	$gol = $this->escape($val['gol']);
	$golPangkat = $gol." - ".$pangkat;
	$eselon = $this->escape($val['eselon']);
	if ($eselon == 'NE') {
		$eselon = 'Non Eselon';
	}
	$i_peg_nip=$this->escape($val['i_peg_nip']);
?>
				<td class='clcenter'>&nbsp;<?php echo $noUrut;?></td>
			    <td>&nbsp;				
					<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/cv/cvview?nip=<?=$this->escape($val['i_peg_nip'])?>','');" class="link" title="View CV"><?=$this->escape($val['n_peg'])?></a></td>
				<td> <?php echo $this->escape($val['i_peg_nip']);?></td>
				<td> <?php echo $golPangkat;?></td>
				<td> <?php echo $eselon;?></td>
				<td> <?php echo $this->escape($val['statusPeg']);?></td>
				<td> <?php echo $this->escape($val['unitKerja']);?></td>
		  </tr>
	<?php endforeach;}?> 

	</table>									
<?
$modul = $this->basePath."/sdm/cv/cvsearch";
echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>								
									
									</fieldset>		 
									</form>
								<span class="corners-bottom"><span></span></span>
							</div>
						</div>
					</div><!-- wrap -->	
			</div>
	</div>	

