<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
$dikJenjangList = count($this->dikJenjangList); 
if ($dikJenjangList == 0) {
		echo "<font color=\"red\">Data Diklat Penjenjangan Tidak Ditemukan</font>";
}
?>
		<table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
				<tr>
			    <th width="15%">Penjenjangan</th>
				<th width="8%">Angkatan / Tahun</th>
				<th width="8%">Lama</th>
				<th width="8%">Peringkat</th>
				<th width="8%">Predikat</th>
				<th width="15%">Penyelenggara</th>
				<th width="15%">Sertifikat</th>
				</tr>

<?
	if ($dikJenjangList == 0) {
?>				<tr class="event">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				</tr>
<? } else { ?>				
		<?php foreach ($this->dikJenjangList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
				<? 
					$nip=trim($this->escape($val['i_peg_nip']));

				?>
					
				<td>
					<a href="#" onclick="detilLatih('<?=$nip?>','<?=trim($this->escape($val['c_penjenjangan']))?>')"><?php echo $this->escape($val['n_penjenjangan']);?></a>
				</td>
				<td class="clcenter"><?php echo $this->escape($val['q_angkatan']);?>/<?php echo $this->escape($val['q_tahun']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['q_lama']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['q_peringkat']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_kualifikasi']);?></td>
				<td class="clleft"><?php echo $this->escape($val['n_penyelenggara']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['i_sertifikat']);?><br><?php echo $this->escape($val['d_sertifikat']);?></td>
			
		  </tr>
	<?php endforeach;?> 	
	<? } ?>
	</table>									
