<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   for ($i = 0; $i < 60; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }

?>
<script type="text/javascript">
	$(function() {
		$( "#d_surat" ).datepicker({changeMonth: true,changeYear: true});	
	
	});
</script>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Utama</a> 
				<strong> &#8250; </strong>Usulan Penerimaan CPNS
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form name="formcpnsusul" id="formcpnsusul" method="post" action="">
<h2 class="title">Usulan Penerimaan CPNS</h2>

	<div class="panel">	
		<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
			<tr>
				<td width="20%">Nomor Surat <span class="hightlight">*</span></td>
				<td width="2%">:</td>
				<td>
					<input type="text" size="60" name="n_surat" id="n_surat" value="<?=$this->n_surat?>" >
					<input type="hidden" size="60" name="id" id="id" value="<?=$this->id?>" >
				</td>
			</tr>
			<tr>
				<td>Perihal <span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<textarea rows="1" name="n_perihal" id="n_perihal"><?=$this->n_perihal?></textarea>
				</td>
			</tr>	
			<tr>
				<td>Tanggal Surat <span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="10" name="d_surat" id="d_surat" value="<?=$this->d_surat?>" >
				</td>
			</tr>	
			<tr>
				<td>Jabatan Penandatangan</td>
				<td>:</td>
				<td>
					<input type="hidden" size="70" name="c_jabatan" id="c_jabatan" value="<?=$this->c_jabatan?>" >
					<input type="text" size="70" name="n_jabatan" id="n_jabatan" value="<?=$this->n_jabatan?>" >
					<input type="button" value="Cari" onClick="CariJabatan()">
				</td>
			</tr>	
	
			<tr>
				<td>Dokumen</td>
				<td>:</td>
				<td valign="bottom">					
					<div class="fileinputs">
						<input type="file" size=45 id="surat" name="surat"  value="<? echo $this->a_file?>"onChange="setvalueuplfile(this.value,'surat','pdf')" />
						<div class="fakefile">
							<input type="text" size=44 name="a_file" id="a_file" value="<? echo $this->a_file?>"/>
						</div>
					</div>
					<input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $this->a_file?>"/>								
				</td>					
			</tr>
			
		</table>
<br>		
<?
$hit=1;
if (count($this->checkListJabatan)!=0){
?>	
	<table border="0" cellpadding="0" cellspacing="1" width="100%">
		<tr>
			<th>&nbsp;</th>
			<th>Nama Jabatan</th>
			<th>Kualifikasi Pendidikan</th>
		</tr>
		<?php 
		if (count($this->checkListJabatan)!=0){
		foreach ($this->checkListJabatan as $key => $val): 
			$check="";
			$c_jabatan="";
			$cek="";
			$c_jabatan=trim($this->escape($val['c_jabatan']));
			if (count($this->dataUsulJabat)!=0){
			foreach ($this->dataUsulJabat as $keyx => $valx):
				$c_jabatan_usul="";
				$c_jabatan_usul=trim($this->escape($valx['c_jabatan_usul']));				
				if ($c_jabatan==$c_jabatan_usul)
				{$check="checked=\"true\""; $cek="ok";}
			endforeach;
			}
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
				<td align="center">
					<input type='checkbox' <?=$check?> value='JB<?=$hit?>' name='jb<?=$hit?>' onclick="if (this.checked == true) {document.getElementById('cek<?=$hit?>').value ='ok'} else {document.getElementById('cek<?=$hit?>').value ='no'}"/>
					<input type='hidden' name="cek<?=$hit?>"  id="cek<?=$hit?>" value='<?=$cek?>'>
				</td>
				<td>								
					<?php echo $this->escape($val['n_jabatan']);?>
					<input type='hidden' name="c_jabatan_usul_<?=$hit?>"  value='<?echo $this->escape($val['c_jabatan'])?>'>
					<input type='hidden' name="n_jabatan_usul_<?=$hit?>"  value='<?echo $this->escape($val['n_jabatan'])?>'>
				</td>
				<td class="clcenter">
				<?php 
					// $jmldata = count($this->listKualifikasiPend);
					// $listKualifikasiPend[''] = '--Pilih--';
					// for ($i = 0; $i < $jmldata; $i++) {
						// $listKualifikasiPend[(string)$this->listKualifikasiPend[$i]['c_kualifikasi_pend']] = (string)$this->listKualifikasiPend[$i]['n_kualifikasi_pend'];
					// }
					// echo $ctrlFrm->formSelect("n_pend_usul_$hit", $this->n_pend_usul, $propAtrib, $listKualifikasiPend)
					
					echo $this->escape($val['n_kualifikasi_pend']);
				?>
					<input type='hidden' name="c_kualifikasi_pend_<?=$hit?>"  value='<?echo $this->escape($val['c_kode'])?>'>
					<input type='hidden' name="n_pend_usul_<?=$hit?>"  value='<?echo $this->escape($val['n_kualifikasi_pend'])?>'>
				</td>
		
		  </tr>
	<?php $hit++;
	endforeach;
	}?> 		  	  
	</table>
	
<?}?>
<div>
<input type='hidden' name="counttable"  value='<?$hit=$hit*1-1; echo $hit;?>'>
<br>
	<div class="panel">
		<div class="spacer"></div><center>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
								<div class="right">
									<input type="button" value="Batal" onClick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/usulanterimacpns/listusulan','<?php echo $this->basePath; ?>/sdmmodule/usulanterimacpns/usulanjs');">
									<input type="submit" value="<?=$this->par;?>" onClick="insertCpnsUsul()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
								</div>
							</td>
						</tr>
			</table>
</div>			

</form>	
<div id="targetdetil"></div>


