<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();
$jumorganisasiList = count($this->organisasiList);   
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Organisasi
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Organisasi</h2>
<?php include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">			
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
   <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	 
<div class="add" title="Tambah Data" onclick="organisasiM('insert','');"></div>
<?}	if ($jumorganisasiList == 0) {
		echo "<font color=\"red\">Data organisasi Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
		    <th width="20%">Jenis Organisasi</th>
			<th width="30%">Nama Organisasi</th>
			<th width="10%">Thn Daftar</th>
			<th width="20%">Jabatan</th>
			<th width="20%">Tempat</th>
			<th width="6%" colspan="2">&nbsp;</th>
		</tr>
<?
	if ($jumorganisasiList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->organisasiList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
			
				<td>
					<a href="#" onclick="detilorganisasi('<?=$nip?>','<?=trim($this->escape($val['n_organisasi']))?>')"><?php echo strtoupper($this->escape($val['n_jenis_organisasi']));?></a>
				</td>
				<td><?php echo $this->escape($val['n_organisasi']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['d_daftar_organisasi']);?></td>
				<td><?php  echo $this->escape($val['n_peran_organisasi']);?></td>
				<td><?php  echo $this->escape($val['n_tempat_organisasi']);?></td>				
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="organisasiM('update','<?=trim($this->escape($val['i_peg_nip']))?>','<?=trim($this->escape($val['n_jenis_organisasi']))?>','<?=trim($this->escape($val['n_organisasi']))?>','<?=trim($this->escape($val['d_daftar_organisasi']))?>');"></div>	
				</td>
   <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>				
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataOrganisasi('<?=$nip?>','<?=trim($this->escape($val['n_jenis_organisasi']))?>','<?=trim($this->escape($val['n_organisasi']))?>','<?=trim($this->escape($val['d_daftar_organisasi']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
