<?php 
require_once 'share/halaman_list.php'; 
$halaman = new halaman_list(); 
?>

<div id="backgroundPopup">
	<div id="popupContact">
	<div style="height: 550px; overflow: auto; padding: 5px width: 300px;">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td>
					<div class="delete" title="Close" onclick="closeDetil()"></div>
					<!--<div class="view" title="Cetak Excel" onclick="viewExl()"></div>-->
				</td>
			</tr>
		</table>
		
		<?
		echo $this->view;
		?>	
		
		<?
		
		$modul = $this->basePath."/sdmmodule/monitoringkp/view?limit=$this->limit&c_eselon_i=$this->c_eselon_i&c_eselon_ii=$this->c_eselon_ii&c_eselon_iii=$this->c_eselon_iii&c_eselon_iv=$this->c_eselon_iv&c_eselon_v=$this->c_eselon_v&c_lokasi_unitkerja=$this->c_lokasi_unitkerja&blnawal=$this->blnawal&c_eselon=$this->c_eselon&c_golongan=$this->c_golongan&c_status_kepegawaian=$this->c_status_kepegawaian&thnakhir=$this->thnakhir&thnawal=$this->thnawal";
		echo $halaman->halamanListPopup($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
		?>		
	</div>		
	</div>
</div>	