<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();

	  
$jumkerabatList = count($this->kerabatList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
	<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Orang Tua dan Kerabat
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Data Orang Tua dan Kerabat</h2>
<?php $opr='psdr';include "$this->leftMenu/linkdatapokok.phtml";?>
						
	<div class="boxholder">	
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>  
<div class="add" title="Tambah Data" onclick="KerabatM('insert','','');"></div>
<?}?>
<?	if ($jumkerabatList == 0) {
		echo "<font color=\"red\">Data Kerabat Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="10%">Status kerabat</th>
			<th width="20%">Nama</th>
			<th width="20%">Jns Kel.</th>
			<th width="16%">Tempat/Tgl Lahir</th>
			<th width="10%">Pekerjaan</th>
			<th width="6%" colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumkerabatList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->kerabatList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				<td>
					<?php echo $this->escape($val['n_kerabat']);?>
				</td>
				<td><?php  echo $this->escape($val['n_nama']);?></td>
				<td><?php  echo $this->escape($val['n_jns_kel']);?></td>
				<td class="clcenter"><u><?php  echo $this->escape($val['a_tempat_lahir']);?></u><br><?php  echo $this->escape($val['d_tanggal_lahir']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['n_pekerjaan']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="KerabatM('update','<?=trim($this->escape($val['id']))?>');"></div>	
				</td>
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>				
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataKerabat('<?=$nip?>','<?=trim($this->escape($val['id']))?>')"></div>
				</td>
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
</div>		 
	</form>
