function tampilTaun(){
	var tahun= document.getElementById('tahun').value;
			
	handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir2/listformulir2';
	
		var opt = {tahun:tahun};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				if(tahun != "Tahun"){
				jQuery(".thn_skr").html(tahun);
				jQuery("#thn_sblm").html(tahun-1);
				jQuery("#tahun").val(tahun);
				}else{
				jQuery(".thn_skr").html("");
				jQuery("#thn_sblm").html("");
				
				}
			 });
		
		
};

function OpenFormulir2Olahdata(par,id,gol_ruang_gaji,jumlah){
		
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val();
		if(thn_skr == ""){
		alert("Tampil Tahun Terlebih dahulu !");
		return;
		}
		
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir2/formulir2olahdata';
		
		if(id==""){
		par="Insert";
		}else{
		par="Update";
		}
		var opt = {par:par,id:id,gol_ruang_gaji:gol_ruang_gaji,jumlah:jumlah};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				jQuery("#gol_ruang_gaji").val(gol_ruang_gaji);
				jQuery("#bezetting").val(jumlah);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
				jQuery("#thn_skrg2").val(thn_skr);
				jQuery("#thn_sblm2").val(thn_sblm);
				jQuery("#tahun").val(thn_skr);
			 });

}

function OpenFormulir2(){
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val()
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir2/listformulir2';
		
		var opt = {tahun:tahun};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });

}

function insertFormulir2(){
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val()
		jQuery("#formformulir2").ajaxForm(maintain_formulir2);
	
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir2/listformulir2';
		var opt = {tahun:tahun,thn_skr:thn_skr,thn_sblm:thn_sblm};
		jQuery.get(handler,opt,function(data) {
				//$("#tableview").html(data);
			jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });
}

var maintain_formulir2 = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formformulir2").ajaxForm(maintain_formulir2);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/formulir2/insertformulir2',
	type: 'post',
	resetForm: false
};

function updateFormulir2(){
	var thn_skr=jQuery(".thn_skr").html();
	var thn_sblm=jQuery("#thn_sblm").html();
	var tahun=jQuery("#tahun").val()
	
	jQuery("#formformulir2").ajaxForm(update_formulir2);
	
	handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir2/listformulir2';
		
		var opt = {tahun:tahun,thn_skr:thn_skr,thn_sblm:thn_sblm};
		jQuery.get(handler,opt,function(data) {
				//$("#tableview").html(data);
				jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });
}

var update_formulir2 = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formformulir2").ajaxForm(update_formulir2);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/formulir2/updateformulir2',
	type: 'post',
	resetForm: false
};