<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldptigaList = count($this->dptigaList);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong> TPM &nbsp;
			<strong>&#8250;</strong>&nbsp;Usulan TPM
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Usulan TPM</h2>
<div class="panel">	

	<form action="" method="post"> 
		<fieldset class="fields"> 
			   <div class="add" title="Tambah Data" onclick="usulTpmM('insert');"></div>
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th>Nomor Surat</th>
			<th>Usulan</th>
			<th>Tanggal</th>
			<th>Instansi</th>
			<th>Periode</th>
			<th>Keterangan</th>
			<th width="5%" colspan="2">&nbsp;</th>
		</tr> 
<? 		if (count($this->dataTpmUsul) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
								
				foreach ($this->dataTpmUsul as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				?>
					<td align="left"><?php echo $this->escape($val['usulan_nomor']);?></td>
					<td align="left"><?php echo $this->escape($val['usulan_keterangan']);?></td>					
					<td align="center"><?php echo $this->escape($val['mod_date']);?></td>
					<td align="left"><?php echo $this->escape($val['tvinstansi_kd']);?></td>
					<td align="left"><?php echo $this->escape($val['periode_text']);?></td>
					<td align="left"><?php echo $this->escape($val['periode_keterangan']);?></td>
					
					<td class="clcenter">
						<div class="edit" title="Ubah Data" onclick="usulTpmM('update','<?=$usulan_id?>');"></div>	
					</td>
					<td class="clcenter">
						<div class="delete" title="Hapus Data"  onClick="javascript:HapusUsulTpm('<?=$usulan_id?>')"></div>
					</td>					
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>		 
	</form>
	

