<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> Laporan
				<strong> &#8250; </strong> Monitoring Daftar Urut Kepangkatan
			</div>
<div id="top"></div>

	

<h2 class="title">Monitoring Daftar Urut Kepangkatan</h2>
<?php include "$this->leftMenu/laporanlink.phtml";?>
<form id="formresult" method="post" action="" name="formresult">
	<div class="boxholder">				
	<div class="panel">
		<div class="spacer"></div> 
			<h3 class="title"><b><u>UNIT KERJA</u></b><h3>
			
	<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">

		<tr>
			<td width="25%">Lokasi</td>
			<td width="2%">:</td> 
			<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon II</td>
			<td>:</td> 
			<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliii')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
			</td>
			</tr>						
		<tr>
			<td>Eselon III</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliv')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon IV</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","disabled"=>"true","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
			</td>
		</tr>
		<tr>
			<td >Eselon V</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
										else{$eslAtrib = array("style"=>"width: 300px","disabled"=>"true","id"=>"c_eselon_v");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			</td>
		</tr>
	
	
	</table>
	<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
		<tr>
			<td width="25%">Tahun</td>
			<td width="2%">:</td> 
			<td>				
				<?
					$tahun =date('Y')-2;
					$eselonvList[''] = '--Pilih--';
					for ($i = 0; $i < 10; $i++) {
						$thnlist[$tahun*1+$i*1] = $tahun*1+$i*1;			 
					}
					echo $ctrlFrm->formSelect('tahunsemester',$this->tahunsemester,null, $thnlist); 							
				?>				
			</td>
		</tr>	
	</table>		
</div>
<br>
	<div class="panel">			
		<div class="spacer"></div>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
				<td colspan="4" align="center">
					Awal Data : <input size="8" name="start" value="1" id="start" onkeypress="return justnumber(event)" type="text">
					&nbsp;&nbsp;&nbsp;&nbsp;
					Data per halaman : <input size="8" name="limit" value="25" onkeypress="return justnumber(event)" type="text">
				</td>
				</tr>
				<tr>
					<td align="center">
						&nbsp;
					</td>
				</tr>					
				<tr>
					<td align="center">
						<input type="submit" value="View" onclick="viewDuk();"> 
						<input type="submit" value="Cetak Excel" onclick="viewExl()"> &nbsp;
					</td>
				</tr>
			</table>				
	</div>
</form>		
</div>	
<div id="popupview"></div>

