	<td width="25%">Masa Kerja Golongan</td>
	<td width="2%">:</td> 
	<td>
		<input maxlength="2" type="text" size="10" name="q_masakerja_tahun" id="q_masakerja_tahun" value="<?=$this->q_masakerja_tahun?>" onKeyup="javascript:isNumber('q_masakerja_tahun');">
		&nbsp; tahun &nbsp;
		<input maxlength="2" type="text" size="10" name="q_masakerja_bulan" id="q_masakerja_bulan" value="<?=$this->q_masakerja_bulan?>" onKeyup="javascript:isNumber('q_masakerja_bulan');">
		&nbsp; bulan &nbsp; <span class="hightlight"><? echo $this->psn;?></span>
	</td>
