<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldptigaList = count($this->dptigaList);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong> TPM &nbsp;
			<strong>&#8250;</strong>&nbsp;Daftar PRA TPM
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $this->pesan;?></h2>				
	</div>
	<h2 class="title">Daftar PRA TPM</h2>
<div class="panel">	

	<form action="" method="post"> 
		<fieldset class="fields"> 
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th>Nomor Surat</th>
			<th>Judul</th>
			<th>Tanggal TPM</th>
			<th width="5%">&nbsp;</th>
		</tr> 
<? 		if (count($this->dataPraTpm) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->dataPraTpm as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				?>
					<td align="right"><?php echo $this->escape($val['usulan_nomor']);?></td>
					<td align="right"><?php echo $this->escape($val['nama_list']);?></td>
					<td align="right"><?php echo $this->escape($val['tpm_tgl']);?></td>					
					<td class="clcenter">
						<!--<div class="edit" title="Ubah Data" onclick="praTpmtpmiM('update','<?=$usulan_id?>');"></div>-->
						<input type="button" value="TPM I" onclick="praTpmtpmiM('update','<?=$usulan_id?>');">
					</td>
			
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>		 
	</form>
	

