<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
	<th width="5%">No</th>
	<th width="10%">NIP</th>
	<th width="20%">Nama</th>
	<th>Unit Kerja</th>	
		<?php 
	if (count($this->remindPensiun)==0){?>

	<?}else{	
		$no=0;
		foreach ($this->remindPensiun as $key => $val): 
		$no++;
			if ($key%2==0) { ?>
			<tr class="event">
					<? } else if ($key%2==1) { ?>
			<tr class="event2">
					<? } ?>
				<? 
					$nip=trim($this->escape($val['i_peg_nip']));
					$nama=trim($this->escape($val['n_peg']));
				?>
			<td><?=$no?></td>
			<td><?=$nip?></td>
			<td><?=$nama?></td>	
			</tr>
	<?php endforeach;}?> 	
</table>