			<div style="overflow: auto; padding: 15px width: 300px;">
						<?echo $this->chartpagub;?>

				
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">Belanja Barang</font></th>
								<th><font face="arial" size="1">Belanja Pegawai</font></th>
								<th><font face="arial" size="1">Belanja Modal</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?echo number_format($this->jmlbadilagBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagBM, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?echo number_format($this->jmlbadilumBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumBM, 2, ',', '.');?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?echo number_format($this->jmlbuaBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaBM, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?echo number_format($this->jmlbadimilBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilBM, 2, ',', '.');?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?echo number_format($this->jmlbpppphpBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpBM, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?echo number_format($this->jmlbawasBB, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasBP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasBM, 2, ',', '.');?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>
			</div>
