			<div style="overflow: auto; padding: 15px width: 500px;">
						<?echo $this->chartKeuanganTgr;?>
			</div>
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">

						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">TGR Pegawai</font></th>
								<th><font face="arial" size="1">TGR TP</font></th>
								<th><font face="arial" size="1">TGR Pihak III</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?=$this->jmlbadilagtgrpeg?></td>
								<td align="right"><?=$this->jmlbadilagtgrtp?></td>
								<td align="right"><?=$this->jmlbadilagtgrp3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?=$this->jmlbadilumtgrpeg?></td>
								<td align="right"><?=$this->jmlbadilumtgrtp?></td>
								<td align="right"><?=$this->jmlbadilumtgrp3?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?=$this->jmlbuatgrpeg?></td>
								<td align="right"><?=$this->jmlbuatgrtp?></td>
								<td align="right"><?=$this->jmlbuatgrp3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?=$this->jmlbadimiltgrpeg?></td>
								<td align="right"><?=$this->jmlbadimiltgrtp?></td>
								<td align="right"><?=$this->jmlbadimiltgrp3?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?=$this->jmlbpppphptgrpeg?></td>
								<td align="right"><?=$this->jmlbpppphptgrtp?></td>
								<td align="right"><?=$this->jmlbpppphptgrp3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?=$this->jmlbawastgrpeg?></td>
								<td align="right"><?=$this->jmlbawastgrtp?></td>
								<td align="right"><?=$this->jmlbawastgrp3?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>