			<div style="overflow: auto; padding: 15px width: 300px;">
						<?echo $this->chartasetb;?>

			</div>	
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">Persediaan</font></th>
								<th><font face="arial" size="1">Tanah</font></th>
								<th><font face="arial" size="1">Peralatan & Mesin</font></th>
								<th><font face="arial" size="1">Gedung & Bangunan</font></th>
								<th><font face="arial" size="1">Jalan,Irigasi & Jaringan</font></th>
								<th><font face="arial" size="1">Aset Tetap Lainnya</font></th>
								<th><font face="arial" size="1">Konstruksi Dalam Pengerjaan</font></th>
								<th><font face="arial" size="1">Aset Tak Berwujud</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?=$this->jmlbadilagPersediaan?></td>
								<td align="right"><?=$this->jmlbadilagTanah?></td>
								<td align="right"><?=$this->jmlbadilagperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbadilag4655?></td>
								<td align="right"><?=$this->jmlbadilagJalan?></td>
								<td align="right"><?=$this->jmlbadilagAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbadilagKDP?></td>
								<td align="right"><?=$this->jmlbadilagATB?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?=$this->jmlbadilumPersediaan?></td>
								<td align="right"><?=$this->jmlbadilumTanah?></td>
								<td align="right"><?=$this->jmlbadilumperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbadilum4655?></td>
								<td align="right"><?=$this->jmlbadilumJalan?></td>
								<td align="right"><?=$this->jmlbadilumAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbadilumKDP?></td>
								<td align="right"><?=$this->jmlbadilumATB?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?=$this->jmlbuaPersediaan?></td>
								<td align="right"><?=$this->jmlbuaTanah?></td>
								<td align="right"><?=$this->jmlbuaperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbua4655?></td>
								<td align="right"><?=$this->jmlbuaJalan?></td>
								<td align="right"><?=$this->jmlbuaAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbuaKDP?></td>
								<td align="right"><?=$this->jmlbuaATB?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?=$this->jmlbadimilPersediaan?></td>
								<td align="right"><?=$this->jmlbadimilTanah?></td>
								<td align="right"><?=$this->jmlbadimilperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbadimil4655?></td>
								<td align="right"><?=$this->jmlbadimilJalan?></td>
								<td align="right"><?=$this->jmlbadimilAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbadimilKDP?></td>
								<td align="right"><?=$this->jmlbadimilATB?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?=$this->jmlbpppphpPersediaan?></td>
								<td align="right"><?=$this->jmlbpppphpTanah?></td>
								<td align="right"><?=$this->jmlbpppphpperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbpppphp4655?></td>
								<td align="right"><?=$this->jmlbpppphpJalan?></td>
								<td align="right"><?=$this->jmlbpppphpAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbpppphpKDP?></td>
								<td align="right"><?=$this->jmlbpppphpATB?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?=$this->jmlbawasPersediaan?></td>
								<td align="right"><?=$this->jmlbawasTanah?></td>
								<td align="right"><?=$this->jmlbawasperalatandanmesin?></td>
								<td align="right"><?=$this->jmlbawas4655?></td>
								<td align="right"><?=$this->jmlbawasJalan?></td>
								<td align="right"><?=$this->jmlbawasAsetTetapLainnya?></td>
								<td align="right"><?=$this->jmlbawasKDP?></td>
								<td align="right"><?=$this->jmlbawasATB?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>
			
