			<div style="overflow: auto; padding: 15px width: 300px;">
		
					
						<?echo $this->chartnaikgol;?>

			</div>			
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Badilag</font></th>
								<th><font face="arial" size="1">Badilum</font></th>
								<th><font face="arial" size="1">BUA</font></th>
								<th><font face="arial" size="1">Badimiltun</font></th>
								<th><font face="arial" size="1">Balitbangkumdil</font></th>
								<th><font face="arial" size="1">Bawas</font></th>
							</tr>
							<tr class="event">
								<td align="right"><?=$this->jmlbadilagnaikgol?></td>
								<td align="right"><?=$this->jmlbadilumnaikgol?></td>
								<td align="right"><?=$this->jmlbuanaikgol?></td>
								<td align="right"><?=$this->jmlbadimilnaikgol?></td>
								<td align="right"><?=$this->jmlbpppphpnaikgol?></td>
								<td align="right"><?=$this->jmlbawasnaikgol?></td>
							</tr>

						</table>
					</td>
				</tr>		
			</table>