			<div style="overflow: auto; padding: 15px width: 300px;">
						<?echo $this->chartasetc;?>

				
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">Persediaan</font></th>
								<th><font face="arial" size="1">Tanah</font></th>
								<th><font face="arial" size="1">Peralatan & Mesin</font></th>
								<th><font face="arial" size="1">Gedung & Bangunan</font></th>
								<th><font face="arial" size="1">Jalan,Irigasi & Jaringan</font></th>
								<th><font face="arial" size="1">Aset Tetap Lainnya</font></th>
								<th><font face="arial" size="1">Konstruksi Dalam Pengerjaan</font></th>
								<th><font face="arial" size="1">Aset Tak Berwujud</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?echo number_format($this->jmlbadilagPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilag4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilagATB, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?echo number_format($this->jmlbadilumPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilum4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadilumATB, 2, ',', '.');?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?echo number_format($this->jmlbuaPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbua4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbuaATB, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?echo number_format($this->jmlbadimilPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimil4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbadimilATB, 2, ',', '.');?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?echo number_format($this->jmlbpppphpPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphp4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbpppphpATB, 2, ',', '.');?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?echo number_format($this->jmlbawasPersediaan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasTanah, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasperalatandanmesin, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawas4655, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasJalan, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasAsetTetapLainnya, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasKDP, 2, ',', '.');?></td>
								<td align="right"><?echo number_format($this->jmlbawasATB, 2, ',', '.');?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>
			</div>
