<div style="overflow: auto; padding: 15px width: 300px;">					
<?echo $this->chartPend;?>
</div>
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">

						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">SD</font></th>
								<th><font face="arial" size="1">SMP</font></th>
								<th><font face="arial" size="1">SMA</font></th>
								<th><font face="arial" size="1">D1</font></th>
								<th><font face="arial" size="1">D2</font></th>
								<th><font face="arial" size="1">D3</font></th>
								<th><font face="arial" size="1">D4</font></th>
								<th><font face="arial" size="1">S1</font></th>
								<th><font face="arial" size="1">S2</font></th>
								<th><font face="arial" size="1">S3</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?=$this->jmlbadilagsd?></td>
								<td align="right"><?=$this->jmlbadilagsmp?></td>
								<td align="right"><?=$this->jmlbadilagsma?></td>
								<td align="right"><?=$this->jmlbadilagd1?></td>
								<td align="right"><?=$this->jmlbadilagd2?></td>
								<td align="right"><?=$this->jmlbadilagd3?></td>
								<td align="right"><?=$this->jmlbadilagd4?></td>
								<td align="right"><?=$this->jmlbadilags1?></td>
								<td align="right"><?=$this->jmlbadilags2?></td>
								<td align="right"><?=$this->jmlbadilags3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?=$this->jmlbadilumsd?></td>
								<td align="right"><?=$this->jmlbadilumsmp?></td>
								<td align="right"><?=$this->jmlbadilumsma?></td>
								<td align="right"><?=$this->jmlbadilumd1?></td>
								<td align="right"><?=$this->jmlbadilumd2?></td>
								<td align="right"><?=$this->jmlbadilumd3?></td>
								<td align="right"><?=$this->jmlbadilumd4?></td>
								<td align="right"><?=$this->jmlbadilums1?></td>
								<td align="right"><?=$this->jmlbadilums2?></td>
								<td align="right"><?=$this->jmlbadilums3?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?=$this->jmlbuasd?></td>
								<td align="right"><?=$this->jmlbuasmp?></td>
								<td align="right"><?=$this->jmlbuasma?></td>
								<td align="right"><?=$this->jmlbuad1?></td>
								<td align="right"><?=$this->jmlbuad2?></td>
								<td align="right"><?=$this->jmlbuad3?></td>
								<td align="right"><?=$this->jmlbuad4?></td>
								<td align="right"><?=$this->jmlbuas1?></td>
								<td align="right"><?=$this->jmlbuas2?></td>
								<td align="right"><?=$this->jmlbuas3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?=$this->jmlbadimilsd?></td>
								<td align="right"><?=$this->jmlbadimilsmp?></td>
								<td align="right"><?=$this->jmlbadimilsma?></td>
								<td align="right"><?=$this->jmlbadimild1?></td>
								<td align="right"><?=$this->jmlbadimild2?></td>
								<td align="right"><?=$this->jmlbadimild3?></td>
								<td align="right"><?=$this->jmlbadimild4?></td>
								<td align="right"><?=$this->jmlbadimils1?></td>
								<td align="right"><?=$this->jmlbadimils2?></td>
								<td align="right"><?=$this->jmlbadimils3?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?=$this->jmlbpppphpsd?></td>
								<td align="right"><?=$this->jmlbpppphpsmp?></td>
								<td align="right"><?=$this->jmlbpppphpsma?></td>
								<td align="right"><?=$this->jmlbpppphpd1?></td>
								<td align="right"><?=$this->jmlbpppphpd2?></td>
								<td align="right"><?=$this->jmlbpppphpd3?></td>
								<td align="right"><?=$this->jmlbpppphpd4?></td>
								<td align="right"><?=$this->jmlbpppphps1?></td>
								<td align="right"><?=$this->jmlbpppphps2?></td>
								<td align="right"><?=$this->jmlbpppphps3?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?=$this->jmlbawassd?></td>
								<td align="right"><?=$this->jmlbawassmp?></td>
								<td align="right"><?=$this->jmlbawassma?></td>
								<td align="right"><?=$this->jmlbawasd1?></td>
								<td align="right"><?=$this->jmlbawasd2?></td>
								<td align="right"><?=$this->jmlbawasd3?></td>
								<td align="right"><?=$this->jmlbawasd4?></td>
								<td align="right"><?=$this->jmlbawass1?></td>
								<td align="right"><?=$this->jmlbawass2?></td>
								<td align="right"><?=$this->jmlbawass3?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>