			<div style="overflow: auto; padding: 15px width: 300px;">
						<?echo $this->kasasichart;?>

			</div>			
<!--
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
		
							<th>Perkara</th>
							<th>Jumlah</th>
							<? //echo $this->jmlks;?>
						</table>
					</td>
				</tr>		
			</table>
-->			
