			
			<div style="overflow: auto; padding: 15px width: 500px;">
						<?echo $this->chartUsia;?>
			</div>			
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1"><25</font></th>
								<th><font face="arial" size="1">26 s/d 35</font></th>
								<th><font face="arial" size="1">36 s/d 45</font></th>
								<th><font face="arial" size="1">46 s/d 55</font></th>
								<th><font face="arial" size="1">>56</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?=$this->jmlbadilag25?></td>
								<td align="right"><?=$this->jmlbadilag2635?></td>
								<td align="right"><?=$this->jmlbadilag3645?></td>
								<td align="right"><?=$this->jmlbadilag4655?></td>
								<td align="right"><?=$this->jmlbadilag56?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?=$this->jmlbadilum25?></td>
								<td align="right"><?=$this->jmlbadilum2635?></td>
								<td align="right"><?=$this->jmlbadilum3645?></td>
								<td align="right"><?=$this->jmlbadilum4655?></td>
								<td align="right"><?=$this->jmlbadilum56?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?=$this->jmlbua25?></td>
								<td align="right"><?=$this->jmlbua2635?></td>
								<td align="right"><?=$this->jmlbua3645?></td>
								<td align="right"><?=$this->jmlbua4655?></td>
								<td align="right"><?=$this->jmlbua56?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?=$this->jmlbadimil25?></td>
								<td align="right"><?=$this->jmlbadimil2635?></td>
								<td align="right"><?=$this->jmlbadimil3645?></td>
								<td align="right"><?=$this->jmlbadimil4655?></td>
								<td align="right"><?=$this->jmlbadimil56?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?=$this->jmlbpppphp25?></td>
								<td align="right"><?=$this->jmlbpppphp2635?></td>
								<td align="right"><?=$this->jmlbpppphp3645?></td>
								<td align="right"><?=$this->jmlbpppphp4655?></td>
								<td align="right"><?=$this->jmlbpppphp56?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?=$this->jmlbawas25?></td>
								<td align="right"><?=$this->jmlbawas2635?></td>
								<td align="right"><?=$this->jmlbawas3645?></td>
								<td align="right"><?=$this->jmlbawas4655?></td>
								<td align="right"><?=$this->jmlbawas56?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>