			<div style="overflow: auto; padding: 15px width: 300px;">
						<?echo $this->chartkgb;?>

			</div>			
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						
						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Badilag</font></th>
								<th><font face="arial" size="1">Badilum</font></th>
								<th><font face="arial" size="1">BUA</font></th>
								<th><font face="arial" size="1">Badimiltun</font></th>
								<th><font face="arial" size="1">Balitbangkumdil</font></th>
								<th><font face="arial" size="1">Bawas</font></th>
							</tr>
							<tr class="event">
								<td align="right"><?=$this->jmlbadilagkgb?></td>
								<td align="right"><?=$this->jmlbadilumkgb?></td>
								<td align="right"><?=$this->jmlbuakgb?></td>
								<td align="right"><?=$this->jmlbadimilkgb?></td>
								<td align="right"><?=$this->jmlbpppphpkgb?></td>
								<td align="right"><?=$this->jmlbawaskgb?></td>
							</tr>

						</table>
					</td>
				</tr>		
			</table>