<div style="overflow: auto; padding: 15px width: 300px;">
<?echo $this->chartGol;?>
</div>
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">

						<table border="0" width="100%" align="center" class="tbl2">
							<tr>
								<th><font face="arial" size="1">Eselon I</font></th>
								<th><font face="arial" size="1">I</font></th>
								<th><font face="arial" size="1">II</font></th>
								<th><font face="arial" size="1">III</font></th>
								<th><font face="arial" size="1">IV</font></th>
							</tr>
							<tr class="event">
								<td align="left">Badilag</td>
								<td align="right"><?=$this->jmlbadilaggol1?></td>
								<td align="right"><?=$this->jmlbadilaggol2?></td>
								<td align="right"><?=$this->jmlbadilaggol3?></td>
								<td align="right"><?=$this->jmlbadilaggol4?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badilum</td>
								<td align="right"><?=$this->jmlbadilumgol1?></td>
								<td align="right"><?=$this->jmlbadilumgol2?></td>
								<td align="right"><?=$this->jmlbadilumgol3?></td>
								<td align="right"><?=$this->jmlbadilumgol4?></td>
							</tr>
			
							<tr class="event">
								<td align="left">BUA</td>
								<td align="right"><?=$this->jmlbuagol1?></td>
								<td align="right"><?=$this->jmlbuagol2?></td>
								<td align="right"><?=$this->jmlbuagol3?></td>
								<td align="right"><?=$this->jmlbuagol4?></td>
							</tr>
							<tr class="event2">
								<td align="left">Badimiltun</td>
								<td align="right"><?=$this->jmlbadimilgol1?></td>
								<td align="right"><?=$this->jmlbadimilgol2?></td>
								<td align="right"><?=$this->jmlbadimilgol3?></td>
								<td align="right"><?=$this->jmlbadimilgol4?></td>
							</tr>
							<tr class="event">
								<td align="left">Balitbangkumdil</td>
								<td align="right"><?=$this->jmlbpppphpgol1?></td>
								<td align="right"><?=$this->jmlbpppphpgol2?></td>
								<td align="right"><?=$this->jmlbpppphpgol3?></td>
								<td align="right"><?=$this->jmlbpppphpgol4?></td>
							</tr>
							<tr class="event2">
								<td align="left">Bawas</td>
								<td align="right"><?=$this->jmlbawasgol1?></td>
								<td align="right"><?=$this->jmlbawasgol2?></td>
								<td align="right"><?=$this->jmlbawasgol3?></td>
								<td align="right"><?=$this->jmlbawasgol4?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>