<? require_once 'Zend/View.php';
   require_once 'share/pesan.php';
   require_once 'share/formatangka.php';
   require_once 'share/halaman_list.php';

   $ctrlFrm = new Zend_View();
   $pesan = new pesan();
   $formatangka = new formatangka();
   $halaman = new halaman_list();

	  
$jumformulir4List = count($this->listFormulir4); 
$jumtotformulir4List = count($this->listJumFormulir4);
$jumgolList = count($this->listGol); 
			
?>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Formasi Kepegawaian <!--a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Maintain Data Pegawai</a-->
				<strong> &#8250; </strong>Formulir 4
			</div>
	        <a name="top"></a>
<?
$proses		= $this->proses;
$keterangan	= $this->keterangan;
$status		= $this->status;
echo $pesan->show_message($proses, $keterangan, $status);
?>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Formulir 4</h2>
	<form method="post" name="tampil" id="tampil" >
	<table width="50%" border="0" cellpadding="0" cellspacing="0">
	<tr><td size="20%">
	
	Tahun Anggaran </td><td size="1%">  :</td><td size="79%"> <select name="tahun" id="tahun">
				<? if($this->tahun != "" && $this->tahun != "Tahun"){
					echo "<option value=".$this->tahun.">".$this->tahun."</option>";
				 ?>
				 <option>Tahun</option>
				 <? for($i=date('Y')+5;$i>=date('Y')-2;$i--){
					echo "<option value=$i>$i</option>";
				    }
				  }else{ ?>
					 <option>Tahun</option>
				 <? for($i=date('Y')+5;$i>=date('Y')-2;$i--){
					echo "<option value=$i>$i</option>";
				    }
				    }
				 ?>
				 </select></td></tr>
	<tr><td>&nbsp;</td><td>&nbsp;</td><td><input type="button" value="Tampil" name="tampil" onclick="tampilTaun()"></td></tr>
	</table>
	</form><br><br>
		<div align="center">DAFTAR KEBUTUHAN PEGAWAI NEGERI SIPIL<br>TAHUN ANGGARAN <span class="thn_skr"><? echo $this->tahun; ?></span></div>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  
	
		<tr><td width="10%"></td></tr>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center" width="50%">
			
			<tr>
		    <th width="5%">No</th>
			<th width="30%">PANGKAT</th>
			<th width="10%">GOL. RUANG GAJI</th>
			<th width="10%">JUMLAH PEGAWAI PADA 31-12-<span id="thn_sblm"><? echo $this->thn_sblm; ?></span> </th>
			<th width="10%">FORMASI TAHUN <span class="thn_skr"><? echo $this->tahun; ?></span></th>
			<th width="35%">KETERANGAN</th>
			<th colspan="2">&nbsp;</th>
			</tr>
			<tr>
			<th>1</th>
			<th>2</th>
			<th>3</th>
			<th>4</th>
			<th>5</th>
			<th>6</th>
			<th colspan="2">&nbsp;</th>
			</tr>
			
			<tr class="event"><td colspan="2"><div align="center">JUMLAH SELURUHNYA</div></td><td>&nbsp;</td>
			<? if($jumgolList != ""){
				foreach($this->listGol as $key => $gol):
				$total = $total + $this->escape($gol['jumlah']); 
				endforeach; ?>
			<td><? 	echo $total;?></td>
			<?  } ?>
			<? if($jumtotformulir4List != ""){
				foreach($this->listJumFormulir4 as $key => $val): ?>
			<td><? echo $this->escape($val['formasi']); ?></td><td>&nbsp;</td><td colspan="2">&nbsp;</td></tr>
<?			endforeach;
			} ?>
<?
	if ($jumformulir4List == 0) {
?>		
		<? $i=1;
			foreach ($this->listGol as $a => $gol):
			//foreach ($this->listFormulir1 as $key => $val):
				if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					//$nip=trim($this->escape($val['i_peg_nip']));*/
					
					?>
				
			<td><?php echo $i++; ?></td>
			<td><?php echo $this->escape($gol['n_peg_pangkat']);?></td>
			<td><?php echo $this->escape($gol['n_peg_golongan']);?></td>
			<td><?php echo $this->escape($gol['jumlah']);?></td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td class="clcenter"  colspan="2">			
					<div class="edit" title="Ubah Data"  onclick="OpenFormulir4Olahdata('Insert','','<?=trim($this->escape($gol['n_peg_golongan']))?>','<?=trim($this->escape($gol['n_peg_pangkat']))?>','<? echo trim($this->escape($gol['jumlah']))?>');"></div>	
				</td>
			
			</tr>
		<? endforeach; ?>
<? 	}	else { ?>

		<?php 	
			$i=1;
					
			foreach ($this->listGol as $a => $gol):
			//foreach ($this->listFormulir1 as $key => $val):
				if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					//$nip=trim($this->escape($val['i_peg_nip']));*/
					
					?>
				
				<td><?php echo $i++; ?></td>
				
				<td><?php echo $this->escape($gol['n_peg_pangkat']);?></td>
				<td><?php echo $this->escape($gol['n_peg_golongan']);?></td>
				<td><?php echo $this->escape($gol['jumlah']);?></td>
				<td><?php foreach ($this->listFormulir4 as $key => $val):
					if($this->escape($gol['n_peg_golongan'])==$this->escape($val['gol_ruang_gaji'])){
					echo $this->escape($val['formasi']);
					} 
					endforeach;?></td>
				<td><?php 
					foreach ($this->listFormulir4 as $key => $val):
					if($this->escape($gol['n_peg_golongan'])==$this->escape($val['gol_ruang_gaji'])){
					echo $this->escape($val['ket']);} 
					endforeach;?></td>
				<td class="clcenter"  colspan="2">			
					<div class="edit" title="Ubah Data" onclick="OpenFormulir4Olahdata('Insert','<?foreach ($this->listFormulir4 as $key => $val):
															if($this->escape($gol['n_peg_golongan'])==$this->escape($val['gol_ruang_gaji'])){
															echo $this->escape($val['id']);} 
															endforeach;?>','<?=trim($this->escape($gol['n_peg_golongan']))?>','<?=trim($this->escape($gol['n_peg_pangkat']))?>','<? echo trim($this->escape($gol['jumlah']))?>');"></div>	
				</td>
				
			</tr>
			<? //endforeach;?>	
	<?php endforeach; ?>  	  
<?	}	
	?>
	</table>
	</fieldset>		 
	</form>
