<?
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once "share/pesan.php";
require_once 'share/halaman.php';
   
	$pesan = new pesan();
	$ctrlDate = new tanggal();
	$ctrlFrm = new Zend_View();
	$halaman = new halaman(); 
	$temp1 = '1';

?>
<div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Rekapitulasi dan Summary
				<strong> &#8250; </strong>Informasi Statistik
</div>
<form method="post" name="frmrekapitulasi" id="frmrekapitulasi">

<div style="overflow: hidden;">
				<div class="wrap">
<div class="panel">
<div class="inner">
	<span class="corners-top"><span></span></span>
	<h2 class="title">Informasi Statistik</h2>
	<br>
	<div id="target">

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td width="20%">Unit Kerja</td>
		<td width="2%">:</td> 
		<td>
		<?php 
			$jmlUnitOrgList = count($this->unitOList);
			$unitOList['-'] = '--Pilih--';
			for ($i = 0; $i < $jmlUnitOrgList; $i++) {
			$unitOList[(string)$this->unitOList[$i]->i_orgb] = (string)$this->unitOList[$i]->n_orgb;			 
			}
			$unitOrgAtrib = array("id"=>"orgSelect","onClick"=>"javascript:cariSatker()"); 
			echo $ctrlFrm->formSelect('i_orgb', $this->i_orgb, $unitOrgAtrib, $unitOList) ?>
		</td>
	</tr>
	
	<tr>
		<td>Satuan Kerja</td>
		<td>:</td> 
		<td id="targetsatker">
		<?php 
			   $jmlUnitKerjaList = count($this->unitKList);
			   $unitKList['-'] = '--Pilih--';
			    for ($i = 0; $i < $jmlUnitKerjaList; $i++) {
			    $unitKList[(string)$this->unitKList[$i]->i_orgb] = (string)$this->unitKList[$i]->n_orgb;			 
			   }		
			echo $ctrlFrm->formSelect('c_unit_kerja', $this->c_unit_kerja, $unitKerjaAtrib, $unitKList);
		?>		
		</td>
	</tr>

</table>		
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td width="20%">Pilihan Laporan</td>
		<td width="2%">:</td>
		<td><input type="checkbox" onclick="getAllPegawai()" value="allPegawai" id="allPegawai" name="allPegawai">&nbsp;Jumlah Seluruh Pegawai</td>
	</tr>

	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegKatKontr()" value="pegKatKontr" id="pegKatKontr" name="pegKatKontr"> Jum Pegawai Kategori Kontrak</td>
		<td><input type="checkbox" onclick="getPegTetap()" name="pegTetap" id="pegTetap"> Pegawai Tetap</td>
	</tr>	
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegKontr()" name="pegKontr" id="pegKontr"> Pegawai Kontrak</td>
	</tr>	
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegKomps()" value="pegKomps" id="pegKomps" name="pegKomps"> Komposisi Pegawai</td>
		<td><input type="checkbox" onclick="getPegOrgn()" name="pegOrgn" id="pegOrgn"> Pegawai Organik</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegTrmp()" name="pegTrmp" id="pegTrmp"> Pegawai Trampil</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegGelar()" name="pegGelar" id="pegGelar"> Pegawai berdasar Kelulusan</td>
		<td><input type="checkbox" onclick="getPegGelarS3()" name="pegGelarS3" id="pegGelarS3"> S3</td>
		<td><input type="checkbox" onclick="getPegGelarS2()" name="pegGelarS2" id="pegGelarS2"> S2</td>
		<td><input type="checkbox" onclick="getPegGelarS1()" name="pegGelarS1" id="pegGelarS1"> S1</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegGelarD3()" name="pegGelarD3" id="pegGelarD3"> D3</td>
		<td><input type="checkbox" onclick="getPegGelarD2()" name="pegGelarD2" id="pegGelarD2"> D2</td>
		<td><input type="checkbox" onclick="getPegGelarD1()" name="pegGelarD1" id="pegGelarD1"> D1</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegGelarSma()" name="pegGelarSma" id="pegGelarSma"> SMA</td>
		<td><input type="checkbox" onclick="getPegGelarSmp()" name="pegGelarSmp" id="pegGelarSmp"> SMP</td>
		<td><input type="checkbox" onclick="getPegGelarSd()" name="pegGelarSd" id="pegGelarSd"> SD</td>
	</tr>	
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegSex()" value="pegSex" id="pegSex" name="pegSex"> Jenis Kelamin Pegawai</td>
		<td><input type="checkbox" onclick="getPegPria()" name="pegPria" id="pegPria"> Pegawai Pria</td>
		<td><input type="checkbox" onclick="getPegPermp()" name="pegPermp" id="pegPermp"> Pegawai Wanita</td>
	</tr>	
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegUsia()" value="pegUsia" id="pegUsia" name="pegUsia"> Usia Pegawai</td>
		<td><input type="checkbox" onclick="getPegUsia56()" name="pegUsia56" id="pegUsia56"> Diatas 56</td>
		<td><input type="checkbox" onclick="getPegUsia4655()" name="pegUsia4655" id="pegUsia4655"> Usia 46 - 55</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><input type="checkbox" onclick="getPegUsia3645()" name="pegUsia3645" id="pegUsia3645"> Usia 36 - 45</td>
		<td><input type="checkbox" onclick="getPegUsia2635()" name="pegUsia2635" id="pegUsia2635"> Usia 26 - 35</td>
		<td><input type="checkbox" onclick="getPegUsia26()" name="pegUsia26" id="pegUsia26"> Dibawah 26</td>
	</tr>		
</table>
<br>	
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td align="center">
			<input type="button" name="cari" id="cari"  class="button2" onclick="getCariRekapDemografi()"  value="Cari">
			<input type="button" class="button2" value="Clear" onclick="resetRekDemogr ('<?=$temp1 ?>');">
		</td>
	</tr>
</table>
</form>
<div id="targetlist">
<?include('rekapitulasidemografilist.phtml');?>
</div>

</table>
			</form>
			<span class="corners-bottom"><span></span></span>
		</div>
	</div>
	</div><!-- wrap -->	
	</div>
	</div>	
<script>
function cariSatker(){
	var i_org_parent=document.getElementById('orgSelect').value;
	var url = '<?php echo $this->basePath; ?>/sdm/datapegawai/listcombosatker';	
	var param = {i_org_parent:i_org_parent};
	jQuery.get(url, param, function(data) {
		jQuery("#targetsatker").html(data);

	});
}
</script>	