<? require_once 'Zend/View.php';
   require_once 'share/tanggal.php'; 
   
	$ctrlDate = new tanggal(); 
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   		
   for ($i = 0; $i < 60; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }
   $biayaList = array("-"=>"--Pilih--","B"=>"Beasiswa","NB"=>"Non Beasiswa");	

?>		
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_pend_ijazah").datepicker();
	});
</script>			
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">					
						<tr>
							<td width="20%">Jenjang Pendidikan
							
							</td>
							<td width="2%">:</td> 
							<td>
							<?php
								$jmljenjang = count($this->nmJenjangList);														   
								$jenjangReff[''] = '--Pilih--';							
								for ($i = 0; $i < $jmljenjang; $i++) {
									$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
									$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;
									if ($this->nmJenjangList[$i]['c_pend']==$this->c_pend){$nama_pend=$n_pend;}
								}							
	
								echo $nama_pend;

							?>
							</td>
						</tr>
						<tr>
							<td>Nama Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->n_pend_lembaga; 
							?>
							</td>
						</tr>
						<tr>
							<td>Alamat Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->a_pend_alamat;
							?>
							</td>
						</tr>
						<tr>
							<td>Nama Pimpinan</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->n_pend_kepsek;
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Masuk</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->d_pend_mulai;
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Lulus</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->d_pend_akhir;
							?>
							</td>
						</tr>
						<tr>
							<td>Nomor Ijazah</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->i_pend_ijazah;
							 ?>
							</td>
						</tr>
						<tr>
							<td>Tanggal Ijazah</td>
							<td>:</td> 
							<td>
								<?=$this->d_pend_ijazah?>
							</td>
						</tr>
						<tr>
							<td>Keterangan</td>
							<td>:</td> 
							<td>
							<?php 
								echo $this->e_keterangan;
							 ?>
							</td>
						</tr>
	
			</table>
