<? require_once 'Zend/View.php';
   require_once 'share/tanggal.php'; 
   
	$ctrlDate = new tanggal(); 
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   		
   for ($i = 1960 ; $i <  ($thnskrg+1) ; $i++) {
     $thnArrayList[$i] = $i;
   }
   $biayaList = array("-"=>"--Pilih--","B"=>"Beasiswa","NB"=>"Non Beasiswa");	

?>		
<script type="text/javascript">
	jQuery(function() {
		//jQuery("#d_pend_ijazah").datepicker();
		$( "#d_pend_ijazah" ).datepicker({	changeMonth: true,changeYear: true});
	});
</script>			
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">					
						<tr>
							<td width="20%">Jenjang Pendidikan
							<span class="hightlight">*</span>
							</td>
							<td width="2%">:</td> 
							<td>
							<?php
								$jmljenjang = count($this->nmJenjangList);														   
								$jenjangReff[''] = '--Pilih--';							
								for ($i = 0; $i < $jmljenjang; $i++) {
									$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
									$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;
									if ($this->nmJenjangList[$i]['c_pend']==$this->c_pend){$nama_pend=$n_pend;}
								}							
							if ($this->par!="Ubah"){
								$pendAtrib = array( "onclick" => "javascript:cPend();"); 
								echo $ctrlFrm->formSelect('c_pend',$this->c_pend,$pendAtrib,$jenjangReff);
							}
							else{?>
								<input type="hidden" name="c_pend" id="c_pend" value="<?=$this->c_pend?>">
							<?	
								echo $nama_pend;
							}
							?>
							</td>
						</tr>
						<tr>
							<td>Nama Sekolah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$pendidikanAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('n_pend_lembaga', $this->n_pend_lembaga, $pendidikanAtrib); 
							?>
							</td>
						</tr>
						<tr>
							<td>Alamat Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								$tempatAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('a_pend_alamat', $this->a_pend_alamat, $tempatAtrib);
							?>
							</td>
						</tr>
						<tr>
							<td>Nama Pimpinan</td>
							<td>:</td> 
							<td>
							<?php 
								$kepSekAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('n_pend_kepsek', $this->n_pend_kepsek, $kepSekAtrib);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Masuk<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_mulai', $this->d_pend_mulai, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Lulus<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_akhir', $this->d_pend_akhir, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Nomor Ijazah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$noIjazahAtrib = array("size"=>"25",
												 "maxlength"=>"30",
												 "class"=>""); 
								echo $ctrlFrm->formText('i_pend_ijazah', $this->i_pend_ijazah, $noIjazahAtrib);
							 ?>
							</td>
						</tr>
						<tr>
							<td>Tanggal Ijazah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
								<input type="text" id="d_pend_ijazah" name="d_pend_ijazah" value="<?=$this->d_pend_ijazah?>" size = "15" maxlength="254" onKeyUp="isNumber('i_waktu_mulai')">
								<span class="hightlight">dd-mm-yyyy</span>
							</td>
						</tr>
						<tr>
							<td>Akreditasi</td>
							<td>:</td> 
							<td>
							<?php 
								$noakreAtrib = array("size"=>"10",
										"maxlength"=>"4"); 
								echo $ctrlFrm->formText('c_akreditasi', $this->c_akreditasi, $noakreAtrib);
							 ?>
							</td>
						</tr>						
						<tr>
							<td>Keterangan</td>
							<td>:</td> 
							<td>
							<?php 
								$keterangan = $_POST['keterangan'];
								if ($keterangan == '') {
									$keterangan = null;
								} 
								$keteranganAtrib = array("rows"=>"3",
													    "cols"=>"20",
														"maxlength"=>"254",
													    "class"=>"medium"); 
								echo $ctrlFrm->formTextarea('e_keterangan', $this->e_keterangan, $keteranganAtrib);
							 ?>
							</td>
						</tr>
	
			</table>
