<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();
?>
<div id="backgroundPopup" >
	<center>
	<div id="popupContact" style="height:400px; width:700px;" >	

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Unit Kerja</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>
			<form enctype="multipart/form-data" method="post" id="f" name="f">
			
			
			<table border="0" width="100%" class="table">
			
		 <tbody><tr>
		<td align="center" colspan="3" class="row1">
			 <textarea cols="70" rows="5" id="query_nip" name="query_nip"></textarea>
		</td>
         </tr>
		 <tr class="row1">
             <td align="left" colspan="3">
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="55" name="bt1">
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'OR ';} else  {var strg = document.getElementById('query_nip').value;document.getElementById('query_nip').value = strg + ' OR ';}" value=" OR " tabindex="56" name="bt0">
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'AND ';} else  {var strg = document.getElementById('query_nip').value;document.getElementById('query_nip').value = strg + ' AND ';}" value=" AND " tabindex="57" name="bt2">					
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt2">
					&nbsp;<input type="button" onclick="document.getElementById('query_nip').value= ''" value=" Clear " tabindex="57" name="bt3">
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg;closeDetil()}" value="OK !" tabindex="58" name="bt3">
			 </td>
         </tr>
		 <tr>
             <td align="center" colspan="3" class="row">&nbsp;
     			</td>
         </tr>
	 </table>
<div id="listcombo" >
<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%" >
	<tr>
		<td width="30%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td>Lokasi</td>
					<td>
					<select id="operand" name="operand">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon I</td>
					<td>
					<select id="operand1" name="operand1">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon II</td>
					<td>
					<select id="operand2" name="operand2">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon III</td>
					<td>
					<select id="operand3" name="operand3">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon IV</td>
					<td>
					<select id="operand4" name="operand4">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
				<tr>
					<td>Eselon V</td>
					<td>
					<select id="operand5" name="operand5">
						<option value=" = ">Sama dengan</option>
						<option value=" != ">Selain</option>
					</select>
					</td>
				</tr>
			
			</table>	
		</td>
		<td width="70%">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td>
						<?
						$jmlLokList=count($this->lokasiList);
						$lokList[''] = '--Pilih--';
						for ($i = 0; $i < $jmlLokList; $i++) {
							$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
							}
						$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('c_lokasi_unitkerja','')"); 
						echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
						?>
					</td>
				</tr>
				<tr>
					<td>				
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('c_eselon_i','1')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[' '] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('c_eselon_ii','2')");
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('c_eselon_iii','3')");
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('c_eselon_iv','4')"); 
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>					
					</td>
				</tr>	
				<tr>
					<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('c_eselon_v','5')"); 
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>					
					</td>
				</tr>	
			
			</table>			
		</td>		
	</tr>
</table>	
</div>


		<input type="hidden" value="" id="kdeselon1" name="kdeselon1">
		<input type="hidden" value="" id="kdeselon2" name="kdeselon2">
		<input type="hidden" value="" id="kdeselon3" name="kdeselon3">
		<input type="hidden" value="" id="kdeselon4" name="kdeselon4">
		<input type="hidden" value="" id="kdeselon5" name="kdeselon5">	
			</form>
			
			</fieldset>
	
	</div>
	</center>
</div>
<script>

function cariCombo(par,par2){
	var c_lokasi_unitkerja=document.getElementById('c_lokasi_unitkerja').value;	
	var eseloni=document.getElementById('c_eselon_i').value;
	var eselonii=document.getElementById('c_eselon_ii').value;
	var eseloniii=document.getElementById('c_eselon_iii').value;
	var eseloniv=document.getElementById('c_eselon_iv').value;		
	if (c_lokasi_unitkerja=='1' || !c_lokasi_unitkerja){
		c_lokasi_unitkerja='1';
	var url = '<?php echo $this->basePath; ?>/sdmmodule/listcombolaporan/listcombolaporan3'; 
	}
	else{
	var url = '<?php echo $this->basePath; ?>/sdmmodule/listcombolaporan/listcombolaporan3b';
	}
	var param = {c_lokasi_unitkerja:c_lokasi_unitkerja,eseloni:eseloni,eselonii:eselonii,eseloniii:eseloniii,eseloniv:eseloniv};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);
		setComboEsl(par,par2);
	});	
}
function setComboEsl(par,par2){
	
	if (par != '') {
		var strg = document.getElementById('query_nip').value;
		var oprand = document.getElementById('operand'+par2).value; 
		var parx = document.getElementById(par).value;
		if (strg == '') {document.getElementById('query_nip').value = par + oprand + '\'' + parx + '\'';} 
		else  {document.getElementById('query_nip').value = strg + par + oprand + '\'' + parx + '\'';}
	}
	
}
function cariComboPngl(par,par2){
	var c_lokasi_unitkerja=document.getElementById('c_lokasi_unitkerja').value;	
	var eseloni=document.getElementById('c_eselon_i').value;
	var eselonii=document.getElementById('c_eselon_ii').value;
	var eseloniii=document.getElementById('c_eselon_iii').value;
	var eseloniv=document.getElementById('c_eselon_iv').value;		
	var url = '<?php echo $this->basePath; ?>/sdmmodule/listcombolaporan/listcombolaporan3b';
	var param = {c_lokasi_unitkerja:c_lokasi_unitkerja,eseloni:eseloni,eselonii:eselonii,eseloniii:eseloniii,eseloniv:eseloniv};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);
		setComboPngl(par,par2);
	});

}
function setComboPngl(par,par2){
	
	if (par != '') {
		var strg = document.getElementById('query_nip').value;
		var oprand = document.getElementById('operand'+par2).value; 
		var parx = document.getElementById(par).value;
		if (par=='c_eselon_ii'){
			var c_eselon_iix=document.getElementById(par).value;
			var c_eselon_ii=c_eselon_iix.substr(0,3) + '\'';
			var c_parent='\'' +c_eselon_iix.substr(4,2);
			parx= c_eselon_ii+' and c_parent '+c_parent;
		}
		if (par=='c_eselon_iii'){
			var c_eselon_iiix=document.getElementById(par).value;
			var c_eselon_iii=c_eselon_iiix.substr(4,2) + '\'';
			var c_satker='\'' +c_eselon_iiix.substr(7,6);
			parx= c_eselon_iii+' and c_satker '+c_satker;

		}
	
		if (strg == '') {document.getElementById('query_nip').value = par + oprand + '\'' + parx + '\'';} 
		else  {document.getElementById('query_nip').value = strg + par + oprand + '\'' + parx + '\'';}
	}
	
}

</script>