<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<div id="backgroundPopup" >
	<center>
	<div id="popupContact" style="height:450px; width:650px;" >	

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Help : Alamat</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>
			<form onsubmit="xjxmW.closeWindow(' .  . ')xajax_add('HELP','querylahir',document.getElementById('keyd').value);return false;" id="fd1" name="fd1" enctype="multipart/form-data" method="post">
			
			
			<table border="0" width="100%" class="table">
		
		<tbody><tr class="row1">
             <td>Alamat</td>
			 <td>
				<input type="text" value="" id="alamat" name="alamat" size="30">
					
			 </td>
			 <td>
				<input type="button" onclick=" var strg = document.getElementById('query_nip').value;  if (document.getElementById('alamat').value != '' ) {document.getElementById('query_nip').value = strg + ' upper(a_peg_rumah) like ' + '\'%'+ document.getElementById('alamat').value.toUpperCase() + '%\''; }" value="Masukan!" tabindex="55" name="bt_input" id="bt_input">
				</td>
		</tr>
		<tr class="row">
             <td>Desa</td>
			 <td>
			<input type="text" value="" id="almt_ds" name="almt_ds" size="30"></td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_ds').value != '' ) {document.getElementById('query_nip').value = strg + ' upper(a_peg_kelurahan) like ' + '\'%'+ document.getElementById('almt_ds').value.toUpperCase() + '%\''; }" value="Masukan!" tabindex="55" name="bt_input0" id="bt_input0">
				</td>
		</tr>
		<tr class="row">
             <td>Kecamatan</td>
			 <td>
			<input type="text" value="" id="almt_kec" name="almt_kec" size="30">
					</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_kec').value != '' ) {document.getElementById('query_nip').value = strg + ' upper(a_peg_kecamatan) like ' + '\'%'+ document.getElementById('almt_kec').value.toUpperCase() + '%\''; }" value="Masukan!" tabindex="55" name="bt_input1" id="bt_input1">
				</td>
		</tr>
		<tr class="row1">
             <td>Propinsi</td>
			 <td>
				<?php 
					$jmlPropList = count($this->propinsiList);
					$propinsiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlPropList; $i++) {
						$propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
					}
					$propAtrib = array("onClick"=>"javascript:cariKabupaten('targetkabupaten')"); 
					echo $ctrlFrm->formSelect('a_propinsi', $this->a_propinsi, $propAtrib, $propinsiList)
				?>
				  
			</td>
			 <td>
				<input type="button" onclick="if (document.getElementById('a_propinsi').value != '') {var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = strg + ' a_peg_propinsi = ' + '\''+ document.getElementById('a_propinsi').value + '\'';} " value="Masukan!" tabindex="55" name="bt_input2" id="bt_input2">
				</td>
		</tr>
		<tr class="row">
             <td>Kabupaten</td>
				<td id="targetkabupaten">
					<?php 
					$jmlKabList = count($this->kabupatenList);
					$kabupatenList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlKabList; $i++) {
						$kabupatenList[(string)$this->kabupatenList[$i]->c_kabupaten] = (string)$this->kabupatenList[$i]->n_kabupaten;			 
					}
					echo $ctrlFrm->formSelect('a_kota', $this->a_kota,null, $kabupatenList);
					?>
				</td>
			 <td>
				<input type="button" onclick="if (document.getElementById('a_kota').value != '') {var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = strg + ' a_peg_kota  = ' + '\''+ document.getElementById('a_kota').value + '\'';}" value="Masukan!" tabindex="55" name="bt_input3" id="bt_input3">
				</td>
		</tr>
		<tr class="row1">
			<td>RT</td>
			 <td>
				<input type="text" onkeypress="return justnumber(event)" value="" id="almt_rt" name="almt_rt" size="10">
			</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_rt').value != '' ) {document.getElementById('query_nip').value = strg + ' a_peg_rt like ' + '\'%'+ document.getElementById('almt_rt').value + '%\''; }" value="Masukan!" tabindex="55" name="bt_input4" id="bt_input4">
			</td>
		</tr>	
		<tr class="row1">
			<td>RW</td>
			 <td>
				<input type="text" onkeypress="return justnumber(event)" value="" id="almt_rw" name="almt_rw" size="10">
			</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_rw').value != '' ) {document.getElementById('query_nip').value = strg + ' a_peg_rw like ' + '\'%'+ document.getElementById('almt_rw').value + '%\''; }" value="Masukan!" tabindex="58" name="bt_input8" id="bt_input8">
			</td>
		</tr>				 
         
		 <tr class="row">
             <td>Kode Pos</td>
			 <td>
				<input type="text" onkeypress="return justnumber(event)" value="" id="almt_kp" name="almt_kp" size="30">
			</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_kp').value != '' ) {document.getElementById('query_nip').value = strg + ' a_peg_kodepos like ' + '\'%'+ document.getElementById('almt_kp').value + '%\''; }" value="Masukan!" tabindex="56" name="bt_input5" id="bt_input5">
				</td>
		</tr>
		 <tr class="row1">
             <td>Telp/HP</td>
			 <td>
				<input type="text" onkeypress="return justnumber(event)" value="" id="almt_hp" name="almt_hp" size="30">
			</td>
			 <td>
				<input type="button" onclick="var strg = document.getElementById('query_nip').value;  if (document.getElementById('almt_hp').value != '' ) {document.getElementById('query_nip').value = strg + ' (i_peg_telponhp like ' + '\'%'+ document.getElementById('almt_hp').value + '%\'' + ' OR i_peg_telponrumah like ' + '\'%'+ document.getElementById('almt_hp').value + '%\')'; }" value="Masukan!" tabindex="57" name="bt_input6" id="bt_input6">
				</td>
		</tr>
			
			 
         
		<tr>
             <td align="center" colspan="3" class="row">&nbsp;
     			</td>
         </tr>
		 <tr>
             <td align="center" colspan="3" class="row1">
			 <textarea cols="70" rows="5" id="query_nip" name="query_nip"></textarea>
						</td>
         </tr>
		 <tr class="row1">
             <td align="left" colspan="2">
					&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'OR ';}  else {document.getElementById('query_nip').value = document.getElementById('query_nip').value + ' OR ';} document.getElementById('bt_input0').disabled= false;document.getElementById('bt_input1').disabled= false;document.getElementById('bt_input2').disabled= false;document.getElementById('bt_input3').disabled= false;document.getElementById('bt_input4').disabled= false;" value=" OR " tabindex="56" name="bt0">
			 	&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {document.getElementById('query_nip').value = 'AND ';}  else {document.getElementById('query_nip').value = document.getElementById('query_nip').value + ' AND ';} document.getElementById('bt_input0').disabled= false;document.getElementById('bt_input1').disabled= false;document.getElementById('bt_input2').disabled= false;document.getElementById('bt_input3').disabled= false;document.getElementById('bt_input4').disabled= false;" value=" AND " tabindex="57" name="bt2">
				&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="56" name="bt1">
			 	&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt2">
			</td>
			 <td align="right">
			 <input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg;closeDetil()}" value="OK !" tabindex="58" name="bt3">
			 </td>
         </tr></tbody></table>      
			</form>
	
	</div>
	</center>
</div>	

<script type="text/javascript">


function cariKabupaten(target){
	var c_propinsi=document.getElementById('a_propinsi').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/listcombokabupaten';	
	var param = {c_propinsi:c_propinsi,target:target};
	jQuery.get(url, param, function(data) {
		jQuery("#"+target).html(data);

	});
}
</script>