<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $jmlLatihStrukList = count($this->latihStrukList);
   $latihStrukList[''] = '--Pilih--';
    for ($i = 0; $i < $jmlLatihStrukList; $i++) {	 
		$latihStrukList[(string)$this->latihStrukList[$i]->n_pend_latih ]= (string)$this->latihStrukList[$i]->n_pend_latih;			 
   }	
   $jenisLatihList = array(""=>"--Pilih--","F"=>"Fungsional","P"=>"Penjenjangan","T"=>"Teknis","L"=>"Lainnya");	  

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		//jQuery("#d_sertifikat").datepicker();
		$( "#d_sertifikat" ).datepicker({	changeMonth: true,changeYear: true});
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikfungsional/listdiklat','');">Diklat Fungsional</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Diklat Fungsional
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Diklat Fungsional</h2>
	<?php $opr = 'dfgs';  include "$this->leftMenu/linkdatadiklat.phtml";?>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formfungsional" method="post" name="formfungsional" enctype="multipart/form-data">		
				<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>	
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
						<td  width="23%">Nama / NIP</td>
						<td width="2%">:</td> 
						<td width="75%"><?=$this->nama." / ".$this->nip;?></td>
					</tr>				
					<tr>
						<td  width="23%">Jenis Pelatihan
						<span class="hightlight">*</span>
						</td>
						<td width="2%">:</td> 
						<td width="75%">					
						<?php	
						   $jmllisjnslatih = count($this->lisjnslatih);
						   $lisjnslatih[''] = '--Pilih--';
							for ($i = 0; $i < $jmllisjnslatih; $i++) {	 
								$lisjnslatih[(string)$this->lisjnslatih[$i]->c_fungsional ]= (string)$this->lisjnslatih[$i]->n_fungsional;			 
						   }						
							$parlisjnslatih= array("onChange"=>"getKelompok()");							
							echo $ctrlFrm->formSelect('c_jns_fungsional', $this->c_jns_fungsional, $parlisjnslatih, $lisjnslatih);
						?>						
						</td>
					</tr>
			
				<tr>
					<td>Kelompok
					<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td id="idkel">
						<?php
							   $jmlliskellatih = count($this->liskellatih);
							   $lisliskellatih[''] = '--Pilih--';
								for ($i = 0; $i < $jmlliskellatih; $i++) {	 
									$lisliskellatih[(string)$this->liskellatih[$i]->c_kelfungsional ]= (string)$this->liskellatih[$i]->n_kelfungsional;			 
							   } 
 						
							//$parlisliskellatih= array("onChange"=>"getJenis()");
							echo $ctrlFrm->formSelect('c_kel_pelatihan', $this->c_kel_pelatihan, $parlisliskellatih, $lisliskellatih);
						?>
					</td>
				</tr>
				<tr>
					<td>Jenis Keahlian<span class="hightlight">*</span></td>
					<td>:</td> 
					<td id="idjnsx">
						<?php
						   $jmllisjenjanglatih = count($this->lisjenjanglatih);
						   $lisjenjanglatih[''] = '--Pilih--';
							for ($i = 0; $i < $jmllisjenjanglatih; $i++) {	 
								$lisjenjanglatih[(string)$this->lisjenjanglatih[$i]->c_jenjang_fungsional ]= (string)$this->lisjenjanglatih[$i]->n_jenjang_fungsional;			 
						   } 						
							$jenisLatihAtrib= array("onchange"=>"getNama()");
							echo $ctrlFrm->formSelect('c_jns_kelompok', $this->c_jns_kelompok, $jenisLatihAtrib, $lisjenjanglatih);
						?>
					</td>
				</tr>
				<tr>
					<td>Nama </td>
					<td>:</td> 
					<td id="idnama">
						<?php
						if($this->c_jns_fungsional == 2){
						   $jmllisnamajenjanglatih = count($this->lisnamajenjanglatih);
						   $lisnamajenjanglatih[''] = '--Pilih--';
							for ($i = 0; $i < $jmllisnamajenjanglatih; $i++) {	 
								$lisnamajenjanglatih[$this->lisnamajenjanglatih[$i]->c_jenjang ]= (string)$this->lisnamajenjanglatih[$i]->n_jenjang;			 
						   }   
						}		
							echo $ctrlFrm->formSelect('c_nama_kelompok', $this->c_nama_kelompok, null, $lisnamajenjanglatih);
						?>
					</td>
				</tr>
				<tr>
					<td>Lama Diklat (JPL)</td>
					<td>:</td> 
					<td>
						<input type="text" name="q_pelatihan" id="q_pelatihan" value="<?=$this->q_pelatihan?>" size="5">
					</td>
				</tr>
				<tr>
					<td>Penyelenggara</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_penyelenggara" id="n_penyelenggara" value="<?=$this->n_penyelenggara?>" size="80">
					</td>
				</tr>
				<tr>
					<td colspan="3"><h3 class="title"><b>SERTIFIKAT/STTPP</b><h3></td>
				</tr>
				<tr>
					<td>Nomor Sertifikat<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>
						<input type="text" maxlength="80" name="i_sertifikat" id="i_sertifikat" value="<?=$this->i_sertifikat?>" size="50">
					</td>
				</tr>				
				<tr>
					<td>Tanggal Sertifikat<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>
						<input type="text" name="d_sertifikat" id="d_sertifikat" value="<?=$this->d_sertifikat?>" size="10">
						<span class="hightlight">dd-mm-yyyy</span>
					</td>
				</tr>	
				<tr>
					<td>Pejabat</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_pejabat" id="n_pejabat" value="<?=$this->n_pejabat?>" size="80">
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
									<? if ($this->id) {?><input type="hidden" value="<?=$this->id;?>" name="id" name="id" ><?}?> 									
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikfungsional/listdiklat','');"> 									
									<input type="submit" value="<?=$this->par;?>" onClick="insertFungsional()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
							</td>
						</tr>
					</table>
</form>
	</div>
	</div>
	