<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
$ceseloncpns=$this->ceseloncpns*1;
?>

 	<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tmt_cpns").datepicker();
		jQuery("#d_tmt_kerjacpns").datepicker();
		jQuery("#d_peg_lahir").datepicker();
		jQuery("#d_sk_cpns").datepicker();
	});
	
	</script>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> <a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datacpns/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datacpns/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data CPNS
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form id="formpegawai" method="post" action="" name="formpegawai"enctype="multipart/form-data" >
<h2 class="title"><?=$this->jdl;?> Data CPNS</h2>
<?if ($this->par=='Ubah'){$readonly="readonly='true'"?>
	<h3 class="tab" title="first"><div class="tabtxt"><a href="#Pns" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapns/pns?par=pns','<?php echo $this->basePath; ?>/sdmmodule/datapns/pnsjs');">PNS</a></div></h3>
	<h3 class="tab" title="first"><div class="tabtxt"><a href="#Pokok" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pokok</a></div></h3>
	<h3 class="tab" title="first"><div class="tabtxt"><a href="#Riwayat" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/listpendidikan','<?php echo $this->basePath; ?>/sdmmodule/datapendidikan/pendidikanjs');">Data Riwayat</a></div></h3>
				
<?	
	}?>
	<div class="boxholder">	
	<div class="panel">
		<div class="spacer"></div> 
			
			<table border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="65%">
					<table width="100%">
							<tr>
								<td width="35%">Status Kepegawaian<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
								<?php 
									   $jmlStatusKePegRef = count($this->statusKePegRef);
									   $statkepegList[''] = '--Pilih--';
									   for ($i = 0; $i < $jmlStatusKePegRef; $i++) {									   
										$statkepegList[(string)$this->statusKePegRef[$i]->c_status_kepegawaian] = (string)$this->statusKePegRef[$i]->n_status_kepegawaian;			 
									   }
									   $statkepegAtrib = array("onChange"=>"javascript:getStatPeg()");
									  echo $ctrlFrm->formSelect('c_status_kepegawaian', $this->c_status_kepegawaian,null, $statkepegList)
								?>							
								</td>
							</tr>
					</table>
					</td>
				</tr>
				<tr>
					<td>
						<table width="100%">
							<tr>
								<td width="25%">NIP Lama<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
									<input type="text" size="25" maxlength="9" name="i_peg_nip" id="i_peg_nip" <?echo $readonly?> value="<?=$this->i_peg_nip?>">
								</td>
							</tr>
							<tr>
								<td>Nama Lengkap<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<input type="text" size="40" maxlength="35" name="n_peg" id="n_peg" value="<?=$this->n_peg?>" >
								</td>
							</tr>
							<tr>
								<td>Gelar Depan</td>
								<td>:</td>
								<td>
									<input type="text" size="5" name="n_peg_gelardepan" id="n_peg_gelardepan" value="<?=$this->n_peg_gelardepan?>">
								</td>
							</tr>
							<tr>
								<td>Pangkat</td>
								<td>:</td>
								<td>
									<?
									$jmlgolref = count($this->statusGolRef);												   
									$golonganReff[''] = '--Pilih--';
									for ($i = 0; $i < $jmlgolref; $i++) {
											$n_peg_pangkat=trim($this->statusGolRef[$i]['n_peg_pangkat']);
											$c_peg_golongan=trim($this->statusGolRef[$i]['c_peg_golongan']);										   
											$golonganReff[trim((string)$this->statusGolRef[$i]['c_peg_golongan'])] = $c_peg_golongan."-".$n_peg_pangkat;											   
									}												 
									 echo $ctrlFrm->formSelect('c_gol_cpns', $this->c_gol_cpns, null, $golonganReff);
									?>
								</td>
							</tr>
							<tr>
								<td>TMT CPNS</td>
								<td>:</td>
								<td>
									<input type="text" name="d_tmt_cpns" id="d_tmt_cpns" value="<?=$this->d_tmt_cpns?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>
							<tr>
								<td>TMT Kerja</td>
								<td>:</td>
								<td>
									<input type="text" name="d_tmt_kerjacpns" id="d_tmt_kerjacpns" value="<?=$this->d_tmt_kerjacpns?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>							
							<tr>
								<td>Eselon</td>
								<td>:</td>
								<td>									
									<?
										$jmlEslList=count($this->eselonList);
										$eslList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlEslList; $i++) {
												$eslList[(string)$this->eselonList[$i]->c_eselon] = (string)$this->eselonList[$i]->n_eselon;			 
											}
										$eslAtrib = array("onChange"=>"javascript:getEselon()"); 		
										echo $ctrlFrm->formSelect('c_eselon_cpns',$this->c_eselon_cpns, $eslAtrib, $eslList); 							
									?>									
								</td>
							</tr>
							<tr>
								<td>Nama Jabatan</td>
								<td>:</td> 
								<td>					
									<input type="hidden" name="c_jabatan_cpns" id="c_jabatan" value="<?=$this->c_jabatan_cpns?>">
									<input type="text" name="n_jabatan_cpns" id="n_jabatan" value="<?=$this->n_jabatan_cpns?>" size="40">
									<input type="button" value="Cari" onClick="CariJabatan()">
								</td>																
							</tr>								
						</table>
					</td>
					<td>
						<table width="100%">
							<tr>
								<td width="45%">NIP Baru</td>
								<td width="2%">:</td>
								<td>
									<input type="text" size="25" maxlength="18" name="i_peg_nip_new" id="i_peg_nip_new" <?echo $readonly?> value="<?=$this->i_peg_nip_new?>">
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>Gelar Belakang</td>
								<td>:</td>
								<td>
									<input type="text" size="5" name="n_peg_gelarblkg" id="n_peg_gelarblkg" value="<?=$this->n_peg_gelarblkg?>">
								</td>
							</tr>
							<tr>
								<td>Pendidikan<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<?php
										$jmljenjang = count($this->nmJenjangList);														   
										$jenjangReff[''] = '--Pilih--';							
										for ($i = 0; $i < $jmljenjang; $i++) {
											$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
											$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;
										}
										echo $ctrlFrm->formSelect('c_pend_cpns',$this->c_pend_cpns,null,$jenjangReff);
									?>									
								</td>
							</tr>
							<tr>
								<td>Tanggal Lahir</td>
								<td>:</td>
								<td>
									<input type="text" name="d_peg_lahir" id="d_peg_lahir" value="<?=$this->d_peg_lahir?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>
						</table>
					</td>					
				</tr>
			</table>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" id="listcombo">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b><u>UNIT KERJA</u></b><h3>
								</td>
							</tr>
							<tr>
								<td width="30%">Lokasi</td>
								<td width="2%">:</td> 
								<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja_cpns","onChange"=>"javascript:cariCombo('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja_cpns',$this->c_lokasi_unitkerja_cpns,$lokAtrib,$lokList); 							
									?>
								</td>
							</tr>
							<tr>
								<td>Eselon I</td>
								<td>:</td> 
								<td id="targetesli">					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i_cpns","onChange"=>"javascript:cariEselon('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i_cpns',$this->c_eselon_i_cpns,$eslAtrib,$eseloniList); 							
									?>
								</td>
							</tr>
							<tr id="targetesliix">
								<td width="30%">Eselon II</td>
								<td width="2%">:</td> 
								<td id="targeteslii">				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii_cpns","onChange"=>"javascript:cariEselon('targetesliii')");}
										else {$eslAtrib = array("style"=>"width: 300px","disabled"=>"true","id"=>"c_eselon_ii_cpns","onChange"=>"javascript:cariEselon('targetesliii')");}
										echo $ctrlFrm->formSelect('c_eselon_ii_cpns',$this->c_eselon_ii_cpns,$eslAtrib,$eseloniiList); 							
									?>
								</td>
							</tr>						
							<tr id="targetesliiix">
								<td width="30%">Eselon III</td>
								<td width="2%">:</td> 
								<td id="targetesliii">					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii_cpns","onChange"=>"javascript:cariEselon('targetesliv')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii_cpns","disabled"=>"true","onChange"=>"javascript:cariEselon('targetesliv')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii_cpns',$this->c_eselon_iii_cpns, $eslAtrib, $eseloniiiList); 							
									?>
								</td>
							</tr>
							<tr id="targeteslivx">
								<td>Eselon IV</td>
								<td>:</td> 
								<td id="targetesliv">				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv_cpns","onChange"=>"javascript:cariEselon('targeteslv')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px","disabled"=>"true", "id"=>"c_eselon_iv_cpns","onChange"=>"javascript:cariEselon('targeteslv')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv_cpns',$this->c_eselon_iv_cpns,$eslAtrib,$eselonivList); 							
									?>
								</td>
							</tr>
							<tr id="targeteslvx">
								<td>Eselon V</td>
								<td>:</td> 
								<td id="targeteslv">				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v_cpns");}										
										else{$eslAtrib = array("style"=>"width: 300px","disabled"=>"true","id"=>"c_eselon_v_cpns");}
										echo $ctrlFrm->formSelect('c_eselon_v_cpns',$this->c_eselon_v_cpns, $eslAtrib, $eselonvList); 							
									?>
								</td>
							</tr>							
						</table>
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>HASIL AKHIR NAMA JABATAN</u></b><h3></td>
							</tr>
							<tr>
								<td colspan="3">					
									<textarea id="jabat_lengkap" name="jabat_lengkap" rows="7"><?=$this->jabat_lengkap?></textarea>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>	

			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b><u>MASA KERJA TAMBAHAN</u></b><h3>
								</td>
							</tr>
							<tr>
								<td>Fiktif</td>
								<td>:</td>
								<td>
									<input type="text" name="q_fiktif_cpns_thn" id="q_fiktif_cpns_thn" value="<?=$this->q_fiktif_cpns_thn?>" size="5"> Tahun
									<input type="text" name="q_fiktif_cpns_bln" id="q_fiktif_cpns_bln" value="<?=$this->q_fiktif_cpns_bln?>" size="5"> Bulan
								</td>
							</tr>	
							<tr>
								<td>Honorer</td>
								<td>:</td>
								<td>
									<input type="text" name="q_honorer_cpns_thn" id="q_honorer_cpns_thn" value="<?=$this->q_honorer_cpns_thn?>" size="5"> Tahun
									<input type="text" name="q_honorer_cpns_bln" id="q_honorer_cpns_bln" value="<?=$this->q_honorer_cpns_bln?>" size="5"> Bulan
								</td>
							</tr>	
							<tr>
								<td>Swasta</td>
								<td>:</td>
								<td>
									<input type="text" name="q_swasta_cpns_thn" id="q_swasta_cpns_thn" value="<?=$this->q_swasta_cpns_thn?>" size="5"> Tahun
									<input type="text" name="q_swasta_cpns_bln" id="q_swasta_cpns_bln" value="<?=$this->q_swasta_cpns_bln?>" size="5"> Bulan
								</td>
							</tr>	
							<tr>
								<td>Masa Kerja Total</td>
								<td>:</td>
								<td>
									<input type="text" name="q_mktotal_cpns_thn" id="q_mktotal_cpns_thn" value="<?=$this->q_mktotal_cpns_thn?>" size="5"> Tahun
									<input type="text" name="q_mktotal_cpns_bln" id="q_mktotal_cpns_bln" value="<?=$this->q_mktotal_cpns_bln?>" size="5"> Bulan
								</td>
							</tr>	
									
						</table>
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>SURAT KEPUTUSAN</u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Nomor</td>
								<td width="2">:</td> 
								<td>					
									<input type="text" name="i_sk_cpns" id="i_sk_cpns" value="<?=$this->i_sk_cpns?>" size="30">
								</td>
							</tr>
							<tr>
								<td>Tanggal</td>
								<td>:</td> 
								<td>					
									<input type="text" name="d_sk_cpns" id="d_sk_cpns" value="<?=$this->d_sk_cpns?>" size="10">
									<span class="hightlight">tgl-bln-thn</span>
								</td>
							</tr>
							<tr>
								<td>Pejabat</td>
								<td>:</td> 
								<td>					
									<input type="text" name="n_sk_pejabatcpns" id="n_sk_pejabatcpns" value="<?=$this->n_sk_pejabatcpns?>" size="50">
								</td>
							</tr>							
						</table>
					</td>
				</tr>
			</table>
	</div>		
<br>
	<div class="panel">
		<div class="spacer"></div> 			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
								<div class="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datacpns/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datacpns/pegawaijs');"> 
									<input type="submit" value="<?=$this->par;?>" onClick="insertPegawai()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
								</div>
							</td>
						</tr>
			</table>				
	</div>
	<div>
	<div id="targetdetil"></div>
</form>	
<script>
function CariJabatan(){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listnamajabatan';
var param = {};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}

function cariEselon(target){

	var esl =document.getElementById('c_eselon_cpns').value;
	var c_lokasi_unitkerja_cpns=document.getElementById('c_lokasi_unitkerja_cpns').value;
	var c_eselon_x='';
	if (target=='targetesli')
		{var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcomboeseloni';}
	if (target=='targeteslii')
		{var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcomboeselonii'; c_eselon_x=document.getElementById('c_eselon_i_cpns').value;}
	if (target=='targetesliii')
		{var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcomboeseloniii'; c_eselon_x=document.getElementById('c_eselon_ii_cpns').value;}
	if (target=='targetesliv')
		{var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcomboeseloniv'; c_eselon_x=document.getElementById('c_eselon_iii_cpns').value;}		
	if (target=='targeteslv')
		{var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcomboeselonv'; c_eselon_x=document.getElementById('c_eselon_iv_cpns').value;}				
	var param = {c_lokasi_unitkerja_cpns:c_lokasi_unitkerja_cpns,c_eselon_x:c_eselon_x};
	jQuery.get(url, param, function(data) {
		jQuery("#"+target).html(data);		
		getEselon();
		getNJab();
	});
	
	
}
function getNJab(){

		var c_eselon_i=document.getElementById('c_eselon_i_cpns').value;
		c_eselon_il=String(c_eselon_i).length
		c_eselon_i= Left(c_eselon_i,c_eselon_il);
		var c_eselon_ii=document.getElementById('c_eselon_ii_cpns').value;
		c_eselon_iil=String(c_eselon_ii).length
		c_eselon_ii= Left(c_eselon_ii,c_eselon_iil);
		var c_eselon_iii=document.getElementById('c_eselon_iii_cpns').value;
		c_eselon_iiil=String(c_eselon_iii).length
		c_eselon_iii= Left(c_eselon_iii,c_eselon_iiil);
		var c_eselon_iv=document.getElementById('c_eselon_iv_cpns').value;
		c_eselon_ivl=String(c_eselon_iv).length
		c_eselon_iv= Left(c_eselon_iv,c_eselon_ivl);
		var c_eselon_v=document.getElementById('c_eselon_v_cpns').value;
		c_eselon_vl=String(c_eselon_v).length
		c_eselon_v= Left(c_eselon_v,c_eselon_vl);		
		document.getElementById('jabat_lengkap').value=document.getElementById('n_jabatan').value+", pada "+c_eselon_v+", "+c_eselon_iv+", "+c_eselon_iii+", "+c_eselon_ii+", "+c_eselon_i;

}

function cariCombo(){
	var esl =document.getElementById('c_eselon_cpns').value;
	var c_lokasi_unitkerja_cpns=document.getElementById('c_lokasi_unitkerja_cpns').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datacpns/listcombo'; 
	var param = {};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);		
	});
}
function getEselon(){
var esl =document.getElementById('c_eselon_cpns').value;

if (esl=='01' || esl=='02')
	{
		document.getElementById('c_eselon_ii_cpns').value="";
		document.getElementById('c_eselon_iii_cpns').value="";
		document.getElementById('c_eselon_iv_cpns').value="";
		document.getElementById('c_eselon_v_cpns').value="";
		document.forms[0].c_eselon_ii_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_iii_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_iv_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_v_cpns.disabled = "disabled" ;
	}
 else if (esl=='03' || esl=='04')
	{
		document.getElementById('c_eselon_iii_cpns').value="";
		document.getElementById('c_eselon_iv_cpns').value="";
		document.getElementById('c_eselon_v_cpns').value="";
		document.forms[0].c_eselon_ii_cpns.disabled = false ;
		document.forms[0].c_eselon_iii_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_iv_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_v_cpns.disabled = "disabled" ;
		
	}
	
else if (esl=='05' || esl=='06')
	{
		document.getElementById('c_eselon_iv_cpns').value="";
		document.getElementById('c_eselon_v_cpns').value="";	
		document.forms[0].c_eselon_ii_cpns.disabled = false ;
		document.forms[0].c_eselon_iii_cpns.disabled = false ;
		document.forms[0].c_eselon_iv_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_v_cpns.disabled = "disabled" ;
		document.forms[0].c_eselon_ii_cpns.value = "" ;
	}
else if (esl=='07' || esl=='08')
	{
		document.getElementById('c_eselon_v_cpns').value="";	
		document.forms[0].c_eselon_ii_cpns.disabled = false ;
		document.forms[0].c_eselon_iii_cpns.disabled = false ;
		document.forms[0].c_eselon_iv_cpns.disabled = false ;
		document.forms[0].c_eselon_v_cpns.disabled = "disabled" ;
	}
else if (esl=='09')
	{
		document.forms[0].c_eselon_ii_cpns.disabled = false ;
		document.forms[0].c_eselon_iii_cpns.disabled = false ;
		document.forms[0].c_eselon_iv_cpns.disabled = false ;
		document.forms[0].c_eselon_v_cpns.disabled = false ;
	}
else	
	{
		document.forms[0].c_eselon_ii_cpns.disabled = false ;
		document.forms[0].c_eselon_iii_cpns.disabled = false ;
		document.forms[0].c_eselon_iv_cpns.disabled = false ;
		document.forms[0].c_eselon_v_cpns.disabled = false ;
	} 	
}
</script>