<?
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
$jmleseloniiiList=count($this->eseloniiiList);
	$eseloniiiList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleseloniiiList; $i++) {
		$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;
	}
	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii_cpns","onChange"=>"javascript:cariEselon('targetesliv')"); 
	echo $ctrlFrm->formSelect('c_eselon_iii_cpns',$this->c_eselon_iiii_cpns, $eslAtrib, $eseloniiiList); 		
?>
