<?
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
	$jmleselonvList=count($this->eselonvList);
	$eselonvList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleselonvList; $i++) {
		$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
	}
	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v_cpns");  	
	echo $ctrlFrm->formSelect('c_eselon_v_cpns',$this->c_eselon_v_cpns, null, $eselonvList); 	
?>
