<? require_once 'Zend/View.php';
   
$ctrlFrm = new Zend_View();
$jumpenghargaanList=count($this->penghargaanList);
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Penghargaan
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Penghargaan</h2>
<?php include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">		
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	  
<div class="add" title="Tambah Data" onclick="PengahargaanM('insert','');"></div>
<?}	if ($jumpenghargaanList == 0) {
		echo "<font color=\"red\">Data Penghargaan Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
		    <th width="20%" rowspan="2">Jenis Penghargaan</th>
			<th width="20%" rowspan="2">Nama Penghargaan</th>
			<th width="50%" colspan="3">Ketegori Lain-lain</th>
			<th width="6%" rowspan="2" colspan="2">&nbsp;</th>
		</tr>
		<tr>
			<th>Tahun</th>
			<th>Negara</th>
			<th>Lembaga Pemberi</th>
		</tr>
<?
	if ($jumpenghargaanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->penghargaanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
			
				<td>
					<a href="#" onclick="detilpenghargaan('<?=$nip?>','<?=trim($this->escape($val['n_jns_penghargaan']))?>')"><?php echo $this->escape($val['jenispenghargaan']);?></a>
				</td>
				<td><?php  echo $this->escape($val['namapenghargaan']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_tahun_alteratif']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['c_negara_alternatif']);?></td>
				<td><?php echo $this->escape($val['n_lembaga_alternatif']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="PengahargaanM('update','<?=trim($this->escape($val['i_peg_nip']))?>','<?=trim($this->escape($val['n_jns_penghargaan']))?>','<?=trim($this->escape($val['n_penghargaan']))?>');"></div>	
				</td>
 <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	 				
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataPenghargaan('<?=trim($this->escape($val['i_peg_nip']))?>','<?=trim($this->escape($val['n_jns_penghargaan']))?>','<?=trim($this->escape($val['n_penghargaan']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
