 <h2 class="accessibility">Navigation</h2><!--start nav-->
  <div id="nav">
	<ul class="nav">
		<li><a href="#keloladatatentangkami" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/tentangkami/listtentangkami','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');">Tentang Kami</a></li>
		<li><a href="#keloladatakontakkami" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kontakkami/listkontakkami','<?php echo $this->basePath; ?>/cmsmodule/kontakkami/kontakkamijs');">Kontak Kami</a></li>
		<li><a href="#keloladataagenda" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/agenda/listagenda','<?php echo $this->basePath; ?>/cmsmodule/agenda/agendajs');">Agenda Kegiatan</a></li>
		<li><a href="">Media<span class="sf-sub-indicator"> »</span></a>
			<ul>
				<li><a href="#keloladataberita" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/berita/listberita','<?php echo $this->basePath; ?>/cmsmodule/berita/beritajs');">Berita</a></li>
				<li><a href="#keloladatapengumuman" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/pengumuman/listpengumuman','<?php echo $this->basePath; ?>/cmsmodule/pengumuman/pengumumanjs');">Pengumuman</a></li>
			</ul>
		</li>
		<li><a href="#keloladataprodukhukum" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/produkhukum/listprodukhukum','<?php echo $this->basePath; ?>/cmsmodule/produkhukum/produkhukumjs');">Produk Hukum</a></li>
		<li><a href="#keloladatashoutbox" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/shoutbox/listshoutbox','<?php echo $this->basePath; ?>/cmsmodule/shoutbox/shoutboxjs');">Shoutbox</a></li>
		<li><a href="">Referensi<span class="sf-sub-indicator"> »</span></a>
			<ul>
				<li><a href="#kategoriprodukhukum" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kategoriprodukhukum/listkategoriprodukhukum','<?php echo $this->basePath; ?>/cmsmodule/kategoriprodukhukum/kategoriprodukhukumjs');">Kategori Produk Hukum</a></li>
			</ul>
		</li>
		<!--li class=""><a href="?module=user&t=user">Administrasi User</a></li-->
		</ul>
		</li>
	</ul>
 </div>		
<!--end nav-->
