<div id="backgroundPopup">
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td>
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>	
		<center>
		<div class="hideshow">
			<table width="100%">
				<tr>
					<td align="center">
					<?echo $this->judul;?>
					</td>
				</tr>
			</table>				
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						<?echo $this->chart;?>
						<table border="0" width="50%" align="center" class="tbl2">
							<tr>
								<th><25</th>
								<th>26 s/d 35</th>
								<th>36 s/d 45</th>
								<th>46 s/d 55</th>
								<th>>56</th>
							</tr>
							<tr class="event">
								<td align="right"><?=$this->jml25?></td>
								<td align="right"><?=$this->jml2635?></td>
								<td align="right"><?=$this->jml3645?></td>
								<td align="right"><?=$this->jml4655?></td>
								<td align="right"><?=$this->jml56?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>		
		</div>	
		</center>
	</div>
</div>	