<?php
function konversi_tanggal($format, $tanggal="now", $bahasa="id"){
 $en=array("Sun","Mon","Tue","Wed","Thu","Fri","Sat","Jan","Feb",
 "Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
 
 $id=array("Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu",
 "Januari","Pebruari","Maret","April","Mei","Juni","Juli","Agustus","September",
 "Oktober","November","Desember");
 
 // tambahan untuk bahasa prancis
 // sumber http://w.blankon.in/6V
 $fr = array("dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi",
 "janvier","février","mars","avril","Mei","mai","juillet","aoùt","septembre",
 "octobre","novembre","décembre");
 
 // mengganti kata yang berada pada array en dengan array id, fr (default id)
 return str_replace($en,$$bahasa,date($format,strtotime($tanggal)));
}
 
// //menampilkan tanggal saat ini
// //keluaran Tue, 26 Mar 2013
// echo date("D, j M Y")."<br/>";
 
// //menampilkan tanggal saat ini setelah di konversi
// //keluaran Minggu, 13 Maret 2011
// echo konversi_tanggal("D, j M Y")."<br/>";
 
// //menampilkan bulan saat ini
// //keluaran Maret
// echo konversi_tanggal("M")."<br/>";
 
// //menampilkan hari saat ini
// //keluaran Minggu
// echo konversi_tanggal("D")."<br/>";
 
// //konversi tanggal dari format tanggal di mysql
// //keluaran Jumat, 17 Agustus 1945
// echo konversi_tanggal("D, j M Y","1945-08-17")."<br/>";
 
// //konversi tanggal dari format tanggal di mysql
// //keluaran Jumat
// echo konversi_tanggal("D","1945-08-17")."<br/>";
 
// //konversi tanggal dari format tanggal di mysql
// //keluaran Agustus
// echo konversi_tanggal("M","1945-08-17")."<br/>";
 
// //konversi tanggal dari format dengan bahasa lain
// //keluaran dimanche, 17 avril 1988
// echo konversi_tanggal("D, j M Y","1988-04-17", "fr")."<br/>";
?>

 <div class="row">
	<div class="span8">
		<div class="title-divider">
			<h3>Berita</h3>
			<div class="divider-arrow"></div>
		</div>
	</div>
	<?php 
		 $jmlBeritaList = count($this->BeritaList);
		//echo $jmlBeritaList;
		for ($j = 0; $j < $jmlBeritaList; $j++) {
		 $berita[$j] = array("c_berita"  		=>(string)$this->BeritaList[$j]['c_berita'],
							"n_judul"      		=>(string)$this->BeritaList[$j]['n_judul'],
							 "n_detil"  		=>(string)$this->BeritaList[$j]['n_detil'],
							  "c_status"  		=>(string)$this->BeritaList[$j]['c_status'],
							  "d_berita"  		=>(string)$this->BeritaList[$j]['d_berita']);
	} 
	
	foreach ($berita as $key => $val): 
		$date= $this->escape($val['d_berita']);
		$date=konversi_tanggal("D, j M Y",$date);
	?>
	<article class="blog-post span8">
		<div class="block-grey">
			<div class="block-light">
				<div class="wrapper-img">
					<a href="./portfolio2.html"><img src="cimteng/slider3.jpg" alt="photo"/></a>
				</div>
				<div class="wrapper">
					<p class="tags">
						<?php echo $date ?>
					</p>
					<h2 class="post-title"><a href="#" onclick="detilBerita('<?php echo $this->escape($val['c_berita']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h2>
					<p>						
						 <?php echo substr($val['n_detil'], 0,450);?>
						<a href="#detailBerita" onclick="detilBerita('<?php echo $this->escape($val['c_berita']);?>')" class="read-more">[Selengkapnya]</a>
					</p>
					
				</div>
			</div>
		</div>
	</article>
	<?php endforeach;?>
	
</div>

<script>
function detilBerita(idberita){
	
	var url = '<?php echo $this->basePath; ?>/cmsmodule/berita/beritadetil';
	var param = {idberita:idberita};
	jQuery.get(url,param,function(data) {
	jQuery("#targetdetil").html(data);
	centerPopup();
	loadPopup();});
}
</script>