<? 
require_once 'Zend/View.php';
require_once 'share/tanggal.php'; 
   
$ctrlDate = new tanggal();   
   
   $ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 11;
   $thnList2 = $thnskrg - 55;
	
   $thnArrayList['#'] = '--';
   		
   for ($i = 0; $i < 21; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }

	
   $thnArrayList2['#'] = '--';
   	 
   for ($i = 0; $i < 60; $i++) {
     $thnList2 = $thnList2 + 1;
     $thnArrayList2[$thnList2] = $thnList2;
   }
		
		
   $pnjngArray = count($thnArrayList);

	  $blnList = 0;
	  for ($j = 0; $j < 12; $j++) {
        $blnList = $blnList + 1;
		if ($blnList < 10) {
		  $blnBaruList = "0".$blnList;
		  $blnArrayList[] = $blnBaruList;
		} else {
		  $blnBaruList = $blnList;
		  $blnArrayList[] = $blnBaruList;
		}
      }
		
	  $hrList = 0;
	  for ($k = 0; $k < 31; $k++) {
        $hrList = $hrList + 1;
		if ($hrList < 10) {
		  $hrBaruList = "0".$hrList;
		  $hrArrayList[] = $hrBaruList;
		} else {
		  $hrBaruList = $hrList;
		  $hrArrayList[] = $hrBaruList;
		}
      }

$nip = $_REQUEST['nip'];
$jumPendList = count($this->pendList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong>Personal Assessment
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>			

			<div style="overflow: hidden;">
				<div class="wrap">
					<div class="panel">
					<div class="inner">
						<span class="corners-top"><span></span></span>
						<h2 class="title">Personal Assessment</h2>
						<div class="spacer"></div> 
						<table border="0" cellpadding="0" cellspacing="1" class="std">

						<tr>
							<td width="2%">&nbsp;</td>
							<td>Eselon</td>
							<td>:</td> 
							<td>
							<?php 
								$eselonList = array("-"=>"--Pilih--",
											  "NE"=>"Non Eselon",
											  "MT"=>"Ketua Mahkamah",
											  "I.a"=>"I.a",
											  "I.b"=>"I.b",
											  "II.a"=>"II.a",
											  "III.a"=>"III.a",
											  "IV.a"=>"IV.a");
								echo $ctrlFrm->formSelect('eselon', $eselon, $eselonAtrib, $eselonList) ?>
							</td>
						</tr>							
						<tr>
							<td width="2%">&nbsp;</td>
							<td>Pendidikan</td>
							<td>:</td> 
							<td>
							<?php
								$jmljenjang = count($this->nmJenjangList);														   
								$jenjangReff[''] = '--Pilih--';
								for ($i = 0; $i < $jmljenjang; $i++) {
									$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
									$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;											   
								}
								$pendAtrib = array( "onblur" => "javascript:cPend();"); 
								echo $ctrlFrm->formSelect('c_pend',$this->c_pend,$pendAtrib,$jenjangReff);
								
							?>
							</td>
						</tr>	
							<tr>
								<td width="2%">&nbsp;</td>
								<td width="25%">Masa Kerja</td>
								<td width="2%">:</td> 
								<td>
									<input type="text" size="5">
								</td>
							</tr>
							<tr>
							<td width="2%">&nbsp;</td>
							<td>Gol / Pangkat</td>
							<td>:</td> 
							<td>					
								<?php 
									echo $ctrlFrm->formSelect('gol', $gol, null, $golList);
								?>
							</td>
							</tr>
							<tr>
								<td width="2%">&nbsp;</td>
								<td width="25%">Pelatihan</td>
								<td width="2%">:</td> 
								<td>
									<?php 
										echo $ctrlFrm->formSelect('gol', $gol, null, $golList);
									?>
								</td>
							</tr>
							<tr>
								<td width="2%">&nbsp;</td>
								<td width="25%">&nbsp;</td>
								<td width="2%">&nbsp;</td> 
								<td>
									<input type="button" value="Cari">
								</td>
							</tr>								
						</table>
						<div class="spacer"></div> 
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<?	if ($jumPendList == 0) {
		echo "<font color=\"red\">Data Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
				<tr>
			    <th width="25%">Nama</th>
				<th width="10%">NIP</th>
				<th width="45%">Unit Kerja</th>
				<th width="5%">Pilih</th>
				</tr>

<?
	if ($jumPendList == 0) {
?>				<tr class="event">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				</tr>
<? } else { ?>				
		<?php foreach ($this->pendList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } ?>
				<? 
					$nip=trim($this->escape($val['i_peg_nip']));
					$c_pend=trim($this->escape($val['c_pend']));
				?>
				<td width="6%">&nbsp;<? echo trim($this->escape($val['n_pend'])); ?> </td>
				<td width="20%">&nbsp;<?php echo ucwords(strtolower($this->escape($val['n_pend_lembaga'])));?></td>
				<td width="20%">&nbsp;<?php echo ucwords(strtolower($this->escape($val['n_pend_jurusan'])));?></td>
				<td class="clcenter" width="8%"> <?php echo $this->escape($val['d_pend_mulai']);?></td>
				<td class="clcenter" width="8%"> <?php echo $this->escape($val['d_pend_akhir']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="PendidikanM('update','<?=$c_pend?>');"></div>	
					<div class="delete" title="Hapus Data"  onClick="HapusDataPend('<?=$nip?>','<?=$c_pend?>')"></div>
				</td>
		  </tr>
	<?php endforeach;?> 	
	<? } ?>
	</table>									
						
									
									</fieldset>		 
									</form>
								<span class="corners-bottom"><span></span></span>
							</div>
						</div>
					</div>
			</div>
	