<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
	
	//var_dump($this->detailAgama);
?>

		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Formasi Kepegawaian<!--a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a-->
				<strong> &#8250; </strong><?//=$this->jdl;?> Formulir 3-R
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Formulir 3-R</h2>	
		
<form id="formformulir3r" method="post" name="formformulir3r">	
		<div align="center">REKAPITULASI KEBUTUHAN PNS PUSAT MENURUT JABATAN TAHUN ANGGARAN <span class="thn_skr"></span></div>
	<div class="panel">
		<div class="spacer"></div> 
			
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<!--tr>
					<td width="40%">UNIT ORGANISASI
					</td>
					<td width="1%">:</td> 
					<td width="59%">	
						<select name="unit_organisasi" id="unit_organisasi" onchange="AmbilUnit('<? echo $this->par; ?>',this.value);">
						<?if($this->unit_organisasi != ""){
							echo "<option value='".$this->unit_organisasi."'>".$this->unit_organisasi."</option>";?>
						 <option>Unit Kerja</option>
						<? 
						foreach ($this->listUnit as $key => $val):
							echo "<option value='".$this->escape($val['nama_satker'])."'>".$this->escape($val['nama_satker'])."</option>";
						endforeach;
						}else{
						?>
						<option>Unit Kerja</option>
						<? 
						foreach ($this->listUnit as $key => $val):
							echo "<option value='".$this->escape($val['nama_satker'])."'>".$this->escape($val['nama_satker'])."</option>";
						endforeach;
						}
						?> 
						 </select>
					</td>
				</tr--><tr><td colspan="3"><u>UNIT KERJA</u></td></tr><tr>
					<td>Lokasi
					</td>
					<td>:</td> 
					<td>	<input type="hidden" name="id" id="id" value="<? echo $this->id ?>">				
						<select name="lokasi" id="lokasi" onchange="AmbilLokasi('<?=$this->par; ?>');">
						<?if($this->c_lokasi != "" && $this->n_lokasi != ""){
							echo "<option value='".$this->c_lokasi.",".$this->n_lokasi."'>".$this->n_lokasi."</option>";?>
						 <option>--Pilih--</option>
						<? 
						foreach ($this->listLokasi as $key => $val):
							echo "<option value='".$this->escape($val['c_lokasi']).",".$this->escape($val['n_lokasi'])."'>".$this->escape($val['n_lokasi'])."</option>";
						endforeach;
						}else{
						?>
						<option>--Pilih--</option>
						<? 
						foreach ($this->listLokasi as $key => $val):
							echo "<option value='".$this->escape($val['c_lokasi']).",".$this->escape($val['n_lokasi'])."'>".$this->escape($val['n_lokasi'])."</option>";
						endforeach;
						}
						?> 
						 </select>
					</td>
				</tr><tr>
					<td>Eselon I
					</td>
					<td>:</td> 
					<td>	
						<select name="eselon1" id="eselon1" width="150" onchange="AmbilEselon1('<?=$this->par; ?>');">
						<?if($this->c_eselon1 != ""){
							echo "<option value='".$this->c_eselon1.",".$this->n_eselon1."'>".$this->n_eselon1."</option>";?>
						 <option>--Pilih--</option>
						<? 
						foreach ($this->listEselon1 as $key => $val):
							echo "<option value='".$this->escape($val['c_eselon_i']).",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						endforeach;
						}else{
						?>
						<option>--Pilih--</option>
						<? 
						foreach ($this->listEselon1 as $key => $val):
							echo "<option value='".$this->escape($val['c_eselon_i']).",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						endforeach;
						}
						?> 
						 </select>
					</td>
				</tr><tr>
					<td>Eselon II
					</td>
					<td>:</td> 
					<td>	
						<select name="eselon2" id="eselon2" width="150" onchange="AmbilEselon2('<?=$this->par; ?>')">
						<?if($this->c_eselon2 != ""){
							echo "<option value='".$this->c_eselon2.",".$this->c_eselon22.",".$this->n_eselon2."'>".$this->n_eselon2."</option>";?>
						 <option>--Pilih--</option>
						<? 
						foreach ($this->listEselon2 as $key => $val):
							echo "<option value='".$this->escape($val['c_eselon_ii']).",".$this->listEselon2[$key+1]['c_eselon_ii'].",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						endforeach;
						}else{
						?>
						<option>--Pilih--</option>
						<? foreach ($this->listEselon2 as $key => $val):
							echo "<option value='".$this->listEselon2[$key+1]['c_eselon_ii'].",".$this->escape($val['c_eselon_ii']).",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						   endforeach;
						 } ?>
						 </select>
					</td>
				</tr><tr>
					<td>Eselon III
					</td>
					<td>:</td> 
					<td>			
						<select name="eselon3" id="eselon3" width="150" onchange="AmbilEselon3('<?=$this->par; ?>')">
						<?if($this->c_eselon23 != ""){
							echo "<option value='".$this->c_eselon23.",".$this->c_eselon3.",".$this->n_eselon3."'>".$this->n_eselon3."</option>";?>
						 <option>--Pilih--</option>
						<? 
						foreach ($this->listEselon3 as $key => $val):
							echo "<option value='".$this->escape($val['c_eselon_ii']).",".$this->escape($val['c_eselon_iii']).",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						endforeach;
						}else{
						?>
						<option>--Pilih--</option>
						<? 
						foreach ($this->listEselon3 as $key => $val):
							echo "<option value='".$this->escape($val['c_eselon_ii']).",".$this->escape($val['c_eselon_iii']).",".$this->escape($val['n_unitkerja'])."'>".$this->escape($val['n_unitkerja'])."</option>";
						endforeach;
						}
						?> 
						 </select>
					</td>
				</tr><!--tr>
					<td>NAMA JABATAN
					</td>
					<td>:</td> 
					<td>					
						<select name="nm_jabatan" id="nm_jabatan" >
						<?if($this->nm_jabatan != ""){
							echo "<option value='".$this->c_jabatan.",".$this->nm_jabatan."'>".$this->nm_jabatan."</option>";?>
						 <option>Nama Jabatan</option>
						<? 
						foreach ($this->listNamaJabatan as $key => $val):
							echo "<option value='".$this->escape($val['c_jabatan']).",".$this->escape($val['n_jabatan'])."'>".$this->escape($val['n_jabatan'])."</option>";
						endforeach;
						}else{
						?>
						<option>Nama Jabatan</option>
						<? 
						foreach ($this->listNamaJabatan as $key => $val):
							echo "<option value='".$this->escape($val['c_jabatan']).",".$this->escape($val['n_jabatan'])."'>".$this->escape($val['n_jabatan'])."</option>";
						endforeach;
						}
						?> 
						 </select>
					</td>
				</tr--><tr><td colspan="3">&nbsp;</td></tr>
				<tr><td colspan="3" style="font-weight:bold">USUL TAMBAHAN PEGAWAI BARU TAHUN ANGGARAN <span class="thn_skr"></span> :</td></tr><tr>
					<td>PENDIDIKAN
					</td>
					<td>:</td> 
					<td>	<input type="hidden" name="thn_skrg" id="thn_skrg2">
						<input type="hidden" name="tahun" id="tahun">				
						<input type="text" name="pendidikan" id="pendidikan" value="<?=$this->detailFormulir3r['pendidikan'];?>" size="25" >
					</td>
				</tr><tr>
					<td>JURUSAN
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="jurusan" id="jurusan" value="<?=$this->detailFormulir3r['jurusan'];?>" size="25" >
					</td>
				</tr><tr>
					<td>GOL. RUANG
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="gol_ruang" id="gol_ruang" value="<?=$this->detailFormulir3r['gol_ruang'];?>" size="25" >
					</td>
				</tr><tr>
					<td>JML
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="jml" id="jml" value="<?=$this->detailFormulir3r['jml'];?>" size="25" >
					</td>
				</tr><tr><td colspan="3">&nbsp;</td></tr><tr>
					<td>KETERANGAN</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="ket" id="ket" value="<?=$this->detailFormulir3r['ket'];?>" size="25" >
					</td>
				</tr>
				<tr>
					<td align="left"></td>
					<td></td>
					<td>
						<div class="center">
							<input type="button" value="Batal" onclick="OpenFormulir3r();"> 
							<?if ($this->par == 'Insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertFormulir3r()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateFormulir3r()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
