<?echo $this->chartjmlpeg;?>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<tr>
<td align="center">
<a href="#"   onclick="showPortalChart('<?php echo $this->basePath; ?>/sdmmodule/portalchart/chartpendidikan','');">Pendidikan</a>
&nbsp;
<a href="#"   onclick="showPortalChart('<?php echo $this->basePath; ?>/sdmmodule/portalchart/chartgolongan','');">Golongan</a>
</td>
</tr>
</table>