<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/halaman_list.php'; 
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmPegList = count($this->PegawaiList);  
$halaman = new halaman_list();
$nom =$this->nom;
?>
<div id="backgroundPopup"></div>
	<div id="popupContact">
	<div class="panel" style="height: 550px;overflow: auto;border: solid 1px #000;padding: 5px;" >
<!--		
<form id="frmSearch" method="post" name="frmSearch">	
			<div class="search-panel">				
				Pencarian berdasarkan :
					<?
						$cCol = array(""=>"--Pilih--",
									"i_peg_nip"=>"NIP",
									"n_peg"=>"Nama",
									"unitkerja"=>"Unit Kerja",
									"c_golongan"=>"Golongan");
							$varUnit = array("onchange"=>"javascript:cariDataUnit('')");  								
							echo $ctrlFrm->formSelect('cCol', $this->cCol, $varUnit, $cCol); 							
					?>
					<span id="target" style="display:inline">
					<?if (trim($this->cCol)=='c_golongan'){include("combogolongan.phtml");}					
					else{
					if (trim($this->cCol)!='unitkerja'){
					?>
						<input type="text" name="nCol" id="nCol" value="<?echo $this->nCol?>" size="50">
					<?}}?>	
					</span>
					
				<?if (trim($this->cCol)=='unitkerja'){?>					
				<div id="targetcari" style="display:inline">
				<?}else{?>
				<div id="targetcari" style="display:none">
				<?}
				if ($this->c_lokasi_unitkerja=='1'){include("listcombo.phtml");}
				else{include("listcombo2.phtml");}
				?>
			</div>				
		<div class="search-panel">	
			<input type="submit" value="Cari" onclick="javascript:cariListPegawai();">
		</div>	
</form>
-->
<table width="100%" border="0" cellpadding="0" cellspacing="1" align="center">
<?
	$kategoriCari = array(""=>"--Pilih--",
						"i_peg_nip"=>"NIP Lama",
						"i_peg_nip_new"=>"NIP Baru",
						"n_peg"=>"Nama");
	echo $ctrlFrm->formSelect('kategoriCari', $this->kategoriCari, null, $kategoriCari);						
?>
	<input type="text" id="carii" name="carii" align="center" value ="<? echo $this->katakunciCari;?>">
	<input type="button" name="cari" value ="Search" onclick="javascript:unitkerjalist();">
	
				<?
			         //$atribSubmit = array("onclick"=>"javascript:unitkerjalist();");
			         //echo $ctrlFrm->formSubmit('cari', 'Search', $atribSubmit)."&nbsp;";
				?>
</table>
					<center>
					
					<div class="inner" id="targettbl">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
						<table width="80%">
						<tr>
						<td>
						<div class="delete" title="Close" onclick="closeDetil()"></div><h2>Daftar Pegawai</h2>
						   <table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
								<tr>
									<th width="4%">No.</th>
									<th width="10%">NIP</th>
									<th width="30%">Nama</th>
									<th width="15%">Jabatan</th>
								</tr> 
<? 		if (count($this->PegawaiList) == 0) {?>
								<tr class="event">
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
<?		}else{
				foreach ($this->PegawaiList as $key => $val):
$e_jabatan='';
$e_jabatan	= $this->escape($val['e_jabatan']);
  
										if ($key%2==0) { ?>
										<tr class="event">
										<? } else if ($key%2==1) { ?>
										<tr class="event2">
										<? } 
										$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
										?>
											<td class="clcenter"><?php echo $noUrut;?></td>
											<td><a href="#" onclick="pilihData('<?php echo $this->escape($val['i_peg_nip']);?>','<?php echo $this->escape($val['n_peg']);?>','<?php echo $this->escape($val['n_pangkat']);?>','<?php echo $this->escape($val['c_golongan']);?>','<?php echo $this->escape($val['c_peg_jeniskelamin']);?>','<? echo $nom;?>')"><?php echo $this->escape($val['i_peg_nip']);?></a></td>
											<td><?php echo $this->escape($val['n_peg']);?></td>
											<!--<td><?php echo $this->escape($val['n_golongan'])."/".$this->escape($val['n_pangkat']);?></td>-->
											<td><?php $e_jabatan;?></td>
										</tr>
<?php 
				endforeach;}
?>
						</table>
	
							
<?
$orderBy=$this->orderBy;
$modul = $this->basePath."/sdmmodule/tpm/listnamapejabat?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol&nom=$this->nom";
echo $halaman->halamanListPopup($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>
						</td>
						</tr>
						</table>
</center>						
						<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>


<script>
function pilihData(nip,nama,pangkat,golongan,jnkel,nom){
	document.getElementById('i_peg_nip_'+nom).value=nip;
	document.getElementById('n_peg_'+nom).value=nama;	
	document.getElementById('n_pangkat_'+nom).value=pangkat;
	document.getElementById('c_golongan_'+nom).value=golongan;
	var nipx=document.getElementById('nip').value;
	if(!nipx){nipx="''";}
	document.getElementById('nip').value="'"+nip+"',"+nipx;
	closeDetil();
}


function cariListPegawai(nom){
var cCol=document.getElementById('cCol').value;
var nCol=document.getElementById('nCol').value;
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listnamapejabatan';
var param = {cCol:cCol,nCol:nCol,nom:nom};
jQuery.get(url,param,function(data) {
jQuery("#popupview").html(data);
centerPopup();
loadPopup();
});}

function cariDataUnit(){

var cCol =document.getElementById('cCol').value;
if (cCol=='unitkerja'){
	$("#targetcari").css("display","block");
	$("#target").css("display","none");
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombo';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#targetcari").html(data);});	
}
else if (cCol=='c_peg_jeniskelamin'){
	$("#targetcari").css("display","none");
	$("#target").css("display","inline");
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/combojnskelamin';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#target").html(data);});

}
else if (cCol=='c_golongan'){
	$("#targetcari").css("display","none");
	$("#target").css("display","inline");
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/combogolongan';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#target").html(data);});

}
else if (cCol=='c_status_kepegawaian'){
	$("#targetcari").css("display","none");
	$("#target").css("display","inline");
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/combostatpegawai';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#target").html(data);});

}
else if (cCol=='c_eselon'){
	$("#targetcari").css("display","none");
	$("#target").css("display","inline");
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/comboeselon';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#target").html(data);});

}
else{
	$("#target").css("display","inline");
	$("#targetcari").css("display","none");	
	document.getElementById('nCol').value="";
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listtext';
	var param = {cCol:cCol};
	jQuery.get(url,param,function(data) {
	jQuery("#target").html(data);});		
}



}
function cariCombo3(){
	var c_lokasi_unitkerja=document.getElementById('c_lokasi_unitkerja').value;	
	var eseloni=document.getElementById('c_eselon_i').value;
	var eselonii=document.getElementById('c_eselon_ii').value;
	var eseloniii=document.getElementById('c_eselon_iii').value;
	var eseloniv=document.getElementById('c_eselon_iv').value;
	
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombo'; 
	var param = {c_lokasi_unitkerja:c_lokasi_unitkerja,eseloni:eseloni,eselonii:eselonii,eseloniii:eseloniii,eseloniv:eseloniv};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);
	});
} 
function cariCombonya(){
	var c_lokasi_unitkerja=document.getElementById('c_lokasi_unitkerja').value;	
	var eseloni=document.getElementById('c_eselon_i').value;
	var eselonii=document.getElementById('c_eselon_ii').value;
	var eseloniii=document.getElementById('c_eselon_iii').value;
	var eseloniv=document.getElementById('c_eselon_iv').value;	
	
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombo'; 
	var param = {c_lokasi_unitkerja:c_lokasi_unitkerja,eseloni:eseloni,eselonii:eselonii,eseloniii:eseloniii,eseloniv:eseloniv};
	jQuery.get(url, param, function(data) {
		jQuery("#listcombo").html(data);
	});
}
</script>