<table>	
	<tr>
		<td align="left" width="22%">Eselon I</td>
		<td align="left" width="2%">:</td> 
		<td align="left">		
			<input type="text" name="n_eselon_iy" id="n_eselon_iy" size="80" value="<?=$this->n_eselon_i?>">
		</td>
	</tr>
	<tr>
		<td align="left">Pengadilan Tk Banding</td>
		<td align="left">:</td> 
		<td align="left">	
			<input type="text" name="n_eselon_iiy" id="n_eselon_iiy" size="80" value="<?=$this->n_eselon_ii?>">
		</td>
	</tr>
	<tr>
		<td align="left">Pengadilan Tk I</td>
		<td align="left">:</td> 
		<td align="left">		
			<input type="text" name="n_eselon_iiiy" id="n_eselon_iiiy" size="80" value="<?=$this->n_eselon_iii?>">
		</td>
	</tr>
	<tr>
		<td align="left">Unit Kerja</td>
		<td align="left">:</td> 
		<td align="left">	
			<input type="text" name="n_eselon_ivy" id="n_eselon_ivy" size="80" value="<?=$this->n_eselon_iv?>">
		</td>
	</tr>
</table>	
