<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/listpenghargaan','<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/penghargaanjs');">Penghargaan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Penghargaan
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Penghargaan</h2>	
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
<form id="formpenghargaan" method="post" name="formpenghargaan">		
	<div class="panel">
		<div class="spacer"></div> 
						<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="30%">Jenis Tanda Jasa</td>
					<td width="2%">:</td> 
					<td>					
						<?php 
							$jmlJasaList = count($this->jnsPenghargaanList);
							for ($i = 0; $i < $jmlJasaList; $i++) {									
								if ($this->n_jns_penghargaan==(string)$this->jnsPenghargaanList[$i]->c_penghargaan){echo $this->jnsPenghargaanList[$i]->n_penghargaan;}
							}
						?>
					</td>
				</tr>
				<tr>
					<td>Nama Tanda Jasa</td>
					<td>:</td> 
					<td>						
						<?php 
							$jmlJasaList = count($this->tandaJasaList);
							for ($i = 0; $i < $jmlJasaList; $i++) {
								if ($this->n_penghargaan==$this->tandaJasaList[$i]->c_tandajasa){echo $this->tandaJasaList[$i]->n_tandajasa;}
							}
						?>						
						<input type="hidden" name="n_penghargaan2" id="n_penghargaan2" value="<?=$this->n_penghargaan?>">
					</td>
				</tr>
				<tr>
					<td colspan="3"><b>Nama Penghargaan Alternatif (Kategori Lain-lain)</b></td>
				</tr>
				<tr>
					<td>Tahun</td>
					<td>:</td> 
					<td>
						<?=$this->d_tahun_alteratif?>
					</td>
				</tr>
				<tr>
					<td>Negara</td>
					<td>:</td> 
					<td>
						<?php 
							$jmlNegaraList = count($this->negaraList);
							for ($i = 0; $i < $jmlNegaraList; $i++) {
								if ($this->c_negara_alternatif==$this->negaraList[$i]->c_negara){ echo  $this->negaraList[$i]->n_negara;}
							}
						?>	
					</td>
				</tr>
				<tr>
					<td>Lembaga Pemberi</td>
					<td>:</td> 
					<td>
						<?=$this->n_lembaga_alternatif?>
					</td>
				</tr>
				<tr>
					<td>Keterangan</td>
					<td>:</td> 
					<td>
					<?php 
						
						echo $this->e_keterangan;
					?>
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">		
				</tr>
						<tr>
							
							<td></td>
							<td>
								<div class="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/listpenghargaan','');"> 
							
								</div>
							</td>
						</tr>			
			</table>
	</div>
	</form>
</div>	
