<? 	
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tmt_golongan").datepicker();
		jQuery("#d_sk_golongan").datepicker();
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapangkat/listpangkat','<?php echo $this->basePath; ?>/sdmmodule/datapangkat/pangkatjs');">Kepangkatan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Riwayat Kepangkatan
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>
	<h2 class="title"><?=$this->jdl;?> Riwayat Kepangkatan</h2>	
						
	<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
				<form id="frmpangkat" method="post" name="frmpangkat">			
	<div class="panel">
		<div class="spacer"></div> 				
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
						<td width="25%">Pangkat</td>
						<td width="2%">:</td> 
					<td>					
					<?
						$jmlgolref = count($this->statusGolRef);												   
						for ($i = 0; $i < $jmlgolref; $i++) {
								if ($this->c_golongan==trim((string)$this->statusGolRef[$i]['c_peg_golongan'])){echo trim($this->statusGolRef[$i]['n_peg_pangkat']);} 
						}
					?>
					</td>
				</tr>
				<tr>
					<td>TMT Pangkat</td>
					<td>:</td> 
					<td>
						<?=$this->d_tmt_golongan?> 
					</td>
				</tr>
				<tr>
					<td>Jenis Kenaikan</td>
					<td>:</td> 
					<td>					
					<?php 
						$jenisList = array("-"=>"--Pilih--","KP"=>"Kenaikan Pangkat","KGB"=>"Kenaikan Gaji Berkala","CPNS"=>"Pengangkatan CPNS","PNS"=>"Pengangkatan PNS");	
						if ($this->c_jenis_naik=="KP"){echo "Kenaikan Pangkat";}
						elseif ($this->c_jenis_naik=="KGB"){echo "Kenaikan Gaji Berkala";}
						elseif ($this->c_jenis_naik=="CPNS"){echo "Pengangkatan CPNS";}
						elseif ($this->c_jenis_naik=="PNS"){echo "Pengangkatan PNS";}
						else{echo "-";}
						
					?>
					</td>
				</tr>
				<tr>
					<td>Masa Kerja Golongan</td>
					<td>:</td> 
					<td>
						<?=$this->q_masakerja_tahun?>
						&nbsp; tahun &nbsp;
						<?=$this->q_masakerja_bulan?>
						&nbsp; bulan
					</td>
				</tr>
				<tr>
					<td>Gaji Pokok</td>
					<td>:</td> 
					<td>
						<?=$this->v_gaji_pokok?>
					</td>
				</tr>
				<tr>
					<td>Surat Keputusan Pejabat</td>
					<td>:</td> 
					<td>
						<?=$this->i_sk_pejabat?>				
					</td>
				</tr>
				<tr>
					<td>Nomor Surat Keputusan</td>
					<td>:</td> 
					<td>
					 <?=$this->i_sk_golongan?>
					</td>
				</tr>
				<tr>
					<td>Tanggal SK</td>
					<td>:</td> 
					<td>
						<?=$this->d_sk_golongan?> 
					</td>
				</tr>
				
				<tr>
					<td>Keterangan</td>
					<td>:</td> 
					<td>
					<?php 
						echo $this->e_keterangan;
					?>
					</td>
				</tr>
</table>
</div>
<br>
<div class="panel">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">			
				</tr>
						<tr>
							<td></td>
							<td></td>
							<td>
								<div class="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapangkat/listpangkat','<?php echo $this->basePath; ?>/sdmmodule/datapangkat/pangkatjs');"> 
								</div>
							</td>
						</tr>			
			</table>
</div>			
			</form>
</div>