<?php 
require_once 'share/halaman_list.php'; 
$halaman = new halaman_list(); 
?>
<div id="backgroundPopup" >
	
	<div id="popupContact" style="height:300px; width:500px;" >
	<center>

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Help : NIP</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table>
			<form onsubmit="xajax_add('HELP','querynip',document.getElementById('keyd').value,document.getElementById('query_nip').value,document.getElementById('valantar').value,'','','','99');xjxmW.closeWindow();return false;" id="fd1" name="fd1" enctype="multipart/form-data" method="post">
			<table border="0" width="100%" class="table">
			<tbody>
				<tr>
					<td align="center" colspan="3" class="row1">
						<input type="radio" onclick="document.getElementById('valantar').value = '=';document.getElementById('val1').value = '';document.getElementById('val2').value = '';" checked="" value="=" id="tpnilai" name="tpnilai" tabindex="49'">Sama Persis&nbsp;
						<input type="radio" onclick="document.getElementById('valantar').value = '!=';document.getElementById('val1').value = '';document.getElementById('val2').value = '';" value="!=" id="tpnilai" name="tpnilai" tabindex="50">Selain&nbsp;
						<input type="radio" onclick="document.getElementById('valantar').value = 'like';document.getElementById('val1').value = '';document.getElementById('val2').value = '%';" value="Aw" id="tpnilai" name="tpnilai" tabindex="51">Awalan&nbsp;
						<input type="radio" onclick="document.getElementById('valantar').value = 'like';document.getElementById('val2').value = '';document.getElementById('val1').value = '%';" value="Ak" id="tpnilai" name="tpnilai" tabindex="52">Akhiran&nbsp;
						<input type="radio" onclick="document.getElementById('valantar').value = 'like';document.getElementById('val1').value = '%';document.getElementById('val2').value = '%';" value="%" id="tpnilai" name="tpnilai" tabindex="53">Mengandung&nbsp;
						<input type="hidden" value="" id="val1" name="val1">
						<input type="hidden" value="" id="val2" name="val1">
						<input type="hidden" value="=" id="valantar" name="valantar">
					</td>
				</tr>
				<tr>
					<td colspan="3" class="row">
						<select id="jnip" name="jnip">
							<option value="i_peg_nip_new">NIP Baru</option>
							<option value="i_peg_nip">NIP Lama</option>
						</select>
							: <input type="text" onkeypress="return justnumber(event)" tabindex="53" value="" name="nipnew" id="nipnew" size="30">
								<input type="button" onclick="if (document.getElementById('nipnew').value != '') { var jenis_nip = document.getElementById('jnip').value;var strg = document.getElementById('query_nip').value;   document.getElementById('query_nip').value = strg + ' ' + jenis_nip + ' ' + document.getElementById('valantar').value + '\'' + document.getElementById('val1').value + document.getElementById('nipnew').value + document.getElementById('val2').value + '\'';} document.getElementById('nipnew').value='';" value="Masukan!" tabindex="54" name="bt_input" id="bt_input">
					</td>
				</tr>
				<tr>
					<td align="center" colspan="3" class="row1">
						<textarea cols="70" rows="5" id="query_nip" name="query_nip"></textarea>
					</td>
				</tr>
				<tr class="row1">
					<td align="left" colspan="2">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="55" name="bt1">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {  document.getElementById('query_nip').value = ' OR ';} else {document.getElementById('query_nip').value = strg + ' OR ';}" value=" OR " tabindex="56" name="bt0">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') {  document.getElementById('query_nip').value = ' AND ';} else {document.getElementById('query_nip').value = strg + ' AND ';}" value=" AND " tabindex="57" name="bt2">
						&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt2">
					</td>
					<td align="right">
						<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg; closeDetil();}" value="OK !" tabindex="58" name="bt3">
					</td>
				</tr>
			<!--	
				<tr>
					<td align="center" colspan="3" class="row">&nbsp;</td>
				</tr>
				<tr>
					<td align="center" colspan="3" class="text">Nama / NIP <input type="text" tabindex="59" value="" name="keyd" id="keyd" size="30">
						<input type="button" onclick="xajax_add('HELP','querynip',document.getElementById('keyd').value,document.getElementById('query_nip').value,document.getElementById('valantar').value,'','','','99');xjxmW.closeWindow();return false;" value="C a r i" tabindex="60" name="submit">
					</td>
				</tr>
				<tr class="tdfield">
                                        <td align="center" width="2%" height="20">No.</td>
                                        <td align="center" width="48%">Nama</td>
					<td align="center" width="50%">NIP</td>
                                </tr>
			-->	
			</tbody>
			</table>              
			<input type="hidden" value="" id="nippenampungan" name="nippenampungan">
			<input type="hidden" value="" id="jnippenampungan" name="jnippenampungan">
			</form>
	</center>		
	* <span class="text1">Harus diisi</span>
	</div>
	
	
</div>	