<div id="backgroundPopup" >
	<center>
	<div id="popupContact" style="height:350px; width:800px;" >
	
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
			<tr class="event">
				<td align="left">
					<h3>Pangkat</h3>
				</td>
				<td align="right">
					<div class="delete" title="Close" onclick="closeDetil()"></div>
				</td>
			</tr>
		</table
		<table width="100%" border="0" align="center" class="tabless">
			<tbody>
				<tr>
					<form onsubmit="xjxmW.closeWindow(' .  . ')xajax_add('HELP','querypangkat',document.getElementById('keyd').value);return false;" id="fd1" name="fd1" enctype="multipart/form-data" method="post">
					<table width="100%" border="0" class="table">			
					<tbody>
					<tr>
						<td align="center" class="row1">
							<table width="100%">
								<tr>
									<td width="20%">									
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="01" id="jns_darah[]" name="jns_darah[]">&nbsp;IV/e&nbsp;[01]&nbsp;&nbsp;&nbsp;
									</td>
									<td width="20%">
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="02" id="jns_darah[]" name="jns_darah[]">&nbsp;IV/d&nbsp;[02]&nbsp;&nbsp;&nbsp;
									</td>
									<td width="20%">	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="03" id="jns_darah[]" name="jns_darah[]">&nbsp;IV/c&nbsp;[03]&nbsp;&nbsp;&nbsp;
									</td>
									<td width="20%">
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="04" id="jns_darah[]" name="jns_darah[]">&nbsp;IV/b&nbsp;[04]&nbsp;&nbsp;&nbsp;
									</td>
								
									<td width="20%">
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="05" id="jns_darah[]" name="jns_darah[]">&nbsp;IV/a&nbsp;[05]&nbsp;&nbsp;&nbsp;<br>
									</td>
								</tr>
								<tr>	
									<td>
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="06" id="jns_darah[]" name="jns_darah[]">&nbsp;III/d&nbsp;[06]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="07" id="jns_darah[]" name="jns_darah[]">&nbsp;III/c&nbsp;[07]&nbsp;&nbsp;&nbsp;
									</td>
									<td>
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="08" id="jns_darah[]" name="jns_darah[]">&nbsp;III/b&nbsp;[08]&nbsp;&nbsp;&nbsp;
									</td>
									
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="09" id="jns_darah[]" name="jns_darah[]">&nbsp;III/a&nbsp;[09]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="10" id="jns_darah[]" name="jns_darah[]">&nbsp;II/d&nbsp;[10]&nbsp;&nbsp;&nbsp;<br>
									</td>
								</tr>
								<tr>	
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="11" id="jns_darah[]" name="jns_darah[]">&nbsp;II/c&nbsp;[11]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="12" id="jns_darah[]" name="jns_darah[]">&nbsp;II/b&nbsp;[12]&nbsp;&nbsp;&nbsp;
									</td>
									
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="13" id="jns_darah[]" name="jns_darah[]">&nbsp;II/a&nbsp;[13]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="14" id="jns_darah[]" name="jns_darah[]">&nbsp; I/d&nbsp;[14]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="15" id="jns_darah[]" name="jns_darah[]">&nbsp; I/c&nbsp;[15]&nbsp;&nbsp;&nbsp;<br>
									</td>
								</tr>
								<tr>	
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="16" id="jns_darah[]" name="jns_darah[]">&nbsp; I/b&nbsp;[16]&nbsp;&nbsp;&nbsp;
									</td>
									<td>	
										<input type="checkbox" onclick="if (this.checked == true) {document.getElementById('jumlahcek').value = eval(parseInt(document.getElementById('jumlahcek').value) + 1)} else {document.getElementById('jumlahcek').value = eval(document.getElementById('jumlahcek').value - 1)}" value="17" id="jns_darah[]" name="jns_darah[]">&nbsp; I/a&nbsp;[17]&nbsp;&nbsp;&nbsp;
									</td>
								</tr>		
						</td>
					</tr>
					<tr>
						<td>
							<a class="link7" onclick="check_all(document.getElementsByName('jns_darah[]'),'',true);document.getElementById('jumlahcek').value= '17'" href="#">Check</a> - <a class="link7" onclick="check_all(document.getElementsByName('jns_darah[]'),'',false);document.getElementById('jumlahcek').value= '0'" href="#">Uncheck</a>	
							<input type="hidden" value="0" id="jumlahcek" name="jumlahcek"> 
						</td>
					</tr>		

					<tr>
						<td align="center" colspan="3" class="row">
							<input type="button" onclick="if (parseInt(document.getElementById('jumlahcek').value) &gt; 0) {var strg = document.getElementById('query_nip').value; var rstdrh = check_all(document.getElementsByName('jns_darah[]'),document.getElementById('jumlahcek').value,true); if (strg != 'AND ' || strg != 'OR ') {document.getElementById('query_nip').value = strg + ' c_golongan IN (' + rstdrh + ') ';} else {document.getElementById('query_nip').value = document.getElementById('query_nip').value + ' c_golongan IN (' + rstdrh + ') ';}}" value="Masukan!" tabindex="55" name="bt_input" id="bt_input">
						</td>
					</tr>
					<tr>
						<td align="center" colspan="3" class="row1">
							<textarea cols="80" rows="5" id="query_nip" name="query_nip"></textarea>
						</td>
					</tr>
					<tr class="row1">
						<td align="left" colspan="2">
							&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + '(';" value=" ( " tabindex="56" name="bt1">
							&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') { document.getElementById('query_nip').value = 'OR ';} else if (strg == 'AND ') {document.getElementById('query_nip').value = 'OR ';}" value=" OR " tabindex="56" name="bt0">
							&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg == '') { document.getElementById('query_nip').value = 'AND ';} else if (strg == 'OR ') {document.getElementById('query_nip').value = 'AND ';}" value=" AND " tabindex="57" name="bt2">
							&nbsp;&nbsp;&nbsp;<input type="button" onclick="var strg = document.getElementById('query_nip').value; document.getElementById('query_nip').value = document.getElementById('query_nip').value + ')';" value=" ) " tabindex="57" name="bt3">
						</td>
						<td align="right">
							<input type="button" onclick="var strg = document.getElementById('query_nip').value; if (strg != '') {document.getElementById('query_result').value = document.getElementById('query_result').value + ' ' + strg;closeDetil()}" value="OK !" tabindex="58" name="bt3">
						</td>
					</tr>
					</tbody>
				</table>      
			</form>
			
			</fieldset>
			</td></tr>
			</tbody></table>  
			</form>
	</div>
	</center>
</div>	