<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
	<tr>
		<td width="10%">Query</td>
		<td width="2%">:</td>
		<td><textarea rows="3" name="query_result" id="query_result" readonly></textarea></td>
	</tr>
</table>
<div class="panel">
	<div class="spacer"></div> 	
	<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">	
			<tr>
				<td align="center">
					<input class="btn" value="Bersih" onclick="document.getElementById('query_result').value= ''" type="button">
					<input class="btn" value="Cetak" onclick="cetakVSerA()" type="submit">
					<!--<input class="btn" value="Cetak excel" onclick="document.getElementById('tipe').value=2;return form_submit();" type="submit">-->
				</td>
			</tr>
	</table>	
</div>