	<div class="left">
		<div id="targetdatadirion" style="display:block">
			<a href="#datadiri" onclick="showFormDiri();"><img src="../../images/open-page.gif" title="buka"></a>&nbsp;&nbsp;Data Diri
		</div>	
		
		<div id="targetdatadirioff" style="display:none">
			<a href="#datadiri" onclick="hideFormDiri();"><img src="../../images/close-page.gif" title="buka"></a>&nbsp;&nbsp;Data Diri
		</div>	
		
		<div id="targetdatadiri" style="display:none">
			<table border="0" width="100%">
				<tr>
					<td width="5%">&nbsp;</td>
					<td width="95%">
					<div class="tabtxt">
						<a href="#" onclick="viewPopupDtDiri('bynama')">Nama</a>					
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bynip')">NIP</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byjnskelamin')">Jenis Kelamin</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bygoldarah')">Golongan Darah</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byagama')">Agama</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bypendidikan')">Tingkat Pendidikan</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bypimakhir')">Pim Terakhir</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byeselon')">Eselon</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byjabatan')">Jabatan Terakhir</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bykelfung')">Kelompok Fungsional</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bypangkat')">Pangkat</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bynikah')">Status Nikah</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bylahir')">Kelahiran</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byalamat')">Alamat</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('bykartu')">No. Kartu</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byidentitas')">Identitas Lain</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byunitkerja')">Unit Kerja</a>	
<!--						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byeseloni')">Eselon I</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byeselonii')">Eselon II</a>
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byeseloniii')">Eselon III</a>						
					&nbsp;|&nbsp;
						<a href="#" onclick="viewPopupDtDiri('byeseloniv')">Eselon IV</a>
-->						
					</div>		
					</td>
				</tr>

			</table>
		</div>
	</div>
<!--	
	<div class="left">
		<div id="targetdatariwayaton" style="display:block">
			<a href="#datadiri" onclick="showFormRiwayat();">
				<img src="../../images/open-page.gif" title="buka"></a>&nbsp;&nbsp;Riwayat
		</div>
		
		<div id="targetdatariwayatoff" style="display:none">
			<a href="#datadiri" onclick="hideFormRiwayat();">
				<img src="../../images/close-page.gif" title="buka"></a>&nbsp;&nbsp;Riwayat
		</div>	
		<div id="targetdatariwayat" style="display:none">
		<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
				<tr>
					<td width="5%">&nbsp;</td>
					<td width="95%">Pendidikan</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Jabatan</td>
				</tr>
				<tr>			
					<td>&nbsp;</td>
					<td>Pangkat</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Penghargaan</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Organisasi</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Luar Negeri</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Sanksi/Hukuman</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Diklat Pim</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Diklat Teknis</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Diklat Fungsional</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Istri/Suami</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Anak</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Orang Tua</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>Saudara</td>
				</tr>

			</table>				
		</div>		
	</div>
-->	
<div id="popupview"></div>