<tr>
	<td width="25%">NIP Lama<span class="hightlight">*</span></td>
	<td width="2%">:</td>
	<td>
		<input type="text" size="25" maxlength="9" name="i_peg_nip" id="i_peg_nip" <?echo $readonly?> value="<?=$this->i_peg_nip?>">
		<input type="hidden" size="25" maxlength="9" name="i_peg_nrp" id="i_peg_nrp" <?echo $readonly?> value="<?=$this->i_peg_nrp?>">
	</td>
</tr>
<tr>
	<td>NIP Baru</td>
	<td>:</td>
	<td>
		<input type="text" size="25" maxlength="18" name="i_peg_nip_new" id="i_peg_nip_new" <?echo $readonly?> value="<?=$this->i_peg_nip_new?>">
	</td>
</tr>