<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->

<head>
	<?php echo $this->render('partials/head-cimsel.phtml'); ?>
</head>
	

<body>

<!-- top menu -->
<section id="top-menu">
    <div class="container">
        <div class="row">
            <div class="span6 hidden-phone">
                <ul class="top-menu">
                    <li><a href="./index.html">Home</a></li>
                    <li><a href="#">Sitemap</a></li>
                    <li><a href="#">Shorcodes</a></li>
                    <li><a href="#" class="last">Contact</a></li>
                </ul>
            </div>
            <div class="span6">
                <ul class="top-social">
                    <li><a href="#" class="twitter2"></a></li>
                    <li><a href="#" class="facebook"></a></li>
                    <li><a href="#" class="google last"></a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- header -->
<header id="header">
    <div class="container">
        <div class="row">
            <div class="span4 logo">
                <a href="./index.html"><img src="images/logo.png" alt="logo"/></a>
            </div>
            <div class="span8 hidden-phone">
                <a href="./index.html" class="alignright banner">
                    <img src="images/banner-468-60.gif" alt="">
                </a>
            </div>
        </div>
        <nav id="menu">
            <ul class="clearfix">
                <li><a href="./index.html" class="current">Home</a></li>
                <li><a href="./about.html">Page</a>
                    <ul>
                        <li><a href="./about.html">About Us</a></li>
                        <li class="last"><a href="./services.html" >Our Services</a></li>
                    </ul>
                </li>
                <li><a href="./portfolio2.html" >Portfolio</a>
                    <ul>
                        <li><a href="./portfolio2.html">Portfolio 2 col</a>
                            <ul>
                                <li><a href="./portfolio2.html">Portfolio 2 Columns</a></li>
                                <li class="last"><a href="./portfolio2ex.html">Portfolio 2 Columns Extended</a></li>
                            </ul>
                        </li>
                        <li><a href="./portfolio3.html">Portfolio 3 col</a>
                            <ul>
                                <li><a href="./portfolio3.html">Portfolio 3 Columns</a></li>
                                <li class="last"><a href="./portfolio3ex.html">Portfolio 3 Columns Extended</a></li>
                            </ul>
                        </li>
                        <li class="last"><a href="./portfolio4.html">Portfolio 4 col</a>
                            <ul>
                                <li><a href="./portfolio4.html">Portfolio 4 Columns</a></li>
                                <li class="last"><a href="./portfolio4ex.html">Portfolio 4 Columns Extended</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="./blog.html">Blog</a>
                    <ul>
                        <li><a href="./blog.html">Blog</a></li>
                        <li class="last"><a href="./blog-single.html">Blog Single</a></li>
                    </ul>
                </li>
                <li><a href="./contact.html" >Contact</a></li>
            </ul>
        </nav>
    </div>
</header>

<!-- container -->
<section id="container">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="row">
                    <!-- page content -->
                    <section id="page-sidebar" class="alignleft span8">
                        <!-- slider -->
                        <div class="row">
                            <div class="span8">
                                <div id="mainslider" class="flexslider">
                                    <ul class="slides">
                                        <li>
                                            <img src="example/slider1.jpg" alt="photo" />
                                            <h3><span>Lorem Ipsum Dolor Sit Amet</span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                        <li>
                                            <img src="example/slider2.jpg" alt="photo" />
                                            <h3><span>Fusce consequat eleifend diam </span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                        <li>
                                            <img src="example/slider3.jpg" alt="photo" />
                                            <h3><span>Donec elementum tortor</span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- content -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Berita</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="./portfolio2.html"><img src="example/latest1.jpg" alt="photo"/></a>
                                        <div class="wrapper">
                                            <h2 class="post-title"><a href="#">Lorem ipsum</a></h2>
                                            <a href="#" class="blog-comments">3</a>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                                sed diam nonummy nibh euismod tdolore mag quam erat volutpat.
                                                <a href="#" class="read-more">[...]</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="./portfolio2.html"><img src="example/latest2.jpg" alt="photo"/></a>
                                        <div class="wrapper">
                                            <h2 class="post-title"><a href="#">Lorem ipsum</a></h2>
                                            <a href="#" class="blog-comments">3</a>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                                sed diam nonummy nibh euismod tdolore mag quam erat volutpat.
                                                <a href="#" class="read-more">[...]</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="./portfolio2.html"><img src="example/latest3.jpg" alt="photo"/></a>
                                        <div class="wrapper">
                                            <h2 class="post-title"><a href="#">Lorem ipsum</a></h2>
                                            <a href="#" class="blog-comments">3</a>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                                sed diam nonummy nibh euismod tdolore mag quam erat volutpat.
                                                <a href="#" class="read-more">[...]</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="./portfolio2.html"><img src="example/latest5.jpg" alt="photo"/></a>
                                        <div class="wrapper">
                                            <h2 class="post-title"><a href="#">Lorem ipsum</a></h2>
                                            <a href="#" class="blog-comments">3</a>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                                                sed diam nonummy nibh euismod tdolore mag quam erat volutpat.
                                                <a href="#" class="read-more">[...]</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        </div>
                        <!-- special offer -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Special Offer</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
                            <div class="span8">
                                <div class="block-grey wrap15">
                                    <section id="welcome">
                                        <div class="row">
                                            <div class="span5">
                                                <h1>Lorem Ipsum Dolor Sit Amet</h1>
                                                <p class="last">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut lagna aliquam erat volutpat.</p>
                                            </div>
                                            <div class="span2 clearfix">
                                                <a class="btn btn-success btn-large" href="#">Buy Now</a>
                                            </div>
                                        </div>


                                    </section>
                                </div>
                            </div>
                            <div class="spacer"></div>
                        </div>
                        <!-- education news -->
                        <div class="row">
                            <div class="span8 education-news">
                                <div class="title-divider">
                                    <h3>Education News</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                                <div class="block-grey">
                                    <div class="block-light wrap15">
                                        <div class="row">
                                            <div class="span2">
                                                <a href="./portfolio2.html"><img alt="photo" src="example/latest6.jpg"></a>
                                            </div>
                                            <div class="span5">
                                                <h2 class="post-title"><a href="#">Lorem ipsum</a></h2>
                                                <a class="blog-comments" href="#">3</a>
                                                <p>
                                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tdolore mag quamr sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tdolore mag quam erat volutpat.
                                                    <a class="read-more" href="#">[...]</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="wrap15 clearfix">
                                        <div class="percent-50">
                                            <ul class="color2 list-style-2">
                                                <li>Lorem ipsum dolor sit amet, consectetuer</li>
                                                <li>Sed diam nonummy nibh euismod tdolore</li>
                                                <li>Sit amet, consectetuer adipiscing elit, sed</li>
                                                <li>Nummy nibh euismod tdolore mag quam</li>
                                            </ul>
                                        </div>
                                        <div class="percent-50">
                                            <ul class="color2 list-style-2">
                                                <li>Lorem ipsum dolor sit amet, consectetuer</li>
                                                <li>Sed diam nonummy nibh euismod tdolore</li>
                                                <li>Sit amet, consectetuer adipiscing elit, sed</li>
                                                <li>Nummy nibh euismod tdolore mag quam</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="spacer"></div>
                        </div>
                        <!-- portfolio slider -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Portfolio Slider</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
                            <div class="span8">
                                <div class="block-grey our-portfolio">
                                    <div class="block-light wrap10">
                                        <div id="latest-work" class="carousel btleft">
                                        <div class="carousel-wrapper">
                                            <ul class="da-thumbs-folio">
                                                <li>
                                                    <img src="example/latest1.jpg" />
                                                    <h3>Creative Ideas</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <img src="example/latest2.jpg" />
                                                    <h3>Twitter? or...</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <img src="example/latest3.jpg" />
                                                    <h3>water painting</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <img src="example/latest4.jpg" />
                                                    <h3>Creative Ideas</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <img src="example/latest5.jpg" />
                                                    <h3>Creative Ideas</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                                <li>
                                                    <img src="example/latest6.jpg" />
                                                    <h3>Creative Ideas</h3>
                                                    <div>
                                                        <a href="example/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                        </div>
                                        <script type="text/javascript">
                                            $(document).ready(function(){
                                                $('#latest-work').elastislide({
                                                    imageW  : 235,
                                                    margin  : 10
                                                });
                                            });
                                        </script>
                                    </div>

                                    <div class="short-text">
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh eui
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- sidebar -->
                    <aside id="sidebar" class="alignright span4">
                        <!-- Search -->
                        <section class="search clearfix">
                            <form id="search" class="input-append">
                                <input class="" id="appendedInputButton" size="16" type="text" value="Search..." name="search site"
                                          onfocus="if(this.value=='Search...') this.value=''" onblur="if(this.value=='') this.value='Search...'"/>
                                <input class="btn search-bt" type="submit" name="submit" value="" />
                            </form>
                        </section>
                        <!-- Tabs -->
                        <section class="block-grey">
                            <!-- Tabs navigation -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#blog" data-toggle="tab">Berita Terbaru</a></li>
                                <li><a href="#archives" data-toggle="tab">Agenda</a></li>
                                <li><a href="#comments" data-toggle="tab">Comments</a></li>
                            </ul>
                            <!-- Tabs content -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="blog">
                                    <section class="post-widget">
                                        <ul class="clearfix">
                                            <li>
                                                <div class="avatar">
                                                    <a href="#"><img src="example/sidebar1.jpg" alt="photo"/></a>
                                                </div>
                                                <div class="description">
                                                    <p><a href="blog-single.html">Etiam sagittis purus quis neque pharetra pretium tempor</a></p>
                                                    <span class="date"><em>12 Apr 2012, 3 comments</em></span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>
                                            <li>
                                                <div class="avatar">
                                                    <a href="#"><img src="example/sidebar2.jpg" alt="photo"/></a>
                                                </div>
                                                <div class="description">
                                                    <p><a href="blog-single.html">Maecenas malesuada convallis varius. Duis nec luctus leo nam venenatis</a></p>
                                                    <span class="date"><em>12 Apr 2012, 3 comments</em></span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>
                                            <li>
                                                <div class="avatar">
                                                    <a href="#"><img src="example/sidebar3.jpg" alt="photo"/></a>
                                                </div>
                                                <div class="description">
                                                    <p><a href="blog-single.html">Donec feugiat luctus sem malesuada sodales praesent rutrum enim eget</a></p>
                                                    <span class="date"><em>12 Apr 2012, 3 comments</em></span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="archives">
                                    <section class="blog-category">
                                        <ul class="ul-col1 clearfix">
                                            <li><a href="#">February 2012</a></li>
                                            <li><a href="#">March 2012</a></li>
                                            <li><a href="#">April 2012</a></li>
                                            <li><a href="#">May 2012</a></li>
                                            <li><a href="#">June 2012</a></li>
                                            <li><a href="#">August 2012</a></li>
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="comments">
                                    <section class="recent-comments">
                                        <ul class="clearfix">
                                            <li><a href="#">Admin</a> on <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                            <li><a href="#">ShmitAcc</a> on <a href="#">Lorem Ipsum Sed Ut</a></li>
                                            <li><a href="#">Admin</a> on <a href="#">Lorem Ipsum Sed Ut</a></li>
                                            <li><a href="#">Admin</a> on <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                            <li><a href="#">ShmitAcc</a> on <a href="#">Lorem Ipsum Sed Ut</a></li>
                                        </ul>
                                    </section>
                                </div>
                            </div>
                        </section>
                        <!-- Video block -->
                        <div class="title-divider">
                            <h3>Video</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="block-dark">
                            <div class="video">
                                <iframe src="http://player.vimeo.com/video/7449107" width="" height="" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </section>
                        <!-- Advertisment -->
                        <div class="title-divider">
                            <h3>Advertisment</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="block-dark">
                            <img src="images/adv.gif" alt=""/>
                        </section>
                        <!-- Recent Posts -->
                        <div class="title-divider">
                            <h3>Recent Posts</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="post-widget block-grey">
                            <ul class="clearfix block-light wrap15">
                                <li>
                                    <a href="#"><img src="example/sidebar1.jpg" alt="photo"/></a>
                                    <a href="#">Ut in lacus rhoncus elit egesta sluctus. Nullam at</a>
                                    <p><em>12 Apr 2012, 3 comments</em></p>
                                    <div class="clear"></div>
                                </li>
                                <li>
                                    <a href="#"><img src="example/sidebar2.jpg" alt="photo"/></a>
                                    <a href="#">Ut in lacus rhoncus elit egesta sluctus. Nullam at</a>
                                    <p><em>12 Apr 2012, 3 comments</em></p>
                                    <div class="clear"></div>
                                </li>
                                <li>
                                    <a href="#"><img src="example/sidebar3.jpg" alt="photo"/></a>
                                    <a href="#">Ut in lacus rhoncus elit egesta sluctus. Nullam at</a>
                                    <p><em>12 Apr 2012, 3 comments</em></p>
                                    <div class="clear"></div>
                                </li>
                            </ul>
                        </section>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>

<!--footer-->
<footer id="footer">
    <div class="container">
    <div class="row">
        <div class="span4">
            <h3>Flickr Photos</h3>
            <ul class="flickr clearfix"></ul>
        </div>
        <div class="span4">
            <h3>Last Tweet</h3>
            <div id="twitter-foot"></div>
        </div>
        <div class="span4">
            <h3>Contact Form</h3>
            <form id="contact" class="form-horizontal" method="post">
                <div class="controls">
                    <input type="text" id="inputName" placeholder="Name" name="inputName">
                    <label class="ferror" for="inputName" id="fname_error">Name is required.</label>
                </div>
                <div class="controls">
                    <input type="text" id="inputEmail" placeholder="Email" name="inputEmail">
                    <label class="ferror" for="inputEmail" id="femail_error">Email is required.</label>
                </div>
                <div class="controls">
                    <textarea rows="3" id="inputMessage" placeholder="Message" name="inputMessage"></textarea>
                    <label class="ferror" for="inputMessage" id="fmessage_error">Message is required.</label>
                </div>
                <div class="controls">
                    <input type="submit" class="btn btn-success btn-large footer-button" value="Submit">
                </div>
            </form>
        </div>
    </div>
    </div>
</footer>

<!--footer menu-->
<section id="footer-menu">
    <div class="container">
        <div class="row">
            <p class="span12"><span>&copy; Copyright 2012, <span class="color2">CITYpress</span> | All Rights Reserved</span></p>
        </div>
    </div>
</section>
</body>
</html>
