<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<?php include "partials/konversi_tanggal.php " ?>
<head>
	<?php echo $this->render('partials/head-cimsel.phtml'); ?>
</head>
	

<body>

<!-- top menu -->
<section id="top-menu">
    <div class="container">
        <div class="row">
            <div class="span6 hidden-phone">
                <ul class="top-menu">
                    <li><a href="<? echo $this->basePath; ?>">Home</a></li>
                    <li><a href="#">Sitemap</a></li>
                    <li><a href="#kontak kami" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kontakkami/cmskontakkami','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');" class="last">Kontak</a></li>
                </ul>
            </div>
            <div class="span6">
                <ul class="top-social">
                    <li><a href="#" class="twitter2"></a></li>
                    <li><a href="#" class="facebook"></a></li>
                    <li><a href="#" class="google last"></a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- header -->
<header id="header">
    <div class="container">
        <div class="row">
            <div class="span4 logo">
                <a href="<? echo $this->basePath; ?>"><img src="cimteng/logo.png" alt="logo"/></a>
            </div>
            <div class="span8 hidden-phone">
                <a href="<? echo $this->basePath; ?>" class="alignright banner">
                    <img src="images/banner-468-60.gif" alt="">
                </a>
            </div>
        </div>
        <nav id="menu">
            <ul class="clearfix">
                <li><a href="<? echo $this->basePath; ?>" class="current">Home</a></li>
                <li><a href="#Tentang Kami" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/tentangkami/about','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');">Tentang Kami</a>
                </li>
                <li><a href="#produk hukum" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/produkhukum/cmsprodukhukum','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');" >Produk Hukum</a>                   
                <li><a href="#pengumuman" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/pengumuman/cmspengumuman','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');" >Pengumuman</a>                   
                </li>
                <li><a href="#berita" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/berita/cmsberita','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');">Berita</a>                   
                </li>
                <li><a href="#kontak kami" onclick="open_url_to_div('<?php echo $this->basePath; ?>/cmsmodule/kontakkami/cmskontakkami','<?php echo $this->basePath; ?>/cmsmodule/tentangkami/tentangkamijs');">Kontak Kami</a></li>
            </ul>
        </nav>
    </div>
</header>

<!-- container -->

<div id="loading"></div>

<section id="container">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="row">
                    <!-- page content -->
					<!-- isi halaman -->
                    <section id="page-sidebar" class="alignleft span8">
                        <!-- slider -->
						<div id="tableview">
                        <div class="row">
                            <div class="span8">
                                <div id="mainslider" class="flexslider">
                                    <ul class="slides">
										<?php
												foreach ($this->agendaPubList as $key => $val):	
										?>
										
                                        <li>
                                            <img src="cimteng/slider1.jpg" alt="photo" />
                                            <h3><span><?php echo $this->escape($val['n_judul']);?></span>
											<a href="#detilagenda" onclick="detilagenda('<?php echo $this->escape($val['c_agenda']);?>')" ><?php echo ($val['n_detil']);?>.</a></h3>
                                        </li>
											<?php endforeach;?>
                                       
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- berita -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Berita</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
						
							<?php
							$jum=count($this->beritaPubList );
							foreach ($this->beritaPubList as $key => $val): 
								$n_judul	= $this->escape($val['n_judul']);		
								$n_detil	=($val['n_detil']);		
								$date= $this->escape($val['d_berita']);
								$date=konversi_tanggal("D, j M Y",$date);
							?>
							<!-- artikel -->
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="#"><img src="cimteng/slider1.jpg" alt="photo"/></a>
                                        <div class="wrapper">
											<p class="tags">
												<?php echo $date ?>
											</p>
                                            <h2 class="post-title"><a href="#judul"><?php echo $n_judul;?></a></h2>
                                            <p>	
												 <?php echo substr($n_detil, 0, 250);?>
												  <a href="#detailBerita" onclick="detilBerita('<?php echo $this->escape($val['c_berita']);?>')" class="read-more">[Selengkapnya]</a> <br /> <br />
                                               
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
							<?php endforeach;?>
							<!-- end artikel -->                           
                        </div>
                          <!-- end berita -->
							<!-- what we do -->
	<div class="row">
		<div class="span8">
			<div class="title-divider">
				<h3>Pengumuman</h3>
				<div class="divider-arrow"></div>
			</div>
		</div>
		<div class="span8">
			<div class="block-grey">
				<div class="block-light wrap15">
				
					<ul class="clearfix">
						<?php	
									foreach ($this->pengumumanPubList as $key => $val): 
									$date=$this->escape($val['d_pengumuman']);
									$date=konversi_tanggal("D, j M Y",$date);
						?>

						<li>
						  <span class="date"><?php echo $date ?></span>
							<h3><a href="#detailpengumuman" onclick="detilpengumuman('<?php echo $this->escape($val['c_pengumuman']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h3>
							  <div class="clear"></div>
						 </li>
						<?php endforeach;?>										
							
					</ul>					
					
				</div>
			</div>
		</div>
	</div>
	<hr>                      
						
			</div> 	<!-- end tableview -->
		</section>
					
					<!-- isi halaman -->
					
                    <!-- sidebar -->
                    <aside id="sidebar" class="alignright span4">
                        <!-- Search -->
                        <section class="search clearfix">
                            <form id="search" class="input-append">
                                <input class="" id="appendedInputButton" size="16" type="text" value="Search..." name="search site"
                                          onfocus="if(this.value=='Search...') this.value=''" onblur="if(this.value=='') this.value='Search...'"/>
                                <input class="btn search-bt" type="submit" name="submit" value="" />
                            </form>
                        </section>
                        <!-- Tabs -->
                        <section class="block-grey">
                            <!-- Tabs navigation -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#blog" data-toggle="tab">Berita</a></li>
                                <li><a href="#archives" data-toggle="tab">Agenda</a></li>
                                <li><a href="#comments" data-toggle="tab">Pengumuman</a></li>
                            </ul>
                            <!-- Tabs content -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="blog">
                                    <section class="post-widget">
                                        <ul class="clearfix">
										<?php
										foreach ($this->beritaPubList as $key => $val): 
											$n_judul	= $this->escape($val['n_judul']);		
											$n_detil	= ($val['n_detil']);		
											$date= $this->escape($val['d_berita']);
											$date=konversi_tanggal("D, j M Y",$date);
										?>
                                            <li>
                                                <div class="avatar">
                                                    <a href="#"><img src="images/logo.jpg" alt="photo"/></a>
                                                </div>
                                                <div class="description">
												<span class="date"><em><?php echo $date ?> </em></span>
                                                    <h3><?php echo $n_judul ?></h3>
													 <?php echo substr($n_detil, 0,100);?>
													 <br />
													<a href="#detailBerita" onclick="detilBerita('<?php echo $this->escape($val['c_berita']);?>')" class="read-more">[Selengkapnya]</a>
													
                                                    
                                                </div>
                                                <div class="clear"></div>
                                            </li>
											<?php endforeach;?>
                                            
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="archives">
                                    <section class="blog-category">
                                        <ul class="ul-col1 clearfix">
											<?php
												foreach ($this->agendaPubList as $key => $val): 
													$date=$this->escape($val['d_agenda']);
													$date=konversi_tanggal("D, j M Y",$date);
											?>
												<li><span class="date"><?php echo $date ?></span>
												<h3><a href="#detilagenda" onclick="detilagenda('<?php echo $this->escape($val['c_agenda']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h3>
											
												</li>
                                           	<?php endforeach;?>
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="comments">
                                    <section class="recent-comments">
									
                                        <ul class="clearfix">
										<?php	
													foreach ($this->pengumumanPubList as $key => $val): 
													$date=$this->escape($val['d_pengumuman']);
													$date=konversi_tanggal("D, j M Y",$date);
													
										?>

										<li><span class="date"><?php echo $date ?></span>
										  <h3><a href="#detailpengumuman" onclick="detilpengumuman('<?php echo $this->escape($val['c_pengumuman']);?>')"><?php echo $this->escape($val['n_judul']);?></a></h3></li>
										<?php endforeach;?>										
                                            
                                        </ul>
                                    </section>
                                </div>
                            </div>
                        </section>
                        <!-- Video block -->
                        <div class="title-divider">
                            <h3>Video</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="block-dark">
                            <div class="video">
                                <iframe src="http://player.vimeo.com/video/7449107" width="" height="" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </section>
                        <!-- User Online -->
                         <div class="widget">
						  <h4 class="widgettitle">User Online</h4>
						  <div class="bd" id="useronline">
						  <?php echo $this->render('partials/main/useronline.phtml');?>
						  </div>
						</div>	
                        <!-- Recent Posts -->
                        <div class="title-divider">
                            <h3>Produk Hukum</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="post-widget block-grey">
                            <ul class="clearfix block-light wrap15">
								<?php	
										foreach ($this->produkhukumPubList as $key => $val): 
													
								?>
                                <li>
                                    <a href="#"><img src="images/logo.jpg" alt="photo"/></a>
                                    <a href="#"><?php echo $this->escape($val['n_judul']);?></a>
                                    <p><em><?php echo $this->escape($val['i_nomor_produkhukum']);?></em></p>
                                    <div class="clear"></div>
                                </li>
								<?php endforeach;?>		                               
                            </ul>
                        </section>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="targetdetil"></div>

<?php echo $this->render('partials/footer.phtml'); ?>

<script>
function detilBerita(idberita){
	
	var url = '<?php echo $this->basePath; ?>/cmsmodule/berita/beritadetil';
	var param = {idberita:idberita};
	jQuery.get(url,param,function(data) {
	jQuery("#targetdetil").html(data);
	centerPopup();
	loadPopup();});
}

function detilagenda(id){
	var url = '<?php echo $this->basePath; ?>/cmsmodule/agenda/cmsagendadetil';
	var param = {id:id};
	jQuery.get(url,param,function(data) {
	jQuery("#targetdetil").html(data);
	centerPopup();
	loadPopup();});}
	
	function detilpengumuman(id){
		var url = '<?php echo $this->basePath; ?>/cmsmodule/pengumuman/cmspengumumandetil';
		var param = {id:id};
		jQuery.get(url,param,function(data) {
		jQuery("#targetdetil").html(data);
		centerPopup();
		loadPopup();});}
		


</script>	

