<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->

<head>
	<?php echo $this->render('partials/head-cimsel.phtml'); ?>
</head>
	

<body>

<!-- top menu -->
<section id="top-menu">
    <div class="container">
        <div class="row">
            <div class="span6 hidden-phone">
                <ul class="top-menu">
                    <li><a href="./index.html">Home</a></li>
                    <li><a href="#">Sitemap</a></li>
                    <li><a href="#">Shorcodes</a></li>
                    <li><a href="#" class="last">Contact</a></li>
                </ul>
            </div>
            <div class="span6">
                <ul class="top-social">
                    <li><a href="#" class="twitter2"></a></li>
                    <li><a href="#" class="facebook"></a></li>
                    <li><a href="#" class="google last"></a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- header -->
<header id="header">
    <div class="container">
        <div class="row">
            <div class="span4 logo">
                <a href="./index.html"><img src="cimteng/logo.png" alt="logo"/></a>
            </div>
            <div class="span8 hidden-phone">
                <a href="./index.html" class="alignright banner">
                    <img src="images/banner-468-60.gif" alt="">
                </a>
            </div>
        </div>
        <nav id="menu">
            <ul class="clearfix">
                <li><a href="./index.html" class="current">Home</a></li>
                <li><a href="./about.html">Tentang Kami</a>
                    <ul>
                        <li><a href="./about.html">Profil</a></li>
                        <li class="last"><a href="./services.html" >Produk Hukum</a></li>
                    </ul>
                </li>
                <li><a href="./portfolio2.html" >Pengumuman</a>                   
                </li>
                <li><a href="./blog.html">Berita</a>
                    <ul>
                        <li><a href="./blog.html">Blog</a></li>
                        <li class="last"><a href="./blog-single.html">Blog Single</a></li>
                    </ul>
                </li>
                <li><a href="./contact.html" >Kontak</a></li>
            </ul>
        </nav>
    </div>
</header>

<!-- container -->
<section id="container">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="row">
                    <!-- page content -->
                    <section id="page-sidebar" class="alignleft span8">
                        <!-- slider -->
                        <div class="row">
                            <div class="span8">
                                <div id="mainslider" class="flexslider">
                                    <ul class="slides">
                                        <li>
                                            <img src="cimteng/slider1.jpg" alt="photo" />
                                            <h3><span>Lorem Ipsum Dolor Sit Amet</span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                        <li>
                                            <img src="cimteng/slider2.jpg" alt="photo" />
                                            <h3><span>Fusce consequat eleifend diam </span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                        <li>
                                            <img src="cimteng/slider3.jpg" alt="photo" />
                                            <h3><span>Donec elementum tortor</span><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</a></h3>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- berita -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Berita</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
						
							<?php
							foreach ($this->beritaPubList as $key => $val): 
								$n_judul	= $this->escape($val['n_judul']);		
								$n_detil	= $this->escape($val['n_detil']);		
								$date= $this->escape($val['d_berita']);
							?>
							<!-- artikel -->
                            <article class="blog-post span4">
                                <div class="block-grey">
                                    <div class="block-light">
                                        <a href="./portfolio2.html"><img src="cimteng/latest1.jpg" alt="photo"/></a>
                                        <div class="wrapper">
                                            <h2 class="post-title"><a href="#"><?php echo $n_judul;?></a></h2>
                                            <p>	
												 <a href="#"><?php echo $n_detil;?></a>
												<?php echo $date;?>
                                                <a href="#" class="read-more">[...]</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
							<?php endforeach;?>
							<!-- end artikel -->                           
                        </div>
                          <!-- end berita -->
                      
                        <!-- portfolio slider -->
                        <div class="row">
                            <div class="span8">
                                <div class="title-divider">
                                    <h3>Pengumuman</h3>
                                    <div class="divider-arrow"></div>
                                </div>
                            </div>
                            <div class="span8">
                                <div class="block-grey our-portfolio">
                                    <div class="block-light wrap10">
                                        <div id="latest-work" class="carousel btleft">
                                        <div class="carousel-wrapper">
                                            <ul class="da-thumbs-folio">
											<?php
											foreach ($this->pengumumanPubList as $key => $val): 
												$n_judul	= $this->escape($val['n_judul']);		
												$n_detil	= $this->escape($val['n_detil']);		
												$date= $this->escape($val['d_berita']);
											?>
                                                <li>
                                                    <img src="cimteng/latest1.jpg" />
                                                    <h3><?php echo $n_judul ?></h3>
                                                    <div>
                                                        <a href="cimteng/view.jpg" class="p-view" data-rel="prettyPhoto"></a>
                                                        <a href="blog-single.html" class="p-link"></a>
                                                    </div>
                                                </li>
											<?php endforeach;?>
                                                
                                            </ul>
                                        </div>
                                        </div>
                                        <script type="text/javascript">
                                            $(document).ready(function(){
                                                $('#latest-work').elastislide({
                                                    imageW  : 235,
                                                    margin  : 10
                                                });
                                            });
                                        </script>
                                    </div>

                                    <div class="short-text">
                                       <?php echo $n_detil ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- sidebar -->
                    <aside id="sidebar" class="alignright span4">
                        <!-- Search -->
                        <section class="search clearfix">
                            <form id="search" class="input-append">
                                <input class="" id="appendedInputButton" size="16" type="text" value="Search..." name="search site"
                                          onfocus="if(this.value=='Search...') this.value=''" onblur="if(this.value=='') this.value='Search...'"/>
                                <input class="btn search-bt" type="submit" name="submit" value="" />
                            </form>
                        </section>
                        <!-- Tabs -->
                        <section class="block-grey">
                            <!-- Tabs navigation -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#blog" data-toggle="tab">Berita Terbaru</a></li>
                                <li><a href="#archives" data-toggle="tab">Agenda</a></li>
                                <li><a href="#comments" data-toggle="tab">Pengumuman</a></li>
                            </ul>
                            <!-- Tabs content -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="blog">
                                    <section class="post-widget">
                                        <ul class="clearfix">
										<?php
										foreach ($this->beritaPubList as $key => $val): 
											$n_judul	= $this->escape($val['n_judul']);		
											$n_detil	= $this->escape($val['n_detil']);		
											$date= $this->escape($val['d_berita']);
										?>
                                            <li>
                                                <div class="avatar">
                                                    <a href="#"><img src="cimteng/sidebar1.jpg" alt="photo"/></a>
                                                </div>
                                                <div class="description">
                                                    <p><a href="blog-single.html"><?php echo $n_judul ?></a></p>
                                                    <span class="date"><em><?php echo $date ?></em></span>
                                                </div>
                                                <div class="clear"></div>
                                            </li>
											<?php endforeach;?>
                                            
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="archives">
                                    <section class="blog-category">
                                        <ul class="ul-col1 clearfix">
											<?php
												foreach ($this->agendaPubList as $key => $val): 
													
											?>

												<li><span class="date"><?php echo $date ?></span>
												<h3><a href="#" onclick="showDetilmed('<?php echo $this->basePath; ?>/portalmodule/agenda/agendadetil','<?=$this->escape($val['c_agenda'])?>','<?php echo $this->basePath; ?>/portalmodule/agenda/indeksagenda','<?php echo $this->basePath; ?>/portalmodule/agenda/agendajs','Agenda');"><?php echo $this->escape($val['n_judul']);?></a></h3>

												<?php endforeach;?>
												</li>
                                           
                                        </ul>
                                    </section>
                                </div>
                                <div class="tab-pane" id="comments">
                                    <section class="recent-comments">
									
                                        <ul class="clearfix">
										<?php	
													foreach ($this->pengumumanPubList as $key => $val): 
													$date=$this->escape($val['d_pengumuman']);
													
										?>

										<li><span class="date"><?php echo $date ?></span>
										  <h3><a href="#" onclick="showDetilmed('<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumandetil','<?=$this->escape($val['c_pengumuman'])?>','<?php echo $this->basePath; ?>/portalmodule/pengumuman/indekspengumuman','<?php echo $this->basePath; ?>/portalmodule/pengumuman/pengumumanjs','Pengumuman');"><?php echo $this->escape($val['n_judul']);?></a></h3></li>
										<?php endforeach;?>										
                                            
                                        </ul>
                                    </section>
                                </div>
                            </div>
                        </section>
                        <!-- Video block -->
                        <div class="title-divider">
                            <h3>Video</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="block-dark">
                            <div class="video">
                                <iframe src="http://player.vimeo.com/video/7449107" width="" height="" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </section>
                        <!-- User Online -->
                         <div class="widget">
						  <h4 class="widgettitle">User Online</h4>
						  <div class="bd" id="useronline">
						  <?php echo $this->render('partials/main/useronline.phtml');?>
						  </div>
						</div>	
                        <!-- Recent Posts -->
                        <div class="title-divider">
                            <h3>Produk Hukum</h3>
                            <div class="divider-arrow"></div>
                        </div>
                        <section class="post-widget block-grey">
                            <ul class="clearfix block-light wrap15">
								<?php	
										foreach ($this->produkhukumPubList as $key => $val): 
													
								?>
                                <li>
                                    <a href="#"><img src="cimteng/sidebar1.jpg" alt="photo"/></a>
                                    <a href="#"><?php echo $this->escape($val['n_judul']);?></a>
                                    <p><em><?php echo $this->escape($val['i_nomor_produkhukum']);?></em></p>
                                    <div class="clear"></div>
                                </li>
								<?php endforeach;?>		                               
                            </ul>
                        </section>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>

<!--footer-->
<footer id="footer">
    <div class="container">
    <div class="row">
        <div class="span4">
            <h3>Flickr Photos</h3>
            <ul class="flickr clearfix"></ul>
        </div>
        <div class="span4">
            <h3>Last Tweet</h3>
            <div id="twitter-foot"></div>
        </div>
        <div class="span4">
            <h3>Contact Form</h3>
            <form id="contact" class="form-horizontal" method="post">
                <div class="controls">
                    <input type="text" id="inputName" placeholder="Name" name="inputName">
                    <label class="ferror" for="inputName" id="fname_error">Name is required.</label>
                </div>
                <div class="controls">
                    <input type="text" id="inputEmail" placeholder="Email" name="inputEmail">
                    <label class="ferror" for="inputEmail" id="femail_error">Email is required.</label>
                </div>
                <div class="controls">
                    <textarea rows="3" id="inputMessage" placeholder="Message" name="inputMessage"></textarea>
                    <label class="ferror" for="inputMessage" id="fmessage_error">Message is required.</label>
                </div>
                <div class="controls">
                    <input type="submit" class="btn btn-success btn-large footer-button" value="Submit">
                </div>
            </form>
        </div>
    </div>
    </div>
</footer>

<!--footer menu-->
<section id="footer-menu">
    <div class="container">
        <div class="row">
            <p class="span12"><span>&copy; Copyright 2012, <span class="color2">CITYpress</span> | All Rights Reserved</span></p>
        </div>
    </div>
</section>
</body>
</html>
