<!DOCTYPE HTML>
<html>

<head>
  <title>Sistem Informasi Pemerintah Kota Cimahi Terintegrasi</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <?php echo $this->render('partials/head.phtml'); ?>
  <link rel="icon" href="images/cimahi.png" type="image/png">
 
</head>

<body>  
    <span href="#" class="button" id="toggle-login">Selamat Datang di  <br />Portal Kecamatan Pemerintah Kota Cimahi </span>
    
	<div id="login">
	
		<h1>Silakan Login</h1>	
			<? echo "<div class='peringatan'>".$this->pesan."</div>"; ?>
			
			<form action="/main" method="post" autocomplete="off">
			 	<input type="text" name="username" value="" placeholder="masukan userID" required />
				<input type="password" name="password" value="" placeholder="masukan password" required/>
				<p><span>&nbsp;</span><input class="submit" type="submit" name="name" value="LOGIN" title="Klik jika sudah mengisi username dan password"/></p>
			 </form>				
    </div>
    <footer>
      <p>Portal Kecamatan Pemerintah Kota Cimahi</p>
    </footer> 
  
  <!-- javascript at the bottom for fast page loading -->
  <script src="js/index.js"></script>
  
  <script src='js/js.js'></script>
</body>

</html>

<script>
jQuery(document).ready(function () { 
	var pesan = document.getElementById('pesan').value;
	if(pesan){
		doCountLogin(5);
		document.getElementById('pesan').value = '';
	}
});  	


function doCountLogin(countdown) {
	document.getElementById("msg").style.display="block";
	
	if (countdown > 0) {
        countdown=countdown-1;
		window.status=countdown + " seconds left to view this page.";
		setTimeout('doCountLogin()',5000); 
    }
    else {
        document.getElementById("msg").style.display="none";
    } 
}
	
</script>