<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><?php echo $this->render('partials/pendaftaranonline/head.phtml'); ?></head>
<body>
<div id="main"><!--main start -->
	<div id="header">
<!--header start -->
	</div><!--header end -->
	<div id="cont-nav">
	    <div id="nav-top">
			
<div class="crdate"><span id="servertime"></span></div>
		</div>
			<div id="nav">
<?php //echo $this->render('partials/sdm/headMenu.phtml'); ?>
			</div>
	
	</div>  


	<div id="page">
	 <div id="content">
		<div id="tableview">
			
<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   for ($i = 0; $i < 40; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }

?>
<script type="text/javascript">
	$(function() {
		$( "#d_lahir" ).datepicker({	changeMonth: true,changeYear: true});
	
	});
</script>
	
<form name="formdaftaronline" id="formdaftaronline" method="post" action=""  enctype="multipart/form-data">
<h2 class="title">Pendaftaran Calon Pegawai Negeri Sipil</h2>
<table border="0" cellpadding="0" cellspacing="1" width="100%">
<tr>
	<td width="20%">
	<div class="boxholder"><h2>Login</h2></div>
	<div class="panel">
		<font color="red"><?php echo $this->pesan;?></font>
		<table border="0" cellpadding="0" cellspacing="1" class="std">
		
			<tr>
				<td>
					<label for="posnusername"><b>Untuk Mengubah biodata Pelamar dan Mencetak Kartu Pendaftaran, silahkan Login terlebih dahulu</label>
				</td>
			</tr>
		</table>	
	</div>
		
	<div class="boxholder"></div>
	<div class="panel">
	<table border="0" cellpadding="0" cellspacing="1" class="std">
			<tr>
				<td>
					<label for="posnusername">Userid/Nomor Kartu Penduduk</label>
					<br>
					<input type="text" name="n_ktp" class="textbox" id="n_ktp" size="33" >
				</td>
			</tr>
			<tr>
				<td>
					<label for="pospaswword">Password</label>
					<br>
					<input type="password" name="n_password_login" class="textbox" id="n_password_login" size="33">
				</td>
			</tr>
			
			<tr>
				<td>
					<input type="button" name="login" value="Login" class="buttonsubmit" onClick="loginConec()"/>
				</td>
			</tr>			
		</table>		
	</div>
	</td>
<td>
<div class="boxholder"><h2>Biodata Pelamar</h2></div>
	<div class="panel">
	
		<table border="0" cellpadding="0" cellspacing="1" class="std">
			<tr>
				<td width="29%">Nomor KTP<span class="hightlight">*</span></td>
				<td width="2%">:</td>
				<td>
					<input type="text" maxlength="16" size="30" name="i_ktp" id="i_ktp" value="<?=$this->i_ktp?>">
					
				</td>
			</tr>	
			<tr>
				<td>Password<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="password"  size="40" name="n_password" id="n_password" value="<?=$this->n_password?>">
					<span class="hightlight">minimal 8 karakter</span>
				</td>
			</tr>
			<tr>
				<td>Ulangi Password<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="password"  size="40" name="n_password2" id="n_password2" value="<?=$this->n_password?>">
					<span class="hightlight">minimal 8 karakter</span>
				</td>
			</tr>
			
			<tr>
				<td>Nama Lengkap<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="70" maxlength="35" name="n_pendaftar" id="n_pendaftar" value="<?=$this->n_pendaftar?>" >
				</td>
			</tr>

			<tr>
				<td>Jenis Kelamin<span class="hightlight">*</span></td>
				<td>:</td> 
				<td>	
				<?php 
					$jenisKel = array("-"=>"--Pilih--","L"=>"Laki-laki","P"=>"Perempuan");	
					echo $ctrlFrm->formSelect('c_jeniskelamin', $this->c_jeniskelamin, null, $jenisKel);
				?>
				</td>
			</tr>
			<tr>
				<td>Gol. Darah/Status Nikah<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
						<?php
							$darahList = array("-"=>"--Pilih--","A"=>"A","B"=>"B","AB"=>"AB","O"=>"O");	
							echo $ctrlFrm->formSelect('c_golongan_darah', $this->c_golongan_darah,null, $darahList); 
						?>	
							&nbsp;/
						<?php 
							$stsNikah = $this->escape($this->stsNikah);
							if (($stsNikah == '') || ($stsNikah == null)) {
				$stsNikah = $_POST['stsNikah'];
							} 
							$stsNikahOpsi = array("-"=>"--Pilih--","M"=>"Menikah","B"=>"Belum Menikah","J"=>"Janda","D"=>"Duda"); 
							echo $ctrlFrm->formSelect('c_statusnikah', $this->c_statusnikah, $stsNikah, $stsNikahOpsi, "&nbsp;"); 
						?>	
				</td>
			</tr>			
		<tr>
				<td>Agama<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<?php
							   
						$agamaList[''] = '--Pilih--';			
						for ($i = 0; $i < count($this->agamaList); $i++) {
							$n_agama=trim($this->agamaList[$i]['n_agama']);   
							$agamaList[trim((string)$this->agamaList[$i]['c_agama'])] = $n_agama;
						}
						echo $ctrlFrm->formSelect('c_agama',$this->c_agama,null,$agamaList);
					?>	
				</td>
			</tr>

							<tr>
								<td>Posisi Jabatan<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<?php
										$jabatanList[''] = '--Pilih--';							
										for ($i = 0; $i < count($this->jabatanList); $i++) {
											$n_jabatan=trim($this->jabatanList[$i]['n_jabatan_usul']);												   
											$jabatanList[trim((string)$this->jabatanList[$i]['c_jabatan_usul']).";".trim((string)$this->jabatanList[$i]['n_surat']).";".trim((string)$this->jabatanList[$i]['c_kualifikasi_pend'])] = $n_jabatan;
										}
										$kualAtrib = array("onChange"=>"javascript:cariKualPend()");
										echo $ctrlFrm->formSelect('c_posisi_jabatan',$this->c_posisi_jabatan,$kualAtrib,$jabatanList);																														
									?>									
								</td>
							</tr>	
							<tr>
								<td>Wilayah Pengadilan Tinggi<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<?php
																							   
										$wilList[''] = '--Pilih--';							
										for ($i = 0; $i < count($this->wilayahList); $i++) {
											$n_pengadilan=trim($this->wilayahList[$i]['n_pengadilan']);												   
											$wilList[trim((string)$this->wilayahList[$i]['c_pengadilan']).";".trim((string)$this->wilayahList[$i]['c_satker'])] = $n_pengadilan;
										}
										echo $ctrlFrm->formSelect('c_wil_pengadilan',$this->c_wil_pengadilan,null,$wilList);
									?>									
								</td>
							</tr>				
</table>
</div>
<div class="boxholder"><h3><b>PENDIDIKAN</b><h3></div>	
<div class="panel">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" id="targetpend">
							<tr>
								<td width="25%">Pendidikan<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
									<?php
										$jmljenjang = count($this->nmJenjangList);														   
										$jenjangReff[''] = '--Pilih--';							
										for ($i = 0; $i < $jmljenjang; $i++) {
											$n_pend=trim($this->nmJenjangList[$i]['n_pendidikan']);												   
											$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;
										}
										//$pendAtrib = array("onChange"=>"javascript:cariPend()"); 
										echo $ctrlFrm->formSelect('c_pend',$this->c_pend,$pendAtrib,$jenjangReff);
									?>									
								</td>
							</tr>
						<tr>
							<td>Jurusan<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$jmljenjang = count($this->jurusanList);														   
								$jurusanList[''] = '--Pilih--';							
								for ($i = 0; $i < $jmljenjang; $i++) {
									$n_kualifikasi_pend=trim($this->jurusanList[$i]['n_kualifikasi_pend']);												   
									$jurusanList[trim((string)$this->jurusanList[$i]['n_kualifikasi_pend'])] = $n_kualifikasi_pend;
								}
										
								echo $ctrlFrm->formSelect('n_pend_jurusan',$this->n_pend_jurusan,null,$jurusanList);								
							?>
							</td>
						</tr>							
						<tr>
							<td>Perguruan Tinggi<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$pendidikanAtrib = array("size"=>"70","class"=>""); 
								echo $ctrlFrm->formText('n_pend_lembaga', $this->n_pend_lembaga, $pendidikanAtrib); 
							?>
							</td>
						</tr>							

						<tr>
							<td>Akreditasi<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
								<?php 
									$akreditasi = array("-"=>"--Pilih--","1"=>"Terdaftar","2"=>"Diakui","3"=>"Disamakan");	
									echo $ctrlFrm->formSelect('c_pend_akreditasi', $this->c_pend_akreditasi, null, $akreditasi);
								?>							
							</td>
						</tr>						
						<tr>
							<td>Tahun Mulai<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_mulai', $this->d_pend_mulai, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Akhir<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_akhir', $this->d_pend_akhir, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr id="idipk">
							<td>IPK / Nilai Ijazah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$ipk = $_POST['ipk'];
								if ($ipk == '') {
									$ipk = 0.00;
								} 			
								$ipkAtrib = array("size"=>"10",
												 "maxlength"=>"5",
												 "class"=>"clright",
												 "id" => "i_pend_ipk",
												 "onKeyup" => "javascript:isNumber('i_pend_ipk');"); 
								echo $ctrlFrm->formText('i_pend_ipk', $this->i_pend_ipk, $ipkAtrib);
							 ?>
						<?
						echo "<font color=\"red\">00.00</font>";
						?>
							</td>
						</tr>
						<tr>
							<td>Nomor Ijazah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
							<?php 
								$noIjazahAtrib = array("size"=>"25",
												 "maxlength"=>"30",
												 "class"=>""); 
								echo $ctrlFrm->formText('i_pend_ijazah', $this->i_pend_ijazah, $noIjazahAtrib);
							 ?>
							</td>
						</tr>
						<tr>
							<td>Tanggal Ijazah<span class="hightlight">*</span></td>
							<td>:</td> 
							<td>
								<input type="text" id="d_pend_ijazah" name="d_pend_ijazah" value="<?=$this->d_pend_ijazah?>" size = "15">
								<span class="hightlight">tgl-bln-thn</span>
							</td>
						</tr>							
			</table>
</div>				
<div class="boxholder"><h3><b>KELAHIRAN</b><h3></div>	
<div class="panel">			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" >			
			<tr>
				<td width="25%">Propinsi<span class="hightlight">*</span></td>
				<td width="2%">:</td>
				<td>
				<?php 
					   $jmlPropList = count($this->propinsiList);
					   $propinsiList[''] = '--Pilih--';
					   for ($i = 0; $i < $jmlPropList; $i++) {
						$propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
					   }
						$propAtrib = array("id"=>"propinsiLahir","onClick"=>"javascript:cariKabupaten('targetkablhr','propinsiLahir')"); 
						echo $ctrlFrm->formSelect('c_propinsi_lahir', $this->c_propinsi_lahir, $propAtrib, $propinsiList)
				?>
				</td>
			</tr>	
			<tr>
				<td>Kabupaten<span class="hightlight">*</span></td>
				<td>:</td>
				<td id="targetkablhr">
				<?php 
					$jmlKabList = count($this->kabupatenListLahir);
					$kabupatenListLahir[''] = '--Pilih--';
					for ($i = 0; $i < $jmlKabList; $i++) {
						$kabupatenListLahir[(string)$this->kabupatenListLahir[$i]->c_kabupaten] = (string)$this->kabupatenListLahir[$i]->n_kabupaten;			 
					}
					echo $ctrlFrm->formSelect('a_kota_lahir', $this->a_kota_lahir,null, $kabupatenListLahir);
				?>
				</td>
			</tr>	
			<tr>
				<td>Tanggal<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" id="d_lahir" name="d_lahir" value="<?=$this->d_lahir?>" size="10"> <span class="hightlight">tgl-bln-thn</span>
				</td>
			</tr>
</table>			
</div>			
<div class="boxholder"><h3><b>CIRI-CIRI FISIK</b><h3></div>	
<div class="panel">			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" >				
			<tr>
				<td width="25%">Tinggi (cm)<span class="hightlight">*</span>/Berat (kg)<span class="hightlight">*</span></td>
				<td width="2%">:</td>
				<td>
					<input type="text" size="10" name="q_tinggibdn" id="q_tinggibdn" value="<?=$this->q_tinggibdn?>"  onkeyup="isNumber('q_tinggibdn')"> /
					<input type="text" size="10" name="q_beratbdn" id="q_beratbdn" value="<?=$this->q_beratbdn?>"  onkeyup="isNumber('q_beratbdn')">
				</td>
			</tr>	
			<tr>
				<td>Rambut<span class="hightlight">*</span>/Bentuk Muka<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="10" name="n_rambut" id="n_rambut" value="<?=$this->n_rambut?>"> /
					<input type="text" size="10" name="n_btkmuka" id="n_btkmuka" value="<?=$this->n_btkmuka?>">
				</td>
			</tr>
			<tr>
				<td>Warna Kulit<span class="hightlight">*</span>/Ciri Khas</td>
				<td>:</td>
				<td>
					<input type="text" size="10" name="n_warnakulit" id="n_warnakulit" value="<?=$this->n_warnakulit?>"> /
					<input type="text" size="10" name="n_cirikhas" id="n_cirikhas" value="<?=$this->n_cirikhas?>">
				</td>
			</tr>
</table>			
</div>			
<div class="boxholder"><h3><b>ALAMAT</b><h3></div>	
<div class="panel">			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" >				

			<tr>
				<td width="25%">Jalan<span class="hightlight">*</span></td>
				<td width="2%">:</td>
				<td>
					<textarea rows="1" name="a_rumah" id="a_rumah"><?=$this->a_rumah?></textarea>
				</td>
			</tr>	
			<tr>
				<td>RT / RW<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="5" name="a_rt" id="a_rt" value="<?=$this->a_rt?>" onkeyup="isNumber('a_rt')" > /
					<input type="text" size="5" name="a_rw" id="a_rw" value="<?=$this->a_rw?>" onkeyup="isNumber('a_rw')">
				</td>
			</tr>	
			<tr>
				<td>Desa/Keluarahan<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="55" name="a_kelurahan" id="a_kelurahan" value="<?=$this->a_kelurahan?>">
				</td>
			</tr>	
			<tr>
				<td>Kecamatan<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" size="55" name="a_kecamatan" id="a_kecamatan" value="<?=$this->a_kecamatan?>">
				</td>
			</tr>	
			<tr>
				<td>Propinsi<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<?php 
					   $jmlPropList = count($this->propinsiList);
					   $propinsiList[''] = '--Pilih--';
					   for ($i = 0; $i < $jmlPropList; $i++) {
					   $propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
					   }
						$propAtrib = array("id"=>"propinsiSelect","onClick"=>"javascript:cariKabupaten('targetkabupaten','propinsiSelect')"); 
						echo $ctrlFrm->formSelect('a_propinsi', $this->a_propinsi, $propAtrib, $propinsiList)
					?>
				</td>
			</tr>
			<tr>
				<td>Kabupaten<span class="hightlight">*</span></td>
				<td>:</td>
				<td id="targetkabupaten">
					<?php 
						$jmlKabList = count($this->kabupatenList);
						$kabupatenList[''] = '--Pilih--';
						for ($i = 0; $i < $jmlKabList; $i++) {
							$kabupatenList[(string)$this->kabupatenList[$i]->c_kabupaten] = (string)$this->kabupatenList[$i]->n_kabupaten;			 
						}
						echo $ctrlFrm->formSelect('a_kota', $this->a_kota,null, $kabupatenList);
					?>
				</td>
			</tr>
			<tr>
				<td>Kode Pos<span class="hightlight">*</span></td>
				<td>:</td>
				<td>
					<input type="text" maxlength="5"  size="10" name="a_kodepos" id="a_kodepos" value="<?=$this->a_kodepos?>" onkeyup="isNumber('a_kodepos')">
				</td>
			</tr>
			
			<tr>
				<td colspan="3" align="left">
					&nbsp;
				</td>
			</tr>
		</table>
</div>			
<div class="boxholder"><h3><b>KODE VERIVIKASI</b><h3></div>	
<div class="panel">		
<div id="verifikasi">
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%" >
			<tr>
				<td align="left">
					<h3 class="title"><b>MASUKAN KODE DI BAWAH INI</b><h3>
				</td>
			</tr>
			<tr>
				<td>			  
				<img src="<?php echo $this->basePath; ?>/pendaftaranonlinemodule/pendaftaranonline/securimageshow?sid=<?php echo md5(uniqid(time())); ?>" id="image" > 
				  <a href="#" onclick="document.getElementById('image').src = '<?php echo $this->basePath; ?>/pendaftaranonlinemodule/pendaftaranonline/securimageshow?sid=' + Math.random(); return false" title="Refresh kode !"><img src="images/refresh.png"></a><br />
				  <input type="text" id="verifikasi" name="verifikasi" size="35"/><br/>
				  <i>Masukkan kode dengan tepat seperti yang ditampilkan. Semua huruf tidak case sensitif.</i> 
				  <br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="red"><?=$this->msgverifikasi;?></font></b>
				</td>

			</tr>	
			</table>			
<br>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
		<tr>
			<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
			<td></td>
			<td align="right">
<div class="right">
	<input type="submit" value="Simpan" onClick="insertReg()">	
	<input type="hidden" name="proses" value="simpan">
	<input type="hidden" name="d_tahun"  id="d_tahun"value="<?=$this->d_tahun;?>">
</div>
			</td>
		</tr>
			</table>

			
</div>
</div>		
	</td>
	</tr>
</table>		


</form>	
</div>	
</div> 
		<div class="space2"></div>
	 </div>

	</div>
</DIV><!--main  end -->
<div id="footer"><!--footer start -->
<?php echo $this->render('partials/sdm/footer.phtml'); ?>
</div><!--footer end -->
</body>
<script type="text/javascript">


function cariKabupaten(target,target2){
	var c_propinsi=document.getElementById(target2).value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/listcombokabupaten';	
	var param = {c_propinsi:c_propinsi,target:target};
	jQuery.get(url, param, function(data) {
		jQuery("#"+target).html(data);

	});
}
function cetakDaftarx(i_ktp,d_tahun)
{
	url = "<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/cetakdaftar?i_ktp="+i_ktp+"&d_tahun="+d_tahun
	BukaWindows('700','500');
}
function BukaWindows(wid,heg){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = wid, popH = heg;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=no,scrollbars=yes,menubar=yes,toolbar=no,status=yes,location=no');
}
function cariPend(){
	var c_pend=document.getElementById("c_pend").value;
	if (c_pend=='01' || c_pend=='02' || c_pend=='03')
	{var url = '<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/pendidikansma';}
	else
	{var url = '<?php echo $this->basePath; ?>/sdmmodule/pendaftaranonline/pendidikanunv';}
	var param = {c_pend:c_pend};
	jQuery.get(url, param, function(data) {jQuery("#targetpend").html(data);});
}
function loginConec(){
	var n_ktp=document.getElementById("n_ktp").value;
	var n_password_login=document.getElementById("n_password_login").value;
	var url = '<?php echo $this->basePath; ?>/pendaftaranonlinemodule/pendaftaranonline/login';
	var param = {n_ktp:n_ktp,n_password_login:n_password_login};
	jQuery.get(url, param, function(data) {jQuery("#tableview").html(data);});
}

function cariKualPend(){
	var c_posisi_jabatan=document.getElementById("c_posisi_jabatan").value;
	var url = '<?php echo $this->basePath; ?>/pendaftaranonlinemodule/pendaftaranonline/kualifikasipend';
	var param = {c_posisi_jabatan:c_posisi_jabatan};
	jQuery.get(url, param, function(data) {jQuery("#targetpend").html(data);});
}
</script>