<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tmt_eselon").datepicker();
		jQuery("#d_mulai_jabat").datepicker();
		jQuery("#d_akhir_jabat").datepicker();
		jQuery("#d_tmt_lantik").datepicker();
		jQuery("#d_sk_jabat").datepicker();
		
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','<?php echo $this->basePath; ?>/sdmmodule/datajabatan/jabatanjs');">Jabatan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jabatan Struktural
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>
		
	<h2 class="title"><?=$this->jdl;?> Jabatan Struktural</h2>	
<form id="formjabatan" method="post" name="formjabatan">		
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>

<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>

<div class="panel">

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">Eselon</td>
								<td width="2%">:</td> 
								<td>					
									<?
											$jmlEslList=count($this->eselonList);
											for ($i = 0; $i < $jmlEslList; $i++) {
												if ($this->c_eselon==$this->eselonList[$i]->c_eselon){$n_eselon=$this->eselonList[$i]->n_eselon;}
											}							
									?>								
									<?=$n_eselon?>
								</td>							
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Dengan Kode Ref.)</td>
								<td>:</td> 
								<td>					
									
									<?=$this->n_jabatan?>
								</td>								
							</tr>	
							<tr>
								<td>TMT. Jabatan</td>
								<td>:</td> 
								<td>					
									<?=$this->d_mulai_jabat?> s/d
									<?=$this->d_akhir_jabat?>
								</td>								
							</tr>							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td width="30%">TMT Eselon</td>
								<td width="2%">:</td> 
								<td>					
									<?=$this->d_tmt_eselon?>
								</td>
							</tr>
							<tr>
								<td>Nama Jabatan <br> (Tanpa Kode Ref.)</td>
								<td>:</td> 
								<td>					
									<?=$this->n_jabatan_nokode?>
								</td>
							</tr>
							<tr>
								<td>Jumlah Angka Kredit</td>
								<td>:</td> 
								<td>					
									<?=$this->q_angka_kredit?>
								</td>
							</tr>								
						</table>	
					</td>
				</tr>
			</table>
		</td>
	</tr>	
</table>
<?if ($this->c_lokasi_unitkerja=='1'){?>
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>UNIT KERJA</u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Lokasi</td>
								<td width="2%">:</td> 
								<td>					
									<?
											$jmlLokList=count($this->lokasiList);
											for ($i = 0; $i < $jmlLokList; $i++) {
												if ($this->c_lokasi_unitkerja==$this->lokasiList[$i]->c_lokasi){$n_lokasi=$this->lokasiList[$i]->n_lokasi;}
											}							
									?>								
									<?=$n_lokasi?>
								</td>
							</tr>
							<tr>
								<td>Eselon I</td>
								<td>:</td> 
								<td>					
									<?=$this->n_eselon_i?>
								</td>
							</tr>
							<tr>
								<td width="30%">Eselon II</td>
								<td width="2%">:</td> 
								<td>				
									<?=$this->n_eselon_i?>
								</td>
							</tr>						
							<tr>
								<td width="30%">Eselon III</td>
								<td width="2%">:</td> 
								<td>					
									<?=$this->n_eselon_i?>
								</td>
							</tr>
							<tr>
								<td>Eselon IV</td>
								<td>:</td> 
								<td>				
									<?=$this->n_eselon_i?>
								</td>
							</tr>
							<tr>
								<td>Eselon V</td>
								<td>:</td> 
								<td>				
									<?=$this->n_eselon_i?>
								</td>
							</tr>
							<tr>
								<td width="17%">Alamat Kantor</td>
								<td width="2%">:</td> 
								<td>					
									<?=$this->a_alamat_kantor?>
								</td>
							</tr>							
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>HASIL AKHIR NAMA JABATAN</u></b><h3></td>
							</tr>
							<tr>
								<td colspan="3">					
									<?=$this->jabat_lengkap?>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
<?}  else{include ("listcombo2.phtml");}?>	
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
	<tr>
		<td>
			<table width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3"><h3 class="title"><b><u>SURAT KEPUTUSAN<u></b><h3></td>
							</tr>
							<tr>
								<td width="30%">Nomor</td>
								<td width="2">:</td> 
								<td>					
									<?=$this->i_sk_jabat?>
								</td>
							</tr>
							<tr>
								<td>Tanggal</td>
								<td>:</td> 
								<td>					
									<?=$this->d_sk_jabat?>
								</td>
							</tr>
							<tr>
								<td>Pejabat</td>
								<td>:</td> 
								<td>					
									<?=$this->n_sk_pejabat?>
								</td>
							</tr>						
						</table>		
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>							
							<tr>
								<td width="30%">Tanggal Pelantikan</td>
								<td width="2">:</td> 
								<td>					
									<?=$this->d_tmt_lantik?>
								</td>
							</tr>	
							<tr>
								<td width="30%">Lokasi KPPN</td>
								<td width="2">:</td> 
								<td>					
									<?=$this->n_lok_kppn?>
								</td>
							</tr>
							<tr>
								<td>Lokasi Taspen</td>
								<td>:</td> 
								<td>					
									<?=$this->n_lok_taspen?>
								</td>
							</tr>	
							<tr>
								<td>Keterangan</td>
								<td>:</td> 
								<td>					
									<?=$this->e_keterangan?>
								</td>
							</tr>							
						</table>	
					</td>
				</tr>
			</table>			
		</td>
	</tr>
</table>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
						<tr>
							<td></td>
							<td align="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatan/listjabatan','');"> 									

							</td>
						</tr>
					</table>



</div>
</form>
</div>
<div id="targetdetil"></div>

