<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();

	  
$jumjabatanList = count($this->jabatanList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Jabatan Struktural
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Jabatan Struktural</h2>
<?php include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">		
	<div class="panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
	</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
 <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	   
<div class="add" title="Tambah Data" onclick="jabatanM('insert','','');"></div>
<?}?>
<!--
<input type="button" value="Jabatan Struktural" disabled="true">&nbsp;

<input type="button" value="Jabatan Fungsional" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datajabatanfungsional/listjabatan','<?php echo $this->basePath; ?>/sdmmodule/datajabatanfungsional/jabatanjs');">
-->
<?	if ($jumjabatanList == 0) {
		echo "<font color=\"red\">Data Jabatan Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th width="10%">Eselon / TMT Eselon</th>
			<th width="20%">Nama Jabatan / TMT Jabatan</th>
			<th width="20%">No SK / Tgl. SK</th>
			<th width="16%">Tgl Pelantikan</th>
			<th width="6%" colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumjabatanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { 

		  foreach ($this->jabatanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				<td class="clcenter">
					<?php echo $this->escape($val['n_eselon']);?> <br> <?php echo $this->escape($val['d_tmt_eselon']);?>
				</td>
				<td><?php  echo $this->escape($val['n_jabatan']);?> <?php  echo $this->escape($val['unitkerjalengkap']);?><br><?php  echo $this->escape($val['d_mulai_jabat']);?></td>
				<td class="clcenter"><u><?php  echo $this->escape($val['i_sk_jabat']);?></u><br><?php  echo $this->escape($val['d_sk_jabat']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['d_tmt_lantik']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="jabatanM('update','<?=trim($this->escape($val['c_eselon']))?>','<?=trim($this->escape($val['c_jabatan']))?>','<?=trim($this->escape($val['d_mulai_jabat']))?>');"></div>	
				</td>
 <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="jabatanM('delete','<?=trim($this->escape($val['c_eselon']))?>','<?=trim($this->escape($val['c_jabatan']))?>','<?=trim($this->escape($val['d_mulai_jabat']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
