<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
   $ctrlFrm = new Zend_View();
   $halaman = new halaman_list(); 
  
    $jmlPegawaiList = count($this->pegawaiList);
  $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
	<a href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a>&nbsp;<strong>&#8250;</strong>&nbsp;SDM&nbsp;<strong>&#8250;</strong>&nbsp;Kelola Data Pegawai&nbsp;
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Kelola Data Pegawai</h2>
	<div class="search-panel">
				<form id="frmSearch" method="post" name="frmSearch">
					Pencarian berdasarkan :
					<?
							$cCol = array(""=>"--Pilih--",
									"i_peg_nip"=>"NIP",
									"n_peg"=>"Nama");								
							echo $ctrlFrm->formSelect('cCol', $this->cCol, null, $cCol); 							
					?>						
					<span id="targetcari"><input type="text" name="nCol" id="nCol" value="<?echo $this->nCol?>"></span>
					<input type="submit" value="Cari" onclick="javascript:cariListPegawai();">		   
				</form>						
	</div>	
	<div class="space-line"></div>
	<form action="" method="post"> 
		<fieldset class="fields"> 
			   <div class="add" title="Tambah Data" onclick="CpnsM('insert','');"></div>
   <table align="center" border="0" cellspacing="1" cellpadding="2" class="sortable">
		<tr>
			<th class="nosort" width="5%">No.</th>
<!--			<th class="nosort" width="8%">Photo</th>-->
			<th class="<?=$this->orderbya?>" width="62%" onclick="orderBy('n_peg','<?=$this->orderbyb?>','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai')">Biodata</th>
			<th width="20%" onclick="orderBy('c_unit_kerja','<?=$this->orderbyb?>','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai')">Satuan Kerja</th>
			<th width="5%">&nbsp;</th>
		</tr> 
<? 		if ($jmlPegawaiList == 0) {?>
		<tr class="event">
<!--			<td>&nbsp;</td>-->
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->pegawaiList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
					$pangkat = $this->escape($val['n_pangkat']);
					$golongan = $this->escape($val['n_golongan']);
					$golPangkat = $golongan." - ".$pangkat;
					$n_lokasi_unitkerja=$this->escape($val['n_lokasi_unitkerja']);
					$n_eselon=$this->escape($val['n_eselon']);
					$n_jabatan=$this->escape($val['n_jabatan']);
					$tmtkgb = $this->escape($val['d_tmt_kgb']);
					$n_status_kepegawaian="";
					if($this->escape($val['c_peg_status'])=='MIL'){$n_status_kepegawaian="/".$this->escape($val['n_status_kepegawaian']);}
				?>
					<td class="clcenter"><?php echo $noUrut;?></td>
<!--					
					<td>
					<?
					//$vFoto="";
					//$vFoto = $this->basePath."/upld/Uploaddata/getphoto?f=".trim($this->escape($val['e_file_photo']));
					?>
					<img src="<?=$vFoto?>" width="55" height="60" >
					</td>
-->					
					<td>
					<table border="0" cellspacing="1" cellpadding="2" class="std">
						<tr>
						<td width="10%">Nama</td>
						<td width="1%">:</td>
						<td width="52%"><?php echo $this->escape($val['n_peg']);?></td>
						<td width="10%">Jns. Kel</td>
						<td width="1%">:</td>
						<td width="25%">
						<?php 
							if($this->escape($val['c_peg_jeniskelamin'])=="L"){echo "Laki-laki";}
							if($this->escape($val['c_peg_jeniskelamin'])=="P"){echo "Perempuan";}
						?>
						</td>
						</tr>
						<tr>
						<td>Nip</td>
						<td>:</td>
						<td><?php echo $this->escape($val['i_peg_nip']);?></td>
						<td>Eselon</td>
						<td>:</td>
						<td><?php echo $n_eselon;?></td>
						</tr>
						<tr>
						<td>Gol/Pangkat</td>
						<td>:</td>
						<td><?php echo $golPangkat;?></td>
						<td>Stat.Peg.</td>
						<td>:</td>
						<td><?php echo $this->escape($val['n_peg_status']).$n_status_kepegawaian;?></td>						
						</tr>	
						<tr>
						<td>Jabatan</td>
						<td>:</td>
						<td><?php echo $n_jabatan;?></td>
					
						</tr>						
					</table>
					</td>	
				    <td><?php echo $this->escape($val['unitkerjalengkap']);?></td>
					<td class="clcenter">
					<?if ($this->escape($val['c_peg_status'])!='2CP'){?>
						<div class="edit" title="Ubah Data" onclick="PnsM('pns','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}else{?>
						<div class="edit" title="Ubah Data" onclick="CpnsM('update','<?=$this->escape($val['i_peg_nip'])?>');"></div>
					<?}?>		
					</td>
				<!--	
					<td class="clcenter">
						<div class="delete" title="Hapus Data"  onClick="javascript:HapusDataPeg('<?php echo $this->escape($val['i_peg_nip']);?>')"></div>
					</td>					
				-->	
				</tr>
				<?php endforeach;}?>
	
	</table>
<div id="targetdetil"></div>

<?
$orderBy=$this->orderBy;
$modul = $this->basePath."/sdmmodule/datapegawai/listpegawai?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol";
echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>	
	</fieldset>		 
	</form>

<script>
function detilPeg(nip){
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/detilpegawai';
var param = {nip:nip};
jQuery.get(url,param,function(data) {
jQuery("#targetdetil").html(data);
centerPopup();
loadPopup();});}
</script>		