<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();
  
$jumseminarList = count($this->seminarList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>Seminar
		</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Seminar</h2>

<?php include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">	
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
	</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  
<div class="add" title="Tambah Data" onclick="SeminarM('insert','');"></div>
<?	if ($jumseminarList == 0) {
		echo "<font color=\"red\">Data Seminar Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
		    <th width="30%">Nama Seminar</th>
			<th width="10%">Peran</th>
			<th width="6%">Mulai</th>
			<th width="6%">Akhir</th>
			<th width="10%">Penyelenggara</th>
			<th width="6%" colspan="2">&nbsp;</th>
		</tr>
<?
	if ($jumseminarList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->seminarList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
			
				<td>
					<a href="#" onclick="detilSeminar('<?=$nip?>','<?=trim($this->escape($val['n_seminar']))?>')"><?php echo $this->escape($val['n_seminar']);?></a>
				</td>
				<td><?php  echo $this->escape($val['n_seminar_peran']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_mulai_seminar']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_akhir_seminar']);?></td>
				<td><?php echo $this->escape($val['n_seminar_lembaga']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="SeminarM('update','<?=trim($this->escape($val['d_mulai_seminar']))?>');"></div>	
				</td>
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataSeminar('<?=$nip?>','<?=trim($this->escape($val['d_mulai_seminar']))?>')"></div>
				</td>	
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
