function tampilTaun(){
	var tahun= document.getElementById('tahun').value;
			
	handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir4/listformulir4';
	
		var opt = {tahun:tahun};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				if(tahun != "Tahun"){
				jQuery(".thn_skr").html(tahun);
				jQuery("#thn_sblm").html(tahun-1);
				jQuery("#tahun").val(tahun);
				}else{
				jQuery(".thn_skr").html("");
				jQuery("#thn_sblm").html("");
				
				}
			 });
		
		
};

function OpenFormulir4Olahdata(par,id,gol_ruang_gaji,pangkat,jum_pegawai){
		
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val();
		if(thn_skr == ""){
		alert("Tampil Tahun Terlebih dahulu !");
		return;
		}
		
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir4/formulir4olahdata';
		
		if(id==""){
		par="Insert";
		}else{
		par="Update";
		}
		var opt = {par:par,id:id,gol_ruang_gaji:gol_ruang_gaji,pangkat:pangkat,jum_pegawai:jum_pegawai};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				jQuery("#gol_ruang_gaji").val(gol_ruang_gaji);
				jQuery("#pangkat").val(pangkat);
				jQuery("#jum_pegawai").val(jum_pegawai);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
				jQuery("#thn_skrg2").val(thn_skr);
				jQuery("#thn_sblm2").val(thn_sblm);
				jQuery("#tahun").val(thn_skr);
			 });

}

function OpenFormulir4(){
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val()
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir4/listformulir4';
		
		var opt = {tahun:tahun};
		jQuery.get(handler,opt,function(data) {
				$("#tableview").html(data);
				jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });

}

function insertFormulir4(){
		var thn_skr=jQuery(".thn_skr").html();
		var thn_sblm=jQuery("#thn_sblm").html();
		var tahun=jQuery("#tahun").val()
		jQuery("#formformulir4").ajaxForm(maintain_formulir4);
	
		handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir4/listformulir4';
		var opt = {tahun:tahun,thn_skr:thn_skr,thn_sblm:thn_sblm};
		jQuery.get(handler,opt,function(data) {
				//$("#tableview").html(data);
			jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });
}

var maintain_formulir4 = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formformulir4").ajaxForm(maintain_formulir4);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/formulir4/insertformulir4',
	type: 'post',
	resetForm: false
};

function updateFormulir4(){
	var thn_skr=jQuery(".thn_skr").html();
	var thn_sblm=jQuery("#thn_sblm").html();
	var tahun=jQuery("#tahun").val()
	
	jQuery("#formformulir4").ajaxForm(update_formulir4);
	
	handler = '<?php echo $this->basePath; ?>/sdmmodule/formulir4/listformulir4';
		
		var opt = {tahun:tahun,thn_skr:thn_skr,thn_sblm:thn_sblm};
		jQuery.get(handler,opt,function(data) {
				//$("#tableview").html(data);
				jQuery("#tahun").val(thn_skr);
				jQuery(".thn_skr").html(thn_skr);
				jQuery("#thn_sblm").html(thn_sblm);
			 });
}

var update_formulir4 = {
	target:'#tableview',
	beforeSubmit: function() {
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formformulir4").ajaxForm(update_formulir4);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/formulir4/updateformulir4',
	type: 'post',
	resetForm: false
};