<br>
<table cellspacing="1" cellpadding="2" border="0" align="center" class="tbl wide">
<tr>
<th rowspan="2">Organisasi</th>
<th rowspan="2">Total Peg</th>
<th colspan="2">Peg Kategori</th>
<th colspan="2">Peg Komposisi</th>
<th colspan="9">Pendidikan</th>
<th colspan="5">Usia</th>
</tr>
<tr>
	<th>Kontrak</th>
	<th>Tetap</th>
	<th>Trampil</th>
	<th>Organik</th>
	<th>S3</th>
	<th>S2</th>
	<th>S1</th>
	<th>D3</th>
	<th>D2</th>
	<th>D1</th>
	<th>SMA</th>
	<th>SMP</th>
	<th>SD</th>
	<th>26</th>
	<th>26-35</th>
	<th>36-45</th>
	<th>46-55</th>
	<th>56</th>	
</tr>
<tr class="event">
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
</tr>	
</table>