<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<table width="100%"  id="listcombo">

	<tr>
		<td width="20%" align="left">&nbsp;</td>
		<td width="30%" align="left">Lokasi</td>
		<td width="2%"  align="left">:</td> 
		<td width="58%" align="left">					
			<?
				$jmlLokList=count($this->lokasiList);
				$lokList[''] = '--Pilih--';
					for ($i = 0; $i < $jmlLokList; $i++) {
$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
					}
				$lokAtrib = array("style"=>"width: 240px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo3('targetesli')"); 
				echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="left">Eselon I</td>
		<td align="left">:</td> 
		<td align="left">					
			<?
				$jmleseloniList=count($this->eseloniList);
				$eseloniList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniList; $i++) {
$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
					}
				$eslAtrib = array("style"=>"width: 240px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo3('targeteslii')");  	
				echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 	
			?>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="left">Pengadilan Tingkat I</td>
		<td align="left">:</td> 
		<td align="left">				
			<?
				$jmleseloniiList=count($this->eseloniiList);
				$eseloniiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiList; $i++) {
$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
					}
				$eslAtrib = array("style"=>"width: 240px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo3('targetesliii')");  	
				echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 	
			?>
		</td>
	</tr>
	<tr>
		<td align="left">&nbsp;</td>
		<td align="left">Pengadilan Tingkat Banding</td>
		<td align="left">:</td> 
		<td align="left">					
			<?
				$jmleseloniiiList=count($this->eseloniiiList);
				$eseloniiiList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleseloniiiList; $i++) {
$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
					}
				$eslAtrib = array("style"=>"width: 240px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo3('targetesliv')");  	
				echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 	
			?>
		</td>
	</tr>
	<tr>
		<td align="left">&nbsp;</td>
		<td align="left">Unit Kerja</td>
		<td align="left">:</td> 
		<td align="left">				
			<?
				$jmleselonivList=count($this->eselonivList);
				$eselonivList[''] = '--Pilih--';
					for ($i = 0; $i < $jmleselonivList; $i++) {
$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
					}
				$eslAtrib = array("style"=>"width: 240px","id"=>"c_eselon_iv");  	
				echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 	
			?>
		</td>
	</tr>
				

</table>
