<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}

$vFoto = $this->basePath."/upld/Uploaddata/getphoto?f=".trim($this->filephoto);

?>
<script type="text/javascript">
	$(function() {
		$("#d_peg_lahir").datepicker();
	
	
	});
</script>

		<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong><?=$this->jdl;?> Data Diri
		</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form name="formpegawai" id="formpegawai" enctype="multipart/form-data" method="post" action="">
<h2 class="title"><?=$this->jdl;?> Data Diri</h2>
	<?if ($this->par=='Ubah'){$readonly="readonly='true'"?>	                    
<?php include "$this->leftMenu/linkdatapokok.phtml";?>


	<?php 
	}?>
	<div class="boxholder">
	<div class="panel">	

		<div class="spacer"></div> 
			<table border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>&nbsp;</td>
				</tr>
			</table>
			<table border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="80%">
						<table width="100%">
							<tr>
								<td width="35%">NIP Baru / NIP Lama<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
									<?=$this->i_peg_nip_new?> /
									<?=$this->i_peg_nip?>								
								</td>
							</tr>
							<tr>
								<td>Nama Lengkap<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<?=$this->n_peg?>
								</td>
							</tr>
							<tr>
								<td>Gelar Depan / Gelar Blk</td>
								<td>:</td>
								<td>
									<?=$this->n_peg_gelardepan?>
									&nbsp;/
									<?=$this->n_peg_gelarblkg?>
								</td>
							</tr>
							<tr>
								<td>Gol. Darah / Status Nikah</td>
								<td>:</td>
								<td>
										<?php
											echo $this->c_golongan_darah;
										?>	
											&nbsp;/
										<?php										
											if ($this->c_peg_statusnikah=="M"){echo "Menikah";}
											elseif ($this->c_peg_statusnikah=="B"){echo "Belum Menikah";}
											elseif ($this->c_peg_statusnikah=="J"){echo "Janda";}
											elseif ($this->c_peg_statusnikah=="D"){echo "Duda";}
											else{echo "-";}	
										?>	
								</td>
							</tr>
							<tr>
								<td>Jenis Kelamin</td>
								<td>:</td> 
								<td>					
								<?php 
									if ($this->c_peg_jeniskelamin=="L"){echo "Laki-laki";}
									elseif ($this->c_peg_jeniskelamin=="P"){echo "Perempuan";}
									else{echo "-";}	
								?>
								</td>
							</tr>
							
							<tr>
								<td>Agama</td>
								<td>:</td> 
								<td>					
								<?php 
									   $jmlPropList = count($this->agamaList);
									   for ($i = 0; $i < $jmlPropList; $i++) {
										if ($this->c_agama==$this->agamaList[$i]->c_agama){echo $this->agamaList[$i]->n_agama;}
									   }
								?>
								</td>
							</tr>							
							<tr>
								<td>Hobi</td>
								<td>:</td>
								<td>
									<?=$this->n_peg_hobi?>
								</td>
							</tr>
						</table>
					</td>					
					<td width="20%">
						<table width="100%">
							<tr>
								<td align="right">
									<img src="<?=$vFoto?>" width="90" height="100" ><br>
								</td>

							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>KELAHIRAN</b><h3>
								</td>
							</tr>
							<tr>
								<td>Propinsi<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
								<?php 
									   $jmlPropList = count($this->propinsiList);
									   for ($i = 0; $i < $jmlPropList; $i++) {
										if ($this->c_peg_propinsi_lahir==$this->propinsiList[$i]->c_propinsi){echo $this->propinsiList[$i]->n_propinsi;}
									   }
								?>
								</td>
							</tr>	
							<tr>
								<td>Kabupaten<span class="hightlight">*</span></td>
								<td>:</td>
								<td id="targetkablhr">
								<?php 
									$jmlKabList = count($this->kabupatenListLahir);
									for ($i = 0; $i < $jmlKabList; $i++) {
										if ($this->a_peg_kota_lahir==$this->kabupatenListLahir[$i]->c_kabupaten){echo $this->kabupatenListLahir[$i]->n_kabupaten;}
									}
								?>
								</td>
							</tr>
							<tr>
								<td>Kecamatan</td>
								<td>:</td>
								<td><?=$this->a_peg_kecamatan_lahir?></td>
							</tr>
							<tr>
								<td>Kelurahan</td>
								<td>:</td>
								<td><?=$this->a_peg_kelurahan_lahir?></td>
							</tr>							
							<tr>
								<td>Tanggal</td>
								<td>:</td>
								<td>
									<?=$this->d_peg_lahir?>
								</td>
							</tr>							
						</table>
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>CIRI-CIRI FISIK</b><h3>
								</td>								
							</tr>
							<tr>
								<td>Tinggi (cm) / Berat (kg)</td>
								<td>:</td>
								<td>
									<?=$this->q_peg_tinggibdn?> /
									<?=$this->q_peg_beratbdn?>
								</td>
							</tr>	
							<tr>
								<td>Rambut / Bentuk Muka</td>
								<td>:</td>
								<td>
									<?=$this->n_peg_rambut?> /
									<?=$this->n_peg_btkmuka?>
								</td>
							</tr>
							<tr>
								<td>Warna Kulit / Ciri Khas</td>
								<td>:</td>
								<td>
									<?=$this->n_peg_warnakulit?> /
									<?=$this->n_peg_cirikhas?>
								</td>
							</tr>	
						</table>
					</td>
				</tr>
			</table>	

			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>ALAMAT</b><h3>
								</td>
							</tr>
							<tr>
								<td width="20%">Jalan</td>
								<td width="2%">:</td>
								<td>
									<?=$this->a_peg_rumah?>
								</td>
							</tr>	
							<tr>
								<td>RT / RW</td>
								<td>:</td>
								<td>
									<?=$this->a_peg_rt?> /
									<?=$this->a_peg_rw?>
								</td>
							</tr>	
							<tr>
								<td>Desa/Keluarahan</td>
								<td>:</td>
								<td>
									<?=$this->a_peg_kelurahan?>
								</td>
							</tr>	
							<tr>
								<td>Kecamatan</td>
								<td>:</td>
								<td>
									<?=$this->a_peg_kecamatan?>
								</td>
							</tr>	
							<tr>
								<td>Propinsi</td>
								<td>:</td>
								<td>
									<?php 
									   $jmlPropList = count($this->propinsiList);
									   for ($i = 0; $i < $jmlPropList; $i++) {
										if ($this->a_peg_propinsi==$this->propinsiList[$i]->c_propinsi){echo $this->propinsiList[$i]->n_propinsi;}
									   }

									?>
								</td>
							</tr>
							<tr>
								<td>Kabupaten</td>
								<td>:</td>
								<td id="targetkabupaten">
									<?php 
										$jmlKabList = count($this->kabupatenList);
										for ($i = 0; $i < $jmlKabList; $i++) {
											if ( $this->a_peg_kota==$this->kabupatenList[$i]->c_kabupaten){echo $this->kabupatenList[$i]->n_kabupaten;}
										}
									?>
								</td>
							</tr>
							<tr>
								<td>Kode Pos</td>
								<td>:</td>
								<td>
									<?=$this->a_peg_kodepos?>
								</td>
							</tr>	
							<tr>
								<td>Telp/HP</td>
								<td>:</td>
								<td>
							<?
								$fieldId="i_peg_telponrumah";
								$value=$this->i_peg_telponrumah;
								$val = explode("-",$value);
								$size="10";
								if (!$size) $size = Array(5,10);
								$xsize = $size[0]+$size[1]+1;
								$h = $f."$val[0]";
								$h .= "<b>-</b>&nbsp;";
								$h .= "$val[1]".$d;
								$h .= "$value";
								echo $h;
							?>
							/ <?=$this->i_peg_telponhp?>
							
								</td>
							</tr>
							
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>NOMOR KARTU</b><h3>
								</td>								
							</tr>
							<tr>
								<td>Nomor KARPEG</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_karpeg?>
								</td>
							</tr>	
							<tr>
								<td>Nomor KARIS / KARSU</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_karis?>
								</td>
							</tr>
							<tr>
								<td>Nomor TASPEN</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_taspen?>
								</td>
							</tr>
							<tr>
								<td>Nomor KORPRI</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_korpri?>
								</td>
							</tr>
							<tr>
								<td>Nomor KTP</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_ktp?>
								</td>
							</tr>
							<tr>
								<td>Nomor ASKES</td>
								<td>:</td>
								<td>
									<?=$this->i_peg_askes?>
								</td>
							</tr>
							<tr>
								<td>Nomor Rekening</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_rekening" id="i_peg_rekening" value="<?=$this->i_peg_rekening?>" onkeyup="isNumber('i_peg_rekening')">
									&nbsp;&nbsp;&nbsp;Nama Bank : 
									<?php 
										$jmlbankList = count($this->bankList);
										for ($i = 0; $i < $jmlbankList; $i++) {
											if ($this->c_peg_bank==$this->bankList[$i]->c_bank){echo $this->bankList[$i]->n_bank;}
										}
									?>
								</td>
							</tr>	
							<tr>
								<td>Nomor NPWP</td>
								<td>:</td>
								<td>
								<?

								 $hx="";
									$fieldIdx="i_peg_npwp";
									$valxue=$this->i_peg_npwp;
									$valx = explode(".",$valxue);
									$valxx2 = explode("-",$valx[3]);
									if (!$sizex) $sizex = Array(2,3,3,1,3,3);
									$xsize = $sizex[0]+$sizex[1]+$sizex[2]+$sizex[3]+$sizex[4]+$sizex[5]+5;
					
									$hx .= $f."$valx[0]";
									$hx .= "<b>.</b>&nbsp;";
									$hx .= "$valx[1]";
									$hx .= "<b>.</b>&nbsp;";
									$hx .= "$valx[2]";
									$hx .= "<b>.</b>&nbsp;";
									$hx .= "$valxx2[0]";
									$hx .= "<b>-</b>&nbsp;";
									$hx .= "$valxx2[1]".$d;
									$hx .= "<b>.</b>&nbsp;";
									$hx .= "$valx[4]".$d;
									$hx .= "$valxue";
									if(trim($hx[0])!=". . . - . ...-."){echo $hx;}
								?>
									
								</td>
							</tr>							
			</table>
	</div>		
<br>
	<div class="panel">
		<div class="spacer"></div>			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td></td>
							<td align="right">
								<div class="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');"> 
								</div>
							</td>
						</tr>
			</table>	
</div>			
	</div>
</form>	

<script type="text/javascript">

function windowListTempat(){
	url = "<?php echo $this->basePath; ?>/sdmmodule/pegawai/listtempat";
	var selectWindow = window.open(url,"Selection","menubar=no,toolbar=no,scrollbars=Yes,width=740,height=530");
} 
function cariSatker(){
	var i_org_parent=document.getElementById('orgSelect').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombosatker';	
	var param = {i_org_parent:i_org_parent};
	jQuery.get(url, param, function(data) {
		jQuery("#targetsatker").html(data);

	});
}
function cariKabupaten(target,target2){
	var c_propinsi=document.getElementById(target2).value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombokabupaten';	
	var param = {c_propinsi:c_propinsi,target:target};
	jQuery.get(url, param, function(data) {
		jQuery("#"+target).html(data);

	});
}



</script>