function PengahargaanM(par,nJnsPenghargaan,nPenghargaan){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/penghargaan"	
	var opt = {par:par,nJnsPenghargaan:nJnsPenghargaan,nPenghargaan:nPenghargaan};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
		});		
} 

var maintain_penghargaan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formpenghargaan;
		astr= "document.formpenghargaan";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!n_jns_penghargaan.value)){cekVal = sdmValidasiData(astr,"n_jns_penghargaan","Jenis Penghargaan harus diisi....!");return false;break;}
				if((!n_penghargaan.value)){cekVal = sdmValidasiData(astr,"n_penghargaan","Nama Penghargaan harus diisi....!");return false;break;}
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/maintaindata',
	type: 'post',
	resetForm: false
};
function insertpenghargaan(){
	jQuery("#formpenghargaan").ajaxForm(maintain_penghargaan);
}

function HapusDataPenghargaan(nip,nJnsPenghargaan,nPenghargaan)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datapenghargaan/hapusdata"
		var opt = {nip:nip,nJnsPenghargaan:nJnsPenghargaan,nPenghargaan:nPenghargaan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
