<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		//jQuery("#d_sertifikat").datepicker();
		$( "#d_sertifikat" ).datepicker({	changeMonth: true,changeYear: true});
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikpenjenjangan/listdiklat','');">Diklat Penjenjangan</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Diklat Penjenjangan
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Diklat Penjenjangan</h2>
<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
	
<form id="formjenjang" method="post" name="formjenjang" enctype="multipart/form-data">		
				<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					
					<tr>
						<td  width="23%">Penjenjangan
						<span class="hightlight">*</span>
						</td>
						<td width="2%">:</td> 
						<td width="75%">					
						<?php
						   $jmllistrpenjenjangan = count($this->listrpenjenjangan);
						   $listrpenjenjangan[''] = '--Pilih--';
							for ($i = 0; $i < $jmllistrpenjenjangan; $i++) {	 
								$listrpenjenjangan[$this->listrpenjenjangan[$i]->c_jenjang ]= (string)$this->listrpenjenjangan[$i]->n_jenjang;			 
						   }    
							echo $ctrlFrm->formSelect('c_penjenjangan', $this->c_penjenjangan, null, $listrpenjenjangan);
						?>					
						</td>
					</tr>
			
				<tr>
					<td>Angkatan / Tahun
					<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>
						<input type="text" name="q_angkatan" id="q_angkatan" value="<?=$this->q_angkatan?>" size="5"> / 
						<input type="text" name="q_tahun" id="q_tahun" value="<?=$this->q_tahun?>" size="5">
					</td>
				</tr>
				<tr>
					<td>Lama Diklat (JPL)</td>
					<td>:</td> 
					<td>
						<input type="text" name="q_lama" id="q_lama" value="<?=$this->q_lama?>" size="5">
					</td>
				</tr>
				<tr>
					<td>Penyelenggara</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_penyelenggara" id="n_penyelenggara" value="<?=$this->n_penyelenggara?>" size="80">
					</td>
				</tr>
				<tr>
					<td>Peringkat</td>
					<td>:</td> 
					<td>
						<input type="text" name="q_peringkat" id="q_peringkat" value="<?=$this->q_peringkat?>" size="5">
					</td>
				</tr>	
				<tr>
					<td>Predikat Kelulusan</td>
					<td>:</td> 
					<td>
						<?php
						   $jmllistrkualifikasi = count($this->listrkualifikasi);
						   $listrkualifikasi[''] = '--Pilih--';
							for ($i = 0; $i < $jmllistrkualifikasi; $i++) {	 
								$listrkualifikasi[$this->listrkualifikasi[$i]->c_kualifikasi ]= (string)$this->listrkualifikasi[$i]->n_kualifikasi;			 
						   }    
							echo $ctrlFrm->formSelect('c_kualifikasi', $this->c_kualifikasi, null, $listrkualifikasi);
						?>							
					</td>
				</tr>				
				<tr>
					<td>&nbsp;</td>
				</tr>
				
				<tr>
					<td colspan="3"><h3 class="title"><b><u>SERTIFIKAT/STTPP</u></b><h3></td>
				</tr>
				<tr>
					<td>Nomor Sertifikat<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>
						<input type="text" maxlength="80" name="i_sertifikat" id="i_sertifikat" value="<?=$this->i_sertifikat?>" size="50">
					</td>
				</tr>				
				<tr>
					<td>Tanggal Sertifikat<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>
						<input type="text" name="d_sertifikat" id="d_sertifikat" value="<?=$this->d_sertifikat?>" size="10">
						<span class="hightlight">dd-mm-yyyy</span>
					</td>
				</tr>	
				<tr>
					<td>Pejabat</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_pejabat" id="n_pejabat" value="<?=$this->n_pejabat?>" size="80">
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikpenjenjangan/listdiklat','');"> 									
									<input type="submit" value="<?=$this->par;?>" onClick="insertPenjenjangan()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
							</td>
						</tr>
					</table>
</form>
	</div>
</div>	
<script>
function getKelompok(){
	var c_filter=document.getElementById("c_jns_fungsional").value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/datapelatihan/listcombokelompok"
	var opt = {c_filter:c_filter};
	jQuery.get(url,opt,function(data) {
		jQuery("#idkel").html(data);
		});		
}
function getJenis(){
	var c_fungsional=document.getElementById("c_kel_pelatihan").value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/datapelatihan/listcombojenis"
	var opt = {c_fungsional:c_fungsional};
	jQuery.get(url,opt,function(data) {
		jQuery("#idjns").html(data);
		});		
} 
function getNama(){
	var c_jenis=document.getElementById("c_jns_kelompok").value;
	url = "<?php echo $this->basePath; ?>/sdmmodule/datapelatihan/listcombonama"
	var opt = {c_jenis:c_jenis};
	jQuery.get(url,opt,function(data) {
		jQuery("#idnama").html(data);
		});		
}  
</script>	