<table>	
	<tr>
		<td align="left" width="22%">Eselon I</td>
		<td align="left"  width="2%">:</td> 
		<td align="left">					
			<input type="text" name="n_eselon_ix" id="n_eselon_ix" size="80" value="<?=$this->n_eselon_i?>">
		</td>
	</tr>
	<tr>
		<td align="left">Eselon II</td>
		<td align="left">:</td> 
		<td align="left">				
			<input type="text" name="n_eselon_iix" id="n_eselon_iix" size="80" value="<?=$this->n_eselon_ii?>">
		</td>
	</tr>
	<tr>
		<td align="left">Eselon III</td>
		<td align="left">:</td> 
		<td align="left">					
			<input type="text" name="n_eselon_iiix" id="n_eselon_iiix" size="80" value="<?=$this->n_eselon_iii?>">
		</td>
	</tr>
	<tr>
		<td align="left">Eselon IV</td>
		<td align="left">:</td> 
		<td align="left">				
			<input type="text" name="n_eselon_ivx" id="n_eselon_ivx" size="80" value="<?=$this->n_eselon_iv?>">
		</td>
	</tr>
</table>

