<? require_once 'Zend/View.php';
   require_once 'share/absensidate.php';
   require_once 'share/halaman.php';

   $ctrlFrm = new Zend_View();
   $convDate = new absensidate();
   $halaman = new halaman();
   $bulanDesc = array("01"=>"Januari",
                      "02"=>"Februari",
                      "03"=>"Maret",
                      "04"=>"April",
                      "05"=>"Mei",
                      "06"=>"Juni",
                      "07"=>"Juli",
                      "08"=>"Agustus",
                      "09"=>"September",
                      "10"=>"Oktober",
                      "11"=>"November",
                      "12"=>"Desember");

$thnSekarang = $this->thnSekarang;
$blnSekarang = $this->blnSekarang;
echo "
<div class='contentdata-modul' id='modul'>
	<div class='navlink'>
		<a  href='".$this->basePath."/main'>Halaman Utama</a> 
		<strong> &#8250; </strong> SDM 
		<strong> &#8250; </strong> Absensi
	</div>
	<h3 class='title'>Buat Hari Kerja</h3>
	<div class='spacer'></div>
	<a name='top'></a>
<form method='post' name='frmbuathrkerja' id='frmbuathrkerja'>
	<div class='search-panel'>
		<fieldset class='panel-form3'>
            <dl>
			   <dt>Bulan</dt>
			   <dd class='dot2'>:</dd>
			   <dd class='col-right3'>";
		  			$thn_atr = array("style"=>"width:40px",
							"maxlength"=>"4");
		  			$bln_atr = array("style"=>"width:100px");
							echo $ctrlFrm->formSelect('blnHariKerja', $blnSekarang, $bln_atr, $bulanDesc)."&nbsp;";
							echo $ctrlFrm->formText('thnHariKerja', $thnSekarang, $thn_atr)."&nbsp;";
echo "
               </dd>
			   <dt></dt>
			   <dd class='dot2'></dd>
			   <dd class='col-right3'>";
  			   $submit_atr = array("style"=>"width:150px");
			   echo $ctrlFrm->formSubmit('ibiBuat', 'Buat Hari Kerja', $submit_atr);
echo "
                </dd>
			</dl>
		</fieldset>";
echo "<a href='#' onclick='funcCreateJamKerja()'>&nbsp;&nbsp;</a>
	<fieldset class='fields' id='fiIsiHariKerja'>
			<table align='center' border='1' cellspacing='0' cellpadding='2' class='tbl'>
				<tr>
					<th rowspan='2'>No</th>			
					<th rowspan='2'>Tanggal</th>
					<th rowspan='2'>Hari</th>
					<th colspan='2'>Jam Kerja</th>
					<th colspan='2'>Jam Istirahat</th>		
					<th rowspan='2'>Status</th>
				</tr>
				<tr>
					<th>Mulai</th>			
					<th>Selesai</th>
					<th>mulai</th>
					<th>Selesai</th>
				</tr>";
	   $hari = array("Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu");
	   $bulan = array("","Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September",
	   "Oktober","November","Desember");
	$dataygAda = $this->sdm_absen_serv->cekHariKerja($thnSekarang,$blnSekarang);
	if ($dataygAda>0)
	{
	   $bln=$blnSekarang;
	   $noUrut=0;
	   //$i=0;
       for ($i=1; $i<32; $i++)
       {
          $tahunE = date("Y", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $bulanE = date("m", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $tglE = date("d", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $hariE = date("w", mktime(0, 0, 0, $bln, $i, $thnSekarang));
		  $datatglketemu = $this->sdm_absen_serv->getJamHariKerja($tglE.$bln.$thnSekarang);
		  if ($bulanE==$bln)
          { 
		     $noUrut++;
		     if ($i%2==0)
			 { 
			    if (($hariE=="0") || ($hariE=="6") || ($datatglketemu['d_jamkerja_mulai']==''))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event' id='triHariKe$i'>"; 
				}
			 }
			 else
			 { 
			    if (($hariE=="0") || ($hariE=="6") || ($datatglketemu['d_jamkerja_mulai']==''))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event2' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event2' id='triHariKe$i'>"; 
				}
			 }
echo "				
					<td class='clcenter'>".$noUrut."</td>			
					<td class='clcenter'>".$tglE."</td>			
					<td class='clleft'>".$hari[$hariE]."</td>			
					<td class='clcenter'>";
					$mskMulai = $datatglketemu['d_jamkerja_mulai'];  //"07:30:00";
echo "				<input type='text' id='itMskMulai$i' name='itMskMulai$i' value='".
                    $mskMulai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$mskSelesai = $datatglketemu['d_jamkerja_selesai'];  //"16:30:00";
echo "				<input type='text' id='itMskSelesai$i' name='itMskSelesai$i' value='".
                    $mskSelesai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakMulai = $datatglketemu['d_jamistrht_mulai'];  //"12:00:00";
echo "				<input type='text' id='itBreakMulai$i' name='itBreakMulai$i' value='".
                    $breakMulai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakSelesai = $datatglketemu['d_jamistrht_selesai'];  //"14:00:00";
echo "				<input type='text' id='itBreakSelesai$i' name='itBreakSelesai$i' value='".
                    $breakSelesai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td align='left'>
					<input type='hidden' id='ihiStatus$i' name='ihiStatus$i' value='".$valStatus."'>
					<input type='checkbox' onClick='swtStatus(this.value)' id='iiStatus$i' name='iiStatus$i' value='".
					$i."' class='icSetStatus' $chCkd>&nbsp;<span id='siStatusHari$i'>".$valStatus."</span>
					</td>			
				</tr>";
		  }
       }
	   //endforeach;
	}
    else
    {	   
	   $bln=$blnSekarang;
	   $noUrut=0;
       for ($i=1; $i<32; $i++)
       {
          $tahunE = date("Y", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $bulanE = date("m", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $tglE = date("d", mktime(0, 0, 0, $bln, $i, $thnSekarang));
          $hariE = date("w", mktime(0, 0, 0, $bln, $i, $thnSekarang));
		  if ($bulanE==$bln)
          { 
		     $noUrut++;
		     if ($i%2==0)
			 { 
			    if (($hariE=="0") || ($hariE=="6"))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event' id='triHariKe$i'>"; 
				}
			 }
			 else
			 { 
			    if (($hariE=="0") || ($hariE=="6"))
				{ 
				   $chCkd = "Checked"; 
				   $dSbld = "disabled";
				   $valStatus = "Libur";
			       echo "<tr class='event2' id='triHariKe$i' style='color:red'>"; 
				}   
				else
				{
				   $chCkd = ""; 
				   $dSbld = "";
				   $valStatus = "Masuk";
			       echo "<tr class='event2' id='triHariKe$i'>"; 
				}
			 }
echo "				
					<td class='clcenter'>".$noUrut."</td>			
					<td class='clcenter'>".$tglE."</td>			
					<td class='clleft'>".$hari[$hariE]."</td>			
					<td class='clcenter'>";
					$mskMulai = "07:30:00";
echo "				<input type='text' id='itMskMulai$i' name='itMskMulai$i' value='".
                    $mskMulai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$mskSelesai = "16:30:00";
echo "				<input type='text' id='itMskSelesai$i' name='itMskSelesai$i' value='".
                    $mskSelesai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakMulai = "12:00:00";
echo "				<input type='text' id='itBreakMulai$i' name='itBreakMulai$i' value='".
                    $breakMulai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td class='clcenter'>";
					$breakSelesai = "14:00:00";
echo "				<input type='text' id='itBreakSelesai$i' name='itBreakSelesai$i' value='".
                    $breakSelesai."' style='width:60px' maxlength='8' ".$dSbld.">&nbsp;
					</td>			
					<td align='left'>
					<input type='hidden' id='ihiStatus$i' name='ihiStatus$i' value='".$valStatus."'>
					<input type='checkbox' onClick='swtStatus(this.value)' id='iiStatus$i' name='iiStatus$i' value='".
					$i."' class='icSetStatus' $chCkd>&nbsp;<span id='siStatusHari$i'>".$valStatus."</span>
					</td>			
				</tr>";
		  }
       }
	}
echo "
			</table>
	</fieldset>
	</div>
    </form>	
</div>";
	
	
