Welcome to &nbsp;
    <?php echo $this->view->userName .' ' .$this->view->userRole; ?>
    <a href="<?php echo $this->baseUrl();?>/admin/user" >help_desk</a>&nbsp;
    <a href="<?php echo $this->baseUrl();?>/admin/user" >online_demo</a>&nbsp;
    <a href="<?php echo $this->baseUrl();?>/admin/">contact</a>&nbsp;
    <a href="<?php echo $this->baseUrl();?>/user" >login</a>&nbsp;
    <a href="<?php echo $this->baseUrl();?>">register</a>
