<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta content="author" name="Gunabalans"/>
<title>Admissionoffice.net</title>
<!-- Framework CSS -->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/screen.css" type="text/css" media="screen, projection"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/plugins/mycss/mycss.css" type="text/css" media="screen, projection"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/print.css" type="text/css" media="print"/>
<!--[if lt IE 8]><link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/ie.css" type="text/css" media="screen, projection"/><![endif]-->