<? require_once 'Zend/View.php';
   
$ctrlFrm = new Zend_View();
	  
$jumhukumanList = count($this->hukumanList);  
   
$pesan = $this->pesan;
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Hukuman
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Hukuman</h2>
<?php //include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">		
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<br>
<? if ($this->sektoral =='W' && ($this->c_izin=="000002" || $this->c_izin=="000003")){?>  
<div class="add" title="Tambah Data" onclick="hukumanM('insert','');"></div>
<?}
	if ($jumhukumanList == 0) {
		echo "<font color=\"red\">Data Hukuman Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
		    <th width="10%">Jenis Pelanggaran</th>
			<th width="10%">Tingkat Hukuman</th>
			<th width="30%">Jenis Hukuman</th>
			<th width="20%">Alasan Hukuman</th>
			<th width="6%">Mulai</th>
			<th width="6%">Akhir</th>
			<th width="20%">Nomor SK / Tgl SK</th>
			<th width="6%" colspan="2">&nbsp;</th>
		</tr>
<?

	if ($jumhukumanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>			
			<td>&nbsp;</td>
			<td>&nbsp;</td>	
		
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->hukumanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					$id=trim($this->escape($val['id']));
					?>
				<td><a href="#" onclick="detilhukuman('<?=$id?>')"><?php  echo $this->escape($val['n_jns_pelanggaran']);?></a></td>
				<td>
					<?=$this->escape($val['nsanksi1'])?>
					<?php //echo ($this->escape($val['nsanksi1']) == '' ? $this->escape($val['nsanksi']) : $this->escape($val['jnssanksi']));?>
				</td>
				<td><?php  echo ''.($this->escape($val['nsanksi1']) == '' ? $this->escape($val['nsanksi']) :$this->escape($val['jnssanksi']));?></td>
				<td class="clcenter"><?php  echo $this->escape($val['e_alasan_sanksi']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_mulai_sanksi']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['d_akhir_sanksi']);?></td>
				<td class="clcenter">
					<u><?php echo $this->escape($val['i_sk_sanksi']);?></u><br>
					<?php echo $this->escape($val['d_sk_sanksi']);?>					
				</td>
				<td class="clcenter"><?php echo $this->escape($val['n_pejabat']);?></td>
<? if ($this->sektoral =='W' && ($this->c_izin=="000002" || $this->c_izin=="000003")){?>				
				<td class="clcenter">			
					<div class="edit" title="Ubah Data" onclick="hukumanM('update','<?=$id?>');"></div>	
				</td>
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDatahukuman('<?=$nip?>','<?=$id?>')"></div>
				</td>	
<?}else{?>
				<td class="clcenter">			
					<div class="edit" title="Lihat Data"  onclick="hukumanM('lihat','<?=$id?>')"></div>	
				</td>
<?}?>				

		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">		
				</tr>
						<tr>
							<td>
								<div class="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datahukuman/listpegawai','');"> 
								</div>
							</td>
						</tr>			
			</table>									
	</div>		 
	</form>
