<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();
 	  
$jumluarnegeriList = count($this->luarnegeriList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong>Luar Negeri
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Luar Negeri</h2>
<?php $opr='rlng';include "$this->leftMenu/linkriwayat.phtml";?>
<div class="boxholder">			
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	  
<div class="add" title="Tambah Data" onclick="LuarnegeriM('insert','');"></div>
<?}	if ($jumluarnegeriList == 0) {
		echo "<font color=\"red\">Data Luar Negeri Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
		<tr>
		    <th width="20%" rowspan="2">Negara</th>
			<th width="20%" rowspan="2">Tujuan</th>
			<th width="15%" rowspan="2">Pembiayaan</th>
			<th width="15%" rowspan="2">Sponsor</th>
			<th width="10%" rowspan="2">Tgl Berangkat</th>
			<th width="20%" colspan="3">Lama Kunjungan</th>
			<th width="6%"  rowspan="2" colspan="2">&nbsp;</th>
		</tr>
		<tr>
		    <th>Hari</th>
			<th>Bulan</th>
			<th>Tahun</th>
		</tr>		
<?
	if ($jumluarnegeriList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->luarnegeriList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>

				<td>
					<?php echo $this->escape($val['n_negara']);?>
				</td>
				<td><?php  echo $this->escape($val['a_tujuan']);?></td>
				<td><?php  echo $this->escape($val['n_biaya']);?></td>
				<td><?php  echo $this->escape($val['e_sponsor']);?></td>
				<td class="clcenter"><?php echo $this->escape($val['d_barangkat']);?></td>
				<td class="clright"><?php echo $this->escape($val['q_hari']);?></td>
				<td class="clright"><?php echo $this->escape($val['q_bulan']);?></td>
				<td class="clright"><?php echo $this->escape($val['q_tahun']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="LuarnegeriM('update','<?=trim($this->escape($val['id']))?>');"></div>	
				</td>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataLuarnegeri('<?=$nip?>','<?=trim($this->escape($val['id']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
						
									
	</div>		 
	</form>
