
function LuarnegeriM(par,id){
	url = "<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/luarnegeri"	
	var opt = {par:par,id:id};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formluarnegeri").ajaxForm(maintain_luarnegeri);
		});		
} 
var maintain_luarnegeri = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formluarnegeri;
		astr= "document.formluarnegeri";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!c_negara.value)){cekVal = sdmValidasiData(astr,"c_negara","Negara harus diisi....!");return false;break;}
				if((!a_tujuan.value)){cekVal = sdmValidasiData(astr,"a_tujuan","Kegiatan harus diisi....!");return false;break;}
				if((!d_barangkat.value)){cekVal = sdmValidasiData(astr,"d_barangkat","Tanggal Berangkat harus diisi....!");return false;break;}
				 break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formluarnegeri").ajaxForm(maintain_luarnegeri);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/maintaindata',
	type: 'post',
	resetForm: false
};
function insertLuarnegeri(){
	jQuery("#formluarnegeri").ajaxForm(maintain_luarnegeri);
}

function HapusDataLuarnegeri(nip,id)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/dataluarnegeri/hapusdata"
		var opt = {nip:nip,id:id};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
