<? require_once 'Zend/View.php';
   require_once 'share/pesan.php';
require_once 'share/halaman_list.php';

   $ctrlFrm = new Zend_View();
   $pesan = new pesan();
   $halaman = new halaman_list();

	  
$jumjabatanList = count($this->listJabatan);     
?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong>Referensi
			</div>
	        <a name="top"></a>
<?
$proses		= $this->proses;
$keterangan	= $this->keterangan;
$status		= $this->status;
echo $pesan->show_message($proses, $keterangan, $status);
?>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>					
</div>
	<h2 class="title">Referensi Jabatan</h2>

<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
  
<div class="add" title="Tambah Data" onclick="openFormJabatan('insert','','');"></div>
<?	if ($jumjabatanList == 0) {
		echo "<font color=\"red\">Data Referensi Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center" width="50%">
			<tr>
		    <th width="5%">Kode Jabatan</th>
			<th width="15%">Nama Jabatan</th>
			<th width="15%">Keterangan</th>
			<th width="5%">Tkfgs</th>
			<th width="5%">Kelfgs</th>
			<th width="5%">C Golr</th>
			<th width="5%">C Golt</th>
			<th width="10%">Nama Jenjang</th>
			<th width="5%">Kode Tanda</th>
			<th width="5%">Kode Eselon</th>
			<th width="5%">Kode Strata</th>
			<th width="5%">Q Tunjangan</th>
			<th width="5%">Q Usia Tunjangan</th>
			<th width="5%">Q Tktfgs</th>
			<th width="5%">Q ak_minimal</th>
			<th colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumjabatanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->listJabatan as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				
				<td><?php  echo $this->escape($val['c_jabatan']);?></td>
				<td><?php  echo $this->escape($val['n_jabatan']);?></td>
				<td><?php  echo $this->escape($val['e_keterangan']);?></td>
				<td><?php  echo $this->escape($val['c_tkfgs']);?></td>
				<td><?php  echo $this->escape($val['c_kelfgs']);?></td>
				<td><?php  echo $this->escape($val['c_golr']);?></td>
				<td><?php  echo $this->escape($val['c_golt']);?></td>
				<td><?php  echo $this->escape($val['n_jenjang']);?></td>
				<td><?php  echo $this->escape($val['c_tanda']);?></td>
				<td><?php  echo $this->escape($val['c_eselon']);?></td>
				<td><?php  echo $this->escape($val['c_strata']);?></td>
				<td><?php  echo $this->escape($val['q_tunjangan']);?></td>
				<td><?php  echo $this->escape($val['q_usia_pens']);?></td>
				<td><?php  echo $this->escape($val['q_tktfgs']);?></td>
				<td><?php  echo $this->escape($val['q_ak_minimal']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="openFormJabatan('update','<?=trim($this->escape($val['c_jabatan']))?>');"></div>	
				</td>
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusJabatan('Jabatan','<?=trim($this->escape($val['c_jabatan']))?>','<?=trim($this->escape($val['n_jabatan']))?>')"></div>
				</td>	
		  </tr>
	<?php endforeach; ?> 		  	  
<?	}	?>
	</table>									
	<?php
	$totalData = $this->totalData;
	$numToDisplay = $this->numToDisplay;
	$currentPage = $this->currentPage;
	$modul	= $this->basePath.'/sdmmodule/refjabatan/listjabatan';
	echo $halaman->halamanList($totalData, $numToDisplay, $currentPage, $modul);

	?>					
									
	</fieldset>		 
	</form>
