
function PasanganM(par,id){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datapasangan/pasangan"	
	var opt = {par:par,id:id};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formpasangan").ajaxForm(maintain_pasangan);
		});		
} 
var maintain_pasangan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formpasangan;
		astr= "document.formpasangan";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!c_pasangan.value)){cekVal = sdmValidasiData(astr,"c_pasangan","Pasangan harus diisi....!");return false;break;}
				//if((!q_pasangan.value)){cekVal = sdmValidasiData(astr,"q_pasangan","Pasangan ke harus diisi....!");return false;break;}
				if((!n_nama.value)){cekVal = sdmValidasiData(astr,"n_nama","Nama Suami/Istri ke harus diisi....!");return false;break;}
				break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formpasangan").ajaxForm(maintain_pasangan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datapasangan/maintaindata',
	type: 'post',
	resetForm: false
};
function insertPasangan(){
	jQuery("#formpasangan").ajaxForm(maintain_pasangan);
}

function HapusDataPasangan(nip,id)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datapasangan/hapusdata"
		var opt = {nip:nip,id:id};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
