<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
   $thnskrg = date("Y");
   $thnList = $thnskrg - 40;
   $thnArrayList[''] = '--';
   for ($i = 0; $i < 60; $i++) {
     $thnList = $thnList + 1;
     $thnArrayList[$thnList] = $thnList;
   }
   $biayaList = array("-"=>"--Pilih--","B"=>"Beasiswa","NB"=>"Non Beasiswa");	
?>
<div id="backgroundPopup"></div>
<div id="popupContact">  


<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
<tr>
<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
</tr>
</table>
			<div style="overflow: hidden;">
				<div class="wrap">
					<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
<h2 class="title">Detil Data Pendidikan</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">					
						<tr>
							<td width="20%">Jenjang Pendidikan
							
							</td>
							<td width="2%">:</td> 
							<td>
							<?php
								$jmljenjang = count($this->nmJenjangList);														   
								$jenjangReff[''] = '--Pilih--';
								for ($i = 0; $i < $jmljenjang; $i++) {
									$n_pend=trim($this->nmJenjangList[$i]['n_pend']);												   
									$jenjangReff[trim((string)$this->nmJenjangList[$i]['c_pend'])] = $n_pend;											   
								}
								$pendAtrib = array( "onclick" => "javascript:cPend();"); 
								echo $ctrlFrm->formSelect('c_pend',$this->c_pend,$pendAtrib,$jenjangReff);
								
							?>
							</td>
						</tr>
						<tr>
							<td>Nama Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								$pendidikanAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('n_pend_lembaga', $this->n_pend_lembaga, $pendidikanAtrib); 
							?>
							</td>
						</tr>
					<?if ($this->c_pend!='1' && $this->c_pend!='2'){?>	
						<tr id="idjur">
							<td>Jurusan</td>
							<td>:</td> 
							<td>
							<?php 
								$jurusanAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('n_pend_jurusan', $this->n_pend_jurusan, $jurusanAtrib);
							?>
							</td>
						</tr>
					<?}?>	
						<tr>
							<td>Alamat Sekolah</td>
							<td>:</td> 
							<td>
							<?php 
								$tempatAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('a_pend_alamat', $this->a_pend_alamat, $tempatAtrib);
							?>
							</td>
						</tr>
						<tr>
							<td>Nama Pimpinan</td>
							<td>:</td> 
							<td>
							<?php 
								$kepSekAtrib = array("size"=>"70",
												 "class"=>""); 
								echo $ctrlFrm->formText('n_pend_kepsek', $this->n_pend_kepsek, $kepSekAtrib);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Mulai</td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_mulai', $this->d_pend_mulai, null, $thnArrayList);
							?>
							</td>
						</tr>
						<tr>
							<td>Tahun Akhir</td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('d_pend_akhir', $this->d_pend_akhir, null, $thnArrayList);
							?>
							</td>
						</tr>
					<?if ($this->c_pend!='1' && $this->c_pend!='2'){?>		
						<tr id="idipk">
							<td>IPK / Nilai Ijazah</td>
							<td>:</td> 
							<td>
							<?php 
								$ipk = $_POST['ipk'];
								if ($ipk == '') {
									$ipk = 0.00;
								} 			
								$ipkAtrib = array("size"=>"10",
												 "maxlength"=>"5",
												 "class"=>"clright",
												 "id" => "i_pend_ipk",
												 "onKeyup" => "javascript:isNumber('i_pend_ipk');"); 
								echo $ctrlFrm->formText('i_pend_ipk', $this->i_pend_ipk, $ipkAtrib);
							 ?>
						<?
						echo "<font color=\"red\">00.00</font>";
						?>
							</td>
						</tr>
						<?}?>
						<tr>
							<td>Nomor Ijazah</td>
							<td>:</td> 
							<td>
							<?php 
								$noIjazahAtrib = array("size"=>"25",
												 "maxlength"=>"30",
												 "class"=>""); 
								echo $ctrlFrm->formText('i_pend_ijazah', $this->i_pend_ijazah, $noIjazahAtrib);
							 ?>
							</td>
						</tr>
						<tr>
							<td>Tanggal Ijazah</td>
							<td>:</td> 
							<td>
							<?php 
								//echo $ctrlDate->formatTanggal('d_pend_ijazah',$this->d_pend_ijazah); 	
							 ?>
								<input type="text" id="d_pend_ijazah" name="d_pend_ijazah" value="<?=$this->d_pend_ijazah?>" size = "15" onKeyUp="isNumber('i_waktu_mulai')">
							</td>
						</tr>
						<?if ($this->c_pend!='1' && $this->c_pend!='2'){?>	
						<tr id="iddana">
							<td>Sumber Biaya</td>
							<td>:</td> 
							<td>
							<?php 
								echo $ctrlFrm->formSelect('c_pend_sumberdana', $this->c_pend_sumberdana, null, $biayaList);
							?>
							</td>
						</tr>
						<tr id="idjudul">
							<td>Judul Skripsi</td>
							<td>:</td> 
							<td>
							<?php 
								$skripsiAtrib = array("rows"=>"3",
													    "cols"=>"20",
														"maxlength"=>"200",
													    "class"=>"medium"); 
								echo $ctrlFrm->formTextarea('e_pend_skripsi', $this->e_pend_skripsi, $skripsiAtrib);
							 ?>
							</td>
						</tr>
						<?}?>
						<tr>
							<td>Keterangan</td>
							<td>:</td> 
							<td>
							<?php 
								$keterangan = $_POST['keterangan'];
								if ($keterangan == '') {
									$keterangan = null;
								} 
								$keteranganAtrib = array("rows"=>"3",
													    "cols"=>"20",
														"maxlength"=>"200",
													    "class"=>"medium"); 
								echo $ctrlFrm->formTextarea('e_keterangan', $this->e_keterangan, $keteranganAtrib);
							 ?>
							</td>
						</tr>
			
			</table>

								<span class="corners-bottom"><span></span></span>
							</div>
						</div>
					</div><!-- wrap -->	
			</div>
	</div>
</div>