<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldptigaList = count($this->dptigaList);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong>&#8250;</strong>DP3
	</div>

	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">DP3</h2>
<?php $opr='kdp3';include "$this->leftMenu/linkdatakinerja.phtml";?>
<div class="boxholder">	
	<div class="panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<form action="" method="post"> 
		<fieldset class="fields"> 
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>			
			   <div class="add" title="Tambah Data" onclick="DptigaM('insert','<?=$this->nip?>');"></div>
<?}?>			   
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="sortable">
		<tr>
			<th>Tahun</th>
			<th>Kesetiaan</th>
			<th>Prestasi Kerja</th>
			<th>Tanggung Jawab</th>
			<th>Ketaatan</th>
			<th>Kejujuran</th>
			<th>Kerjasama</th>
			<th>Prakarsa</th>
			<th>Kepemimpinan</th>
			<th>Jumlah</th>
			<th width="5%" colspan="2">&nbsp;</th>
		</tr> 
<? 		if ($jmldptigaList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($this->dptigaList as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$id=$this->escape($val['id']);
				$i_peg_nip=$this->escape($val['i_peg_nip']);
				$d_peg_pnilai=$this->escape($val['d_peg_pnilai']);
				?>
					<td align="right"><?php echo $this->escape($val['d_peg_pnilai']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_kesetiaan']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_preskerja']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_tggjawab']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_ketaatan']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_kejujuran']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_kerjasama']);?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_prakarsa']);?></td>
					<td align="right"><?php echo ''.($this->escape($val['q_peg_kpimpinan']) > 0 ? $this->escape($val['q_peg_kpimpinan']) : '').'';?></td>
					<td align="right"><?php echo $this->escape($val['q_peg_totalnilai']);?></td>
					
					<td class="clcenter">
						<div class="edit" title="Ubah Data" onclick="DptigaM('update','<?=$i_peg_nip?>','<?=$id?>');"></div>	
					</td>
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>						
					<td class="clcenter">
						<div class="delete" title="Hapus Data"  onClick="javascript:HapusDatadptiga('<?=$i_peg_nip?>','<?=$id?>')"></div>
					</td>			
<?}?>					
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>		 
	</form>
