<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_sertifikat").datepicker();
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikteknis/listdiklat','');">Diklat Teknis</a>				
			<strong> &#8250; </strong><?=$this->jdl;?> Diklat Teknis
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Diklat Teknis</h2>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formteknis" method="post" name="formteknis" enctype="multipart/form-data">		
				<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>	
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
						<td  width="23%">Nama / NIP</td>
						<td width="2%">:</td> 
						<td width="75%"><?=$this->nama." / ".$this->nip;?></td>
					</tr>				
					<tr>
						<td  width="23%">Kelompok
						
						</td>
						<td width="2%">:</td> 
						<td width="75%">					
						<?php
						   $jmllistrkelteknis = count($this->listrkelteknis);
							for ($i = 0; $i < $jmllistrkelteknis; $i++) {	 
								if ($this->c_kelompok==$this->listrkelteknis[$i]->c_kelompok){echo $this->listrkelteknis[$i]->n_kelompok;}
						   }    
						?>					
						</td>
					</tr>
			
				<tr>
					<td>Nama Diklat
					
					</td>
					<td>:</td> 
					<td>
						<?=$this->n_diklat?>
					</td>
				</tr>
					<tr>
						<td  width="23%">Negara
						
						</td>
						<td width="2%">:</td> 
						<td width="75%">					
						<?php
						   $jmllistnegara = count($this->listnegara);
							for ($i = 0; $i < $jmllistnegara; $i++) {	 
								if ($this->c_negara==$this->listnegara[$i]->c_negara){echo $this->listnegara[$i]->n_negara;}
						   }    
						?>					
						</td>
					</tr>				
				<tr>
					<td>Lama Diklat (JPL)</td>
					<td>:</td> 
					<td>
						<?=$this->q_lama?>
					</td>
				</tr>
				<tr>
					<td>Penyelenggara</td>
					<td>:</td> 
					<td>
						<?=$this->n_penyelenggara?>
					</td>
				</tr>
				<tr>
					<td colspan="3"><h3 class="title"><b>SERTIFIKAT/STTPP</b><h3></td>
				</tr>
				<tr>
					<td>Nomor Sertifikat</td>
					<td>:</td> 
					<td>
						<?=$this->i_sertifikat?>
					</td>
				</tr>				
				<tr>
					<td>Tanggal Sertifikat</td>
					<td>:</td> 
					<td>
						<?=$this->d_sertifikat?>
					</td>
				</tr>	
				<tr>
					<td>Pejabat</td>
					<td>:</td> 
					<td>
						<?=$this->n_pejabat?>
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datadikteknis/listdiklat','');"> 									
							</td>
						</tr>
					</table>
</form>
	</div>
</div>	
	