<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php"; 
require_once 'share/halaman_list.php'; 
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$jmlnmPegList = count($this->pegawaiList);  
$halaman = new halaman_list(); 
?>
<div id="backgroundPopup"></div>
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
		<tr>
		<td>
			Pencarian berdasarkan :
			<?
				$cCol = array(""=>"--Pilih--",
						"i_peg_nip"=>"NIP",
						"n_peg"=>"Nama");								
				echo $ctrlFrm->formSelect('cCol', $this->cCol, null, $cCol); 							
			?>						
			<span id="targetcari"><input type="text" name="nCol" id="nCol" value="<?echo $this->nCol?>"></span>
			<input type="submit" value="Cari" onclick="javascript:cariListPegawai('<?=$this->par?>');">		
		</td>
		<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
		</tr>
		</table>
		<div style="overflow: hidden;">
			<div class="wrap">
				<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h2 class="title">Daftar Pegawai</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
						   <table align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
								<tr>
									<th width="4%">No.</th>
									<th width="10%">NIP</th>
									<th width="30%">Nama</th>
									<th width="15%">Gol/Pangkat</th>
									<th width="20%">Jabatan</th>
								</tr> 
<? 		if ($jmlnmPegList == 0) {?>
								<tr class="event">
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
									<td>&nbsp;</td>
								</tr>	
<?		}else{
				foreach ($this->pegawaiList as $key => $val):  
										if ($key%2==0) { ?>
										<tr class="event">
										<? } else if ($key%2==1) { ?>
										<tr class="event2">
										<? } 
										$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
										?>
											<td class="clcenter"><?php echo $noUrut;?></td>
											<td><a href="#" onclick="pilihData('<?=$this->par?>','<?php echo $this->escape($val['i_peg_nip']);?>','<?php echo $this->escape($val['n_peg']);?>','<?php echo $this->escape($val['n_jabatan']);?>')"><?php echo $this->escape($val['i_peg_nip']);?></a></td>
											<td><?php echo $this->escape($val['n_peg']);?></td>
											<td><?php echo $this->escape($val['n_nama']);?></td>
											<td><?php echo $this->escape($val['n_jabatan']);?></td>		
										</tr>
<?php 
				endforeach;}
?>
							
							</table>
<?
$orderBy=$this->orderBy;
//$modul = $this->basePath."/sdmmodule/detil/listpegawaidptiga";
$modul = $this->basePath."/sdmmodule/detil/listpegawaidptiga?orderBy=$orderBy&order=$this->orderbya&cCol=$this->cCol&nCol=$this->nCol$par=$this->par";
echo $halaman->halamanListPopup($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>								
						<span class="corners-bottom"><span></span></span>
					</div>
				</div>
			</div><!-- wrap -->	
		</div>
		</div>
	</div>

<script>
function pilihData(par,nip,nama,jabatan){
if (par=='b'){
	document.getElementById('i_peg_nipatasanpnilai').value=nip;
	document.getElementById('n_peg_nipatasanpnilai').value=nama;	
	document.getElementById('n_jabatan_atasanpnilai').value=jabatan;	
	}
else{
	document.getElementById('i_peg_nippnilai').value=nip;
	document.getElementById('n_peg_nippnilai').value=nama;	
	document.getElementById('n_jabatan_pnilai').value=jabatan;
	document.getElementById('i_peg_nippnilai').focus();
}
	document.getElementById('i_peg_nippnilai').focus();	
	closeDetil();
}

function cariListPegawai(par){
var cCol=document.getElementById('cCol').value;
var nCol=document.getElementById('nCol').value;
var url = '<?php echo $this->basePath; ?>/sdmmodule/detil/listpegawaidptiga';
var param = {par:par,cCol:cCol,nCol:nCol};
jQuery.get(url,param,function(data) {
jQuery("#popupview").html(data);
centerPopup();
loadPopup();
});}
</script>