<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>
<div id="backgroundPopup">
<div id="popupContact">  


<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
<tr>
<td><div class="delete" title="Close" onclick="closeDetil()"></div></td>
</tr>
</table>
			<div style="overflow: hidden;">
				<div class="wrap">
					<div class="panel" style="height: 500px;overflow: auto;border: solid 1px #000;padding: 5px;" >
<h2 class="title">Detil Data Pegawai</h2>					
					<div class="inner">					
						<span class="corners-top"><span></span></span>
						<div class="spacer"></div> 
					<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std" >
						<tr>
						<td>Nama Pegawai</td>
						<td>:</td> 
						<td>
							<input type="text" size="60" name="n_peg" id="n_peg" value="<?=$this->n_peg?>" >
						</td>
						</tr>
						<tr>
							<td>NIP / Id Pegawai</td>
							<td>:</td> 
							<td>
								<input type="text" size="10" name="i_peg_nip" id="i_peg_nip" readonly="true" value="<?=$this->i_peg_nip?>">
							</td>
						</tr>
						<tr>
							<td>Gelar Depan</td>
							<td>:</td> 
							<td>
								<input type="text" size="5" name="n_peg_gelardepan" id="n_peg_gelardepan" value="<?=$this->n_peg_gelardepan?>">
								&nbsp;&nbsp;Gelar Belakang   :  
								<input type="text" size="15" name="n_peg_gelarblkg" id="n_peg_gelarblkg" value="<?=$this->n_peg_gelarblkg?>">
							</td>
						</tr>
						<tr>
							<td>NPWP</td>
							<td>:</td> 
							<td>
							<?
								$value=$this->i_npwp;
								$val = explode(".",$value);
								$val2 = explode("-",$val[3]);
								$event = "onKeyUp=\"if(($('".$fieldId."1').value)||($('".$fieldId."2').value)||($('".$fieldId."3').value)||($('".$fieldId."4').value)||($('".$fieldId."5').value))$('".$fieldId."').value=''+$('".$fieldId."1').value+'.'+$('".$fieldId."2').value+'.'+$('".$fieldId."3').value+'.'+$('".$fieldId."4').value+'-'+$('".$fieldId."5').value+'.'+$('".$fieldId."6').value+'';else $('".$fieldId."').value=null;\"";
								if (!$size) $size = Array(2,3,3,1,3,3);
								$xsize = $size[0]+$size[1]+$size[2]+$size[3]+$size[4]+$size[5]+5;
								$h .= $f."<input id='".$fieldId."1' name='".$fieldId."1' type='".$type."' size='".$size[0]."' maxlength='".$size[0]."' title='".$title."' value='".$val[0]."' ".$event.">";
								$h .= "<b>.</b>&nbsp;";
								$h .= "<input id='".$fieldId."2' name='".$fieldId."2' type='text' size='".$size[1]."' maxlength='".$size[1]."' title='".$title."' value='".$val[1]."' ".$event.">";
								$h .= "<b>.</b>&nbsp;";
								$h .= "<input id='".$fieldId."3' name='".$fieldId."3' type='text' size='".$size[2]."' maxlength='".$size[2]."' title='".$title."' value='".$val[2]."' ".$event.">";
								$h .= "<b>.</b>&nbsp;";
								$h .= "<input id='".$fieldId."4' name='".$fieldId."4' type='text' size='".$size[3]."' maxlength='".$size[3]."' title='".$title."' value='".$val2[0]."' ".$event.">";
								$h .= "<b>-</b>&nbsp;";
								$h .= "<input id='".$fieldId."5' name='".$fieldId."5' type='text' size='".$size[4]."' maxlength='".$size[4]."' title='".$title."' value='".$val2[1]."' ".$event.">".$d;
								$h .= "<b>.</b>&nbsp;";
								$h .= "<input id='".$fieldId."6' name='".$fieldId."6' type='text' size='".$size[5]."' maxlength='".$size[5]."' title='".$title."' value='".$val[4]."' ".$event.">".$d;
								$h .= "<input id='".$fieldId."' name='".$fieldId."' type='hidden' size='".$xsize."' maxlength='".$xsize."' class='".$c." validate-npwp' title='".$title."' value='".$value."'>";
								echo $h;
							?>
							</td>
						</tr>
						<tr>
							<td>KARPEG
								
							</td>
							<td>:</td> 
							<td>
								<input type="text" size="25" name="i_peg_karpeg" id="i_peg_karpeg" value="<?=$this->i_peg_karpeg?>">
							</td>
						</tr>
						<tr>
							<td>Jenis Kelamin</td>
							<td>:</td> 
							<td>
							<?php 

								   $jenisKelaminList = array("-"=>"--Pilih--",
															"L"=>"Laki-laki",
															"P"=>"Perempuan");
								echo $ctrlFrm->formSelect('c_peg_jeniskelamin', $this->c_peg_jeniskelamin, null, $jenisKelaminList);
							?>
							</td>
						</tr>
						<tr>
							<td>Tempat Lahir</td>
							<td>:</td> 
							<td>
								<input type="text" size="35" name="a_peg_lahir" id="a_peg_lahir" value="<?=$this->a_peg_lahir?>">
							</td>
						</tr>
						<tr>
							<td>Tanggal Lahir</td>
							<td>:</td> 
							<td>
						    <?php 
								echo $tanggal->formatTanggal("d_peg_lahir",$this->d_peg_lahir); 			 
							 ?>
							</td>
						</tr>

						<tr>
							<td>Eselon</td>
							<td>:</td> 
							<td>
							<?php 
								$eselonList = array("-"=>"--Pilih--",
											  "NE"=>"Non Eselon",
											  "MT"=>"Ketua Mahkamah",
											  "I.a"=>"I.a",
											  "I.b"=>"I.b",
											  "II.a"=>"II.a",
											  "III.a"=>"III.a",
											  "IV.a"=>"IV.a");
								echo $ctrlFrm->formSelect('eselon', $eselon, $eselonAtrib, $eselonList) ?>
								&nbsp;TMT Eselon&nbsp;&nbsp;:
							<?php
								echo $tanggal->formatTanggal("d_eselon_tmt",$this->d_eselon_tmt); 		
							?>	
							</td>
						</tr>				
						<tr>
							<td>Unit Kerja</td>
							<td>:</td> 
							<td>
							<?php 					
								$jmlUnitOrgList = count($this->unitOList);
								$unitOList['-'] = '--Pilih--';
								for ($i = 0; $i < $jmlUnitOrgList; $i++) {
								$unitOList[(string)$this->unitOList[$i]->i_orgb] = (string)$this->unitOList[$i]->n_orgb;			 
								}
								$unitOrgAtrib = array("id"=>"orgSelect","onClick"=>"javascript:cariSatker()","style"=>"width:400px"); 
								echo $ctrlFrm->formSelect('i_orgb', $this->i_orgb, $unitOrgAtrib, $unitOList) ?>					
							</td>
						</tr>
						
						<tr>
							<td>Satuan Kerja</td>
							<td>:</td> 
							<td id="targetsatker">
							<?php 
								   $jmlUnitKerjaList = count($this->unitKList);
								   $unitKList['-'] = '--Pilih--';
								    for ($i = 0; $i < $jmlUnitKerjaList; $i++) {
								    $unitKList[(string)$this->unitKList[$i]->i_orgb] = (string)$this->unitKList[$i]->n_orgb;			 
								   }
								$unitKerjaAtrib = array("style"=>"width:400px"); 								   
								echo $ctrlFrm->formSelect('c_unit_kerja', $this->c_unit_kerja, $unitKerjaAtrib, $unitKList);
							?>							
							</td>
						</tr>
						
						
						</tr>
							
						<tr>
							<td>Instansi Asal</td>
							<td>:</td> 
							<td>
								<input type="text" size="35" name="i_peg_karpegX" id="i_peg_karpegX" value="<?=$this->i_peg_karpegX?>">
							</td>
						</tr>				
						<tr>
							<td>TMT CPNS</td>
							<td>:</td> 
							<td>
						    <?php 
								echo $tanggal->formatTanggal("d_peg_tmtmasuk",$this->d_peg_tmtmasuk);	
							?>		 					
							</td>
						</tr>
						<tr>
							<td>Status Pegawai</td>
							<td>:</td> 
							<td>
							<?php 
								   $jmlStatList = count($this->statusPegList);
								   $statusPegList['-'] = '--Pilih--';
								   for ($i = 0; $i < $jmlStatList; $i++) {
								   $statusPegList[(string)$this->statusPegList[$i]->c_peg_status] = (string)$this->statusPegList[$i]->n_peg_status;			 
								   }
								echo $ctrlFrm->formSelect('c_peg_status', $this->c_peg_status,null, $statusPegList);
							?>
							</td>
						</tr>
						<tr>
							<td>Agama</td>
							<td>:</td> 
							<td>
							<?php 
								   $jmlAgamaList = count($this->agamaList);
								   $agamaList['-'] = '--Pilih--';
								   for ($i = 0; $i < $jmlAgamaList; $i++) {
								    $agamaList[(string)$this->agamaList[$i]->c_agama] = (string)$this->agamaList[$i]->n_agama;			 
								   }							
								echo $ctrlFrm->formSelect('c_agama', $this->c_agama,null, $agamaList); 
							?>
							</td>
						</tr>	
						<tr>
							<td valign="top">Alamat</td>
							<td valign="top">:</td> 
							<td>
								<textarea rows="2" cols="60" name="a_peg_rumah" id="a_peg_rumah"><?=$this->a_peg_rumah?></textarea>
							</td>
						</tr>
						<tr>
							<td>RT / RW</td>
							<td>:</td> 
							<td>
								<input type="text" size="5" name="a_peg_rt" id="a_peg_rt" value="<?=$this->a_peg_rt?>"> /
								<input type="text" size="5" name="a_peg_rw" id="a_peg_rw" value="<?=$this->a_peg_rw?>">
							</td>
						</tr>
						<tr>
							<td>Kelurahan</td>
							<td>:</td> 
							<td>
								<input type="text" size="65" name="a_peg_kelurahan" id="a_peg_kelurahan" value="<?=$this->a_peg_kelurahan?>">
							</td>
						</tr>
						<tr>
							<td>Kecamatan</td>
							<td>:</td> 
							<td>
								<input type="text" size="65" name="a_peg_kecamatan" id="a_peg_kecamatan" value="<?=$this->a_peg_kecamatan?>">
							</td>
						</tr>
						<tr>
							<td>Propinsi</td>
							<td>:</td> 
							<td>
							<?php 
								   $jmlPropList = count($this->propinsiList);
								   $propinsiList['-'] = '--Pilih--';
								   for ($i = 0; $i < $jmlPropList; $i++) {
								   $propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
								   }
								$propAtrib = array("id"=>"propinsiSelect","onClick"=>"javascript:cariKabupaten()"); 
								echo $ctrlFrm->formSelect('a_peg_propinsi', $this->a_peg_propinsi, $propAtrib, $propinsiList)
							?>
							</td>
						</tr>
						<tr>
							<td>Kabupaten</td>
							<td>:</td> 
							<td id="targetkabupaten">
							<?php 
								$jmlKabList = count($this->kabupatenList);
								$kabupatenList['-'] = '--Pilih--';
								for ($i = 0; $i < $jmlKabList; $i++) {
									$kabupatenList[(string)$this->kabupatenList[$i]->c_kabupaten] = (string)$this->kabupatenList[$i]->n_kabupaten;			 
								}
								echo $ctrlFrm->formSelect('kabupaten', $kabupaten,null, $kabupatenList);
							?>
							</td>
						</tr>
						<tr>
							<td>Kode Pos</td>
							<td>:</td> 
							<td>
								<input type="text" size="10" name="a_peg_kodepos" id="a_peg_kodepos" value="<?=$this->a_peg_kodepos?>" onblur="checkNumber()">
							</td>
						</tr>
						<tr>
							<td>Telepon Rumah
								
							</td>
							<td>:</td> 
							<td>
							<?
								$value=$this->i_peg_telponrumah;
								$val = explode("-",$value);
								$size="10";
								if (!$size) $size = Array(5,10);
								$xsize = $size[0]+$size[1]+1;
								$event = "  onkeypress=javascript:checkNumber(this); ";
								$h = $f."<input id='".$fieldId."1' name='".$fieldId."1' type='text' size='".$size[0]."' maxlength='".$size[0]."' title='".$title."' value='".$val[0]."' $event>";
								$h .= "<b>-</b>&nbsp;";
								$h .= "<input id='".$fieldId."2' name='".$fieldId."2' type='text' size='".$size[1]."' maxlength='".$size[1]."' title='".$title."' value='".$val[1]."' $event>".$d;
								$h .= "<input id='".$fieldId."' name='".$fieldId."' type='hidden' size='".$xsize."' maxlength='".$xsize."' class='".$c." validate-telp' title='".$title."' value='".$value."'>";
								echo $h;
							?>
							</td>
						</tr>
						<tr>
							<td>Telepon Genggam</td>
							<td>:</td> 
							<td>
								<input type="text" size="15" name="i_peg_telponhp" id="i_peg_telponhp" value="<?=$this->i_peg_telponhp?>" onblur="checkNumber()">
							</td>
						</tr>
						<tr>
							<td>Email</td>
							<td>:</td> 
							<td>
								<input type="text" size="25" name="i_peg_email" id="i_peg_email" value="<?=$this->i_peg_email?>">
							</td>
						</tr>
						<tr>
							<td>Email 2</td>
							<td>:</td> 
							<td>
								<input type="text" size="25" name="i_peg_email2" id="i_peg_email2" value="<?=$this->i_peg_email2?>">
							</td>
						</tr>
						<tr>
							<td>Status Nikah</td>
							<td>:</td> 
							<td>
							<?php 
								$stsNikah = $this->escape($this->stsNikah);
								if (($stsNikah == '') || ($stsNikah == null)) {
									$stsNikah = $_POST['stsNikah'];
								} 
								$stsNikahOpsi = array("M"=>"Menikah",
													"B"=>"Belum Menikah",
													"J"=>"Janda", 
													"D"=>"Duda"); 
								echo $ctrlFrm->formRadio('stsNikah', $stsNikah, $stsNikah, $stsNikahOpsi, "&nbsp;"); 
							?>			
							</td>
						</tr>
						<tr>
							<td>Kewarganegaraan</td>
							<td>:</td> 
							<td>
							<?php 
								   $wnList = array("-"=>"--Pilih--",
										                  "WNI"=>"WNI",
										                  "WNA"=>"WNA");
								echo $ctrlFrm->formSelect('n_peg_wn', $this->n_peg_wn,null, $wnList) ?>
							</td>
						</tr>
						<tr>
							<td>Identitas Diri</td>
							<td>:</td> 
							<td>
							<?php 
								   $jenisIdentitasList = array("-"=>"--Pilih--", "KTP"=>"KTP","SIM"=>"SIM","PASPOR"=>"PASPOR");	
								echo $ctrlFrm->formSelect('c_peg_identitas', $this->c_peg_identitas, null, $jenisIdentitasList) ?>
							</td>
						</tr>
						<tr>
							<td>No Identitas</td>
							<td>:</td> 
							<td>
								<input type="text" size="25" name="i_peg_identitas" id="i_peg_identitas" value="<?=$this->i_peg_identitas?>">
							</td>
						</tr>

						<tr>
							<td>Jumlah Anak</td>
							<td>:</td> 
							<td>
								<input type="text" size="5" name="v_jumlah_anak" id="v_jumlah_anak" value="<?=$this->v_jumlah_anak?>"  onblur="checkNumber()">
							</td>
						</tr>
						<tr>
							<td>Golongan Darah</td>
							<td>:</td> 
							<td>
							<?php
								$darahList = array("-"=>"--Pilih--","A"=>"A","B"=>"B","AB"=>"AB","O"=>"O");	
								echo $ctrlFrm->formSelect('c_golongan_darah', $this->c_golongan_darah,null, $darahList); 
							?>							
							</td>
						</tr>	
						<tr>
							<td>Hobi</td>
							<td>:</td> 
							<td>
								<input type="text" size="70" name="n_peg_hobi" id="n_peg_hobi" value="<?=$this->n_peg_hobi?>">
							</td>
						</tr>
					</table>

								<span class="corners-bottom"><span></span></span>
							</div>
						</div>
					</div><!-- wrap -->	
			</div>
	</div>
</div>
</div>	
