function cetakCv()
{
	url = "<?php echo $this->basePath; ?>/sdmmodule/datacv/datacv?par=cetak"	
	BukaWindows('1000','600');
}

function BukaWindows(wid,heg){
	var w = 0; 
	var h = 0;
	w = screen.availWidth;
	h = screen.availHeight;
	var popW = wid, popH = heg;
	var leftc = (w-popW)/2;
	var topc = (h-popH)/2;
	var selectWindow = window.open(url,'Selection', 'left=' + leftc + ',top=' + topc + ', width='+popW+',height='+popH+',resizable=0,scrollbars=yes');
}