function KepangkatanM(par,c_jns_kepangkatan,d_test_kepangkatan){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datakepangkatan/kepangkatan"	
	var opt = {par:par,d_test_kepangkatan:d_test_kepangkatan,c_jns_kepangkatan:c_jns_kepangkatan};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formkepangkatan").ajaxForm(maintain_kepangkatan);
		});		
} 
var maintain_kepangkatan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formkepangkatan;
		astr= "document.formkepangkatan";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!c_jns_kepangkatan.value)){cekVal = sdmValidasiData(astr,"c_jns_kepangkatan","Jenis Kepangkatan harus diisi....!");return false;break;}
				if((!d_test_kepangkatan.value)){cekVal = sdmValidasiData(astr,"d_test_kepangkatan","Tanggal Test harus diisi....!");return false;break;}
				break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formkepangkatan").ajaxForm(maintain_kepangkatan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datakepangkatan/maintaindata',
	type: 'post',
	resetForm: false
};

function insertKepangkatan(){
	jQuery("#formkepangkatan").ajaxForm(maintain_kepangkatan);
}

function HapusDataKepangkatan(nip,c_jns_kepangkatan,d_test_kepangkatan)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datakepangkatan/hapusdata"
		var opt = {nip:nip,c_jns_kepangkatan:c_jns_kepangkatan,d_test_kepangkatan:d_test_kepangkatan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}
