<? require_once 'Zend/View.php';
   
   $ctrlFrm = new Zend_View();

	  
$jumkepangkatanList = count($this->kepangkatanList);     
$pesan = $this->pesan;
$spath = $this->getScriptPaths();
$this->addScriptPath($spath[0] . 'pegawai');
$pesancek=$this->pesancek;
if ($pesancek=='gagal'){$confirm ='confirmfail';}
else {$confirm ='confirm';}	  

?>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Tes Kepangkatan
			</div>
	        <a name="top"></a>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
</div>
	<h2 class="title">Data Tes Kepangkatan</h2>
	<?php include "$this->leftMenu/linkdatapenilaian.phtml";?>				
	<div class="boxholder">	
	<div class="search-panel">
	<?php include "$this->leftMenu/toplink.phtml";?>
</div>			
<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
   <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	 
<div class="add" title="Tambah Data" onclick="KepangkatanM('insert','');"></div>
<?}	if ($jumkepangkatanList == 0) {
		echo "<font color=\"red\">Data Bahasa Tidak Ditemukan</font>";
}
?>
		<table class="tbl" cellspacing="1" cellpadding="2" border="0" align="center">
			<tr>
		    <th>Jenis Kepangkatan</th>
			<th>Tanggal</th>
			<th>Tempat</th>
			<th>Hasil</th>
			<th>Nomor SK/Tgl SK</th>
			<th width="6%" colspan="2">&nbsp;</th>
			</tr>		
<?
	if ($jumkepangkatanList == 0) {
?>		
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
<? 	}	else { ?>

		<?php foreach ($this->kepangkatanList as $key => $val): 
					   if ($key%2==0) { ?>
				      <tr class="event">
					<? } else if ($key%2==1) { ?>
					  <tr class="event2">
					<? } 
					$nip=trim($this->escape($val['i_peg_nip']));
					?>
				<td><?php echo $this->escape($val['n_jns_kepangkatan']);?></a></td>
				<td><?php  echo $this->escape($val['d_test_kepangkatan']);?></td>
				<td><?php  echo $this->escape($val['a_tempat_test']);?></td>
				<td class="clcenter"><?php  echo $this->escape($val['n_hasil_kepangkatan']);?></td>
				<td class="clcenter"><u><?php echo $this->escape($val['i_sk_kepangkatan']);?></u><br><?php echo $this->escape($val['d_sk_kepangkatan']);?></td>
				<td class="clcenter">			
					<div class="edit" title="Ubah Data"  onclick="KepangkatanM('update','<?=trim($this->escape($val['c_jns_kepangkatan']))?>','<?=trim($this->escape($val['d_test_kepangkatan']))?>');"></div>	
				</td>
  <?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>					
				<td class="clcenter">			
					<div class="delete" title="Hapus Data"  onClick="HapusDataKepangkatan('<?=$nip?>','<?=trim($this->escape($val['c_jns_kepangkatan']))?>','<?=trim($this->escape($val['d_test_kepangkatan']))?>')"></div>
				</td>	
<?}?>				
		  </tr>
	<?php endforeach;?> 		  	  
<?	}	?>
	</table>									
</div>	 
	</form>
