<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> Statistik
				<strong> &#8250; </strong> Statistik Tingkat Pendidikan
			</div>
<div id="top"></div>

	
<form id="formpegawai" method="post" action="" name="formpegawai"enctype="multipart/form-data" >
<h2 class="title">Statistik Tingkat Pendidikan</h2>
<?php include "$this->leftMenu/statistiklink.phtml";?>
<form id="formresult" method="post" action="" name="formresult">
	<div class="boxholder">	
	<div class="panel">
		<div class="spacer"></div> 
			
			<h3 class="title"><b><u>UNIT KERJA</u></b><h3>

	<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
		<tr>
			<td width="25%">Status Kepegawaian</td>
			<td width="2%">:</td>
			<td>
							<?php 
									   $jmlStatusKePegRef = count($this->statusKePegRef);
									   $statkepegList[''] = '--Pilih--';
									   for ($i = 0; $i < $jmlStatusKePegRef; $i++) {									   
										$statkepegList[(string)$this->statusKePegRef[$i]->c_status_kepegawaian] = (string)$this->statusKePegRef[$i]->n_status_kepegawaian;			 
									   }
									   $statkepegAtrib = array("onChange"=>"javascript:getStatPeg()");
									  echo $ctrlFrm->formSelect('c_status_kepegawaian', $this->c_status_kepegawaian,$statkepegAtrib, $statkepegList)
								?>							
			</td>
		</tr>		
		<tr>
			<td width="25%">Eselon</td>
			<td width="2%">:</td> 
			<td>				
									<?
										$jmlEslList=count($this->eselonList);
										$eslList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlEslList; $i++) {
												$eslList[(string)$this->eselonList[$i]->c_eselon] = (string)$this->eselonList[$i]->n_eselon;			 
											}
										$eslAtrib = array("onChange"=>"javascript:getEselon()"); 		
										echo $ctrlFrm->formSelect('c_eselon',$this->c_eselon, $eslAtrib, $eslList); 							
									?>
			</td>
		</tr>
	</table>			
	<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">

		<tr>
			<td width="25%">Lokasi</td>
			<td width="2%">:</td> 
			<td>					
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon II</td>
			<td>:</td> 
			<td>				
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliii')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
			</td>
			</tr>						
		<tr>
			<td>Eselon III</td>
			<td>:</td> 
			<td>					
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","disabled"=>"true","onChange"=>"javascript:cariCombo('targetesliv')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon IV</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv." ".(string)$this->eselonivList[$i]->n_unitkerja] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","disabled"=>"true","onChange"=>"javascript:cariCombo('targeteslv')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon V</td>
			<td>:</td> 
			<td>				
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v." ".(string)$this->eselonvList[$i]->n_unitkerja] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
										else{$eslAtrib = array("style"=>"width: 300px","disabled"=>"true","id"=>"c_eselon_v");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			</td>
		</tr>							
	</table>
	</div>
<br>	
	<div class="panel">
			<table border="0" cellpadding="0" cellspacing="1" class="std" width="100%">
							<tr>
								<td align="center">
								<input type="button" value="Grafik Bar" onclick="viewStatPend('bar');"> &nbsp;
								<input type="button" value="Grafik Pie" onclick="viewStatPend('pie');"> 
								</td>
							</tr>	
							
			</table>
	</div>
<!--	
<br>	
<div class="panel">	
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
				<td colspan="2" align="left">
					<h3 class="title"><b>Jenis Laporan</b><h3>
				</td>
				</tr>
				<tr>
					<td width="50%">
						<table>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Tingkat Pendidikan
								</td>
							</tr>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Kelas Umur
								</td>
							</tr>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Kelompok Fungsional
								</td>
							</tr>
					
						</table>	
					</td>
					<td width="50%">
						<table>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Jenis Jabatan
								</td>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Lokasi Unit Kerja
								</td>
							</tr>
							<tr>					
								<td>
									<input type="radio" name="profilfoto" id="profilfoto-1" value="1"> Menurut Golongan Per Kelompok Fungsional (detil)
								</td>
							</tr>
					
							</tr>
						</table>	
					</td>					
				</tr>
		</table>
</div>
<br>
	<div class="panel">		
			<table width="100%">	
				<tr>
				<td align="center">
					<input type="button" value="View Laporan" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datacpns/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datacpns/pegawaijs');">
				</td>
				</tr>
				<tr>				
			</table>				
	</div>
-->	
</div>
	<div id="popupview"></div>
</form>	
