<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_sertifikat").datepicker();
		jQuery("#d_diklat").datepicker();
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datakejuruanmiliter/listkejuruanmiliter','');">Pendidikan Kejuruan Militer</a>				
				<strong> &#8250; </strong><?=$this->jdl;?> Pendidikan Kejuruan Militer
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Pendidikan Kejuruan Militer</h2>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formdikmil" method="post" name="formdikmil" >		
<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
					<td  width="23%">Kelompok/Jenis</td>
					<td  width="2%">:</td> 
					<td>
						<?php
						   $jmlcmbkelompok = count($this->cmbkelompok);
						   $cmbkelompok[''] = '--Pilih--';
							for ($i = 0; $i < $jmlcmbkelompok; $i++) {	 
								$cmbkelompok[$this->cmbkelompok[$i]->c_jenis_kel]= (string)$this->cmbkelompok[$i]->n_jenis_kel;			 
							}  
							echo $ctrlFrm->formSelect('c_jenis_kel', $this->c_jenis_kel, null, $cmbkelompok);
						?>
					</td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td> 
					<td>
						<?php
						   $jmlcmbkejuruan = count($this->cmbkejuruan);
						   $cmbkejuruan[''] = '--Pilih--';
							for ($i = 0; $i < $jmlcmbkejuruan; $i++) {	 
								$cmbkejuruan[$this->cmbkejuruan[$i]->c_kejuruanmil]= (string)$this->cmbkejuruan[$i]->n_kejuruanmil;			 
						   }    
							echo $ctrlFrm->formSelect('c_kejuruanmil', $this->c_kejuruanmil, null, $cmbkejuruan);
						?>
					</td>
				</tr>					
				<tr>
					<td>Tahun Masuk</td>
					<td>:</td> 
					<td>					
						<input type="text" name="d_tahun_masuk" id="d_tahun_masuk" value="<?=$this->d_tahun_masuk?>" size="5">
					</td>
				</tr>				
				<tr>
					<td>Tahun Lulus</td>
					<td>:</td> 
					<td>
						<input type="text" name="d_tahun_lulus" id="d_tahun_lulus" value="<?=$this->d_tahun_lulus?>" size="5">
					</td>
				</tr>
				<tr>
					<td>Status</td>
					<td>:</td> 
					<td>
					<?
						$cmbstatus = array(""=>"--Pilih--",
								"1"=>"Lulus",
								"2"=>"Tidak Lulus");
						echo $ctrlFrm->formSelect('c_status',$this->c_status, null, $cmbstatus);
					?>	
					</td>
				</tr>
	
				<tr>
					<td>Tempat</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_tempat" id="n_tempat" value="<?=$this->n_tempat?>" size="80">
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="left">ket :&nbsp;()&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datakejuruanmiliter/listkejuruanmiliter','');"> 									
							</td>
						</tr>
					</table>
</form>
	</div>
	</div>
	