<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
	
$vFoto = $this->basePath."/upld/Uploaddata/getphoto?f=".trim($this->filephoto);
?>
		   <div class="navlink">
					<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Photo
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form name="formphoto" id="formphoto" enctype="multipart/form-data" method="post" action="">
<h2 class="title"><?=$this->jdl;?> Data Photo</h2>
	<?if ($this->par=='Ubah'){$readonly="readonly='true'"?>	                    
<?php $opr='ppht';include "$this->leftMenu/linkdatapokok.phtml";?>

	<?php 
	}?>
<div class="boxholder">					
	<div class="box">	
		<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
			<tr>
				<td width="5%">NIP</td>
				<td width="2%">:</td>
				<td width="10%"><?=$this->nipnew;?>
				<input type="hidden" size="15" maxlength="20" name="i_peg_nip" id="i_peg_nip" value="<?=$this->nip?>">
				</td>
				<td width="5%">Nama</td>
				<td width="2%">:</td>
				<td><?=$this->nama;?></td>					
			</tr>
		</table>		
	</div>
	<div class="panel">	
		<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
			<tr>
				<td align="left">
					<img src="<?=$vFoto?>" width="190" height="200" >
				</td>		
			</tr>
			<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>	
			<tr>
				<td valign="bottom">
					<div class="fileinputs">
						<input type="file" size=25 id="photo" name="photo"  value="<? echo $a_file?>"onChange="setvalueuplfile(this.value,'photo','jpg')" />
						<div class="fakefile">
							<input type="text" size=24 name="a_file" id="a_file" value="<? echo $a_file?>"/> 
						</div> (.jpg  / .gif / .png)
					</div>
					<input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $a_file?>"/>								
				</td>		
			</tr>
			<?}?>	
		</table>		
	</div>	
	
<br>
	<div class="panel">
		<div class="spacer"></div>
<?if ($this->c_izin=='000002' || $this->c_izin=='000003'){ ?>			
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td></td>
							<td align="right">
								<div class="right">									
									<input type="submit" value="Ubah" onClick="insertPhoto()">
									<input type="submit" value="Hapus" onClick="deletePhoto()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
								</div>
							</td>
						</tr>
			</table>
<?}?>			
</div>			
	</div>
</form>	
