<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_sertifikat").datepicker();
		jQuery("#d_diklat").datepicker();
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikanmiliter/listpendidikanmiliter','');">Pendidikan Militer</a>				
			<strong> &#8250; </strong><?=$this->jdl;?> Pendidikan Militer
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Pendidikan Militer</h2>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formdikmil" method="post" name="formdikmil" >		
<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
					<td  width="23%">Jenjang<span class="hightlight">*</span></td>
					<td  width="2%">:</td> 
					<td>
						<?php
						   $jmlcmbjenjang = count($this->cmbjenjang);
						   $cmbjenjang[''] = '--Pilih--';
							for ($i = 0; $i < $jmlcmbjenjang; $i++) {	 
								$cmbjenjang[$this->cmbjenjang[$i]->c_jenjang]= (string)$this->cmbjenjang[$i]->n_jenjang;			 
							}  
							echo $ctrlFrm->formSelect('c_jenjang', $this->c_jenjang, null, $cmbjenjang);
						?>
					</td>
				</tr>
				<tr>
					<td>Sekolah<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>
						<?php
						   $jmlcmbsekolah = count($this->cmbsekolah);
						   $cmbsekolah[''] = '--Pilih--';
							for ($i = 0; $i < $jmlcmbsekolah; $i++) {	 
								$cmbsekolah[$this->cmbsekolah[$i]->c_sekolahmil ]= (string)$this->cmbsekolah[$i]->n_sekolahmil;			 
						   }    
							echo $ctrlFrm->formSelect('c_sekolahmil', $this->c_sekolahmil, null, $cmbsekolah);
						?>
					</td>
				</tr>					
				<tr>
					<td>Tahun Masuk<span class="hightlight">*</span></td>
					<td>:</td> 
					<td>					
						<input type="text" name="d_tahun_masuk" id="d_tahun_masuk" value="<?=$this->d_tahun_masuk?>" size="5">
					</td>
				</tr>				
				<tr>
					<td>Tahun Lulus</td>
					<td>:</td> 
					<td>
						<input type="text" name="d_tahun_lulus" id="d_tahun_lulus" value="<?=$this->d_tahun_lulus?>" size="5">
					</td>
				</tr>
				<tr>
					<td>Status</td>
					<td>:</td> 
					<td>
					<?
						$cmbstatus = array(""=>"--Pilih--",
								"1"=>"Lulus",
								"2"=>"Tidak Lulus");
						echo $ctrlFrm->formSelect('c_status',$this->c_status, null, $cmbstatus);
					?>	
					</td>
				</tr>
	
				<tr>
					<td>Tempat</td>
					<td>:</td> 
					<td>
						<input type="text" name="n_tempat" id="n_tempat" value="<?=$this->n_tempat?>" size="80">
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapendidikanmiliter/listpendidikanmiliter','');"> 									
									<input type="submit" value="<?=$this->par;?>" onClick="insertDikMil()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
									<input type="hidden" name="c_jenjang2" value="<?=$this->c_jenjang;?>">
									<input type="hidden" name="c_sekolahmil2" value="<?=$this->c_sekolahmil;?>">
									<input type="hidden" name="d_tahun_masuk2" value="<?=$this->d_tahun_masuk;?>">
							</td>
						</tr>
					</table>
</form>
	</div>
	</div>
	