<?php 
require_once 'share/halaman_list.php'; 
$halaman = new halaman_list(); 
?>
<div id="backgroundPopup"></div>
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1">
			<tr>
				<td align="center">
					<?echo $this->judul;?>
				</td>
			</tr>
			<tr>
				<td align="right">
					<!--<div class="delete" title="Close" onclick="closeDetil()"></div>-->
					<input type="button" value="Keluar"  onclick="closeDetil()">
					<!--<div class="view" title="Cetak Excel" onclick="viewExl()"></div>-->
				</td>
			</tr>
		</table>		
		<div style="height: 450px; overflow: auto; padding: 5px  width=300px">	
		<?
		echo $this->view;
		?>	
		</div>	
		<?		
		$modul = $this->basePath."/sdmmodule/monitoringperiodik/view?limit=$this->limit&c_eselon_i=$this->c_eselon_i&c_eselon_ii=$this->c_eselon_ii&c_eselon_iii=$this->c_eselon_iii&c_eselon_iv=$this->c_eselon_iv&c_eselon_v=$this->c_eselon_v&c_lokasi_unitkerja=$this->c_lokasi_unitkerja&semester=$this->semester&start=$this->start&tahunsemester=$this->tahunsemester";
		echo $halaman->halamanListPopup($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
		?>			
	</div>
	
