<? require_once 'Zend/View.php';   
	$ctrlFrm = new Zend_View();
   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_sertifikat").datepicker();
		jQuery("#d_diklat").datepicker();
	});
</script>
		   <div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdmmodule/datapegawai/pegawaijs');">Data Pegawai</a>
			<strong> &#8250; </strong>
			<a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datakejuruanmiliter/listkejuruanmiliter','');">Pendidikan Kejuruan Militer</a>				
				<strong> &#8250; </strong><?=$this->jdl;?> Pendidikan Kejuruan Militer
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
<br>	
</div>

	<h2 class="title"><?=$this->jdl;?> Pendidikan Kejuruan Militer</h2>

<div class="boxholder">					
	<div class="panel">
		<?php include "$this->leftMenu/toplink.phtml";?>
	</div>
	<br>
		
<form id="formdikmil" method="post" name="formdikmil" >		
<?echo $ctrlFrm->formHidden('i_peg_nip', $this->nip, null); 	?>
<div class="panel">				
				<div class="spacer"></div> 
				<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
					<tr>
					<td  width="23%">Kelompok/Jenis</td>
					<td  width="2%">:</td> 
					<td>
						<?php
						   $jmlcmbkelompok = count($this->cmbkelompok);
							for ($i = 0; $i < $jmlcmbkelompok; $i++) {	 
								if ($this->c_jenis_kel==$this->cmbkelompok[$i]->c_jenis_kel){echo $this->cmbkelompok[$i]->n_jenis_kel;}
							}  
						?>
					</td>
				</tr>
				<tr>
					<td>Nama</td>
					<td>:</td> 
					<td>
						<?php
						   $jmlcmbkejuruan = count($this->cmbkejuruan);
							for ($i = 0; $i < $jmlcmbkejuruan; $i++) {	 
								if ($this->c_kejuruanmil==$this->cmbkejuruan[$i]->c_kejuruanmil){echo $this->cmbkejuruan[$i]->n_kejuruanmil;}
						   }    
						?>
					</td>
				</tr>					
				<tr>
					<td>Tahun Masuk</td>
					<td>:</td> 
					<td>					
						<?=$this->d_tahun_masuk?>
					</td>
				</tr>				
				<tr>
					<td>Tahun Lulus</td>
					<td>:</td> 
					<td>
						<?=$this->d_tahun_lulus?>
					</td>
				</tr>
				<tr>
					<td>Status</td>
					<td>:</td> 
					<td>
					<?
						if ($this->c_status=="1"){echo "Lulus";}
						elseif ($this->c_status=="2"){echo "Tidak Lulus";}
						else{echo "-";}
					?>	
					</td>
				</tr>
	
				<tr>
					<td>Tempat</td>
					<td>:</td> 
					<td>
						<?=$this->n_tempat?>
					</td>
				</tr>
	</table>
	</div>
	<br>
	<div class="panel">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
						<tr>
							<td align="left">ket :&nbsp;()&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
									<input type="button" value="Kembali" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datakejuruanmiliter/listkejuruanmiliter','');"> 									
							</td>
						</tr>
					</table>
</form>
	</div>
	</div>
	