<? require_once 'Zend/View.php';
    require_once 'share/halaman_list.php';
  
	$ctrlFrm = new Zend_View();
	$halaman = new halaman_list(); 
  
	$jmldptigaList = count($this->dptigaList);

	$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}  
?>
	<div class="navlink">
			<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong>&#8250;</strong>TPM
			<strong>&#8250;</strong>Pra TPM
	</div>
	<form method="post" id="frmCariUsulanTPM" name="frmCariUsulanTPM">


	<div id="top"></div>
	<div id="confirm" class="<?=$confirm?>" style="display: none">
		<h2 class="title"><?echo $pesan = $this->pesan;?></h2>				
	</div>
	<h2 class="title">Pra TPM</h2>
<div class="panel">	
No Surat : <input type="text" name="periode" id="periode" value="<?echo $this->periode?>" size="5">
	  <!---select name="cd_proses" id="cd_proses">
	   <?
	 /* foreach($this->filtperiode as $key => $value){
		$sel='';
		if($key == $this->cd_proses){$sel='selected';}
		?><option value="<?=$key?>" <?=$sel?>><?=$value?></option><?
	   }
	   */
	  ?>
	   
	  </select--->
	  <input type="button" value="Cari" onclick="javascript:cariPeriode();">
	</form>
		<fieldset class="fields"> 
<div class="add" title="Tambah Data" onclick="praTpmM('insert','');"></div>
   <table width="100%" border="0" cellpadding="0" cellspacing="1" class="tbl">
		<tr>
			<th width="13%">Nomor Surat d</th>
			<th width="20%">Usulan Jabatan</th>
			<th>Unit Kerja</th>
			<th width="8%">Tanggal<br>Pra TPM</th>
			<th width="10%">Status</th>
			<th width="10%">Proses </th>
		</tr> 
<? 		if (count($this->dataTpmUsul) == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
								
				foreach ($this->dataTpmUsul as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="event">
				<? } else if ($key%2==1) { ?>
				<tr class="event2">
				<? } 
				$usulan_id=$this->escape($val['usulan_id']);
				$c_proses = $this->escape($val['c_proses']);
				?>
					<td align="left"><?php echo $this->escape($val['usulan_nomor']);?></td>
					<td align="left"><?php echo $this->escape($val['n_jabatan']);?></td>					
					<td align="left">
					<?php 

					echo ''.($this->escape($val['neselon4']) ? $this->escape($val['neselon4']).', ':"").($this->escape($val['neselon3']) ? $this->escape($val['neselon3']).', ' :'').($this->escape($val['neselon2']) ? $this->escape($val['neselon2']).', ':"").$this->escape($val['neselon1']);
					?>
					</td>
					<td align="center"><?php echo $this->escape($val['tgl_pratpm']);?></td>
					<td align="left">
					<?php 
					if($c_proses == '1') echo 'Pra TPM';
					else if($c_proses == '2') echo 'TPM 1';
					else if($c_proses == '3') echo 'TPM 2';
					else if($c_proses == '4') echo 'Hasil TPM';
					?>
					</td>
					
					<td class="clcenter">
					<? 
					if ($c_proses == 1) { ?> 
						<a href=# onClick="praTpmM('update','<?=$usulan_id?>')"><img src="icon/icon_ubah.gif" title="Ubah Data Pra TPM" alt="Ubah Data Pra TPM"></a> - 
						<? 
					} 
						if($c_proses > 0){?> <a href=# onClick="viewTpm('0','<?=$usulan_id?>','pratpm')"><img src="icon/icon_lihat.gif" title="View Pra TPM" alt="View Pra TPM"></a>
						<?}
						if($c_proses > 1){?> - <a href=# onClick="viewTpm('1','<?=$usulan_id?>','pratpm')"><img src="icon/icon_lihat.gif" title="View  TPM 1" alt="View  TPM 1"></a>
						<?}
						if($c_proses > 2){?>- <a href=# onClick="viewTpm('2','<?=$usulan_id?>','pratpm')"><img src="icon/icon_lihat.gif" title="View  TPM 2" alt="View  TPM 2"></a>
						<?}
					?>	
					</td>	
					
					
				</tr>
				<?php endforeach;}?>
	
	</table>
	</div>
<?php

$modul = $this->basePath."/sdmmodule/tpm/listpratpm?periode=$this->periode"; 
//echo $halaman->halamanList($this->totalpegawaiList, $this->numToDisplay, $this->currentPage, $modul)
?>
<script>

function cariPeriode(){
	var periode=document.getElementById('periode').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/tpm/listpratpm'; 
	var param = {periode:periode};
	jQuery.get(url, param, function(data) {
		jQuery("#tableview").html(data);
	});
}
</script>