<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
$ceseloncpns=$this->ceseloncpns*1;
?>

 	<script type="text/javascript">
	jQuery(function() {
		jQuery("#mod_date").datepicker();
		
	});
	
	</script>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Depan</a> 
			<strong> &#8250; </strong><strong> &#8250; </strong> TPM &nbsp;
				<strong> &#8250; </strong><?=$this->jdl;?> TPM
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form id="formtpmusul" method="post" action="" name="formtpmusul"enctype="multipart/form-data" >
<h2 class="title"><?=$this->jdl;?></h2>	
<div class="panel">
<table width="100%">
	<tr>
		<td width="22%">Nomor Surat</td>
		<td width="2%">:</td>
		<td><?=$this->usulan_nomor?>
		</td>
	</tr>
	<tr>
		<td width="22%">Usulan Jabatan</td>
		<td width="2%">:</td>
		<td><?=$this->n_jabatan?>
		</td>
	</tr>
</table>
<?
$c_eselon_i=trim($this->c_eselon_ix);
if ($c_eselon_i=='03' || $c_eselon_i=='04' || $c_eselon_i=='05')
{include("unitkerjay.phtml");}
else{include("unitkerjax.phtml");}
?>
<table width="100%">	
	<tr>
		<td width="20%">Periode</td>
		<td width="2%">:</td>
		<td><?=$this->periode_text?>
		</td>
	</tr>		
	<tr>
		<td>Keterangan</td>
		<td>:</td>
		<td><?=$this->periode_keterangan?>
		</td>
	</tr>
	<tr>
	<td width="22%">Tanggal </td>
	<td width="2%">:</td>
	<td><?
	if($this->c_proses == '0' ) {$jdulket = $this->ket_pratpm;echo $this->tgl_pratpm;}
	else if($this->c_proses == '1' ) {$jdulket = $this->ket_tpm1;echo $this->tgl_tpm1;}
	else if($this->c_proses == '2' ) {$jdulket = $this->ket_tpm2;echo $this->tgl_tpm2;}
	
	?>
	</td>
	</tr>
	<tr>
	<td width="22%">Judul</td>
	<td width="2%">:</td>
	<td><?=$jdulket?>
	</td>
	</tr>
	</table>
</table>
  <table  align="center" border="0" cellspacing="1" cellpadding="2" class="tbl">
				<th width="22%">NIP</th>
				<th width="38%">Nama</th>
				<th width="25%">Status / No. Surat Rekomendasi</th>
				
<?
$jnsstatus = array("0"=>"--Pilih--","2"=>"Dipending","3"=>"Disetujui");
if(count($this->dataPraTpm) > 0){						
$con=1;				
foreach ($this->dataPraTpm as $key => $val):
	if ($key%2==0) { ?>
				<tr class="event" id="tr_<?echo $con?>">
	<? } else if ($key%2==1) { ?>
				<tr class="event2" id="tr_<?echo $con?>">
	<? } 
	?>
	<td width="22%">
						<?php echo $this->escape($val['peg_nip']);?>
	</td>
	<td width="38%"><?php echo trim($this->escape($val['tpm_namalengkap']));?>		
	<td width="25%">
	<? 
	if($this->c_proses == '0' ) { //pra  tpm 
		$rekomendasi = $this->escape($val['usulan_rekomendasi_pratpm']); 
		$tpm_status = '';//$this->escape($val['tpm_status_1']);
	}
	else if($this->c_proses == '1' ) { // tpm 1
		$rekomendasi = $this->escape($val['usulan_rekomendasi_tpmi']); 
		$tpm_status = $this->escape($val['tpm_status_2']);
	}
	else if($this->c_proses == '2' ) { // tpm2
		$rekomendasi = $this->escape($val['usulan_rekomendasi_tpmii']); 
		$tpm_status = $this->escape($val['tpm_status_3']);
	}
	if($rekomendasi) echo $rekomendasi;
	if($tpm_status) echo ''.$jnsstatus[$tpm_status];
		?>						
		</td>
		</tr>
		<?
	$con++; endforeach;
}
		?>
</table>
		
</div>
	
	<div class="panel">

		<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">	
			<tr>
				<td align="left"></td>
				<td></td>
				<td align="right">
					<input type="button" value="Back" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/tpm/list<?=$this->varback?>','<?php echo $this->basePath; ?>/sdmmodule/tpm/tpmjs');"> 									
				</td>
			</tr>
		</table>

	</div>
<div id="popupview"></div>

</form>
	