
function jabatanM(par,c_eselon,c_jabatan,d_mulai_jabat){
	url = "<?php echo $this->basePath; ?>/sdmmodule/datajabatan/jabatan"	
	var opt = {par:par,c_eselon:c_eselon,c_jabatan:c_jabatan,d_mulai_jabat:d_mulai_jabat};
	jQuery.get(url,opt,function(data) {
		jQuery("#tableview").html(data);
			jQuery("#formjabatan").ajaxForm(maintain_jabatan);
		});		
} 
var maintain_jabatan = {
	target:'#tableview',
	beforeSubmit: function() {
		aobj= document.formjabatan;
		astr= "document.formjabatan";
		var cekVal=true;
		with(aobj){      
			var Proceed = 1;
			while (Proceed == 1)
			{
				/*sdmValidasiData (navigation.js)*/				
				if((!c_eselon.value)){cekVal = sdmValidasiData(astr,"c_eselon","Eselon harus diisi....!");return false;break;}
				if((!c_jabatan.value)){cekVal = sdmValidasiData(astr,"c_jabatan","Nama jabatan ke harus diisi....!");return false;break;}
				if((!d_mulai_jabat.value)){cekVal = sdmValidasiData(astr,"d_mulai_jabat","Tanggal mulai menjabat ke harus diisi....!");return false;break;}	
				if((!d_akhir_jabat.value)){cekVal = sdmValidasiData(astr,"d_akhir_jabat","Tanggal akhir menjabat ke harus diisi....!");return false;break;}	
				if (d_akhir_jabat.value && d_mulai_jabat.value){
					cekVal = compareDate(d_mulai_jabat.value,d_akhir_jabat.value);
					if (cekVal == false) {return false;break;}						
				}
				break;
			}
		}
		}, 
	success:function(){
		location.href="#top";
		doCounter(5);
		jQuery("#formjabatan").ajaxForm(maintain_jabatan);
	},
	url: '<?php echo $this->basePath; ?>/sdmmodule/datajabatan/maintaindata',
	type: 'post',
	resetForm: false
};
function insertJabatan(){
	jQuery("#formjabatan").ajaxForm(maintain_jabatan);
}

function HapusDatajabatan(nip)
{
	var where_to= confirm("Yakin anda akan hapus data ini ???");
	 if (where_to== true)
	 {
		url = "<?php echo $this->basePath; ?>/sdmmodule/datajabatan/hapusdata"
		var opt = {nip:nip,n_jabatan:n_jabatan};
		jQuery.get(url,opt,function(data) {
			jQuery("#tableview").html(data);
				location.href="#top";
				doCounter(5);
			});
	 }
}

function Left(str, n){
	if (n <= 0)
	    return "";
	else if (n > String(str).length)
	    return str;
	else
	    return String(str).substring(3,n);
}

function Right(str, n){
    if (n <= 0)
       return "";
    else if (n > String(str).length)
       return str;
    else {
       var iLen = String(str).length;
       return String(str).substring(iLen, iLen - n);
    }
}