<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Kelompok Fungsional
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Kelompok Fungsional</h2>	
		
<form id="formkelfungsional" method="post" name="formkelfungsional">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode kelfungsional<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_kelfungsional" id="c_kelfungsional" value="<?=$this->detailKelfungsional['c_kelfungsional']?>" size="70" maxlength="2">
					</td>
				</tr><tr>
					<td>Nama Diklat fungsional<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_kelfungsional" id="n_kelfungsional" value="<?=$this->detailKelfungsional['n_kelfungsional']?>" size="70" >
					</td>
				</tr><tr>
					<td>Kode Filter<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_filter" id="c_filter" value="<?=$this->detailKelfungsional['c_filter']?>" size="70" maxlength="1">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refkelfungsional/listkelfungsional','<?php echo $this->basePath; ?>/sdmmodule/refkelfungsional/kelfungsionaljs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertKelfungsional()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateKelfungsional()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
