<div id="backgroundPopup"></div>
	<div id="popupContact">
		<table width="100%" border="0" cellpadding="0" cellspacing="1">
			<tr>
				<td align="center">
					<?echo $this->judul;?>
				</td>
			</tr>
			<tr>
				<td align="right">
					<input type="button" value="Keluar"  onclick="closeDetil()">
				</td>
			</tr>
		</table>	
		<center>
		<div class="hideshow">
			<table border="0" width="100%" align="center">
				<tr>
					<td align="center">
						<?echo $this->chart;?>
						<table border="0" width="80%" align="center" class="tbl2">
							<tr>
								<th>Eselon I</th>
								<th>Eselon II</th>
								<th>Eselon III</th>
								<th>Eselon IV</th>
								<th>Eselon V</th>
								<th>Fungsional</th>
								<th>Pejabat Negara</th>
								<th>Tenaga Teknis Peradilan</th>
								<th>Ad Hoc</th>
								<th>Non Job</th>
								<th>Staf</th>
								<th>Data Kosong</th>
								<th>Total</th>
							</tr>
							<tr class="event2">
								<td align="right"><?=$this->esl1?></td>
								<td align="right"><?=$this->esl2?></td>
								<td align="right"><?=$this->esl3?></td>
								<td align="right"><?=$this->esl4?></td>
								<td align="right"><?=$this->esl5?></td>
								<td align="right"><?=$this->fungsional?></td>
								<td align="right"><?=$this->pn?></td>
								<td align="right"><?=$this->ttp?></td>
								<td align="right"><?=$this->adhoc?></td>
								<td align="right"><?=$this->nonjob?></td>
								<td align="right"><?=$this->staf?></td>
								<td align="right"><?=$this->jmlkosong?></td>
								<td align="right"><?=($this->esl1+$this->esl2+$this->esl3+$this->esl4+$this->esl5+$this->fungsional+$this->staf+$this->jmlkosong+$this->pn+$this->ttp+$this->adhoc+$this->nonjob)?></td>
							</tr>
						</table>
					</td>
				</tr>		
			</table>		
		</div>	
		</center>
	</div>
	