<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Jurusan Pendidikan
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Jurusan Pendidikan</h2>	
		
<form id="formjurusan" method="post" name="formjurusan">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Jurusan<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_jurusan" id="c_jurusan" value="<?=$this->detailJurusan['c_jurusan']?>" size="70" maxlength="4">
					</td>
				</tr><tr>
					<td>Nama Jurusan<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_jurusan" id="n_jurusan" value="<?=$this->detailJurusan['n_jurusan']?>" size="70" >
					</td>
				</tr><tr>
					<td>Q Strata<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="q_strata" id="q_strata" value="<?=$this->detailJurusan['q_strata']?>" size="70" maxlength="1">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refjurusan/listjurusan','<?php echo $this->basePath; ?>/sdmmodule/refjurusan/jurusanjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertJurusan()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updateJurusan()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
