
	<!-- what we do -->
	<div class="row">
		<div class="span8">
			<div class="title-divider">
				<h3>Produk Hukum</h3>
				<div class="divider-arrow"></div>
			</div>
		</div>
		<div class="span8">
			<div class="block-grey">
				<div class="block-light wrap15">
				<?php
					 $jmlkategoriprodhukumList = count($this->kategoriprodhukumList);
						//echo $jmlkategoriprodhukumList;
					   for ($j = 0; $j < $jmlkategoriprodhukumList; $j++) {
						 $kategoriprodhukum[$j] = array("c_kategori"=>(string)$this->kategoriprodhukumList[$j]['c_kategori'],
						 "n_kategori"=>(string)$this->kategoriprodhukumList[$j]['n_kategori'],
											"n_judul"=>(string)$this->kategoriprodhukumList[$j]['n_judul'],
											 "n_detil"=>(string)$this->kategoriprodhukumList[$j]['n_detil'],
											 "c_produkhukum"=>(string)$this->kategoriprodhukumList[$j]['c_produkhukum'],
											 "n_file"=>(string)$this->kategoriprodhukumList[$j]['n_file'],
											"i_nomor_produkhukum"=>(string)$this->kategoriprodhukumList[$j]['i_nomor_produkhukum'],
											"d_tahun_produkhukum"=>(string)$this->kategoriprodhukumList[$j]['d_tahun_produkhukum'],
											  "c_status"=>(string)$this->kategoriprodhukumList[$j]['c_status']);
					   } 
		?>
					<table class="widefat sortable" cellspacing="1">
		<tr>
			<th class="nosort" width="5%">No.</th>
			<th width="30%">Judul</th>
			<th width="10%">Nomor</th>
			<th width="10%">Tahun</th>	
			<th width="15%">File</th>
			<th width="10%">Kategori</th>
		</tr> 
<? 		if ($jmlkategoriprodhukumList == 0) {?>
		<tr class="event">
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>	
<?}else{
				foreach ($kategoriprodhukum as $key => $val): 
				if ($key%2==0) { ?>
				<tr class="alternate">
				<? } else if ($key%2==1) { ?>
				<tr class="alternate2">
				<? } 
				$noUrut = (($this->currentPage -1)* $this->numToDisplay) + $key +1;
				$cstatus = $this->escape($val['c_status']);
				$date=formatDate2($this->escape($val['d_kategoriprodhukum']));
				if ($cstatus == 1) 	$status = 'Diterbitkan';
				else $status = 'Tidak Diterbitkan';
				
				?>
					<td class="clcenter"><?php echo $noUrut;?></td>
					<td><?php echo $this->escape($val['n_judul']);?></td>
					<td align="left"><?php echo $this->escape($val['i_nomor_produkhukum']);?></td>
					<td align="center"><?php echo $this->escape($val['d_tahun_produkhukum']);?></td>
					<td align="center"><a title="file <?php echo $this->escape($val['n_judul']);?>" href="<?php echo $path_data_produkhukum.$this->escape($val['n_file']);?>"><img src="images/word.png"></a></td>
					<td><?php echo $val['n_kategori'];?></td>
				</tr>
				<?php endforeach;}?>
	
			</table>
					
					
				</div>
			</div>
		</div>
	</div>
	<hr>	