<? require_once 'Zend/View.php';
   $ctrlFrm = new Zend_View();

   $pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}
?>
<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_tanggal_lahir").datepicker();
		jQuery("#d_tanggal_nikah").datepicker();
		
	});
</script>
		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a> 
				<strong> &#8250; </strong>SDM 
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/pegawaisearch','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Referensi</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Pengadilan
			</div>
<div id="top"></div>
	
	<h2 class="title"><?=$this->par;?> Referensi Pengadilan</h2>	
		
<form id="formpengadilan" method="post" name="formpengadilan">		
	<div class="panel">
		<div class="spacer"></div> 
			<table width="100%" border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>Kode Pengadilan<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_pengadilan" id="c_pengadilan" value="<?=$this->detailPengadilan['c_pengadilan']?>" size="70" maxlength="2" <? if($this->par != "insert"){ ?> readonly <? } ?> >
					</td>
				</tr><tr>
					<td>Nama Pengadilan<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_pengadilan" id="n_pengadilan" value="<?=$this->detailPengadilan['n_pengadilan']?>" size="70">
					</td>
				</tr><tr>
					<td>Kode Wilayah<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="c_wilayah" id="c_wilayah" value="<?=$this->detailPengadilan['c_wilayah']?>" size="70" maxlength="2">
					</td>
				</tr><tr>
					<td>Nama Wilayah<span class="hightlight">*</span>
					</td>
					<td>:</td> 
					<td>					
						<input type="text" name="n_wilayah" id="n_wilayah" value="<?=$this->detailPengadilan['n_wilayah']?>" size="70">
					</td>
				</tr>
				
				<tr>
					<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
					<td></td>
					<td>
						<div class="right">
							<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/refpengadilan/listpengadilan','<?php echo $this->basePath; ?>/sdmmodule/refpengadilan/pengadilanjs');"> 
							<?if ($this->par == 'insert'){?>
								<input type="submit" value="<?=$this->par;?>" onClick="insertPengadilan()">
							<?} else {?>
								<input type="submit" value="<?=$this->par;?>" onClick="updatePengadilan()">
							<?}?>
							<input type="hidden" name="proses" value="<?=$this->par;?>">
						</div>
					</td>
				</tr>			
			</table>
	</div>
	</form>
