<?php 
require_once 'Zend/View.php';
$ctrlFrm = new Zend_View();
?>
<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">		 
	<tr class="row1">
				<td align="left" width="120" nowrap="">Lokasi </td>
				<td align="left" colspan="2">
					<select id="operand" name="operand">
						<option value="=">Sama dengan</option>
						<option value="!=">Selain</option>
					</select>&nbsp;
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariComboLok('targetesli')"); 
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
				</td>
			</tr>
			<tr class="row">
				<td align="left" nowrap="">Eselon I </td>
				<td align="left" colspan="2">
					<select id="operand1" name="operand1">
						<option value="=">Sama dengan</option>	
						<option value="!=">Selain</option>
					</select>&nbsp;
									<?
										$jmleseloniList=count($this->eseloniList);
										$eseloniList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniList; $i++) {
												$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i] = (string)$this->eseloniList[$i]->n_unitkerja;			 
											}
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('a')");  	
										echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 							
									?>
       </td>
			</tr>
			<tr class="row1">
				<td align="left" nowrap="">Eselon II </td>
				<td align="left" colspan="2"><select id="operand2" name="operand2">
					<option value="=">Sama dengan</option>
					<option value="!=">Selain</option>
				</select>&nbsp;
									<?
										$jmleseloniiList=count($this->eseloniiList);
										$eseloniiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiList; $i++) {
												$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii] = (string)$this->eseloniiList[$i]->n_unitkerja;
											}
										if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('b')");}
										else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('b')");}
										echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 							
									?>
       </td>
			</tr>
			<tr class="row">
				<td align="left" nowrap="">Eselon III </td>
				<td align="left" colspan="2"><select id="operand3" name="operand3">
					<option value="=">Sama dengan</option>
					<option value="!=">Selain</option>
					</select>&nbsp;
									<?
										$jmleseloniiiList=count($this->eseloniiiList);
										$eseloniiiList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleseloniiiList; $i++) {
												$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
											}
										
										if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('c')");  	}										
										else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('c')");}
										
										echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 							
									?>
       </td>
			</tr>
			<tr class="row1">
				<td align="left" nowrap="">Eselon IV </td>
				<td align="left" colspan="2"><select id="operand4" name="operand4">
					<option value="=">Sama dengan</option>
					<option value="!=">Selain</option>
					</select>&nbsp;
									<?
										$jmleselonivList=count($this->eselonivList);
										$eselonivList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonivList; $i++) {
												$eselonivList[(string)$this->eselonivList[$i]->c_eselon_iv] = (string)$this->eselonivList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=7){
										$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('d')"); 
										}
										else{
										$eslAtrib = array("style"=>"width: 300px", "id"=>"c_eselon_iv","onChange"=>"javascript:cariCombo('d')"); 
										}
										
										
										echo $ctrlFrm->formSelect('c_eselon_iv',$this->c_eselon_iv,$eslAtrib,$eselonivList); 							
									?>
			 	</td>
			</tr>
			<tr class="row">
				<td align="left" nowrap="">Eselon V </td>
				<td align="left" colspan="2"><select id="operand5" name="operand5">
					<option value="=">Sama dengan</option>
					<option value="!=">Selain</option>
					</select>&nbsp;
									<?
										$jmleselonvList=count($this->eselonvList);
										$eselonvList[''] = '--Pilih--';
											for ($i = 0; $i < $jmleselonvList; $i++) {
												$eselonvList[(string)$this->eselonvList[$i]->c_eselon_v] = (string)$this->eselonvList[$i]->n_unitkerja;			 
											}
										if ($ceseloncpns>=9){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}										
										else{$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_v");}
										echo $ctrlFrm->formSelect('c_eselon_v',$this->c_eselon_v, $eslAtrib, $eselonvList); 							
									?>
			 	</td>
			</tr>
 
         
		</table>
