<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
$pesancek=$this->pesancek;

$pesancek=$this->pesancek;
	if ($pesancek=='gagal'){$confirm ='confirmfail';}
	else {$confirm ='confirm';}


$vFoto = $this->basePath."/data/sdm/photo/".trim($this->i_peg_nip).".jpg";
//if (!file_exists($vFoto)) {$vFoto = $this->basePath."/images/nophoto.jpg";} 

?>

 	<script type="text/javascript">
	jQuery(function() {
		jQuery("#d_eselon_tmt").datepicker();
		jQuery("#d_peg_lahir").datepicker();		
	});
	
	</script>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/home/index/main">Halaman Utama</a><strong> &#8250; </strong>Pegawai Baru
				<strong> &#8250; </strong><a href="#" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdm/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');">Data Pokok</a>
				<strong> &#8250; </strong><?=$this->jdl;?> Data Diri
			</div>
<div id="top"></div>
<div id="confirm" class="<?=$confirm?>" style="display: none">
	<h2 class="title"><?echo $pesan = $this->pesan;?></h2>	
	<br>	
</div>

	
<form id="formpegawai" method="post" action="" name="formpegawai"enctype="multipart/form-data" >
<h2 class="title"><?=$this->jdl;?> Data Diri</h2>

	<div class="panel">
		<div class="spacer"></div> 
	<?if ($this->par=='Ubah'){$readonly="readonly='true'"?>
	<?php include "$this->leftMenu/toplink.phtml";}?>

			<table border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td>&nbsp;</td>
				</tr>
			</table>
			<table border="0" cellpadding="0" cellspacing="1" class="std">
				<tr>
					<td width="70%">
						<table width="100%">
							<tr>
								<td width="35%">NIP / NIP Baru<span class="hightlight">*</span></td>
								<td width="2%">:</td>
								<td>
									<input type="text" size="15" maxlength="20" name="i_peg_nip" id="i_peg_nip" <?echo $readonly?> value="<?=$this->i_peg_nip?>"> /
									<input type="text" size="25" maxlength="20" name="i_peg_nip_new" id="i_peg_nip_new" <?echo $readonly?> value="<?=$this->i_peg_nip_new?>">
								</td>
							</tr>
							<tr>
								<td>Nama Lengkap<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<input type="text" size="40" maxlength="35" name="n_peg" id="n_peg" value="<?=$this->n_peg?>" >
								</td>
							</tr>
							<tr>
								<td>Gelar Depan / Gelar Blk</td>
								<td>:</td>
								<td>
									<input type="text" size="5" name="n_peg_gelardepan" id="n_peg_gelardepan" value="<?=$this->n_peg_gelardepan?>">
											&nbsp;/
									<input type="text" size="15" name="n_peg_gelarblkg" id="n_peg_gelarblkg" value="<?=$this->n_peg_gelarblkg?>">
								</td>
							</tr>
							<tr>
								<td>Gol. Darah / Status Nikah</td>
								<td>:</td>
								<td>
										<?php
											$darahList = array("-"=>"--Pilih--","A"=>"A","B"=>"B","AB"=>"AB","O"=>"O");	
											echo $ctrlFrm->formSelect('c_golongan_darah', $this->c_golongan_darah,null, $darahList); 
										?>	
											&nbsp;/
										<?php 
											$stsNikah = $this->escape($this->stsNikah);
											if (($stsNikah == '') || ($stsNikah == null)) {
												$stsNikah = $_POST['stsNikah'];
											} 
											$stsNikahOpsi = array("-"=>"--Pilih--","M"=>"Menikah","B"=>"Belum Menikah","J"=>"Janda","D"=>"Duda"); 
											echo $ctrlFrm->formSelect('c_peg_statusnikah', $this->c_peg_statusnikah, $stsNikah, $stsNikahOpsi, "&nbsp;"); 
										?>	
								</td>
							</tr>
							<tr>
								<td>Hobi</td>
								<td>:</td>
								<td>
									<input type="text" size="60" name="n_peg_hobi" id="n_peg_hobi" value="<?=$this->n_peg_hobi?>">
								</td>
							</tr>
						</table>
					</td>					
					<td width="30%">
						<table width="100%">
							<tr>
								<td>
									<img src="<?=$vFoto?>" width="90" height="100" ><br>
									<input type=checkbox name="del_photo"> Hapus
								</td>
								<td>
									<div class="fileinputs">
										<input type="file" size=15 id="a_filex" name="a_filex"  value="<? echo $a_file?>"onChange="setvalueuplpdf(this.value,'a_filex','jpg')" />
											<div class="fakefile">
												<input type="text" size=14 name="a_file" id="a_file" value="<? echo $a_file?>"/>
											</div>
									</div>
									<input type="hidden" size=49 name="a_file2" id="a_file2"value="<? echo $a_file?>"/>								
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>KELAHIRAN</b><h3>
								</td>
							</tr>
							<tr>
								<td>Propinsi<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
								<?php 
									   $jmlPropList = count($this->propinsiList);
									   $propinsiList[''] = '--Pilih--';
									   for ($i = 0; $i < $jmlPropList; $i++) {
										$propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
									   }
										$propAtrib = array("id"=>"propinsiLahir","onClick"=>"javascript:cariKabupaten('targetkablhr','propinsiLahir')"); 
										echo $ctrlFrm->formSelect('c_peg_propinsi_lahir', $this->c_peg_propinsi_lahir, $propAtrib, $propinsiList)
								?>
								</td>
							</tr>	
							<tr>
								<td>Kabupaten<span class="hightlight">*</span></td>
								<td>:</td>
								<td id="targetkablhr">
								<?php 
									$jmlKabList = count($this->kabupatenListLahir);
									$kabupatenListLahir[''] = '--Pilih--';
									for ($i = 0; $i < $jmlKabList; $i++) {
										$kabupatenListLahir[(string)$this->kabupatenListLahir[$i]->c_kabupaten] = (string)$this->kabupatenListLahir[$i]->n_kabupaten;			 
									}
									echo $ctrlFrm->formSelect('a_peg_kota_lahir', $this->a_peg_kota_lahir,null, $kabupatenListLahir);
								?>
								</td>
							</tr>	
							<tr>
								<td>Tanggal<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<input type="text" id="d_peg_lahir" name="d_peg_lahir" value="<?=$this->d_peg_lahir?>" size="10"> tgl-bln-thn
								</td>
							</tr>							
						</table>
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>CIRI-CIRI FISIK</b><h3>
								</td>								
							</tr>
							<tr>
								<td>Tinggi (cm) / Berat (cm)</td>
								<td>:</td>
								<td>
									<input type="text" size="10" name="q_peg_tinggibdn" id="q_peg_tinggibdn" value="<?=$this->q_peg_tinggibdn?>"  onkeyup="isNumber('q_peg_tinggibdn')"> /
									<input type="text" size="10" name="q_peg_beratbdn" id="q_peg_beratbdn" value="<?=$this->q_peg_beratbdn?>"  onkeyup="isNumber('q_peg_beratbdn')">
								</td>
							</tr>	
							<tr>
								<td>Rambut / Bentuk Muka</td>
								<td>:</td>
								<td>
									<input type="text" size="10" name="n_peg_rambut" id="n_peg_rambut" value="<?=$this->n_peg_rambut?>"> /
									<input type="text" size="10" name="n_peg_btkmuka" id="n_peg_btkmuka" value="<?=$this->n_peg_btkmuka?>">
								</td>
							</tr>
							<tr>
								<td>Warna Kulit / Ciri Khas</td>
								<td>:</td>
								<td>
									<input type="text" size="10" name="n_peg_warnakulit" id="n_peg_warnakulit" value="<?=$this->n_peg_warnakulit?>"> /
									<input type="text" size="10" name="n_peg_cirikhas" id="n_peg_cirikhas" value="<?=$this->n_peg_cirikhas?>">
								</td>
							</tr>	
						</table>
					</td>
				</tr>
			</table>	

			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>ALAMAT</b><h3>
								</td>
							</tr>
							<tr>
								<td>Jalan<span class="hightlight">*</span></td>
								<td>:</td>
								<td>
									<textarea rows="1" name="a_peg_rumah" id="a_peg_rumah"><?=$this->a_peg_rumah?></textarea>
								</td>
							</tr>	
							<tr>
								<td>RT / RW</td>
								<td>:</td>
								<td>
									<input type="text" size="5" name="a_peg_rt" id="a_peg_rt" value="<?=$this->a_peg_rt?>" onkeyup="isNumber('a_peg_rt')"> /
									<input type="text" size="5" name="a_peg_rw" id="a_peg_rw" value="<?=$this->a_peg_rw?>" onkeyup="isNumber('a_peg_rw')">
								</td>
							</tr>	
							<tr>
								<td>Desa/Keluarahan</td>
								<td>:</td>
								<td>
									<input type="text" size="55" name="a_peg_kelurahan" id="a_peg_kelurahan" value="<?=$this->a_peg_kelurahan?>">
								</td>
							</tr>	
							<tr>
								<td>Kecamatan</td>
								<td>:</td>
								<td>
									<input type="text" size="55" name="a_peg_kecamatan" id="a_peg_kecamatan" value="<?=$this->a_peg_kecamatan?>">
								</td>
							</tr>	
							<tr>
								<td>Propinsi</td>
								<td>:</td>
								<td>
									<?php 
									   $jmlPropList = count($this->propinsiList);
									   $propinsiList[''] = '--Pilih--';
									   for ($i = 0; $i < $jmlPropList; $i++) {
									   $propinsiList[(string)$this->propinsiList[$i]->c_propinsi] = (string)$this->propinsiList[$i]->n_propinsi;			 
									   }
										$propAtrib = array("id"=>"propinsiSelect","onClick"=>"javascript:cariKabupaten('targetkabupaten','propinsiSelect')"); 
										echo $ctrlFrm->formSelect('a_peg_propinsi', $this->a_peg_propinsi, $propAtrib, $propinsiList)
									?>
								</td>
							</tr>
							<tr>
								<td>Kabupaten</td>
								<td>:</td>
								<td id="targetkabupaten">
									<?php 
										$jmlKabList = count($this->kabupatenList);
										$kabupatenList[''] = '--Pilih--';
										for ($i = 0; $i < $jmlKabList; $i++) {
											$kabupatenList[(string)$this->kabupatenList[$i]->c_kabupaten] = (string)$this->kabupatenList[$i]->n_kabupaten;			 
										}
										echo $ctrlFrm->formSelect('a_peg_kota', $this->a_peg_kota,null, $kabupatenList);
									?>
								</td>
							</tr>
							<tr>
								<td>Kode Pos</td>
								<td>:</td>
								<td>
									<input type="text" maxlength="5"  size="10" name="a_peg_kodepos" id="a_peg_kodepos" value="<?=$this->a_peg_kodepos?>" onblur="isNumber('a_peg_kodepos')">
								</td>
							</tr>	
							<tr>
								<td>Telp/HP</td>
								<td>:</td>
								<td>
							<?
								$fieldId="i_peg_telponrumah";
								$value=$this->i_peg_telponrumah;
								$val = explode("-",$value);
								$size="10";
								if (!$size) $size = Array(5,10);
								$xsize = $size[0]+$size[1]+1;
								$event = "  onkeypress=javascript:isNumber(this); ";
								$h = $f."<input id='".$fieldId."1' name='".$fieldId."1' type='text' size='".$size[0]."' maxlength='3' title='".$title."' value='".$val[0]."' $event>";
								$h .= "<b>-</b>&nbsp;";
								$h .= "<input id='".$fieldId."2' name='".$fieldId."2' type='text' size='".$size[1]."' maxlength='10' title='".$title."' value='".$val[1]."' $event>".$d;
								$h .= "<input id='".$fieldId."' name='".$fieldId."' type='hidden' size='".$xsize."' maxlength='".$xsize."' class='".$c." validate-telp' title='".$title."' value='".$value."'>";
								echo $h;
							?>
							/ <input type="text" size="16" name="i_peg_telponhp" id="i_peg_telponhp" value="<?=$this->i_peg_telponhp?>" onblur="isNumber('i_peg_telponhp')">
							
								</td>
							</tr>								
						</table>
					</td>
					<td width="50%">
						<table width="100%">
							<tr>
								<td colspan="3" align="left">
									<h3 class="title"><b>NOMOR KARTU</b><h3>
								</td>								
							</tr>
							<tr>
								<td>Nomor KARPEG</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_karpeg" id="i_peg_karpeg" value="<?=$this->i_peg_karpeg?>">
								</td>
							</tr>	
							<tr>
								<td>Nomor KARIS</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_karis" id="i_peg_karis" value="<?=$this->i_peg_karis?>">
								</td>
							</tr>
							<tr>
								<td>Nomor TASPEN</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_taspen" id="i_peg_taspen" value="<?=$this->i_peg_taspen?>">
								</td>
							</tr>
							<tr>
								<td>Nomor KORPRI</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_korpri" id="i_peg_korpri" value="<?=$this->i_peg_korpri?>">
								</td>
							</tr>
							<tr>
								<td>Nomor KTP</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_ktp" id="i_peg_ktp" value="<?=$this->i_peg_ktp?>">
								</td>
							</tr>
							<tr>
								<td>Nomor ASKES</td>
								<td>:</td>
								<td>
									<input type="text" size="30" name="i_peg_askes" id="i_peg_askes" value="<?=$this->i_peg_askes?>">
								</td>
							</tr>							
						</table>
					</td>
				</tr>
			</table>
			<? if ($this->menu!='lihatdatapokok'){?>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
						<tr>
							<td align="left">ket :&nbsp;(<span class="hightlight">*</span>)&nbsp;harus diisi</td>
							<td></td>
							<td align="right">
								<div class="right">
									<input type="button" value="Batal" onclick="open_url_to_div('<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listpegawai','<?php echo $this->basePath; ?>/sdm/pegawai/pegawaijs');"> 
									<input type="submit" value="<?=$this->par;?>" onClick="insertPegawai()">
									<input type="hidden" name="proses" value="<?=$this->par;?>">
								</div>
							</td>
						</tr>
			</table>
			<?}?>	
	</div>
</form>	
<script>
function windowListTempat(){
	url = "<?php echo $this->basePath; ?>/sdmmodule/pegawai/listtempat";
	var selectWindow = window.open(url,"Selection","menubar=no,toolbar=no,scrollbars=Yes,width=740,height=530");
} 
function cariSatker(){
	var i_org_parent=document.getElementById('orgSelect').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombosatker';	
	var param = {i_org_parent:i_org_parent};
	jQuery.get(url, param, function(data) {
		jQuery("#targetsatker").html(data);

	});
}
function cariKabupaten(target,target2){
	var c_propinsi=document.getElementById(target2).value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/datapegawai/listcombokabupaten';	
	var param = {c_propinsi:c_propinsi,target:target};
	jQuery.get(url, param, function(data) {
		jQuery("#"+target).html(data);

	});
}
</script>