<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
require_once 'share/Portalconf.php'; 

$idberita = $_REQUEST['idberita'];

?>


<div id="backgroundPopup">
  <div id="popupContact">  
    <div id="popupContactClose" title="Close" onclick="closeDetil()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
		<div style="overflow: hidden;">
			<div class="wrapper">
				<div class="panel" style="height: 600px;overflow: auto;border: solid 1px #000;padding: 5px;" >
					<h3><?=$this->jdlpengumuman;?></h3>
					<span class="date"><?=tglpengumuman?></span>
					<p>
					Isi Pengumuman : <?=$this->detilpengumuman?>
					</p>
	  </div>
	</div>	
  </div>
</div>	