<?php
session_start();
$_SESSION["UserSession"]="admin";
$_SESSION["NameSession"]="Administrator";
?>
<title>Portal Internal - Pemerintah Kota Cimahi</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="<?echo $this->baseUrl;?>/css/main/style.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="<?echo $this->baseUrl;?>/css/load.css" type="text/css" />
<link href="<?echo $this->baseUrl;?>/css/main/coloring.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="<?echo $this->baseUrl;?>/FusionCharts/main/fcstyle.css" type="text/css" />
<LINK href="<?echo $this->baseUrl;?>/css/main/popuppassword.css" type="text/css" rel="stylesheet">


<link rel="icon" href="<?echo $this->baseUrl;?>/images/icon_ma.gif" type="image/png">
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/jquery.form.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/portal.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/main/popuppassword.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/ui.datepicker.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/superfish.js"></script>
<script type="text/javascript" src="<?echo $this->baseUrl;?>/js/superfishgen.js"></script>
<script type="text/javascript">
function Add(URL) {
    	window.location.href=URL;
    	}
</script>
<script type="text/javascript">
$(document).ready(function() {

	$().ajaxStart(function() {
		$('#loading').show();
	}).ajaxStop(function() {
		$('#loading').hide();
		//document.getElementById("message").value= ''; 
		document.getElementById("remaining").value= '400';  
	});
    
	$('#myForm').submit(function() {
		$.ajax({
			type: 'POST',
			url: $(this).attr('action'),
			data: $(this).serialize(),
			success: function(data) {
				$('#shoutboxdata').html(data);
			}
		})
		return false;
	});
})
</script>

<SCRIPT language=JavaScript>
function masukadata2()
{
var name = document.formshoutbox.name.value;
var message = document.formshoutbox.message.value;
var userid = document.formshoutbox.userid.value;
		url = "<?php echo $this->basePath; ?>/portalmodule/showdata/shoutbox"
		var opt = {name:name,message:message,userid:userid};
		jQuery.get(url,opt,function(data) {
			jQuery("#targetshoutbox").html(data);
			});

}
function masukadata()
{
var name = document.formshoutbox.name.value;
var message = document.formshoutbox.message.value;
var userid = document.formshoutbox.userid.value;
if (message=='') {
 alert ("Isi Pesan Anda !") ;
 document.formshoutbox.message.focus();
} else {
		url = "<?php echo $this->basePath; ?>/portalmodule/shoutbox/showdata/"
		var opt = {name:name,message:message,userid:userid};
		jQuery.get(url,opt,function(data) {
			jQuery("#shoutboxdata").html(data);
			document.getElementById("message").value= ''; 
			document.getElementById("remaining").value= '200';  
			});
	}		

}


function characterCount(field, count, maxchars) {
	if (field.value.length > maxchars) {
		field.value = field.value.substring(0, maxchars);
		alert("Error:\n\n- You are only allowed to enter up to "+maxchars+" characters.");
	} else {
		count.value = maxchars - field.value.length;
	}
}
</SCRIPT>
<script type="text/javascript">

// Current Server Time script (SSI or PHP)- By JavaScriptKit.com (http://www.javascriptkit.com)
// For this and over 400+ free scripts, visit JavaScript Kit- http://www.javascriptkit.com/
// This notice must stay intact for use.

//Depending on whether your page supports SSI (.shtml) or PHP (.php), UNCOMMENT the line below your page supports and COMMENT the one it does not:
//Default is that SSI method is uncommented, and PHP is commented:

//var currenttime = '<!--#config timefmt="%B %d, %Y %H:%M:%S"--><!--#echo var="DATE_LOCAL" -->' //SSI method of getting server date
//var currenttime = 'July 08, 2011 17:47:41' //PHP method of getting server date
var currenttime = '<? print date("F d, Y H:i:s", time())?>'; //'May 10, 2011 10:46:11' //PHP method of getting server date

///////////Stop editting here/////////////////////////////////

var int=self.setInterval("displaytime()",1000);

var dayarray=new Array("Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu");
var montharray=new Array("Januari","Februari","Maret","April","Mei","Juni","July","Agustus","September","Oktober","November","Desember")
var serverdate=new Date(currenttime)

function padlength(what){
var output=(what.toString().length==1)? "0"+what : what
return output
}

function displaytime(){
serverdate.setSeconds(serverdate.getSeconds()+1)
var datestring=dayarray[serverdate.getDay()]+", "+padlength(serverdate.getDate())+" "+montharray[serverdate.getMonth()]+" "+serverdate.getFullYear()
var timestring=padlength(serverdate.getHours()-1)+":"+padlength(serverdate.getMinutes())+":"+padlength(serverdate.getSeconds())
document.getElementById("servertime").innerHTML=datestring+" | "+timestring
}

/* window.onload=function(){
setInterval("displaytime()", 1000)
} */

function showPortalChart(pageAction, scriptAction) {
   jQuery.get(pageAction,function(data) {
		jQuery("#dashboard").html(data);
        jQuery.getScript(scriptAction,function (data) {
        });
   });	  
}

</script>