<?php 
require_once 'Zend/View.php';
require_once "share/tanggal.php";  
$tanggal = new tanggal();
$ctrlFrm = new Zend_View();
?>


		   <div class="navlink">
				<a  href="<? echo $this->basePath; ?>/sdm">Halaman Utama</a> 
				<strong> &#8250; </strong> SDM 
				<strong> &#8250; </strong> Laporan
				<strong> &#8250; </strong> Monitoring Pejabat
			</div>
<div id="top"></div>

	

<h2 class="title">Monitoring Pejabat</h2>
<?php $opr='pjb'; include "$this->leftMenu/laporanlink.phtml";?>
<form id="formresult" method="post" action="" name="formresult">
	<div class="boxholder">				
	<div class="panel">
		<div class="spacer"></div> 
			<h3 class="title"><b><u>UNIT KERJA</u></b><h3>

<? if ($this->c_lokasi_unitkerja=='1') {?>	
	<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">

		<tr>
			<td width="25%">Lokasi</td>
			<td width="2%">:</td> 
			<td>
									<?
										$jmlLokList=count($this->lokasiList);
										$lokList[''] = '--Pilih--';
											for ($i = 0; $i < $jmlLokList; $i++) {
												$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
											}
										if ($this->ceseloni=='01'){
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
										}else{
										$lokAtrib = array("style"=>"width: 300px","id"=>"c_lokasi_unitkerja"); }										
										echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 							
									?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>
				<?
					$jmleseloniList=count($this->eseloniList);
					$eseloniList[''] = '--Pilih--';
						for ($i = 0; $i < $jmleseloniList; $i++) {
							$eseloniList[(string)$this->eseloniList[$i]->c_eselon_i." ".(string)$this->eseloniList[$i]->n_unitkerja] = (string)$this->eseloniList[$i]->n_unitkerja;			 
						}
					$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
					echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 		
				?>
			</td>
		</tr>
		<tr>
			<td>Eselon II</td>
			<td>:</td> 
			<td>				
				<?
$jmleseloniiList=count($this->eseloniiList);
$eseloniiList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleseloniiList; $i++) {
		$eseloniiList[(string)$this->eseloniiList[$i]->c_eselon_ii." ".(string)$this->eseloniiList[$i]->n_unitkerja] = (string)$this->eseloniiList[$i]->n_unitkerja;
	}
if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
else {$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 		
				?>
			</td>
			</tr>	
		<tr>
			<td>Eselon III</td>
			<td>:</td> 
			<td>
				<?
$jmleseloniiiList=count($this->eseloniiiList);
$eseloniiiList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleseloniiiList; $i++) {
		$eseloniiiList[(string)$this->eseloniiiList[$i]->c_eselon_iii." ".(string)$this->eseloniiiList[$i]->n_unitkerja] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
	}

if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}
else{	$eslAtrib = array("style"=>"width: 300px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}

echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 		
				?>
			</td>
		</tr>
	
	</table>
<?} else {?>

			<table border="0" cellpadding="0" cellspacing="1" class="std" id="listcombo"  width="100%">

		<tr>
			<td width="25%">Lokasi</td>
			<td width="2%">:</td> 
			<td>
				<?
$jmlLokList=count($this->lokasiList);
$lokList[''] = '--Pilih--';
	for ($i = 0; $i < $jmlLokList; $i++) {
		$lokList[(string)$this->lokasiList[$i]->c_lokasi] = (string)$this->lokasiList[$i]->n_lokasi;			 
	}
$lokAtrib = array("style"=>"width: 320px","id"=>"c_lokasi_unitkerja","onChange"=>"javascript:cariCombo('targetesli')"); 
echo $ctrlFrm->formSelect('c_lokasi_unitkerja',$this->c_lokasi_unitkerja,$lokAtrib,$lokList); 		
				?>
			</td>
		</tr>
		<tr>
			<td>Eselon I</td>
			<td>:</td> 
			<td>
				<?
$jmleseloniList=count($this->eseloniList);

$eseloniList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleseloniList; $i++) {
		$eseloniList[trim((string)$this->eseloniList[$i][c_eselon_i].";".(string)$this->eseloniList[$i][n_unitkerja])] = (string)$this->eseloniList[$i][n_unitkerja];			 
	}
$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_i","onChange"=>"javascript:cariCombo('targeteslii')");  	
echo $ctrlFrm->formSelect('c_eselon_i',$this->c_eselon_i,$eslAtrib,$eseloniList); 		
				?>
			</td>
		</tr>
		<tr>
		<td align="left">Pengadilan Tk Banding</td>
		<td align="left">:</td> 
		<td align="left">		
			
				<?
$jmleseloniiList=count($this->eseloniiList);
$eseloniiList[''] = '--Pilih--';
	for ($i = 0; $i < $jmleseloniiList; $i++) {
		$eseloniiList[trim((string)$this->eseloniiList[$i]->c_eselon_ii.";".(string)$this->eseloniiList[$i]->c_parent.";".(string)$this->eseloniiList[$i]->n_unitkerja)] = (string)$this->eseloniiList[$i]->n_unitkerja;
	}
if ($ceseloncpns>=3){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
else {$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_ii","onChange"=>"javascript:cariCombo('targetesliii')");}
echo $ctrlFrm->formSelect('c_eselon_ii',$this->c_eselon_ii,$eslAtrib,$eseloniiList); 		
				?>
			</td>
		</tr>	
		<tr>
		<td align="left">Pengadilan Tingkat I</td>
		<td align="left">:</td> 
		<td align="left">			

				<?
$jmleseloniiiList=count($this->eseloniiiList);
$eseloniiiList[''] = '--Pilih--';

	for ($i = 0; $i < $jmleseloniiiList; $i++) {
		$eseloniiiList[trim((string)$this->eseloniiiList[$i]->c_eselon_ii.";".(string)$this->eseloniiiList[$i]->c_eselon_iii.";".(string)$this->eseloniiiList[$i]->c_satker.";".(string)$this->eseloniiiList[$i]->n_unitkerja)] = (string)$this->eseloniiiList[$i]->n_unitkerja;			 
		
	}
if ($ceseloncpns>=5){$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");  	}
else{$eslAtrib = array("style"=>"width: 320px","id"=>"c_eselon_iii","onChange"=>"javascript:cariCombo('targetesliv')");}
echo $ctrlFrm->formSelect('c_eselon_iii',$this->c_eselon_iii, $eslAtrib, $eseloniiiList); 		
				?>
			</td>
		</tr>
	
			</table>

<?}?>	
		</div>

<br>
	<div class="panel">			
		<div class="spacer"></div>
			<table border="0" cellpadding="0" cellspacing="1" class="std"  width="100%">
				<tr>
<td align="center">
	<input type="submit" value="View" onclick="viewPejabat();"> 
	<input type="submit" value="Cetak Excel" onclick="viewExl()"> &nbsp;
</td>
				</tr>
			</table>				
	</div>
</div>	
</form>	
<div id="popupview"></div>
<script>
function getStatPeg(){
	var c_status_kepegawaian=document.getElementById('c_status_kepegawaian').value;
	var url = '<?php echo $this->basePath; ?>/sdmmodule/monitoringkgb/listgolongan'; 
	var param = {c_status_kepegawaian:c_status_kepegawaian};
	jQuery.get(url, param, function(data) {
		jQuery("#targetgol").html(data);	
	});

}
</script>